### ISSUE TITLE
How to add dropout to a specific layer in python

### ISSUE THREAD

**Issue by rasoolims** [clab/dynet#100]
I am using pyCNN:

```python
self.hid2Layer = parameter(self.model["hidden2-layer"])
self.hidLayer = parameter(self.model["hidden-layer"])
self.outLayer = parameter(self.model["output-layer"])
```

How can I explicitly have one of the layers with a pre-defined dropout probability?

Thanks,
Mohammad

**Comment by yoavg** [comment]
First, you seem to be using a v1 model, please migrate to v2.

As to your question, use the `dropout` operation:
```python
import dynet as dy
m = dy.Model()
pp = m.add_lookup_parameters((10,10))
p = dy.parameter(pp)
x = dropout(p, 0.5)
...
```

**Comment by jcyk** [comment]
Hi, but how to properly handle it during test time ?
Can you please give an example using python? @rasoolims @yoavg
