### ISSUE TITLE
Can't initialize CUDA / no CUDA-capable device is detected

### ISSUE THREAD

**Issue by aghie** [clab/dynet#1020]
Hi,

I'm trying to run dynet with GPU, but I'm getting the following error, when running my command together the option `--dynet-gpus`

`` [dynet] initializing CUDA
   CUDA failure in cudaGetDeviceCount(&nDevices) 
   no CUDA-capable device is detected
   terminate called after throwing an instance of 'dynet::cuda_exception'
   what():cudaGetDeviceCount(&nDevices) ``

I have installed cuda 8.0 at /usr/local/cuda/ and when I installed dynet I chose the option:

` cmake .. -DEIGEN3_INCLUDE_DIR=../../eigen -DPYTHON=PATH_PYTHON -DBACKEND=cuda `

With CPU support, the program is running OK.

Any help is very much appreciated, thanks!

**Comment by chunyang-wen** [comment]
Can you paste the result of command  `nvidia-smi`?

**Comment by aghie** [comment]
I was running on Ubuntu 16.04. When I run `nvidia-smi`, I got this error:

`nvidia-smi failed to initialize nvml: driver/library version mismatch`

Googling it (https://stackoverflow.com/questions/43022843/nvidia-nvml-driver-library-version-mismatch), what worked for me was to reboot the machine.

P.S: Now when running `nvidia-smi` I get the expected output.

**Comment by chunyang-wen** [comment]
Good, problem solved.
