### ISSUE TITLE
When use tensor.value() got Error message I don't know how to solve

### ISSUE THREAD

**Issue by andy-yangz** [clab/dynet#1023]
What I am doing is to use several forward networks to predict different tasks.
So I put these networks in a list, and then loop them.
However, the result always comes to success the first one or two nets, and then failed at this Error I can not understand.
The code as below.
```
                    for feature in self.morphs:
                        feat_out = self.morphPredictors[feature].predict_sequence(concat_layer)
                        predicted_featIDs = [np.argmax(o.value()) for o in feat_out]
```
Error message:
```
ValueError: PickElement::forward_impl requested element 3 from a dimension of length 3
```
I tried my best and I find it's the `o.value()` goes wrong.
But when I search about tensor.value function error, I can not find the solution.
So I wish someone can help me solve this.

Thank you.

**Comment by neubig** [comment]
Take a look at DyNet's immediate computation mode, which should help you debug: http://dynet.readthedocs.io/en/latest/debugging.html#immediate-computation

In this case, you are calling `pick(x,3)` where the size of `x` is 3, and thus getting an index out of bounds error.
