### ISSUE TITLE
Memory used by the computation graph

### ISSUE THREAD

**Issue by smar111** [clab/dynet#1031]
Hi. So my program (in C++) runs out of memory on the GPU after a few hours of runtime. I want to know if there is any way to find out how much memory is being used by the computation graph, for instance, for a few sentences/minibatch in my training data?

**Comment by chunyang-wen** [comment]
It seems that it is on the working list and logged [here](https://github.com/clab/dynet/issues/498)

**Comment by neubig** [comment]
Yes, this is important, but it's a duplicate of #498
