### ISSUE TITLE
autobatch error when combined with manual batching

### ISSUE THREAD

**Issue by cindyxinyiwang** [clab/dynet#1037]
I am using xnmt for MT. My encoder part could be processed in a batch but decoder needs to be processed line by line. I manually batch the encoder part, and when process decoder part, I use pick_batch_elem to pick each encoder state and process its corresponding target. It runs fine without using auto batching. However, if I turn auto batching on, I got the following error

Assertion failed: (op.offset() < input_dims[m_dim.actualDim()]), function TensorEvaluator, file /Users/cindywang/dynet-base/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorChipping.h, line 159.
Abort trap: 6

Is it because of some added/removed dimension when I pick elements from a batch?

**Comment by neubig** [comment]
Can you print the dimensions of the expression that is passed in to the function, and the function call itself?

**Comment by cindyxinyiwang** [comment]
I just found out I still get the error without autobatching. My program runs through until probably the call to back_prop on the accumulated loss. Thanks I will print out the dimensions!

**Comment by neubig** [comment]
To clarify: could you print out the dimensions and post them here? This is a bug with DyNet that should be fixed.

**Comment by cindyxinyiwang** [comment]
Which function and dimension specifically? I just found the problem only arises when I calculate dev set loss

**Comment by neubig** [comment]
OK, if you can send me an email with details of how to reproduce the error in our environment I can help debug.

**Comment by neubig** [comment]
This should be fixed by #1040. The `pick_batch_elem` function was not doing boundary checking for out-of-bounds indices. Once that pull request is merged it will do proper boundary checking, and you will get the following error:

    ValueError   :    PickBatchElements::forward_impl requested element 1 from a batch size of 1

In other words, you are requesting the index "1" from an expression with batch size of "1", so you can only request index "0".

**Comment by cindyxinyiwang** [comment]
That's great! Thank you!
