### ISSUE TITLE
Mac OS X installation is broken

### ISSUE THREAD

**Issue by mitchellstern** [clab/dynet#1054]
Attempting to install from source from the current master branch on a Mac gives the following error:

```
error: can't copy '/usr/local/lib/libdynet.dylib': doesn't exist or not a regular file
```

I believe the culprit is pull request #1043, commit 1bdfe5d5c815ee558060144d22c79dcb270bdcd7, line 163 in `setup.py`:

```
DATA_FILES += [LIBS_INSTALL_DIR + "lib" + lib + ".dylib" for lib in LIBRARIES]
```

Commenting this line out allows me to install the Python DyNet module without issue.

**Comment by neubig** [comment]
I encountered this to. Any ideas @danielhers ?

**Comment by danielhers** [comment]
Sorry about that. It's assuming that you did `make install` (which happens in the tests but isn't actually necessary).

**Comment by danielhers** [comment]
I tried making it copy the library from `PROJECT_BINARY_DIR` but its value appears to be incorrect, so that's why I chose `LIBS_INSTALL_DIR` instead. I'll see what I can do.

**Comment by mitchellstern** [comment]
For reference, I'm following the instructions [here](https://dynet.readthedocs.io/en/latest/python.html#manual-installation), starting from `mkdir build` and ending with the Python command.

**Comment by neubig** [comment]
Confirmed fixed!
