### ISSUE TITLE
Mac OSX: pip install works, but import fails

### ISSUE THREAD

**Issue by dirkhovy** [clab/dynet#1056]
Following the instructions [here](http://dynet.readthedocs.io/en/latest/python.html), I am able to pip-install dynet (having to use `sudo -H`, though):
```
sudo -H pip install git+https://github.com/clab/dynet#egg=dynet
Collecting dynet from git+https://github.com/clab/dynet#egg=dynet
  Cloning https://github.com/clab/dynet to /private/tmp/pip-build-sqkw552n/dynet
Requirement already satisfied: cython in ./anaconda3/lib/python3.5/site-packages (from dynet)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.5/site-packages (from dynet)
Installing collected packages: dynet
  Running setup.py install for dynet ... done
Successfully installed dynet-0.0.0
```
However, when I try to import dynet, I get the following error:

```
[In [1]: import dynet
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-2d622ed12c90> in <module>()
----> 1 import dynet

~/anaconda3/lib/python3.5/site-packages/dynet.py in <module>()
     13     def print_graphviz(**kwarge):
     14         print("Run with --dynet-viz to get the visualization behavior.")
---> 15     from _dynet import *
     16 
     17 __version__ = 2.0

ImportError: dlopen(/Users/dirkhovy/anaconda3/lib/python3.5/site-packages/_dynet.cpython-35m-darwin.so, 2): Library not loaded: @loader_path/libdynet.dylib
  Referenced from: /Users/dirkhovy/anaconda3/lib/python3.5/site-packages/_dynet.cpython-35m-darwin.so
  Reason: image not found
```

Any pointers?

**Comment by danielhers** [comment]
Could you please check if `/Users/dirkhovy/anaconda3/lib/python3.5/site-packages/libdynet.dylib` exists?

**Comment by dirkhovy** [comment]
Thanks, Daniel. No, the file does not exist. Shouldn't that be installed by pip? (Btw, I also tried the updated setup.py version from your fork, but got the same error. Not sure that helps.)

**Comment by danielhers** [comment]
Right, of course, it went to `/Users/dirkhovy/anaconda3/lib/libdynet.dylib`, didn't it?
I'll try and fix that.
In the meantime, please simply uninstall and install from PyPI - it should work:

    pip uninstall dynet
    pip install dynet

**Comment by dirkhovy** [comment]
Yes, /Users/dirkhovy/anaconda3/lib/libdynet.dylib exists!
And the PyPI version seems to work. Thanks!
