### ISSUE TITLE
Use of convolution

### ISSUE THREAD

**Issue by duyvuleo** [clab/dynet#1060]
Hi all,

Sorry for a silly question. 

I would like to use equivalent code in DyNet for the following code in Tensorflow:

```
# x.shape = (H, L) where H is no. of hidden units and L is input length
params = {"inputs": x, "filters": 2048, "kernel_size": 1, "activation": tf.nn.relu, "use_bias": True}
y = tf.layers.conv1d(**params)
# y.shape should be equal to x.shape?
```

I found this (https://github.com/clab/dynet/blob/master/examples/textcat/train_textcat.cc), but am not very sure it is equivalent. Looking for your pointer/example. 

Thank you so much!

**Comment by stefan-it** [comment]
Hi :)

You can find a good example in the `nn4nlp2017` repository:

https://github.com/neubig/nn4nlp2017-code/blob/master/05-cnn/cnn-class.py#L48

**Comment by duyvuleo** [comment]
Thanks for your pointer!

So, I used the following in DyNet:

```
# i_x.dim() must be in the form of ((1, L, H), B) where H is no. of hidden units and L is input length (B is batch dim)
p_W = mod.add_parameters((1, 1, H , 2048))
p_b = mod.add_parameters((2048))
i_W = dy.parameter(p_W)
i_b = dy.parameter(p_b)

i_y = dy.conv2d(i_x, i_W, i_b, (1,1), False)	
```
