### ISSUE TITLE
Can I convert Vector of Expressions to mini-batched Expression?

### ISSUE THREAD

**Issue by shuheik** [clab/dynet#1061]
Suppose I have a vector of _n_ Expressions with Dim(_d_), and want to convert them into a mini-batched Expression of Dim({_d_}, _n_).
What's the best way to do that in dynet?

**Comment by neubig** [comment]
concat_to_batch()

**Comment by shuheik** [comment]
Thanks for quick answer!
I'll wrap that function in SWIG and send a PR.
