### ISSUE TITLE
Pass flags to cmake via pip

### ISSUE THREAD

**Issue by EggyLv999** [clab/dynet#1062]
As far as I can tell, there's no way to pass flags through pip->setup.py->cmake. I'm following the installation instructions tying to set -DCUDNN_ROOT as a cmake option. https://github.com/clab/dynet/blob/master/setup.py#L277 is probably the right place for it to go, I'm happy to implement this if someone gives me some pointers on what the best way to pass a string from the pip command level to here is.

**Comment by danielhers** [comment]
You're right, that's where you need to implement this. Just add `"CUDNN_ROOT"` to the tuple, changing `for env_var in ("BACKEND",)` to `for env_var in ("BACKEND", "CUDNN_ROOT")`.

**Comment by neubig** [comment]
Thanks, this would be nice @EggyLv999 !

**Comment by neubig** [comment]
Fixed by #1109
