### ISSUE TITLE
Getting RNN parameters in Python

### ISSUE THREAD

**Issue by danielhers** [clab/dynet#1063]
For debugging purposes, I would like to get all parameter arrays in my model and write them to a `.npz` file. For regular parameters and lookup parameters I just call `as_array`, but I'm not sure what to do for builders, e.g. `BiRNNBuilder` or even `LSTMBuilder`. Is there a way to get their parameter arrays in Python?

**Comment by pmichel31415** [comment]
[This maybe?](http://dynet.readthedocs.io/en/latest/python_ref.html#dynet.VanillaLSTMBuilder.get_parameters)

Or even [this](http://dynet.readthedocs.io/en/latest/python_ref.html#dynet.ParameterCollection.parameters_list) directly?

**Comment by danielhers** [comment]
Great, thanks! Don't know how I missed that.
