### ISSUE TITLE
DyNet init function is not easy to use

### ISSUE THREAD

**Issue by neubig** [clab/dynet#108]
Currently, the DyNet "init" function takes command line arguments as-is, and is not straightforward to access programmatically. It would be better to have a structure containing the options that  can be passed to the initializer (while maintaining the compatibility with the current interface).

**Comment by odashi** [comment]
I saw that currently there are 2 codeblocks to parse commandline args (one is in `initialize()`, and another is in `initialize_gpu()` which is called from the former).
They attempt to consume same args like `--dynet-mem`, and this behavior looks kind of confusing.
I think it might be better to integrate both to single codeblock as well as separating commandline parsing and actual configurations.

**Comment by odashi** [comment]
Oh thanks, new code look better!

**Comment by neubig** [comment]
Resolved by https://github.com/clab/dynet/pull/117
