### ISSUE TITLE
train_xor example is not built with C++: problem with lpthreads?

### ISSUE THREAD

**Issue by elisaF** [clab/dynet#1083]
I am following the installation instructions for DyNet with C++. However, there is no train_xor executable in the examples directory after running the make command.

I believe the problem is that cmake fails to find the library for pthread. Snippet from CMakeError.log:
`CMakeFiles/cmTC_40759.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_40759.dir/build.make:97: recipe for target 'cmTC_40759' failed`

System info:
OS: Ubuntu 16.04.3 LTS (Xenial Xerus)
build-essential: 12.2
cmake: 3.9.6
mercurial: 4.4.1

Note that I have manually installed these since I do not have `ROOT` access on the system.

Some env vars:
PATH=~/bin:$PATH
LD_LIBRARY_PATH=~/share:$LD_LIBRARY_PATH

Attached files:
[CMakeError.log](https://github.com/clab/dynet/files/1492491/CMakeError.log)
[CMakeOutput.log](https://github.com/clab/dynet/files/1492492/CMakeOutput.log)
[make.log](https://github.com/clab/dynet/files/1492493/make.log)

**Comment by elisaF** [comment]
I also see the pthread error (and several others) if I try to install Eigen using cmake:

` cmake /scratch/cluster/elisaf/eigen/`

Snippet from cmake output:
`-- Performing Test COMPILER_SUPPORT_FASTMATH - Success
-- Boost version: 1.58.0
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
`

And snippet from CMakeError.log:
`/v/filer5b/v37q001/elisaf/bin/cmake -E cmake_link_script CMakeFiles/cmTC_8fbd4.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_8fbd4.dir/CheckSymbolExists.c.o  -o cmTC_8fbd4
CMakeFiles/cmTC_8fbd4.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_8fbd4.dir/build.make:97: recipe for target 'cmTC_8fbd4' failed
make[1]: *** [cmTC_8fbd4] Error 1
`

**Comment by neubig** [comment]
Hmm, this doesn't seem to be a DyNet specific issue then... Perhaps you could consult with the cmake mailing list?

**Comment by elisaF** [comment]
The error in cmake turned out to be a red herring since it does eventually find pthreads by other means. The real problem is that there is no train_xor example -- but that's just because it was renamed at some point. The docs need to be updated to reflect the new name. You can use this issue for that change, or I am also happy to close this one.
