### ISSUE TITLE
Manual Installation  error with python on Ubuntu 16.04

### ISSUE THREAD

**Issue by tom2002965** [clab/dynet#1084]
Hello,

When I type `cmake .. -DEIGEN3_INCLUDE_DIR=../../eigen -DPYTHON=`which python3` -DBACKEND=cuda`

```
It would run error information about 
CMake Warning at /usr/share/cmake-3.5/Modules/FindCUDA.cmake:1649 (add_library):
  Cannot generate a safe runtime search path for target dynet because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libcudnn.so.5] in /lib64 may be hidden by files in:
      /usr/local/cuda-8.0/lib64

  Some of these libraries may not be found correctly.
```

How could I fix it ? 

Thank you!

My cuda version is 8.0
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

**Comment by onurgu** [comment]
This means that you have `libcudnn.so.5` file both in `/lib64` and `https://github.com/clab/dynet`.

You can check there and remove the redundant one. However, please be advised that one of them might be a symbolic link to the other.
