### ISSUE TITLE
reallocate memory when dynet_load_model cause double memory consumption.

### ISSUE THREAD

**Issue by Oneplus** [clab/dynet#110]
I happen to find there is a large memory consumption when I load a model with dynet_load_model. The workflow of my code is like:

```
Model m;
m.add_parameter(...); // add several parameter
for (unsigned iter = 0; iter < max_iter; ++iter) {
   // training m
   if (best development score achieved) { save_dynet_model(path, m); }
}
load_dynet_model(path, m);
// perform testing.
```

I see line 201 in tensor.cc:

```
  device->allocate_tensor(mem_pool, *this)
```

which means each time we load a model (or more exactly, a tensor), no matter whether the memory has been allocated, we still want some memory from the pool. It ok if the model is small but when the model is large, doubling the memory is fatal.

**Comment by neubig** [comment]
Yes, this should be fixed. @armatthews do you think there's any easy solution?

**Comment by Oneplus** [comment]
@neubig I tried to fix this but I am afraid there seems no easy solution. The most difficult part is that dynet model serialize the `vector<ParameterStorage*>` and `vector<LookupParameterStorage*>`. That means the boost::serialize module would automatically allocate new ParameterStorage and it cannot keep track on the old (by old I mean the ParameterStorage* already allocated) ParameterStorage.

So the easiest solution might be let the users manually free their model before dynet_load_model. ☹️

**Comment by danielhers** [comment]
@Oneplus I would like to use the workaround you suggested. Is it possible to manually free the memory used by a model?

**Comment by Oneplus** [comment]
@danielhers currently, there is no API in `dynet::Model` that allow you to fully free the memory (or more precisely, return the memory to the memory pool). In C++, you can just `Model* m = new Model` and `delete m` at last. I am not sure what happens if you `del m` in python. But it's worth to try.
@neubig can we add an API to `dynet::Model` like `Model.pruge()` that allow users to fully free the memory of model.

**Comment by neubig** [comment]
This double loading should be fixed when we fix https://github.com/clab/dynet/issues/84
This is currently in development on the "new-readwrite" branch.

**Comment by neubig** [comment]
I believe this should be fixed by https://github.com/clab/dynet/pull/637
