### ISSUE TITLE
cannot install for python 3.6 with pip3

### ISSUE THREAD

**Issue by RobinChenRichmond** [clab/dynet#1101]
When I tried:
sudo pip3 install git+https://github.com/clab/dynet#egg=dynet

Here's the error:
(normal output skipped)............................
INFO:root:Creating build directory /private/tmp/pip-build-h0xm3sj0/dynet/build/py3.6-64bit
    INFO:root:Fetching Eigen...
    error: Could not download Eigen from 'https://bitbucket.org/eigen/eigen/get/699b6595fc47.zip'
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-h0xm3sj0/dynet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-0laqqle5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-h0xm3sj0/dynet/

can someone help and check if it's the problem of setting for my python 3.6?

**Comment by yanfeiyu** [comment]
I have a similar issue with 
pip install git+https://github.com/clab/dynet#egg=dynet

Here is the error:

INFO:root:Copying built extensions...
    running install_lib
    copying build/lib.macosx-10.7-x86_64-3.6/_dynet.cpython-36m-darwin.so -> /Users/Olivia/anaconda3/lib/python3.6/site-packages
    copying build/lib.macosx-10.7-x86_64-3.6/dynet.py -> /Users/Olivia/anaconda3/lib/python3.6/site-packages
    copying build/lib.macosx-10.7-x86_64-3.6/dynet_config.py -> /Users/Olivia/anaconda3/lib/python3.6/site-packages
    copying build/lib.macosx-10.7-x86_64-3.6/dynet_viz.py -> /Users/Olivia/anaconda3/lib/python3.6/site-packages
    byte-compiling /Users/Olivia/anaconda3/lib/python3.6/site-packages/dynet.py to dynet.cpython-36.pyc
    byte-compiling /Users/Olivia/anaconda3/lib/python3.6/site-packages/dynet_config.py to dynet_config.cpython-36.pyc
    byte-compiling /Users/Olivia/anaconda3/lib/python3.6/site-packages/dynet_viz.py to dynet_viz.cpython-36.pyc
    running install_data
    copying /Users/Olivia/anaconda3/lib/python3.6/site-packages/../../../lib/libdynet.dylib -> /Users/Olivia/anaconda3/../..
    error: could not create '/Users/Olivia/anaconda3/../../libdynet.dylib': Permission denied
    
    ----------------------------------------
Command "/Users/Olivia/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/mb/1nx6fbk10l7179v1b8ysnscc0000gn/T/pip-build-d4v8v_7b/dynet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/mb/1nx6fbk10l7179v1b8ysnscc0000gn/T/pip-jkg3__pn-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/mb/1nx6fbk10l7179v1b8ysnscc0000gn/T/pip-build-d4v8v_7b/dynet/

Can anyone help me out? Thanks in advance!

**Comment by neubig** [comment]
Hi Guys, you have two different errors.

@RobinChenRichmond DyNet downloads the Eigen linear algebra library from bitbucket as a part of the install process. It looks like this download failed, perhaps because bitbucket was down. Could you just try to run it one more time?

@yanfeiyu this error is a bit strange, it looks like it's trying to copy the library to a strange location and getting a permission denied error. Perhaps @danielhers can help debug?

**Comment by RobinChenRichmond** [comment]
@neubig Thanks a lot for the reply! I guess it may not be the download problem. I actually just installed the dynet for my python2.7 using the similar command:
sudo pip install git+https://github.com/clab/dynet#egg=dynet, and everything went fine. Could it be problem related to settings of my python 3.6?

**Comment by danielhers** [comment]
@yanfeiyu's problem is due to [this line](https://github.com/clab/dynet/blob/master/setup.py#L388), which is necessary to include `libdynet.dylib` in the wheel properly. It's very hard to get `data_files` to work properly for all environments, but I'll see what I can do.

**Comment by yanfeiyu** [comment]
@danielhers Thanks for your reply! I have tried the following and it works!

brew install python3
brew postinstall python3
sudo pip3 install dynet

**Comment by danielhers** [comment]
@yanfeiyu yes, well, now you installed using the PyPI wheel, which is just as good :) I also opened a PR so that installing from master will work.

**Comment by neubig** [comment]
Should be fixed by #1102
