### ISSUE TITLE
getting computation graph size

### ISSUE THREAD

**Issue by alsuhr-c** [clab/dynet#1106]
Is there any way to get the current size of the computation graph while it is being built? "Size" is ill-defined and I'm not sure how the computation graph works behind the scenes, so maybe this would be number of nodes or # of bytes (if possible). I am running into out-of-memory issues during forward/backward passes, and since I can't seem to completely catch the OOM exception in python (which makes sense if it causes a fault in the GPU, necessitating reallocation of memory; not sure how it works), it would be very nice to have a way to catch OOM errors before they actually happen and deal with them before a crash. 

E.g., if I know the graph I'm building is close to the limit for my GPU during training, I can quit building it, do forward/backward pass, and continue with a new CG/batch.

Apologies if this has been addressed in the past -- couldn't find anything about it from a cursory search.

**Comment by neubig** [comment]
Try to set the command line flag `--dynet-profiling 1` or `--dynet-profiling 2`, then run `cg.print_graphviz()` in C++ or `dy.print_text_graphviz()` in Python.
