### ISSUE TITLE
V100-PCIE-16GB gpus??

### ISSUE THREAD

**Issue by miguelballesteros** [clab/dynet#1108]
does dynet support tesla V100-PCIE-16GB gpus? I just tried the same thing I was running in k80s, and it crashed when initializing.
 
does somebody know if this is supposed to work out of the box? I tried with cuDNN-v5.1-8.0 and cudnn-8.0
 
dynet] initializing CUDA
Request for 1 GPU ...
[dynet] Device Number: 0
[dynet]   Device name: Tesla V100-PCIE-16GB
[dynet]   Memory Clock Rate (KHz): 877000
[dynet]   Memory Bus Width (bits): 4096
[dynet]   Peak Memory Bandwidth (GB/s): 898.048
[dynet]   Memory Free (GB): 16.4797/16.9369
[dynet]
[dynet] Device(s) selected: 0CUDNN failure in cudnnCreate(&cudnnHandle)
CUDNN_STATUS_INTERNAL_ERROR
terminate called after throwing an instance of 'dynet::cuda_exception'
  what():  cudnnCreate(&cudnnHandle)
Aborted (core dumped)
 
thanks,
Miguel

**Comment by miguelballesteros** [comment]
I tried this simple cuda program to try to emulate what Dynet is doing:

#include <stdio.h>
int main() {
  int nDevices;
  cudaError_t err = cudaGetDeviceCount(&nDevices);
  if (err != cudaSuccess) {
    printf("cuda fail: %s\n", cudaGetErrorString(err));
    return 1;
  }
  for (int i = 0; i < nDevices; i++) {
    cudaDeviceProp prop;
    cudaGetDeviceProperties(&prop, i);
    printf("Device Number: %d\n", i);
    printf("  Device name: %s\n", prop.name);
    printf("  Memory Clock Rate (KHz): %d\n",
           prop.memoryClockRate);
    printf("  Memory Bus Width (bits): %d\n",
           prop.memoryBusWidth);
    printf("  Peak Memory Bandwidth (GB/s): %f\n\n",
           2.0*prop.memoryClockRate*(prop.memoryBusWidth/8)/1.0e6);
  }
  err=cudaSetDevice(0);
    if (err != cudaSuccess) {
      printf("CUDA failure in %s\n", cudaGetErrorString(err));
    }
    else printf("success \n");
 size_t freebytes, totalbytes;
  err = cudaMemGetInfo(&freebytes,&totalbytes);
  if (err != cudaSuccess) {
    printf("CUDA mem get fail %s\n", cudaGetErrorString(err));
  }
  else printf("cudamem success\n");

}

and this successfully communicates with the GPU... so I have no idea what the issue could be.
any ideas are welcome :)

Thanks!
Miguel

**Comment by neubig** [comment]
Are things working now?

**Comment by miguelballesteros** [comment]
Yes, sorry. 
It was an issue with the software, cuda9 was installed in those machines as default and just installing an older version locally made it.

The speed up with the V100 is quite significant, like 2.5x~3x with the same network and batch sizes. 💯
