### ISSUE TITLE
How to not update the parameters of the encoder in an MT model?

### ISSUE THREAD

**Issue by smar111** [clab/dynet#1111]
Hi. I am using the C++ version of Dynet. I know that if you use const_parameter/const_lookup function, when adding a parameter to the graph then it will not get updated. 
My question is how to make other parameters in the encoder i.e. within the LSTM constant so as they are not updated during backpropagation? I am not sure if using nobackprop() before I start the decoder sequence would work.

**Comment by neubig** [comment]
Yep, that should work.

**Comment by pmichel31415** [comment]
For completeness sake: you can also pass a boolean to the `new_graph` method specifiying whether you should update the parameters http://dynet.readthedocs.io/en/latest/builders.html#_CPPv2N5dynet10RNNBuilder9new_graphER16ComputationGraphb
