### ISSUE TITLE
Problem running dynet with CUDA toolkit V8.0.61

### ISSUE THREAD

**Issue by aminianmary** [clab/dynet#1112]
Hi,

I try to install dynet with CUDA support on CentOS release 6.7. I have CUDA toolkit V8.0.61 installed (determined using nvcc --version) and nvidia-smi returns the following info about the driver version:

+------------------------------------------------------+                       
| NVIDIA-SMI 352.63     Driver Version: 352.63         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro K600         Off  | 0000:42:00.0     Off |                  N/A |
| 25%   42C    P0    N/A /  N/A |      7MiB /  1023MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

Dynet is successfully installed with BACKEND=cuda but when I try to run my script with --dynet-gpu I get the following error message:

`[dynet] initializing CUDA
CUDA failure in cudaGetDeviceCount(&nDevices)
CUDA driver version is insufficient for CUDA runtime version
terminate called after throwing an instance of 'dynet::cuda_exception'
  what():  cudaGetDeviceCount(&nDevices)
`

Any suggestion to resolve this issue is appreciated!

--Thanks
Maryam

**Comment by neubig** [comment]
This is a problem with your environment: your NVIDIA driver is too low for your version of CUDA. Please upgrade your NVIDIA driver.
