### ISSUE TITLE
Passing None to affine_transform has confusing error message

### ISSUE THREAD

**Issue by bdusell** [clab/dynet#1114]
In Python, passing a value of `None` to the function `dynet.affine_transform` results in a misleading error message, making it difficult to track down what the actual problem is. Here's a simple program that illustrates the problem:

**bug.py**
```python
import dynet

params = dynet.ParameterCollection()
W_param = params.add_parameters((3, 3))
b_param = params.add_parameters((3,))

dynet.renew_cg()
W = dynet.parameter(W_param)
b = dynet.parameter(b_param)
x = None
y = dynet.affine_transform([b, W, x])
print(y.value())
```

```
$ python bug.py 
[dynet] random seed: 1672194714
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Traceback (most recent call last):
  File "bug.py", line 11, in <module>
    y = dynet.affine_transform([b, W, x])
  File "_dynet.pyx", line 4018, in _dynet.affine_transform
  File "_dynet.pyx", line 4033, in _dynet.affine_transform
  File "_dynet.pyx", line 1567, in _dynet.ensure_freshness
ValueError: Attempt to use a stale expression.
```

This came up when I was using the result of `dynet.RNNState.output()` as `x`. The actual problem was that `RNNState` was the initial state, so `output()` returned `None`.

**Comment by xunzhang** [comment]
Good catch. In `_dynet.pyx`, we only handle the case for `None` instead of `None`. Will file a pull request to fix this soon.

**Comment by neubig** [comment]
Fixed by https://github.com/clab/dynet/pull/1126
