### ISSUE TITLE
Import error image not found after installation on macOS 10.13.1 python 3.6

### ISSUE THREAD

**Issue by venkatasg** [clab/dynet#1116]
I installed dynet using pip and there were no problems. However when I try ```import dynet``` I get the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/dynet.py", line 15, in <module>
    from _dynet import *
ImportError: dlopen(/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_dynet.cpython-36m-darwin.so, 2): Library not loaded: /tmp/pip-build-_ybly6u6/dynet/build/py3.6-64bit/dynet/libdynet.dylib
  Referenced from: /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/_dynet.cpython-36m-darwin.so
  Reason: image not found
```

I tried the steps given in the installation documentation to edit ```$DYLD_LIBRARY_PATH```. I found dynet.dylib in 2 places and edited the path to both locations, and I still get the same error. Why does it keep looking for libdynet.dylib in tmp folder even after I set the PATH variable?

**Comment by neubig** [comment]
Hmm, I'm not sure. Can you run `env | grep PATH` to print out all your relevant environmental variables?

**Comment by neubig** [comment]
Closing until we can get more info.

**Comment by Systemcluster** [comment]
This is probably an issue with macOS SIP interfering with `DYLD_LIBRARY_PATH`, making the variable unavailable in the env. See https://github.com/nteract/nteract/issues/1523 for the same issue, a few workarounds are listed in that thread.
