### ISSUE TITLE
ValueError: Out-of-bounds when calling .value()

### ISSUE THREAD

**Issue by yoavartzi** [clab/dynet#1117]
I got this message today. Are you familiar with it? It happened when calling .value() on a post-softmax vector. 

```
probs = probs.value()
  File "_dynet.pyx", line 1766, in _dynet.Expression.value
  File "_dynet.pyx", line 1780, in _dynet.Expression.value
ValueError: Out-of-bounds attempt to access index 5 for LookupParameter of size 5
```

It never happened before, but not happens consistently using this model.

**Comment by neubig** [comment]
Yes, this means you have a lookup parameter (e.g. `x`) of size 5 where you're accessing the index 5 (e.g. `x[5]`) which is out of bounds because indices are zero-indexed.

The reason why this appears when you call `value()` is because DyNet uses lazy evaluation by default. Turn on immediate computation if you'd like the error to be thrown where the offending code is: http://dynet.readthedocs.io/en/latest/debugging.html#immediate-computation

**Comment by yoavartzi** [comment]
Turning on immediate computation gives `Segmentation fault: 11`. Any way to debug the debugger?

**Comment by neubig** [comment]
Hmm, that's strange that turning on immediate computation would break anything. Are you on mac? If so, `lldb` can sometimes help track segmentation faults down (just add it to the beginning of your command line). Alternatively, and perhaps preferably, if you can come up with a simple example of how to reproduce this I can help fix the segmentation fault though.

For the time being, you can also just look for the places where you're using lookup parameters and make sure that the indices that you're passing in are smaller than the size of the lookup parameters.

**Comment by yoavartzi** [comment]
I am on a Mac. This is what I get from lldb:

```
(lldb) target create "python"
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/user/miniconda2/envs/dynet/lib/python2.7/copy.py", line 52, in <module>
    import weakref
  File "/Users/user/miniconda2/envs/dynet/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
Current executable set to 'python' (x86_64).
(lldb) settings set -- target.run-args  "script.py"
(lldb)
(lldb)
(lldb) run
Process 26273 launched: '/Users/user/miniconda2/envs/dynet/bin/python' (x86_64)
[dynet] random seed: 1
[dynet] using autobatching
[dynet] allocating memory: 10000MB
[dynet] memory allocation done.
Computing accuracy: 25it [00:00, 27.73it/s]python(26273,0x7fffad9ef340) malloc: *** error for object 0x10048dc00: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Process 26273 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff744ebfce libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff744ebfce <+10>: jae    0x7fff744ebfd8            ; <+20>
    0x7fff744ebfd0 <+12>: movq   %rax, %rdi
    0x7fff744ebfd3 <+15>: jmp    0x7fff744e376c            ; cerror_nocancel
    0x7fff744ebfd8 <+20>: retq
Target 0: (python) stopped.
```

It has a been a while since I tried to read assembly. Not sure should be relevant, but this is without any training, I just started generating (roughly speaking, this is a seq2seq model) with a randomly initialized model. Funny enough though, training seems to start OK even with non-lazy eval. 

I did solve the problem that got me here to start with. printf() and value() calls until I locked down on it. It was my bug.
