### ISSUE TITLE
Does temporary expression persist in the computation graph until we call NewGraph?

### ISSUE THREAD

**Issue by xyda** [clab/dynet#1119]
When we creat a temporary expression by using **_input_** method (input(cg, variable)), does it take up the GPU memory until we call NewGraph again? If a temporary expression are created in a loop, it raise the worry of its continued consuming memory.

**Comment by neubig** [comment]
Yes, they do. DyNet does not have a concept of garbage collection at the moment, although it is possible to revert back to the previous state: http://dynet.readthedocs.io/en/latest/python_ref.html#dynet.cg_revert
