### ISSUE TITLE
Python Documentation is down?

### ISSUE THREAD

**Issue by yoavg** [clab/dynet#1120]
The python documentation on the website (latest) is not working.
Should be fixed..

**Comment by neubig** [comment]
cc @pmichel31415 any ideas?

**Comment by pmichel31415** [comment]
That' weird I don't have any issues accessing the documentation and there doesn't seem to be a problem on the readthedocs side of things... Can you retry?

If it's still not working can you give more details on what's happening? 404? outdated doc?

**Comment by yoavg** [comment]
Maybe "down" is not the right word for it.
But see the python reference page:
http://dynet.readthedocs.io/en/latest/python_ref.html

The "stable" url is up, but this is the one people get to from Google etc.

**Comment by pmichel31415** [comment]
Ah OK I see now. This seems to have been introduced with 9a51a5a74feda301fddf5b5d0d687652723fdb25 but I have no idea how, I'll investigate

**Comment by pmichel31415** [comment]
OK this was because the hack I used to generate the documentation didn't handle single line docstrings, this should be fixed now

**Comment by redpony** [comment]
Thank you- sorry for the hassle!
