### ISSUE TITLE
Issue installing dynet with MSVC

### ISSUE THREAD

**Issue by alex-calderwood** [clab/dynet#1123]
Would anyone be able to help? I was following the tutorial here, as well as the official tutorial. I posted my question here https://stackoverflow.com/questions/47661042/error-installing-dynet-w-python-on-windows
but haven't gotten a reply.

**Comment by neubig** [comment]
It looks like @danielhers gave some advice to try the MSVC option on the link, I'll mark this as "need more info" until we get more.
