### ISSUE TITLE
Attempting to concatenate [None] in python throws confusing error

### ISSUE THREAD

**Issue by EggyLv999** [clab/dynet#1124]
As in the title, running `dy.concatenate([None])` gives me the following error:

```
File "_dynet.pyx", line 1535, in _dynet.ensure_freshness
ValueError: Attempt to use a stale expression.
```

Should be an easy fix to check that something is a valid dynet expression and throw the right error message first.

**Comment by xunzhang** [comment]
Duplicate with https://github.com/clab/dynet/issues/1114

**Comment by neubig** [comment]
Fixed by https://github.com/clab/dynet/pull/1126
