### ISSUE TITLE
Plain C bindings?

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1144]
It might be nice to have plain-C bindings for DyNet. This is not trivial to do because DyNet uses C++ style quite heavily, but for creating things like interfaces to other languages, this might be useful. See:

https://github.com/chantera/dynet-rs/issues/1

**Comment by xbainbain** [comment]
I am working on that now. I created a temporary repository ([dynet-c](https://github.com/xbainbain/dynet-c)) for that but it's still in early stage. A pull request will be made to the main repository when basic functions are fully implemented.
