### ISSUE TITLE
Issue installing using on Ubuntu either using pip or manually

### ISSUE THREAD

**Issue by tomergill** [clab/dynet#1145]
Pip fails and gives output (log.txt).
Manually installing doesn't give an error but doesn't work.
Thanks in advance, Tomer
[log.txt](https://github.com/clab/dynet/files/1579609/log.txt)
**EDIT:** command was "sudo pip install git+https://github.com/clab/dynet#egg=dynet"

**Comment by danielhers** [comment]
Looks like Bitbucket was momentarily down. Please try again.

**Comment by neubig** [comment]
If this is still giving problems I'll re-open.
