### ISSUE TITLE
Swapping out `--dynet-gpu` for `--dynet-gpus 1` automatically is confusing

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1147]
In the code below, the `--dynet-gpu` argument is replaced with `--dynet-gpus 1`.
https://github.com/clab/dynet/blob/master/python/_dynet.pyx#L100

This is confusing if you have a downstream python library that uses `argparse`, because suddenly the `--dynet-gpus` argument appears out of nowhere. It'd be nice if we could just keep the `--dynet-gpu` argument and deal with it appropriately (in C++ maybe?). CC @xunzhang

**Comment by xunzhang** [comment]
I think it should be implemented in python. I'll do a quick enhancement for this.
