### ISSUE TITLE
pre-compiled wheels do not work

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1151]
It looks like pre-compiled wheels do not install properly, perhaps because a dependency on Cython is not recognized? Any ideas @danielhers ?

    neubig:~$ conda create --name test-pip-install python=3
    [... creates environment]
    neubig:~$ source activate test-pip-install
    (test-pip-install) neubig:~$ pip install dynet
    Collecting dynet
      Downloading dyNET-2.0.2.tar.gz (388kB)
        100% |████████████████████████████████| 389kB 1.0MB/s 
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/private/var/folders/xk/kk1w64y15394y2943l7jm1kw0000gn/T/pip-build-pj2k14cx/dynet/setup.py", line 17, in <module>
            from Cython.Distutils import build_ext as _build_ext
        ModuleNotFoundError: No module named 'Cython'
        
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/xk/kk1w64y15394y2943l7jm1kw0000gn/T/pip-build-pj2k14cx/dynet/

**Comment by danielhers** [comment]
It's the source distribution you're getting. I will fix the wheel
deployment. For the sdist you need cython before installing, not sure how
to fix this.

**Comment by neubig** [comment]
Thanks! I didn't realize exactly how things worked. It looks like we have binaries for most platforms now (https://pypi.python.org/pypi/dyNET/2.0.2) so this should be resolved.

**Comment by danielhers** [comment]
Yes, they're all there now.
