### ISSUE TITLE
one-hot expression

### ISSUE THREAD

**Issue by duyvuleo** [clab/dynet#1153]
Hi,

Does there exist a fast way in dynet to create a one-hot like vectors (supports batch as well)? For example:

`Expression one_hot(unsigned int vocab_size, const std::vector<unsigned int>& indices);`

will return an expression of batched one-hot representation according to indices and vocab size?

I am implementing the label smoothing (section 7, https://arxiv.org/pdf/1512.00567v1.pdf), but am still confused to figure out a good way. An example of label smoothing impl. is as follows:
```
dynet::Expression i_log_softmax = dynet::log_softmax(i_r_t);
dynet::Expression i_onehot = dynet::one_hot(_tfc._tgt_vocab_size, next_words);// not yet available!
dynet::Expression i_onehot_soft = (1.f - _tfc._label_smoothing_weight) * i_onehot + (_tfc._label_smoothing_weight / (_tfc._tgt_vocab_size - 1)) * (1.f - i_onehot);
i_err = dynet::transpose(i_log_softmax) * i_onehot_soft;
```
Looking for your help! Thanks!

**Comment by neubig** [comment]
Two things:
* If you want to implement label smoothing you actually don't really need a one-hot expression. See here: https://github.com/neulab/xnmt/blob/2e745aaf1a4da81640c2cb22fd7f30aa8da5b191/xnmt/decoder.py#L138
* If you want to do sparse input, like a one hot vector, you can use `sparse_inputTensor`: http://dynet.readthedocs.io/en/latest/python_ref.html#dynet.sparse_inputTensor

**Comment by duyvuleo** [comment]
Oh, my bad that i did not look at xnmt in details.

Thanks. Sorry for my silly issue.

**Comment by neubig** [comment]
No problem, this is not silly at all! I'm happy to answer questions.
