### ISSUE TITLE
dynet2.0.2 - to_device 

### ISSUE THREAD

**Issue by CathyW77** [clab/dynet#1162]
Hi,
    Recently, I instaill the latest dynet.
    I wanna use multiple devices, so I use "to_device( _X_ , **gpu1** )" to change _X_ to **gpu1**. But I found  it seems that when my training program moves on, the memory in gpu1 continues to increase. Old information seems still exists, and that leads to error " out of memory ". I wanna to ask if there is any way to free old information, just like my old _X_.

**Comment by xunzhang** [comment]
It sounds strange, could you give a sample code for me to reproduce/investigate?

**Comment by neubig** [comment]
Going to close this unless we can get an example.
