### ISSUE TITLE
AMSGrad

### ISSUE THREAD

**Issue by danielhers** [clab/dynet#1166]
[An ICLR submission](https://openreview.net/pdf?id=ryQu7f-RZ) shows a problem with Adam and suggests a better optimizer, AMSGrad - see more [here](http://ruder.io/deep-learning-optimization-2017/index.html#fixingtheexponentialmovingaverage). There are implementations in [Lasagne](https://github.com/Lasagne/Lasagne/pull/887/files), [Pytorch](https://github.com/pytorch/pytorch/pull/4034/files), [Keras](https://gist.github.com/kashif/3eddc3c90e23d84975451f43f6e917da). I think it should be one of the optimizers DyNet offers.

**Comment by neubig** [comment]
Go for it, thanks!

**Comment by kashif** [comment]
would a flag to the Adam trainer that uses Amsgrad be ok?

**Comment by neubig** [comment]
I think probably a separate trainer would be more appropriate.

**Comment by kashif** [comment]
@neubig  you can close this

**Comment by neubig** [comment]
Added by #1185 . Thanks @kashif !
