### ISSUE TITLE
POS tagger example

### ISSUE THREAD

**Issue by fiammettaAtGit** [clab/dynet#1168]
Hi,
after solving some problems with dynet installation, I was able to run some examples.
I'm interested with undestanding the POS tagger and the underlying LSTM network.
I just ran the example in the  "../dynet/examples/tagger/bilstmtagger.py"
changing the train_file and the test_file.
I'd like to know if is available a way (any command line or how I can write a script) to test single sentences, in order to check  single POS tagging result.
thanks a lot.

**Comment by neubig** [comment]
The examples are simply examples of how to program using DyNet, and not full POS taggers per say. If you want to do this you'll have to make a few modifications to the example code yourself.
