### ISSUE TITLE
Why is set_dropout method in RNNBuilder not virtual?

### ISSUE THREAD

**Issue by tohtsky** [clab/dynet#1174]
I'm developing a C++ application by which a user can choose the type of RNNBuilder at runtime.
A part of the code looks like this:

``` 
RNNBuilder* builder_factory(const std::string & type, unsigned layers, unsigned input_dim, 
        unsigned hidden_dim, ParameterCollection &model, float dropout_ratio){
    RNNBuilder * result;
    if(type == "SimpleRNN")
        result = new SimpleRNNBuilder(layers, input_dim, hidden_dim, model);
    else if(type == "VanillaLSTM") 
        result = new VanillaLSTMBuilder(layers, input_dim, hidden_dim, model);
    else ....

    result->set_dropout(dropout_ratio);  // calls RNNBuilder::set_dropout
    return result; 
} 
```

Since ``RNNBuilder::set_dropout`` is not marked virtual, it will not call those of derived classes,
so, for example, ``dropout_rate_h`` in ``VanillaLSTMBuilder`` remains 0 in the above example.
Is this the recommended behavior?

**Comment by neubig** [comment]
Hmm, this is probably a bug. Assuming so, we should fix this ASAP.

**Comment by tohtsky** [comment]
I believe it's been fixed by the above PR.
