### ISSUE TITLE
CMake Install error

### ISSUE THREAD

**Issue by sarahwie** [clab/dynet#1177]
I am trying to install Dynet with GPU functionality in a virtualenv. Running `pip install dynet` works fine, but as soon as I try `BACKEND=cuda pip install git+https://github.com/clab/dynet#egg=dynet`, or try it manually following the instructions [here](http://dynet.readthedocs.io/en/latest/python.html), I get an error at the `make -j num_cores` line. The `cmake` command works fine, so I'm not sure what's happening. Note: I get this error even when I don't specify the `-DBACKEND=cuda` flag with cmake for gpus.

This is the error I am getting:

`[  1%] Building NVCC (Device) object dynet/CMakeFiles/dynet.dir//./dynet_generated_gpu-merge3.cu.o
nvcc warning : The -std=c++11 flag is not supported with the configured host compiler. Flag will be ignored.
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/type_traits:35,
                 from /nethome/swiegreffe6/dynet-base/dynet/dynet/dim.h:12,
                 from /nethome/swiegreffe6/dynet-base/dynet/dynet/tensor.h:15,
                 from /nethome/swiegreffe6/dynet-base/dynet/dynet/tensor-eigen.h:8,
                 from /nethome/swiegreffe6/dynet-base/dynet/dynet/nodes-arith-cwise.cc:1,
                 from /nethome/swiegreffe6/dynet-base/dynet/build/dynet/gpu-merge3.cu:1:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/c++0x_warning.h:31:2: error: #error This file requires compiler and library support for the upcoming ISO C++ standard, C++0x. This support is currently experimental, and must be enabled with the -std=c++0x or -std=gnu++0x compiler options.
CMake Error at dynet_generated_gpu-merge3.cu.o.cmake:202 (message):
  Error generating
  /nethome/swiegreffe6/dynet-base/dynet/build/dynet/CMakeFiles/dynet.dir//./dynet_generated_gpu-merge3.cu.o

make[2]: *** [dynet/CMakeFiles/dynet.dir/./dynet_generated_gpu-merge3.cu.o] Error 1
make[1]: *** [dynet/CMakeFiles/dynet.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by neubig** [comment]
Hmm, it looks like your compiler may be too old (gcc 4.4.7 is 6 years old now). Try installing a newer version of gcc through yum and see if this solves the problem.

**Comment by sarahwie** [comment]
Thank you! Updating to gcc 4.8, everything runs fine.
