### ISSUE TITLE
How to transpose an expression? dy.transpose works unexpectedly

### ISSUE THREAD

**Issue by hankcs** [clab/dynet#1181]
Hi DyNet team,

I want to transpose a (100, 149) matrix (expression) to (149, 100) using `dy.transpose`, but DyNet gives me (1, 100, 149).

<img width="389" alt="hankcs com 2018-01-13 7 54 14" src="https://user-images.githubusercontent.com/5326890/34906648-21b69c68-f837-11e7-8fc7-4e335521847a.png">
<img width="437" alt="hankcs com 2018-01-13 7 54 35" src="https://user-images.githubusercontent.com/5326890/34906649-260a2104-f837-11e7-8ca5-b337d928e69d.png">

This behaviour is different with numpy:

```
import numpy as np
A = np.eye(100, 149)
np.transpose(A).shape
(149, 100)
```

How can I do numpy-like transposing in DyNet? I want to implement a "batched" version of Character-level model, where word embeddings are final char-lstm states. Here I have 149 words, the so-called `subword_embs` is a matrix of final lstm states for every word. I want to use this matrix as a lookup table.

Thanks!

**Comment by neubig** [comment]
I was not able to reproduce this, see below:

    >>> import dynet as dy
    [dynet] random seed: 2294189396
    [dynet] allocating memory: 512MB
    [dynet] memory allocation done.
    >>> val = dy.zeros((100,149))
    >>> valT = dy.transpose(val)
    >>> val.npvalue().shape
    (100, 149)
    >>> valT.npvalue().shape
    (149, 100)

If the above code gives you a different result than me, could you please tell us more about your environment: what version of Python and DyNet?

**Comment by hankcs** [comment]
Thanks for the quick reply. I'm using DyNet 2.0 in Python3. Your code gives me the correct result. I guess it's due to my error somewhere else. Let me debug deeper.

**Comment by hankcs** [comment]
Just figured out, this is due to the special batch implementation in DyNet. In case that other beginners may wonder, let me explain a little.

You simply can't transpose the batch dim of an expression. A batched matrix is actually a list of vectors, so dy.transpose only transpose those column vectors (100,) into row vectors (1, 100). It can be reproduced like this:

```
import dynet as dy
import numpy as np

a = np.eye(100, 149)
b = dy.inputTensor(a, batched=True)
print(dy.transpose(b).npvalue().shape)
```

Outputs:

```
(1, 100, 149)
```

**Comment by neubig** [comment]
Yes, DyNet does things differently with regards to minibatching, and for posterity: people who are interested can find more info here: http://dynet.readthedocs.io/en/latest/minibatch.html#minibatching
