### ISSUE TITLE
segmentfault ---------------

### ISSUE THREAD

**Issue by zhang-wen** [clab/dynet#119]
hello, everyone, i try to invoke the load_array function of a Parameters type like this, 

i from _gdynet import *
attention_w1.load_array(numpy_val), but it show segment fault, somebody can fix this problem ? appreciate for this ...

and i fount another problem, i try to run cpu_vs_gpu.py which is ok, even i do not add --dynet-gpu command.
CPU time: 0.525084018707
GPU time: 0.013307094574

but when i run rnnlm.py, the speed is even slower on gpu than that on cpu, i can not figure out what is the reason, can any developers help me about this ?  how to use the gpu, i try to use --dynet-gpu in command line, and i try to import _gdynet, but all seem to be failed ..

i know dyne is a new python network toolkits, there are some bugs, i understand.

**Comment by yoavg** [comment]
re load_array, we'll check.

re speed -- for small matrices the overhead of using the GPU is not worth it. Try increasing the size of the layers in rnnlm.py

**Comment by zhang-wen** [comment]
thank you for reply.  the init_from_array function of lookup_table Parameters works well, but there are some problems for as_array()

another issue:
i implement an lstm-attention model by using dynet, however, if i increase the size of the size of the 
layers and weights, after it update several times, it always shows following error:

Loss[713.869873047], Upd[42.8563950062s], AvgSents/batch[3511/80=43], AvgUpd/sent[0.996660348981]
dynet is out of memory, try increasing with --dynet-mem (current capacity: 1746927616)

i specify the memory in the command line :  --dynet-mem 5000
do i need to note somethings? i invoke renew_cg() once for each update...

**Comment by yoavg** [comment]
re load_array, it is now deprecated, and there is a new API:
https://github.com/clab/dynet/blob/master/python/CHANGES.md#parameter-initialization

see the newest version.

re memory problem, please open in a separate issue.
