### ISSUE TITLE
Using a vector for an input is either a type error, or a stale expression

### ISSUE THREAD

**Issue by AmitMY** [clab/dynet#1196]
I have input data that is already vectorized into dense vectors.

If I use that vector as is in my computation graph, I get the following error:

> TypeError: Argument 'x' has incorrect type (expected _dynet.Expression, got numpy.ndarray)

but if I wrap it with `dy.Expression`, I get:

> ValueError: Attempt to use a stale expression, from a previous Computation Graph.

Weirdly, the numpy array works for parameters multiplication, but does not for any dynet function like `dy.rectify` or `dy.dropout`, and the multiplication result with the parameter is a numpy array (and not a dynet expression)

**Comment by pmichel31415** [comment]
Yes, you need to implicitly input the numpy array in the computation graph with e.g. `inputTensor`. More details here: http://dynet.readthedocs.io/en/latest/tutorials_notebooks/API.html#Expression-building

**Comment by AmitMY** [comment]
Missed that in the doc. thanks for the fast response!
