### ISSUE TITLE
Implementation of a straight-through operator ?

### ISSUE THREAD

**Issue by FilippoC** [clab/dynet#1199]
Hello,

is there an easy way to implement a straight-through operator in dynet?
i.e.:
- Forward: argmax
- Backward: softmax loss

Thanks.

**Comment by pmichel31415** [comment]
FYI this is not doable with the current set of operations but I'm working on it

**Comment by FilippoC** [comment]
@pmichel31415  well, the easy way is to manually compute the argmax (i.e. outside dynet), create a new input with the argmax and then add (softmax - block_gradient(softmax)), but its kinda annoying.

**Comment by neubig** [comment]
Fixed by #1208
