### ISSUE TITLE
issue:   dynet is out of memory (--dynet-mem and error messages should be documented better)

### ISSUE THREAD

**Issue by zhang-wen** [clab/dynet#120]
no matter whether i use gpu or cpu, i always get following error:

dynet is out of memory, try increasing with --dynet-mem (current capacity: 3494903808)

even i use 1024 memory by --dynet-mem, still got above issue, is it 1024MB or 1024KB by --dynet-mem 1024 ?

**Comment by neubig** [comment]
This should be documented better, but the number for --dynet-mem is MB. Try setting it to a higher value than 1024. I'll keep this open as an enhancement for better documentation.

**Comment by zhang-wen** [comment]
thanks a lot, i still does not solve this issue, even i set it to be 5000MB which, i am sure, is enough large for my task, but it still show this memory error after training for a while, i am not sure whether should i free some memory after a while, have this interface ?

**Comment by neubig** [comment]
Are you using Python? If so, are you calling the renew_cg() function? If not, you need to call the renew_cg() function every time you start a new training example. If you are calling this function, could you please provide a minimal working example of your code and the data that causes it to crash?

**Comment by zhang-wen** [comment]
yes, @neubig , i am using Python. i call renew_cg() function every time i start a new batch training.
i implemented a lstm attention for nmt, the code is little bit complicated, and the training data is about 1.8M sentence pair, so i can provide the code and data, how can i do this ?

**Comment by neubig** [comment]
Well if you're doing mini-batches for a complicated model on large data, 5,000MB of memory still might not be enough. I usually use 12,000MB to train my full models. Perhaps you need to try reducing your minibatch size or increasing the amount of memory you can allocate. You can also try specifying memory like "--dynet_mem 2000,2000,1000" which will allocate 2000MB for the forward step, 2000MB for the backward step, and 1000MB for the parameter storage, and adjust these values so that your parameters just barely fit in memory and the rest of the memory is allocated to the forward and backward passes.

**Comment by zhang-wen** [comment]
thank you so much. i have been perplexed by this issue for a long time, i will try according to what you said. However, i have trained the same model by using Theano, the memory training use is less than 5000M, i think 5000M is enough.

my code here:
https://github.com/zhang-wen/dynmt.git , but i did not upload training data, so you can not run my code. can you help me to check `upd_loss_wbatch_with_atten_sbs` function in `nmt.py`

**Comment by neubig** [comment]
Sorry, I don't have time to debug code in a big separate toolkit like this, but if you can come up with a minimal example (50 lines or so, with the associated data) where dynet uses more memory than the corresponding theano code we might be able to do some optimization.

**Comment by zhang-wen** [comment]
hi, @neubig , i have come up with a minimal example based on your rnnlm.py example, the small code is here: 
https://github.com/zhang-wen/dymem-test.git
you just need to run: (i allocate 8000M memory)
`sh run.sh runlm.py`
after about 10 seconds, you will get following error:
dynet is out of memory, try increasing with --dynet-mem (current capacity: 2795503616)
hope you can figure out this issue, thanks a lot.

**Comment by neubig** [comment]
Thanks! For reference, how much memory does theano use with similar settings on this data?

**Comment by zhang-wen** [comment]
it is different, for this demo code, i just make the vocabulary size larger, i set the output size of lstm unit to be the size of large vocabulary, actually i do not know where it is reasonable.
the training data of this rnnlm demo is just one sentence (about 20 training samples, no batch), but in my real task, the training sample is 18M sentence pair, even using batch, it is much larger than this demo. Usually, theano use less than 5000M memories on my real data with similar settings.


------------------------------------------------------------------------------------
张文，在读博士
中国科学院计算技术研究所
中科院智能信息处理重点实验室
自然语言处理研究组
---
Wen Zhang, Ph.D Candidate
Natural Language Processing Research Group
CAS Key Laboratory of Intelligent Information Processing
Institute of Computing Technology, Chinese Academy of Sciences

已使用 Sparrow (http://www.sparrowmailapp.com/?sig)


在 2016年10月28日 星期五，15:37，Graham Neubig 写道：

**Comment by zhang-wen** [comment]
i set the memory to be 10,000M which is the upper limit of our sever , still not enough ...

DEBUG:network:one column words in each batch loss => <type '_gdynet.Expression'> (1,) [ 300.40194702]
dynet is out of memory, try increasing with --dynet-mem (current capacity: 3494903808)
run.sh: line 2: 55268                python $1 --dynet-gpu --dynet_mem 10000 --dynet-gpu-ids 2

**Comment by neubig** [comment]
documentation is done, so i'll close this.
