### ISSUE TITLE
Best practice for training a memory-intensive model on the GPU

### ISSUE THREAD

**Issue by vered1986** [clab/dynet#1204]
Hi,

I'm trying to train my model on the GPU and I'm struggling with memory issues. General relevant details are:

- I have 300d pre-trained embeddings for many words, so they don't fit in the GPU memory.
- I don't need to update the embeddings.
- I can run on multiple GPUs.
- The model includes an LSTM.

I'd love to get some tips on the best practices of how to train a model that needs a large amount of memory. I played with several parameters such as training on CPU/one GPU/two GPUs, auto batching/no auto batching, batch size (1/10), setting or not setting the memory in advance. Nothing seems to work well:

1. Training on CPU works if I set the memory to 32MB, but it's very slow.

2. Training on GPU(s) and loading all the embeddings to a lookup table either causes a memory error in the initialization (if I try to set the memory higher than the GPU's memory limits) or during training (if I don't set the memory in advance and it fails to increase the memory pool).

3. Training on GPU(s) and putting the lookup table on the CPU, then moving specific expressions to the GPU during training caused exceptions of expressions being in different devices (how do I know which GPU to move the expression to if I'm using two GPUs?). 

4. Training on GPU(s) and instead of creating a lookup table for the embeddings, loading the vectors of each batch separately using inputTensor: very slow and only works with batch size 1, otherwise occasionally a batch consumes too much memory and causes `RuntimeError: cudaMalloc(&ptr, n)`.

Thanks in advance!

**Comment by roeeaharoni** [comment]
- Regarding 2 - how many words do you have in the pre-trained embeddings vocabulary? Did you try to filter it according to the training vocabulary in your task?

- Regarding 4 - do you truncate/ignore very long sentences (say, above 50 tokens)? many times the training data contains very long sentences that cause out-of-memory exceptions

**Comment by vered1986** [comment]
Thanks @roeeaharoni! I have 1.1M words in my vocabulary (I'm only loading the embeddings for the words in my dataset), and I'm my sequences all have at most 15 tokens. However, each instance can have multiple (up to 30,000) sequences.

**Comment by neubig** [comment]
@vered1986 I think 3. is the right way to go, but we need a good example of this. Perhaps I and @xunzhang can help, but would it be possible for you to mock up an example of what you're trying to do in a simple Python script? We will work with it and try to create this as a more sophisticated multi-device example.

**Comment by Aditi138** [comment]
I have a somewhat similar question. I am training on a corpus having 56M corpus and have a GRU over the characters. Since the corpus is large, is there a provision to just put the batch on the GPU and run the matrix operations on GPU or does --dynet-gpu do this optimization automatically? Since I want to update the embeddings as well, they reside on the CPU, what would be the best strategy to minimize cpu-gpu interaction?

**Comment by neubig** [comment]
@Aditi138 Normally you will split your 56M corpus into smaller mini-batches which will all fit in your GPU memory. The best strategy to minimize CPU-GPU interaction is to call lookup_batch on CPU, move the memory on GPU, then do everything else on GPU. That being said, depending on your application, you might not need GPU at all; CPU can be very competitive for smaller models. Have you tried just running on CPU? If it's close in efficiency to the GPU, you could also consider trying multi-processing: http://dynet.readthedocs.io/en/latest/multiprocessing.html

**Comment by vered1986** [comment]
Sorry for the late reply. I took another look at https://github.com/clab/dynet/blob/9ab97efb3daa5c2dd8ca01bc51780dda6b0c265a/examples/devices/xor-multidevice.py and I think I understand better now: you need to specify exactly what needs to be computed in each device. I think I originally expected that multidevice support means that parameters are somehow moved across devices according the available memory in each device.

**Comment by neubig** [comment]
Yes, that is correct. It is not easy to automatically move parameters across devices in a dynamic framework like DyNet, which is one of their disadvantages compared to TensorFlow for example.
