### ISSUE TITLE
how to configure  neural networks with dynet? 

### ISSUE THREAD

**Issue by yaira24** [clab/dynet#1207]
I what to use dynet(c++) to build neural networks with 39 inputs, 50 hidden and 10 outputs.
I go over the examples and this is not clear how to this configure this type of neural networks.
same of the examples need input files that are not in the source code.

how can I configure, train and test neural networks?
where can I find a good example or documentation to understand how to work with dynet

**Comment by neubig** [comment]
Here you go: https://github.com/clab/dynet/blob/master/examples/fflm/train_fflm.cc
