### ISSUE TITLE
python's Parameters.load_array not implemented for GPU

### ISSUE THREAD

**Issue by yoavg** [clab/dynet#121]
The  python binding has a method of initializing the parameters with a numpy array.
This is currently not supported for the GPU.

**Comment by zhang-wen** [comment]
m = dy.Model()
n = numpy.asarray([1,2,3])
w = m.add_parameters(n)

you mean this? i have tested it, it doesn't work for cpu and gpu.

**Comment by yoavg** [comment]
This is not how `add_parameters` is supposed to be used.
This bug report is about `load_array` not working on the GPU.

**Comment by zhang-wen** [comment]
okay, i see. thank you.

**Comment by yoavg** [comment]
Python initialization now uses the new cpp initialization API.
https://github.com/clab/dynet/blob/master/python/CHANGES.md#parameter-initialization
