### ISSUE TITLE
Setting initial hidden state of a new input sequence to final hidden state of the previous

### ISSUE THREAD

**Issue by sarahwie** [clab/dynet#1210]
Is there a way I can maintain/store the last hidden state of the previously processed input sequence to use to initialize the hidden state of the next input sequence, while still backpropagating for each input? I am currently doing this by not renewing the computation graph until all inputs have been processed, but I would still like to backpropagate at each input. The hidden state become a stale expression when I renew the computation graph at each input to allow for this. I know this is possible in other languages, does this functionality exist in Dynet?

Here's my code:
`

    for i in xrange(NUM_EPOCHS):

        dy.renew_cg()

        #start a fresh list to store values
        j = 0
        sum_of_losses = []
        z = 0
        for sentence in sentences:
            z = z + 1
            if z == 1:
                loss, st = do_one_sentence(rnn, "first", None, sentence, params, vocab, pc, 'perplexity')
            else:
                loss, st = do_one_sentence(rnn, None, st, sentence, params, vocab, pc, 'perplexity') 
            # sum accumulated losses, and do forward-backward as usual.
            batch_loss = dy.esum(loss)/len(loss)
            print "batch %d loss:" % z, batch_loss.value() # call forward on batch
            print "train perpl.", (dy.exp(batch_loss)).npvalue()
            #call backward pass
            batch_loss.backward()
            #print(batch_loss.gradient())

            trainer.update()

     def do_one_sentence(rnn, status, state, sentence, params, word2int, pc, loss_fn):
        if status is not None:
            s = rnn.initial_state()
        else:
            s = state

        R = dy.parameter(params["R"])
        bias = dy.parameter(params["bias"])
        lookup = params["lookup"]
        sentence = [word2int[c] for c in sentence]
        loss = []
        for word,next_word in zip(sentence,sentence[1:]):
            s = s.add_input(lookup[word])
            preds = dy.log_softmax(R*(s.output()) + bias)
            loss.append( -(dy.pick(preds,next_word)))

        return loss, s
`

where the `do_one_sentence()` loss calculation function accepts as input a state to set as the first hidden state, unless this is the first input in the entire sequence of input sequences, in which case i use the `initial_state()` function.

I get the following output:
`

            batch 1 loss: 5.59098720551
            train perpl. [ 268.00006104]
            batch 2 loss: 5.59098720551
            train perpl. [ 268.00006104]
            batch 3 loss: 5.59098720551
            train perpl. [ 268.00006104]
            batch 4 loss: 5.59098720551
            train perpl. [ 268.00006104]
            batch 5 loss: 5.59098720551
            train perpl. [ 268.00006104]
            batch 6 loss: 5.59098720551
            train perpl. [ 268.00006104]
            batch 7 loss: 5.59098720551
            train perpl. [ 268.00006104]
            batch 8 loss: 5.59098720551
            train perpl. [ 268.00006104]
            epoch size 8
            EPOCH 1 LOSS (avgd across all the batches): 5.59098720551

            batch 1 loss: 5.29239845276
            train perpl. [ 198.81971741]
            batch 2 loss: 5.29185581207
            train perpl. [ 198.71185303]
            batch 3 loss: 5.29110336304
            train perpl. [ 198.56239319]
            batch 4 loss: 5.29053401947
            train perpl. [ 198.44937134]
            batch 5 loss: 5.29016399384
            train perpl. [ 198.3759613]
            batch 6 loss: 5.28990268707
            train perpl. [ 198.3241272]
            batch 7 loss: 5.28968906403
            train perpl. [ 198.2817688]
            batch 8 loss: 5.28950023651
            train perpl. [ 198.24432373]
            epoch size 8
            EPOCH 2 LOSS (avgd across all the batches): 5.2906434536
`

I'd like output similar to a model doing the same thing in Torch:
`

            epoch size	8	
            epoch = 0.125, summed losses = 5.591, train perp. = 268.000, wps = 1, dw:norm() = 2.239, lr = 1.000, since beginning = 0 mins.	
            epoch = 0.250, summed losses = 5.613, train perp. = 273.874, wps = 2, dw:norm() = 4.137, lr = 1.000, since beginning = 0 mins.	
            epoch = 0.375, summed losses = 5.860, train perp. = 350.625, wps = 3, dw:norm() = 7.377, lr = 1.000, since beginning = 0 mins.	
            epoch = 0.500, summed losses = 5.875, train perp. = 356.143, wps = 5, dw:norm() = 1.988, lr = 1.000, since beginning = 0 mins.	
            epoch = 0.625, summed losses = 5.892, train perp. = 362.207, wps = 6, dw:norm() = 1.973, lr = 1.000, since beginning = 0 mins.	
            epoch = 0.750, summed losses = 5.909, train perp. = 368.362, wps = 7, dw:norm() = 1.913, lr = 1.000, since beginning = 0 mins.	
            epoch = 0.875, summed losses = 5.927, train perp. = 374.883, wps = 9, dw:norm() = 1.875, lr = 1.000, since beginning = 0 mins.	
            epoch = 1.000, summed losses = 5.945, train perp. = 381.892, wps = 10, dw:norm() = 1.847, lr = 1.000, since beginning = 0 mins.	

            epoch = 1.125, summed losses = 5.861, train perp. = 351.061, wps = 10, dw:norm() = 1.734, lr = 1.000, since beginning = 0 mins.	
            epoch = 1.250, summed losses = 5.851, train perp. = 347.539, wps = 11, dw:norm() = 1.803, lr = 1.000, since beginning = 0 mins.	
            epoch = 1.375, summed losses = 5.464, train perp. = 235.958, wps = 12, dw:norm() = 2.286, lr = 1.000, since beginning = 0 mins.	
            epoch = 1.500, summed losses = 5.355, train perp. = 211.647, wps = 13, dw:norm() = 1.997, lr = 1.000, since beginning = 0 mins.	
            epoch = 1.625, summed losses = 5.246, train perp. = 189.755, wps = 15, dw:norm() = 2.002, lr = 1.000, since beginning = 0 mins.	
            epoch = 1.750, summed losses = 5.144, train perp. = 171.403, wps = 16, dw:norm() = 1.999, lr = 1.000, since beginning = 0 mins.	
            epoch = 1.875, summed losses = 5.048, train perp. = 155.639, wps = 17, dw:norm() = 1.981, lr = 1.000, since beginning = 0 mins.	
            epoch = 2.000, summed losses = 4.955, train perp. = 141.863, wps = 18, dw:norm() = 1.957, lr = 1.000, since beginning = 0 mins.
`

where the loss is being calculated and the weights updated from each input in the computation graph created at the epoch.

Or, alternatively, if I do renew the computation graph at each input so that I can backpropagate and update the parameters for each input, is there a way I can preserve the state from the previous cg prior to resetting, to use for initialization? I haven't been able to find a method for getting any preservable value out of an `RNNState()` object

**Comment by neubig** [comment]
You'll want to use `npvalue()` to get a numpy array from the previous graph, then `inputTensor()` to add it again after you renew the graph.

**Comment by sarahwie** [comment]
Updated- I need not to renew the computation graph in order to be able to backprop the loss through all prior inputs, so just using `npvalue()` to pull the hidden state value out doesn't work in this case. The fact that the parameters are not being updated for each input as shown in the output above even though I am calling `loss.backward()` and `trainer.update()` at each input is a bug that I haven't been able to resolve.

**Comment by neubig** [comment]
What happens when you just don't call `renew_cg()` until you are completely done with the graph? I think this should work fine, even if you call `backward()` multiple times between `renew_cg()` calls.

**Comment by sarahwie** [comment]
Oops, deleted the comment. I am currently not calling `renew_cg()` until I am done with the graph. When I call it at each input, I get standard loss updating behavior.

**Comment by sarahwie** [comment]
Original follow-up comment that was deleted (for reference) was that I am observing no parameter updates when calling `loss.backward()` followed by `trainer.update()` at each input in the above code. The loss only appears to be changing at the end of an epoch, which happens to also be when I am renewing the computation graph. I don't want to just reset the computation graph at each input and set the initial state to the hidden state values, as I originally stated would be a fix, because I want to backprop through all prior input sequences as well as the current.

**Comment by neubig** [comment]
OK, thank you, I understand now. This will be

**Comment by sarahwie** [comment]
Another (potentially related) error is when I attempt to print `batch_loss.gradient()` following `batch_loss.backward()`, I get the following error:

`
RuntimeError: Requested gradient for node 113, but backward pass was computed from node 112`

**Comment by neubig** [comment]
So the gradient of the loss function will always be the scalar "1", so this is not very informative. That being said, it shouldn't throw an error, so I'll try to fix this.

**Comment by emanjavacas** [comment]
Sorry to reopen the thread. I am using `prev_hidden = dynet.inputTensor([h.npvalue() for h in state.s()])` to keep the hidden state of the previous sentence. Then I use `self.builder.initial_state(prev_hidden)` on the next sequence to initialize with the previous hidden state and I am observing that everything slows down by a factor of 3. Not sure why that operation would cause such a slow down.

A related question would be how to actually backpropagate through a number of consecutive sequences. I can imagine that since we are extracting the tensor from the expression, the computational graph is also cut from its previous history. Still I would like to backpropagate through a number of consecutive sentences to implement a kind of BPTT at the level of sequences.

Any help will be very much welcomed! Thanks!
