### ISSUE TITLE
dynet with cuda compilation error

### ISSUE THREAD

**Issue by yaira24** [clab/dynet#1211]
I compile dynet with this flags 
cmake .. -DEIGEN3_INCLUDE_DIR=C:\eigen -DENABLE_CPP_EXAMPLES=ON -DBACKEND=cuda -DCUDNN_ROOT=C:\cudnn-9.1-windows7-x64-v7\cuda -G"Visual Studio 14 2015 Win64"

I see that all the information is good
-- The C compiler identification is MSVC 19.0.24225.1
-- The CXX compiler identification is MSVC 19.0.24225.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BACKEND: cuda
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1 (found version "9.1")
CUDA_LIBRARIES: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.1/lib/x64/cudart_static.lib
-- Found CUDNN (include: C:/cudnn-9.1-windows7-x64-v7/cuda/include, library: C:/cudnn-9.1-windows7-x64-v7/cuda/lib/x64/cudnn.lib)
-- Successfully include CUDNN flags
-- Eigen dir is C:/eigen
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done

when I build the project in visual 2015 I get this error:
Severity	Code	Description	Project	File	Line	Source	Suppression State	Tool
Error		assertion failed at: "C:/dvs/p4/build/sw/rel/gpu_drv/r387/r387_00/drivers/compiler/edg/EDG_4.12/src/lookup.c", line 2652	dynet	C:\Users\Alon\Downloads\dynet-master\build\dynet\CUSTOMBUILD		

what do I need to do to solve this issue?

**Comment by neubig** [comment]
I'm not sure, but maybe @mattr1 or someone familiar with Windows can help?

**Comment by mattr1** [comment]
I have no idea what that that error might be. Do you know what is c:\dvs? Or "EDG 4.12"? Or "r387"? Looks like maybe your graphics driver? Or is that a CUDA compiler of some sort? Perhaps look in build\CMakeCache.txt to see what variables are pointing to that path (c:\dvs\p4\build\sw\rel\gpu_drv\r387\....) to get a hint about what might be going wrong? Also, maybe look at the assert in that file, in line 2652, to see what assert is failing?

**Comment by yaira24** [comment]
there is no c:\dvs..., I have no clue what "EDG 4.12"? Or "r387" is.
CMakeCache.txt don't have any data that have this kind of information.
this issue related to CUDA, I set new project without CUDA and I don't get this errors.
what the CUDA & CUDNN version dynet is supported?  I will like to download this type of version to check maybe this is a compatibility issue whit the CUDA versions
thanks

**Comment by mattr1** [comment]
Do you have access to another machine with a different graphics card? It looks like something about your graphics driver. R387 seems to be the release of the NVidia driver from last November. I guess the assert is in the driver itself, and that path is the path of the compilation that NVidia did? Perhaps try updating your graphics driver (or downgrading)??

Another option: When you do the compile, look at the "Output" tab instead of the Errors tab. Sometimes it gives more of a clue about what is happening. You might be able to find out what line of code in dynet is calling something that is triggering this assert. It might help if you also just compile the "dynet" project (right-click on the project and choose Build) so you have less output to dig through. And that will help verify the problem is with that project.

**Comment by yaira24** [comment]
I build only the dynet project and get the same error.
I removed CUDA 9.1 and install CUDA 8.0 with CUDNN 5.1 and was able to compile the project.
but when I run mnist example I get a runtime exception 

Exception thrown at 0x000000013F4A9439 in mnist.exe: 0xC0000005: Access violation reading location 0x0000000000000080.

this is the call stuck: 
 	mnist.exe!dynet::AffineTransform::backward_dev_impl<class dynet::Device_GPU>(class dynet::Device_GPU const &,class std::vector<struct dynet::Tensor const *,class std::allocator<struct dynet::Tensor const *> > const &,struct dynet::Tensor const &,struct dynet::Tensor const &,unsigned int,struct dynet::Tensor &)	C++
>	mnist.exe!dynet::AffineTransform::backward_impl(const std::vector<dynet::Tensor const *,std::allocator<dynet::Tensor const *> > & xs, const dynet::Tensor & fx, const dynet::Tensor & dEdf, unsigned int i, dynet::Tensor & dEdxi) Line 219	C++
 	mnist.exe!dynet::Node::backward(const std::vector<dynet::Tensor const *,std::allocator<dynet::Tensor const *> > & xs, const dynet::Tensor & fx, const dynet::Tensor & dEdf, unsigned int xs_i, dynet::Tensor & dEdxi) Line 65	C++
 	mnist.exe!dynet::SimpleExecutionEngine::backward(unsigned int from_where, bool full) Line 270	C++
 	mnist.exe!dynet::ComputationGraph::backward(const dynet::Expression & last, bool full) Line 403	C++
 	mnist.exe!main(int argc, char * * argv) Line 125	C++
 	[External Code]	


this is the output of the run 
[dynet] initializing CUDA
Request for 1 GPU ...
[dynet] Device Number: 0
[dynet]   Device name: GeForce GTX TITAN X
[dynet]   Memory Clock Rate (KHz): 3505000
[dynet]   Memory Bus Width (bits): 384
[dynet]   Peak Memory Bandwidth (GB/s): 336.48
[dynet]   Memory Free (GB): 12.3129/12.8849
[dynet]
[dynet] Device(s) selected: 0
[dynet] random seed: 2414496279
[dynet] allocating memory: 2048MB
[dynet] memory allocation done.
Parameters will be written to: encdec_mlp_784-512-relu-0.2_512-512-relu-0.2_512-
10-softmax_8732.params
**SHUFFLE
CUBLAS failure in cublasSgemm(dev.cublas_handle, CUBLAS_OP_T, CUBLAS_OP_N, dEdxi
.d.rows(), dEdxi.d.cols()*dEdxi.d.batch_elems(), xs[i-1]->d.rows(), dev.kSCALAR_
ONE, xs[i-1]->v, xs[i-1]->d.rows(), dEdf.v, dEdf.d.rows(), dev.kSCALAR_ONE, dEdx
i.v, dEdxi.d.rows())
14

I have a dynet project without CUDA that I run this example and get a result without any exception.

what do I need to check to solve this issue?
thanks
