### ISSUE TITLE
CURAND failure

### ISSUE THREAD

**Issue by eunice730711** [clab/dynet#1218]
Hi, 

I’m trying to run the example file below on my Ubuntu16.04.
https://github.com/clab/dynet/blob/master/examples/devices/cpu_vs_gpu.py
but I got this error message.

```
CURAND failure in curandGenerateUniform(curandeng, val.v, val.d.size())
201
Process Process-2:
Traceback (most recent call last):
File “/home/emily/anaconda3/lib/python3.6/multiprocessing/process.py”, line 258, in _bootstrap
self.run()
File “/home/emily/anaconda3/lib/python3.6/multiprocessing/process.py”, line 93, in run
self._target(*self._args, **self._kwargs)
File “test.py”, line 28, in do_gpu
gpW = gm.add_parameters((1000,1000))
File “_dynet.pyx”, line 1192, in _dynet.ParameterCollection.add_parameters
File “_dynet.pyx”, line 1218, in _dynet.ParameterCollection.add_parameters
RuntimeError: curandGenerateUniform(curandeng, val.v, val.d.size())
```
My GPU device is GeForce GTX 1050 Ti and with driver version 384.
What do I need to do to solve this issue?

**Comment by neubig** [comment]
For reference, what version of CUDA are you using? If you don't know, you can get it by running `nvcc --version`.

**Comment by eunice730711** [comment]
After upgrading to CUDA 8.0, the problem fixed. Thank you!
