### ISSUE TITLE
Scala test failing on GPU

### ISSUE THREAD

**Issue by shuheik** [clab/dynet#1219]
ParameterInitSpec is failing since #1154 on GPU, ParameterInit.normal(10, 4) is returning an average around 0.0.
Replacing this line 
https://github.com/clab/dynet/blob/5309f1119b11f0f87896764ece4f7993bc64db68/dynet/tensor.cc#L274
with
`    CURAND_CHECK(curandGenerateNormal(curandeng, val.v, val.d.size(), mean, stddev));`
eliminates the error.

**Comment by neubig** [comment]
Thanks for pointing this out! This was a bad bug, but has been fixed.
