### ISSUE TITLE
Layer Normalization

### ISSUE THREAD

**Issue by zhang-wen** [clab/dynet#122]
hello, guys, do implementations of run or lstm in  dynet use Layer Normalization Technique which can speed run Training (make earlier convergence) , if not, i suggest that you guys try it, thanks.

**Comment by neubig** [comment]
You're referring to this, right?: https://arxiv.org/abs/1607.06450

This is not implemented, but it'd be nice to have. If you want to implement it @zhang-wen , we'd certainly appreciate a pull request.

**Comment by zhang-wen** [comment]
yes, it is that paper.
need to implement by C++ ?

**Comment by neubig** [comment]
Yes, C++ would be better. If that is not possible a prototype in Python might also be sufficient to allow us to translate it into c++.

**Comment by zhang-wen** [comment]
https://github.com/ryankiros/layer-norm/blob/master/layers.py 
actually this contains an implementation on theano and torch, which is probably implemented by Jamie Ryan Kiros.
you can see the ln() function, but i think if you add Layer Normalization in your network framwork, it still need some coding, because the Layer Normalization is applied on the weights and bias of lstm, gru or run.

**Comment by danielhers** [comment]
Is *batch* normalization implemented?

**Comment by neubig** [comment]
No, neither of these are implemented, but we'd be happy to have a pull request!

**Comment by neubig** [comment]
Layer norm is implemented by https://github.com/clab/dynet/pull/482
