### ISSUE TITLE
buggy python RNN.initial_state(vecs)

### ISSUE THREAD

**Issue by yoavg** [clab/dynet#1223]
This function (as well as the one initializing a state from raw vectors) is buggy:

https://github.com/clab/dynet/blob/850c4c87f966a9f9f96e06f0ad12a2b20bd95ebb/python/_dynet.pyx#L4652

the `vecs != None` case should be outside the cg version check.

**Comment by neubig** [comment]
Fixed by https://github.com/clab/dynet/pull/1228
