### ISSUE TITLE
mini-batched AffineTransform in Python (needs documentation)

### ISSUE THREAD

**Issue by zhang-wen** [clab/dynet#123]
if i use the result of lookup_table to be the parameter of add_input(), it works fine;
s = s0.add_input(from_lookup_table), works well

however, if i construct a vector or matrix myself, the shape is the same with lookup_table result. it doesn't work, such as:
s = s0.add_input(dy.matInput(hid_sz, batch_sz))
s = s0.add_input(expr0)
error:
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Bad dimensions for AffineTransform: [{32} {32,32} {32,80}]

very weird, appreciated if somebody helps me about this issue.

**Comment by neubig** [comment]
DyNet does batching differently from other libraries. When you do input, you need to not specify a matrix with "hid_sz x batch_sz" dimensions, but create a vector with "hid_sz" dimensions, that has a special mini-batch dimension with size "batch_sz". I'm not sure how to do this in Python though, maybe @yoavg knows?

This needs to be documented, related to #85 , but I'll leave this open in case other people are confused.

**Comment by chaitanyamalaviya** [comment]
Is there any workaround to this for Python? I am facing the same issue as reproduced above while minibatching.

**Comment by neubig** [comment]
Just FYI, you can find an example of minibatched input here: https://github.com/clab/dynet_tutorial_examples/blob/master/tutorial_rnnlm_minibatch.py

Better documentation is pending.

**Comment by chaitanyamalaviya** [comment]
I managed to get it to work now! Thanks!

**Comment by neubig** [comment]
Given the documentation (http://dynet.readthedocs.io/en/latest/minibatch.html), I believe this issue has been fixed.
