### ISSUE TITLE
Is it possible to achieve a dropout behavior but set manually the omitted neurons?

### ISSUE THREAD

**Issue by yanaiela** [clab/dynet#1230]
For example, I'd like to use only a subset of the encoded vectors for a constant number of iterations. But I also want to control exactly which neurons I use and be able to switch the subset if needed.

**Comment by yoavg** [comment]
This sounds like masking. Create a parameter vector of the desired dimension, set its values to 0 and 1 according to the desired pattern, and then `cmult` it with the vectors you want to mask.

**Comment by yanaiela** [comment]
sounds good! thanks
