### ISSUE TITLE
l2_norm() backward fails when the L2 norm is zero

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1232]
Currently the `l2_norm()` function fails when the L2 norm is zero, giving NaN on the backward pass due to a divide by zero error. This should be fixed.

**Comment by pmichel31415** [comment]
Hmm how should we fix this? the l2 norm doesn't have a derivative on 0 (and there is an infinity of possible values, one in each direction)

**Comment by neubig** [comment]
I think we should set the gradient to zero (and have this documented)
