### ISSUE TITLE
How to populate only a Builder with an already saved model?

### ISSUE THREAD

**Issue by smar111** [clab/dynet#1235]
Hi,
So I have asked this question before but I was unable to get a satisfactory answer. I know that simple parameters can be individually populated using the .populate(,) function but it doesn't work for Builder. How to do it then for individual builders?

**Comment by yoavg** [comment]
You can save and load its `.param_collection`:

`builder.param_collection().populate(...)`

**Comment by smar111** [comment]
It doesn't work. I am using C++. I get the error: builder has no method param_collection()

**Comment by smar111** [comment]
Yes you are right. I tried that as well. Then the error changes to get_parameter_collection() has no method "populate". I am wondering if this is implemented for C++ at the moment?

**Comment by xunzhang** [comment]
Sorry for the late reply. The interface is a little different between C++ and Python. In Python, the `populate` function is a method of `Parameter`, `LookupParameter`, `ParameterCollection` or a builder. In C++, only a loader owns `populate` methods.

The `populate` method of a loader takes a `ParameterCollection`, a `parameter` or `LookupParameter` as its argument. So for your case, I think probably what you need is something as below:
```
ParameterCollection m_src, m_dst;
builder_src = RNNBuilder(LAYERS, INPUT_DIM, HIDDEN_DIM, m_src);
dynet::TextFileSaver sv("/tmp/tmp.model");
sv.save(builder_src.get_parameter_collection());
builder_dst = RNNBuilder(LAYERS, INPUT_DIM, HIDDEN_DIM, m_dst);
dynet::TextFileLoader ld("/tmp/tmp.model");
ld.populate(m_dst);
```

I'll add more examples and documentation, please keep an eye on the update from https://github.com/clab/dynet/issues/1212.

**Comment by smar111** [comment]
Oh so you mean if I want to use a Builder builder_src to initialize another one builder_dst later, I need to save that Builder's parameter collection (builder_src) in a separate file and then use it to load into builder_dst? 

I thought it should have been more straightforward than that. For instance, if I have already saved a model using save(model) I should be able to just access the Builder in that same as what is done for the Parameter and LookupParameter. 

But anyways thank you for the reply. This should work.

**Comment by xunzhang** [comment]
One possible way for your requirement is to write a wrapper builder inherits the built-in builder and in the constructor of your builder_wrapper/builder, populate the `ParameterCollection` object. But if you don't need a customized builder, the directest way is the answer I replied above.

**Comment by smar111** [comment]
Thanks for the reply.
