### ISSUE TITLE
Build fails on Windows, becasue 'unistd.h' is missing

### ISSUE THREAD

**Issue by slaweks17** [clab/dynet#1237]
Hi,
When I try to build the latest code with Visual Studio 2015, several examples fail to build, e.g.
<...>\examples\cpp\imdb\train_imdb.cc(17): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory

Regards,
Slawek

**Comment by neubig** [comment]
This isn't the latest code, as the latest code has no `examples/cpp` directory. Could you make sure you're using the latest version of the master branch of DyNet and try again?

**Comment by slaweks17** [comment]
Hi,
Well they are there if after executing 
git clone https://github.com/clab/dynet.git
I follow (as per instructions on the first page) with
cd dynet
# Checkout the latest release
git checkout tags/v2.0

Regards,
Slawek

**Comment by neubig** [comment]
Can you do git checkout master instead? v2.0 is an old version of DyNet.

**Comment by slaweks17** [comment]
Hi,
Yes, things are OK on master. But I am now pointing to the apparently wrong instructions on the Dynet website.

Regards,
Slawek

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by neubig** [comment]
Thank you for pointing this out, we've fixed the instructions.
