### ISSUE TITLE
to_device in python

### ISSUE THREAD

**Issue by mpsilfve** [clab/dynet#1260]
I get a segmentation fault when running the following code on a GPU using the dynet python interface (version 2.0 according to `dynet.__version__`). The idea is the do lookup on the CPU, copy the result over to the GPU, and then run the rest of the model on the GPU. Should I use `to_device` differently? 

```
import dynet as dy

model = dy.Model()
trainer = dy.AdamTrainer(model)
lookup = model.add_lookup_parameters((100,100),device='CPU')
lstm = dy.LSTMBuilder(1,100,100,model)
W = model.add_parameters((2,100))

emb = [dy.to_device(lookup[0],'GPU:0')]
s = lstm.initial_state().transduce(emb)[-1]
loss = dy.pickneglogsoftmax(dy.parameter(W)*s,0)

dy.forward([loss])
loss.backward()
trainer.update()
```

This is what happens when I run the code

```
$ python3 devicetest.py --dynet-gpu 1 
[dynet] initializing CUDA
Request for 1 GPU ...
[dynet] Device Number: 0
[dynet]   Device name: TITAN Xp
[dynet]   Memory Clock Rate (KHz): 5705000
[dynet]   Memory Bus Width (bits): 384
[dynet]   Peak Memory Bandwidth (GB/s): 547.68
[dynet]   Memory Free (GB): 12.4942/12.7788
[dynet]
[dynet] Device(s) selected: 0
[dynet] random seed: 269416795
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Segmentation fault (core dumped)
```

**Comment by xunzhang** [comment]
It works in my environment. Can you try Python2?

**Comment by mpsilfve** [comment]
I can confirm it does on my machine as well work in Python2 but not in Python3.

**Comment by mpsilfve** [comment]
I also get a segmentation fault in Python2.

**Comment by xunzhang** [comment]
The `dynet.__version__` stuff is a little out of date, can I know the exact version you use? I think maybe you should try v2.0.2 or later (https://github.com/clab/dynet/releases).

**Comment by mpsilfve** [comment]
Great! Thank you :) It seems to work with the latest version installed from source.
