### ISSUE TITLE
pip3 install issue

### ISSUE THREAD

**Issue by RuiPChaves** [clab/dynet#1267]
I suspect this has been discussed before (#146) but that discussion didn't help me, likely because I'm not terribly familiar with paths and python's innards. 

Running "sudo pip3 install dynet" now returns:

    Requirement already satisfied: dynet in 
    /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
    Requirement already satisfied: cython in 
    /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from dynet)
    Requirement already satisfied: numpy in 
    /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from dynet)

But the following error occurs while importing

    python3.6
    Python 3.6.4 (v3.6.4:d48ecebad5, Dec 18 2017, 21:07:28) 
    [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import dynet as np
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-
    packages/dynet.py", line 15, in <module>
        from _dynet import *
    ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-
    packages/_dynet.cpython-36m-darwin.so, 2): Library not loaded: /tmp/pip-build-
    8sbhxbq1/dynet/build/py3.6-64bit/dynet/libdynet.dylib
      Referenced from: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-
    packages/_dynet.cpython-36m-darwin.so
      Reason: image not found

Can anyone give me some assistance with this matter? (the more verbose the better)
Thanks

ps - Import works fine for the default Python installation, of course.

**Comment by danielhers** [comment]
Not sure why, but `install_name_tool` failed to update `libdynet.dylib` when you installed. But you can tell it yourself where the library should be found, by setting

    export DYLD_LIBRARY_PATH=/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-
packages

Before running Python.

**Comment by RuiPChaves** [comment]
This works. Much appreciated!
