### ISSUE TITLE
Implementing and benchmarking a few model/application examples, providing trained weights

### ISSUE THREAD

**Issue by zhisbug** [clab/dynet#1268]
- [ ] MNIST Convnets
- [ ] Word level Language Modeling using LSTM RNNs
- [ ] Residual Networks
- [ ] Generative Adversarial Networks (DCGAN)
- [ ] Variational Auto-Encoders

Reference: https://github.com/pytorch/examples

**Comment by neubig** [comment]
Closed in favor of https://github.com/clab/dynet/issues/1284
