### ISSUE TITLE
Need well organized examples of how to do things in DyNet

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1276]
We need a better tutorial about how to get started with DyNet with examples all in the same place. Currently, our tutorials are here:
> http://dynet.readthedocs.io/en/latest/tutorial.html

All of these tutorials should be extensively commented with information about how things work, and should have parity between Python and C++. This is a "super-issue," and I will create several "sub-issues" that will link to this.

Also, we should make sure that they appear in the DyNet example folder (https://github.com/clab/dynet/tree/master/examples) in a way so that it is obvious that they should be done in sequence.

**Comment by pmichel31415** [comment]
FYI that's not super organized and shouldn't be a surrogate for an official documentation but I've started writing tutorials for dynet recently:

https://github.com/pmichel31415/dynet-tutorial
