### ISSUE TITLE
"Competitive Example" (1): MNIST Classification

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1285]
Part of: https://github.com/clab/dynet/issues/1284

A first example is image classification on MNIST.

We already have an example here:
> https://github.com/clab/dynet/tree/master/examples/mnist

We should confirm that it achieves competitive accuracy to that reported on the official page:
> http://yann.lecun.com/exdb/mnist/

and also with the implementation in PyTorch:
> https://github.com/pytorch/examples/tree/master/mnist

**Comment by gpengzhi** [comment]
I am working on this issue.

**Comment by neubig** [comment]
Fixed by #1334. Thanks @gpengzhi !
