### ISSUE TITLE
"Competitive Example" (2): Penn Treebank Language Modeling

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1286]
Part of: https://github.com/clab/dynet/issues/1284

We already have a language model here:
> https://github.com/clab/dynet/tree/master/examples/rnnlm

But it is not competitive with existing numbers for various reasons, largely because the training paradigm is different. We should restructure it to match, for example, the PyTorch example:
> https://github.com/pytorch/examples/tree/master/word_language_model

**Comment by duyvuleo** [comment]
Hi Graham,

What makes the huge difference between perplexities (current dynet impl
>100 vs the SOTA 53-60)? Looking at the codes, I can see the difference of
batching and hidden state reinitialisation but I am still confused why
dynet impl. is not good like that.

I just tried to implement a transformer LM
<https://github.com/duyvuleo/Transformer-DyNet/blob/master/src/transformer-lm.cc>
(the training paradigm is quite similar) but the best perplexity I got is
around 99 (still far from the SOTA). With the same paradigm of my
transformer for translation, I can get the BLEU close to SOTA. This makes
me confused!

Can you give some hints that we can make to improve the current impl.?

Thanks!

--
Cheers,
Vu

**Comment by neubig** [comment]
The biggest reason is probably because existing work trains models that pass information across sentence boundaries, while the DyNet implementation trains models where each sentence is independent. There might be other things as well. Part of the goal of this issue is to try to reduce the number of differences.

**Comment by pmichel31415** [comment]
IIRC I wrote code for RNNLM on PTB with truncated BPTT but I couldn't get it close to SOTA, if that's something you'd be interested in

**Comment by duyvuleo** [comment]
Hi Paul,

How much PPLX did you get with your RNNLM?

--
Cheers,
Vu

**Comment by pmichel31415** [comment]
Hi @duyvuleo I think I got 95 test ppl without a lot of tuning.

Here's the code I used, mostly adapted from the dynet examples or benchmark: http://www.cs.cmu.edu/~pmichel1/cont-lm-dynet.zip

**Comment by duyvuleo** [comment]
Thanks a lot, Paul!

I will look into it.

--
Cheers,
Vu
