### ISSUE TITLE
"Competitive Example" (5): Variational Auto-encoders

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1289]
Part of: https://github.com/clab/dynet/issues/1284

We should have an example of variational auto-encoders. This could be either for:

1. Something like the PyTorch example: https://github.com/pytorch/examples/tree/master/vae
2. An implementation of Bowman et al.: https://arxiv.org/abs/1511.06349

I tend to prefer the latter, but the former would also potentially be OK.

**Comment by pw2393** [comment]
Pull Request #1307: 1. done 2. to start

**Comment by pw2393** [comment]
Hi! Got a question regarding the implementation of Bowman et al.: https://arxiv.org/abs/1511.06349:

I noticed in the [line 106](https://github.com/clab/dynet/blob/master/examples/variational-autoencoder/train_rnnlm-aevb.cc#L106) to [line 108](https://github.com/clab/dynet/blob/master/examples/variational-autoencoder/train_rnnlm-aevb.cc#L106) of `train_rnnlm-aevb.cc`, that the input of decoder RNN is the original `sent`. **HOWEVER**, should it only decodes the new hidden state? In other words, with the start-of-sentence token as initial input, the decoding RNN generates (i.e. reconstructs) the sentence step by step (**where the output of last step is the input of next step**) till the end-of-sentence token, right? 

![screen shot 2018-03-22 at 4 58 29 pm](https://user-images.githubusercontent.com/21228317/37798668-cd5677c2-2df3-11e8-9441-a2942b5d546c.png)

Just wanna make sure if I am not misunderstanding something here.
