### ISSUE TITLE
"Competitive Example" (6): Reinforcement Learning

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1290]
Part of: https://github.com/clab/dynet/issues/1284

It would be nice to have a benchmark of a reinforcement learning task. One example is the PyTorch cartpole balancing task:
> http://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html

There may be more interesting ones.

**Comment by gregid** [comment]
Another interesting example from mxnet (Arcade game, also DQN):
https://github.com/apache/incubator-mxnet/tree/master/example/reinforcement-learning/dqn
