### ISSUE TITLE
"Competitive Example" (7): GAN-related

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1291]
Part of: https://github.com/clab/dynet/issues/1284

It'd be nice to have a competitive GAN example. One example is the PyTorch DCGAN:
> https://github.com/pytorch/examples/tree/master/dcgan

We might also consider a GAN for text example, such as something related to style transfer.

**Comment by pw2393** [comment]
just a memo:
> a `conv_2d_tranpose` (i.e. deconv_2d) is needed in DyNet to build a dcgan example.

**Comment by gpengzhi** [comment]
I am working on this issue.

**Comment by pw2393** [comment]
@gpengzhi you're building a `conv_2d_transpose` operator for dynet?

**Comment by gpengzhi** [comment]
@pw2393 no, I am working on the example instead of the operator.

**Comment by zhisbug** [comment]
If you want to implement DCGAN, a conv2d_transpose op might be required.
