### ISSUE TITLE
"Competitive Example" (2.5): Sequence-to-sequence

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1292]
Part of: https://github.com/clab/dynet/issues/1284

We have an example of a sequence-to-sequence model:
> https://github.com/clab/dynet/tree/master/examples

We should make sure that it is obvious how to download training data, and that the model is at least as good as the PyTorch example:
> http://pytorch.org/tutorials/intermediate/seq2seq_translation_tutorial.html

**Comment by gpengzhi** [comment]
I am working on this issue.

**Comment by gpengzhi** [comment]
#1388

**Comment by gpengzhi** [comment]
#1391
