### ISSUE TITLE
Profiling against other toolkits

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1293]
Currently we have the DyNet benchmarks repository that needs to be updated:
> https://github.com/neulab/dynet-benchmark

Specifically, we should (1) make it automated so we can run all the tests easily, (2) add a few of the competitive examples cited here, (3) document things, (4) try to expand the coverage of toolkits to at least PyTorch, maybe others: https://github.com/clab/dynet/issues/1284

**Comment by danielhers** [comment]
My PR neulab/dynet-benchmark#14 fixes a problem with the test automation.
