### ISSUE TITLE
"Competitive Example" (4.5): BiLSTM-CRF

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1294]
Part of: #1284

It would be nice to have a BiLSTM-CRF example such as this one from PyTorch:
> http://pytorch.org/tutorials/beginner/nlp/advanced_tutorial.html

There are a number of implementations of BiLSTM-CRF taggers in DyNet that can be used for reference:
> https://github.com/onurgu/ner-tagger-dynet
> https://github.com/rguthrie3/BiLSTM-CRF

**Comment by pmichel31415** [comment]
I might do that in the next weeks

**Comment by neubig** [comment]
FYI: here is a reference https://github.com/neulab/cmu-ner/blob/master/models/decoders.py#L28
