### ISSUE TITLE
'pip' error for installing  DyNet on GPU

### ISSUE THREAD

**Issue by qiangzi11hao** [clab/dynet#1297]
When I want to  install DyNet on my computer with a GPU version,  it doesn't work.  The BUG messages
show as : 
$ BACKEND=cuda pip install git+https://github.com/clab/dynet#egg=dynet
Collecting dynet from git+https://github.com/clab/dynet#egg=dynet
  Cloning https://github.com/clab/dynet to /tmp/pip-build-nt70guui/dynet
Requirement already satisfied: cython in ./anaconda3/lib/python3.6/site-packages (from dynet)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.6/site-packages (from dynet)
Installing collected packages: dynet
  Running setup.py install for dynet ... error
    Complete output from command /home/lzq/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nt70guui/dynet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ze9ffx_p-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    INFO:root:CMAKE_PATH='/usr/bin/cmake'
    INFO:root:MAKE_PATH='/usr/bin/make'
    INFO:root:MAKE_FLAGS='-j 12'
    INFO:root:EIGEN3_INCLUDE_DIR='/tmp/pip-build-nt70guui/dynet/build/py3.6-64bit/eigen'
    INFO:root:EIGEN3_DOWNLOAD_URL='https://bitbucket.org/eigen/eigen/get/2355b229ea4c.zip'
    INFO:root:CC_PATH='/usr/bin/gcc'
    INFO:root:CXX_PATH='/usr/bin/g++'
    INFO:root:SCRIPT_DIR='/tmp/pip-build-nt70guui/dynet'
    INFO:root:BUILD_DIR='/tmp/pip-build-nt70guui/dynet/build/py3.6-64bit'
    INFO:root:INSTALL_PREFIX='/home/lzq/anaconda3/lib/python3.6/site-packages/../../..'
    INFO:root:PYTHON='/home/lzq/anaconda3/bin/python'
    cmake version 3.5.1
    
    CMake suite maintained and supported by Kitware (kitware.com/cmake).
    g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
    Copyright (C) 2015 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    
    INFO:root:Creating build directory /tmp/pip-build-nt70guui/dynet/build/py3.6-64bit
    INFO:root:Fetching Eigen...
    error: Could not download Eigen from 'https://bitbucket.org/eigen/eigen/get/2355b229ea4c.zip'
    
    ----------------------------------------
Command "/home/lzq/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-nt70guui/dynet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-ze9ffx_p-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-nt70guui/dynet/

**Comment by pw2393** [comment]
Can you access this link `https://bitbucket.org/eigen/eigen/get/2355b229ea4c.zip ` directly in browser from where you are?

**Comment by neubig** [comment]
It looks like bitbucket may have been down when you tried to install. Could you try just installing again?
