### ISSUE TITLE
operation: pow()

### ISSUE THREAD

**Issue by pw2393** [clab/dynet#1298]
### In document:
![screen shot 2018-03-13 at 2 21 30 pm](https://user-images.githubusercontent.com/21228317/37361727-f5e2f8ae-26c9-11e8-9734-4a74674f25d3.png)
![screen shot 2018-03-13 at 2 44 02 pm](https://user-images.githubusercontent.com/21228317/37362929-01df8ea8-26cd-11e8-8a80-dd7d9f101ab6.png)

### However
```
t = dy.inputVector([1,2,3])
l = dy.pow(t, dy.scalarInput(2)) # works >> [1.0, 4.0, 9.0]
l = dy.pow(t, dy.inputVector([2]) # works >> [1.0, 4.0, 9.0]
l = dy.pow(t, dy.inputVector([2, 2, 2]))  # fails (1)
l = dy.pow(t, 2) # fails (2)
l = t ** 2 # fails (3)
```

### Failures

**(1)** The first failure contradicts the documents. 
It reports
![screen shot 2018-03-13 at 2 27 52 pm](https://user-images.githubusercontent.com/21228317/37362123-d23613ea-26ca-11e8-8992-915f6be301ad.png)
because in `nodes-arith-cwise.cc`
![screen shot 2018-03-13 at 2 28 58 pm](https://user-images.githubusercontent.com/21228317/37362851-c4619d8c-26cc-11e8-8dd0-cdf1880d8cea.png)

It **REQUIRES** second parameter as a 1-dim vector or scalar. **So this part of document is incorrect.**

**(2, 3)** Not a bug. (2) is only because the second parameter is required as an `Expression`; (3) without definition of reloading. It could possibly be more intuitive like `Expression**real` or `Expression**Expression` for python layer.

**Comment by xunzhang** [comment]
Very good catch! I'll fix all threes very quick: Add cwise support for `pow` to match the document.  And support (2) and (3).

I think the DyNet document should review again and update a lot.

**Comment by pmichel31415** [comment]
Yes the documentation has been created in a bulk in a short amount of time and hasn't been updated a lot since then (especially C++), it could use some dusting.

**Comment by xunzhang** [comment]
Fixed in latest master. coefficient-wise support is pending since Eigen::Tensor doesn't support that yet. I'd rather wait for the Eigen Impl instead of Impl CUDA kernel ourselves.

Before:
```
t = dy.inputVector([1,2,3])
l = dy.pow(t, dy.scalarInput(2)).value() # works: [1., 4., 9.]
l = dy.pow(t, dy.inputVector([2])).value() # works: [1., 4., 9.]
l = dy.pow(t, dy.inputVector([2, 2, 2]))  # don't support
l = dy.pow(t, 2) # don't support
l = t ** 2 # don't support
```

After:
```
t = dy.inputVector([1,2,3])
l = dy.pow(t, dy.scalarInput(2)).value() # works: [1., 4., 9.]
l = dy.pow(t, dy.inputVector([2])).value() # works: [1., 4., 9.]
l = dy.pow(t, dy.inputVector([2, 2, 2]))  # don't support, waiting for Eigen::Tensor cwise pow impl
l = dy.pow(t, 2) # don't support since we should be consistent with the params of dynet operators
l = (t ** 2).value() # works: [1., 4., 9.]
l = (t ** dy.scalarInput(2)).value() # works: [1., 4., 9.]
```
