### ISSUE TITLE
Running dynet c++

### ISSUE THREAD

**Issue by Aditi138** [clab/dynet#1305]
I am facing a weird issue when running C++ dynet on a Linux server. When I run "make" for my project I get the following [message"](url
<img width="1440" alt="screen shot 2018-03-14 at 2 05 54 pm" src="https://user-images.githubusercontent.com/29302213/37422338-6d5cad36-2791-11e8-90f5-e86040ee1d42.png">
)

 It seems to be working on my local machine (Mac)

**Comment by neubig** [comment]
This is a linker error, which means that your program cannot find the DyNet library when it is linking. It seems that this error is happening when compiling your own code (`multi_aspece`), not DyNet itself. I'll close this issue, but feel free to send me details directly.
