### ISSUE TITLE
Parameters with update=False

### ISSUE THREAD

**Issue by pmichel31415** [clab/dynet#1315]
How do I do the equivalent of  `dy.parameter(W, update=False)` or `W.expr(False)` with the new API? Can't find anything in the documentation

**Comment by pmichel31415** [comment]
So I've resorted to 

```python
W if update else dy.const_parameter(W)
```
Which is a bit ugly. Still wondering if there's an easy way. the `_iexpr` method in `Parameters` seems to be accepting an `update` parameter but this functionality is not used anywhere.

**Comment by neubig** [comment]
Should either be documented as part of https://github.com/clab/dynet/issues/1302 and/or fixed to restore the old functionality.

**Comment by yoavg** [comment]
Is there a downside to just wrapping with nobackprop if needed?

**Comment by neubig** [comment]
Yes, there is a disadvantage. nobackprop uses memory in the backward step (not the forward step). Not sure how important this is, but given that these are parameters (which are big) it might be important.

**Comment by yoavg** [comment]
In that case, I guess using dy.const_parameter(W) when appropriate is the best option.
The `W if update else dy.const_parameter(W)` usage above is fine (why is it considered ugly?) or alternatively:
`if not update: W =  dy.const_parameter(W)`

I don't see how `W = dy.parmater(W, False)` makes it any nicer, but this should be trivial to add if wanted.

**Comment by neubig** [comment]
I guess it adds an extra line of code (now that we aren't calling `dy.parameter()` any more). Perhaps we could add a boolean to parameters about whether they should be updated or not, which can be set at `__init__` time. This could be added to the C++ side as well.

**Comment by speedcell4** [comment]
But I got segment fault on calling `const_parameter`.
BTW, what is the reason to remove `expr`? I thought it's good to use actually.

**Comment by pmichel31415** [comment]
If no one objects I think I'll add the `update` option back in `expr()`

**Comment by TheElephantInTheRoom** [comment]
What exactly happens in this toy case:

        layerA = model.add_parameters((1, 100))
        layerA= const_parameter(layerA)
        ...
        output = layerA.expr()* ...
        ...
        trainer.update()

First, can we still assign a value (manually) to a constant parameter anytime we want?
Second, if I do it this way, is it guaranteed that layerA is not going to be updated by update()?

**Comment by pmichel31415** [comment]
Unless I'm mistaken your snippet won't work because `layerA` is an Expression. If you want a parameter that will never be updated you should call `.expr(False)` each time or just not make it a parameter (but an input with `inputTensor`
