### ISSUE TITLE
batch_size in Expressions

### ISSUE THREAD

**Issue by zhechenyan** [clab/dynet#1316]
This is related to #1312 I am currently working on. I found that I have some problems creating an Expression with batch_size.

For example, if I want to create a new Expression of size (2, 3) and batch_size=4, what I am expecting is 4 x (2, 3) Expression. In Tensorflow, it is:
```
matrix = tf.ones([4, 2, 3], dtype=tf.float32)
with tf.Session() as sess:
    t= sess.run([matrix])
    print(t, matrix.shape)
```
What I got in return was:
```
[array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]], dtype=float32)] (4, 2, 3)
```
Yes, what I was expecting.

When I tried to do the same thing in DyNet, I got:

```
import dynet as dy

matrix = dy.ones((2, 3), batch_size=4)
print(matrix.npvalue(), matrix.dim())
```
And now the output is:
```
(array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]]), ((2, 3), 4))
```
It seemed that it had different behaviors.

I could be wrong, but my question is: should we be consistent with Tensorflow, which is more intuitively correct?

**Comment by xunzhang** [comment]
DyNet handles batch with an additional batch dimension(bd) instead of explicitly adding it as the first dimension(TF way), which might have more flexibility. They shouldn't be same.

Here I guess this is an issue in Python layer when printing out batched expression? But the `dim()` seems correct.

**Comment by neubig** [comment]
I don't think this is incorrect. Could you take a look here http://dynet.readthedocs.io/en/latest/minibatch.html and if it's still confusing, we can consider updating the documentation. I'll close for now though, feel free to re-open if you feel the documentation is insufficient.
