### ISSUE TITLE
xor example doesn't work

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1323]
When I run the xor example:

    python examples/xor/xor.py

on Python 2.7.13 or 3.6.4, I get the following error:

    [dynet] random seed: 2913802817
    [dynet] allocating memory: 512MB
    [dynet] memory allocation done.
    Traceback (most recent call last):
      File "examples/xor/xor.py", line 23, in <module>
        h = dy.tanh((W*x) + b)
      File "_dynet.pyx", line 1856, in _dynet.Expression.__mul__
    NotImplementedError

I suspect that this is related to recent changes in the parameters here https://github.com/clab/dynet/pull/1233

This seems to be a relatively major problem, any ideas for a fix? (cc: @yoavg)

**Comment by yoavg** [comment]
I am on python 2.7.11 and the xor example runs fine for me.

**Comment by neubig** [comment]
Bizarre... This breaks for me on Python 2 and 3, and both Mac and Linux. I'll try to locate the problem.

**Comment by yoavg** [comment]
fwiw, my cython version on this machine is 0.27.3.

**Comment by neubig** [comment]
OK, I did a clean install of DyNet and everything seems to work. This seems to indicate that `setup.py` is no longer properly overwriting the old install of DyNet with the newest version, which is worrying but a different problem. I'll close this and see if I can create a minimal example of the problem.
