### ISSUE TITLE
AdamTrainer fills the memory

### ISSUE THREAD

**Issue by mardir89** [clab/dynet#1333]
Hi,
using python, I'm building a model that trains two LSTM. I tried to replicate the structure present in the sequence-to-sequence example for python, attention.py, found in the github directory. The problem is that when I use the SimpleSGDTrainer everything is okay, but with AdamTrainer the program fills the memory and the swap memory and gets automatically killed. This problem does not appear when I simply modify the code from attention.py using for example AdamTrainer.

The structure i have is:
SingleSampleTrain - a function that invokes the trainer, calls a function that generates the loss, does the backpropagation and updates the trainer;
GetLoss - it calls the embedder and then the encoder, applies  an activation function, gives an output in [0,1] and generates the loss;
Encoder - this one concatenate the samples representations, with some regularization, and gives them to the run_lstm function, identical to the one found in the example;
EmbedSequence - takes in input a list of vectors (of lenght 250) and creates a list of dy.Expressions of said vectors; I am not using a parameter collection for the embeddings (like in the example) because I don't want to update the values of the embeddings and each embedding represents a sentence, so they are not parameters usable both in training and testing.

In the attachment you can find the functions used in the training
[code.txt](https://github.com/clab/dynet/files/1859803/code.txt)

How can I solve the problem with the memory without using a lookup_parameter table?

**Comment by neubig** [comment]
Adam has to additionally keep track of values for the momentum and variance for each parameter, so it will require 3 times as much memory for parameters than SimpleSGD parameters. If you're right on the border of what is possible in your memory, this could cause a memory overflow. Can you count the total size of all parameter tensors in your model?

**Comment by mardir89** [comment]
Thank you for your reply.
The parameters inside the parameter_collection are a matrix of 100*250 and one o 1*100, a vector of lenght 100 and a coefficient, so 2701 parameters; in addition, there are two lstm of two layers each, with input of lenght 500 and output of lenght 125. In terms of memory size, they occupy about 1500MB, about 6% of the total memory.
But if it also saves the dynet expressions of every input that is given to the two LSTMs, then the memory is not enough (in an early stage of the code, I tried to save a dictionary with the expressions, and it reached the limit before reading all of the samples).

**Comment by neubig** [comment]
Yeah, I think you're probably just running out of memory, so you need to use smaller parameters or smaller inputs, or use DyNet's multi-device support. If there's more evidence that this is a bug I'll re-open, but I'll close this for now.
