### ISSUE TITLE
Outdated error message

### ISSUE THREAD

**Issue by AmitMY** [clab/dynet#1342]
Running:
```
main.py --dynet-autobatch 1 --dynet-mem 4096 --dynet-gpu 1 --dynet-devices CPU,GPU:1,GPU:2
```
Results:
> terminate called after throwing an instance of 'std::invalid_argument'
>   what():  Use only --dynet_gpus or --dynet_gpu_ids, not both

Should not mention `gpu_ids` because:
> The option --dynet-gpu-ids is deprecated.

**Comment by pmichel31415** [comment]
Fixed ddbf5602720eede8e3035f1728b8de9cb1436432
