### ISSUE TITLE
PickNegLogSoftmax::forward not yet implemented for multiple columns

### ISSUE THREAD

**Issue by zhang-wen** [clab/dynet#135]
i found following the code in nodes.cc:

`throw std::runtime_error("PickNegLogSoftmax::forward not yet implemented for multiple columns");`

when using batch, it does not support the multiple tensor yet, which may affect my training speed. guys, is it easily to implement for multiple columns ?

**Comment by neubig** [comment]
Fixed by: https://github.com/clab/dynet/commit/e9cee422dcff69bfcf17544aa1092733cfd36f66
