### ISSUE TITLE
Inconsistent invalid argument exceptions

### ISSUE THREAD

**Issue by danielhers** [clab/dynet#136]
I'm using the Python bindings and I [use](https://github.com/danielhers/ucca/blob/dynet/parsing/classifiers/nn/feedforward.py#L45) `reshape` to change a batch of embeddings into one long vector.
The same code sometimes works fine and sometimes fails with the [error](https://travis-ci.org/danielhers/ucca/jobs/172277222) `Bad arguments to Reshape: {3200}, {10X32}`.
In the same network I [use](https://github.com/danielhers/ucca/blob/dynet/parsing/classifiers/nn/feedforward.py#L59) matrix multiplication, and this also sometimes fails the [error](https://travis-ci.org/danielhers/ucca/jobs/172277231) `Mismatched input dimensions in MatrixMultiply: [{200} {200}]`.
This happens both on my computer and on Travis CI.

I thought it might be related to the fact I'm creating several models during the run, but I noticed it also happens sometimes for the first model.

**Comment by neubig** [comment]
Just to confirm, what is the problem here? That the error messages are different?

**Comment by danielhers** [comment]
No, the problem is that there are errors at all - as far as I know, I'm
passing the parameters correctly, and indeed it usually runs without
errors...

**Comment by neubig** [comment]
Multiplying a 200x1 vector and another 200x1 vector is not a valid operation. You'll need to either take the transpose of the first (i.e. dot product), or the transpose of the second (i.e. Kronecker product). For reshape, the product of all of the dimensions must be the same before and after reshaping, and it looks like the product of the first and second are different (3200 and 320). Try to check your code.

**Comment by neubig** [comment]
I'm going to close this. If there's a valid issue, I'll reopen.

**Comment by danielhers** [comment]
Thanks. I suppose it is probably a problem with my code but I didn't have time to debug it yet.
