### ISSUE TITLE
CyclicalSGDTrainer: learning_rate never updated with default Trainer constructor

### ISSUE THREAD

**Issue by jihelhere** [clab/dynet#1360]
Hi,
I don't know if this is a bug, but it really is counter-intuitive!

In the Cyclical SGD trainer contructor, gamma is set to zero by default which cancels any learning_rate update
See function cyclic_update_eta, l.249 in current master.
The update is multiplied by the itth power of gamma, which is zero by default. See:

https://github.com/clab/dynet/blob/b07411ca75e74afe3f19f6fbda5646c5ddd6f4b2/dynet/training.h#L249

**Comment by neubig** [comment]
Yes, this does seem counter-intuitive and should probably be fixed (cc @pmichel31415 )

**Comment by pmichel31415** [comment]
Wow yeah this is really dumb I'll fix set it to `1.0` by default, thanks for bringing this to our attention @jihelhere

**Comment by neubig** [comment]
Fixed by #1361
