### ISSUE TITLE
How to get access final states s.s() by using RNN transduce?

### ISSUE THREAD

**Issue by YubinXie** [clab/dynet#1375]
The output of RNN transduce function is a list of outputs. I want to feed my encoder's final s() to my decoder and I can not find a way to get it from transduce function. Any ideas? Thanks!

**Comment by neubig** [comment]
Are you using an RNNBuilder or BiRNNBuilder? If it's an RNNBuilder, then maybe `add_inputs()[-1].s()`? If it's a BiRNNBuilder then it's not easy to get the "final" state using the transduce function, as the final state will be `[-1]` for the forward RNN, and `[0]` for the backward RNN. Maybe you could just write a for loop?

**Comment by YubinXie** [comment]
@neubig Sounds like a smart trick. Is the logics behind your trick: 1) get the final output 2) add an empty input using a normal RNN command 3) get state from the new 'node'?

**Comment by neubig** [comment]
No, AFAIK, RNNBuilders have an `add_inputs()` command that is like `transduce()` but preserves the state information that you need to call `s()`.

**Comment by YubinXie** [comment]
@neubig This `add_inputs()` is directly after `transduce()` or it is actually follows ` transduce()[-1]`

**Comment by pmichel31415** [comment]
Hi @YubinXie I think your question is answered in the tutorial here: https://dynet.readthedocs.io/en/latest/tutorials_notebooks/RNNs.html#Aside:-memory-efficient-transduction
