### ISSUE TITLE
Cannot run Dynet on GPU

### ISSUE THREAD

**Issue by jyp** [clab/dynet#1377]
When running a dynet program over CUDA we (@sharidloaiciga) get:

```
[dynet] initializing CUDA
CUDA failure in cudaGetDeviceCount(&nDevices)
CUDA driver version is insufficient for CUDA runtime version
terminate called after throwing an instance of 'dynet::cuda_exception'
  what():  cudaGetDeviceCount(&nDevices)
Aborted (core dumped)
```

Would it be possible to print the versions (expected / cuda), as TensorFlow does, so that we can debug the problem?

Version of dynet: master branch from last week.

**Comment by neubig** [comment]
Yes, I think adding the current and expected versions would be good. This could be added to `cuda.cc`, so we'd welcome a pull request: https://github.com/clab/dynet/blob/master/dynet/cuda.cc

**Comment by pmichel31415** [comment]
Dynet now prints the  CUDA driver and runtime version thanks to #1447
