### ISSUE TITLE
How to use to_device properly?

### ISSUE THREAD

**Issue by iclementine** [clab/dynet#1378]
I am using Dynet 2.0.3 with cuda. I have a problem how to properly use the `to_device` in python API. I have a piece of example where restircted softmax is not implemented in cuda. If I run the script with `--dynet-devices CPU,CPU:0`, I would get `RuntimeError: r_log_softmax(a) not implemented for CUDA yet. You can use CPU implementation with to_device operation instead.`. 
```
import dynet as dy

pc = dy.ParameterCollection()
pw = pc.add_parameters((30, 10)) 

dy.renew_cg()
x = dy.vecInput(10)
W = dy.parameter(pw)
y = W * x
p = dy.log_softmax(y, [11,12,13,14,15])
p = dy.to_device(p, 'CPU') # adding this does not help!
print(p.npvalue())
```

but simply adding `p = dy.to_device(p, 'CPU')`  does not help, I have to specify pw and x to CPU as well. So does it mean that I have to specify all the related node to CPU? If so, shouldn't it be better to run it without GPU? I expected running specific Expression on a certain device with `to_device` but is it not true?

Thank you.

**Comment by neubig** [comment]
You need to do `to_device()` before the operation that you want to run on CPU. So the appropriate code would be:

    p = dy.to_device(p, 'CPU') # adding this does not help!
    p = dy.log_softmax(y, [11,12,13,14,15])

**Comment by iclementine** [comment]
Now it works fine, thank you! 
I used to think that `to device` moves the exact expression which uses a CPU-only operation, but now I  the logic is to move the inputs of an expression which uses a CPU-only operation to CPU.
