### ISSUE TITLE
Re-init parameters

### ISSUE THREAD

**Issue by talbaumel** [clab/dynet#1379]
Hi, I want to test the same model with several random initialisations. The problem is that I'm creating multiple instances of the same model and it takes up a lot of memory.

Is there a why I can re-init a model?

Thanks, Tal 👍🏻

**Comment by AmitMY** [comment]
I don't know if it works for parameters, but for lookup tables you can:
```
lookup = model.add_lookup_parameters((len(vectors), len(vectors[0])))
lookup.init_from_array(matrix)
```
Where your `matrix` is a matrix you create with numpy at however initialisation style you choose

**Comment by talbaumel** [comment]
Thanks, but it doesn't apply for other parameters types.

**Comment by neubig** [comment]
No, there is not a way you can do this, and I think we likely won't be adding this feature as it would complicate things. I'd suggest just running the program multiple times.
