### ISSUE TITLE
MomentumSGDTrainer in python does not work properly

### ISSUE THREAD

**Issue by taggg** [clab/dynet#138]
Sorry if this is known issue or the API is being dropped.

I just transitioned my code from cnn to dynet and MomentumSGDTrainer does not work properly in Python. You can still call it but it does not seem to work as it should. I switched to AdamTrainer and it works as expected.

**Comment by neubig** [comment]
Could you be a bit more specific? What do you expect, and what are you seeing?

**Comment by taggg** [comment]
OK. I found that parameters order in cnn and dynet is different when calling MomentumSGDTrainder (as with other optimizers):

From training.h:

cnn:
explicit MomentumSGDTrainer(Model* m, real lam = 1e-6, real e0 = 0.01, real mom = 0.9) :

dynet:
explicit MomentumSGDTrainer(Model* m, real e0 = 0.01, real mom = 0.9, real edecay = 0.0) :


The problem was I was calling MomentumSGDTrainer with older parameter order and it was behaving weirdly. Sorry for the confusion.
