### ISSUE TITLE
dy.max fails - 'module' object has no attribute 'max'

### ISSUE THREAD

**Issue by AmitMY** [clab/dynet#1383]
I was following http://dynet.readthedocs.io/en/latest/operations.html, and trying to use `dy.max` instead of `dy.average`, but while average works fine, max throws this error:
> 'module' object has no attribute 'max'

**Comment by AmitMY** [comment]
The documentation should say `emax` not `max`

**Comment by pmichel31415** [comment]
So I double check and the python doc already says `emax`: https://dynet.readthedocs.io/en/latest/python_ref.html#dynet.emax

**Comment by AmitMY** [comment]
@pmichel31415 I triple checked and if you go to the link in my first comment, you’ll find:

> Expressiondynet::max(constExpression &x, constExpression &y)
