### ISSUE TITLE
conv2d_bias performance issues

### ISSUE THREAD

**Issue by talbaumel** [clab/dynet#1385]
Hi, I replaced the LSTM in a classifier with the following class:
```
class Conv():
    def __init__(self, model, n_gram, filter_size, emb_size):
        self.emb_size = emb_size
        self.filter = model.add_parameters((1, n_gram, emb_size, filter_size))
        self.bias = model.add_parameters((filter_size))
        
    def __call__(self, embeds):
        conv_filter = dy.parameter(self.filter)
        bias = dy.parameter(self.bias)
        seq_len = len(embeds)
        
        embeds = dy.transpose(dy.concatenate_cols(embeds))
        embeds = dy.reshape(embeds, (1, seq_len, self.emb_size))
        conved =  dy.rectify(dy.conv2d_bias(embeds, conv_filter, bias, [1, 1], is_valid=False))
        return conved[0]
```

The LSTM based network ~6 hours while the CONV run for ~7 hours,
As I understand  CONV should be faster.

Is it known? 

Thanks, Tal 👍🏻

*The accuracy of the classifier also suffered but this was sort of expected.

**Comment by neubig** [comment]
If this is on CPU, then the fact that convolutions are a bit slow is a known issue. https://github.com/clab/dynet/issues/1337

If it's on GPU this would be unexpected. A simple end-to-end comparing with LSTM would be useful to debug.

**Comment by talbaumel** [comment]
Leet issue number, I used a CPU so I guess the issue is redundent.

BTW, I think I mentioned it in a previous issue but since most of the people I know use DyNet for NLP and use conv layers over a list of embeddings, there should be a version of conv2d that can be applied over such list.

**Comment by neubig** [comment]
I'll close this issue in favor of the more leet one, but I agree.
