### ISSUE TITLE
_dynet.Expression.__mul__ NotImplementedError

### ISSUE THREAD

**Issue by dreamilam** [clab/dynet#1386]
I was running the dynet python tutorial.

```python
import dynet as dy
# define the parameters
m = dy.ParameterCollection()
W = m.add_parameters((8,2))
V = m.add_parameters((1,8))
b = m.add_parameters((8))

# renew the computation graph
dy.renew_cg()

# create the network
x = dy.vecInput(2) # an input vector of size 2.
output = dy.logistic(V*(dy.tanh((W*x)+b)))
```

I am getting this error.

```
[dynet] random seed: 3380132027
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Traceback (most recent call last):
  File "xor.py", line 13, in <module>
    output = dy.logistic(V*(dy.tanh((W*x)+b)))
  File "_dynet.pyx", line 1907, in _dynet.Expression.__mul__
NotImplementedError
```

Don't know where the problem is. Any input would be appreciated.

**Comment by pmichel31415** [comment]
Are you using the latest version from github?

**Comment by xbainbain** [comment]
I’ve tried your snippet with the latest version. It works fine.

**Comment by neubig** [comment]
Closing, but re-open if this is not a version issue.

**Comment by xcgfth** [comment]
@xbainbain , which version you use?

**Comment by xcgfth** [comment]
@dreamilam  I also encountererd this problem, Did you have solve it?

**Comment by xcgfth** [comment]
Okay, I have sovled it.
use installation from github insetad of pip itself, like this:
pip install git+https://github.com/clab/dynet#egg=dynet
