### ISSUE TITLE
Cannot install DyNet GPU version on Google Colab

### ISSUE THREAD

**Issue by urialon** [clab/dynet#1390]
Hi,
I can't install DyNet with GPU support on a Google Colab notebook.
The standard installation *without GPU* (pip install dynet) works fine, but installing from sources to enable GPU fails, apparently because the Colab backend doesn't have CUDA Toolkit installed.

I don't know how much effort it takes, but TensorFlow, PyTorch and Keras all run smoothly on Google Colab, so you might want to support GPU installation on Colab too...

**Comment by neubig** [comment]
Could you please send more log information to help us identify the problem?

http://dynet.readthedocs.io/en/latest/debugging.html#asking-questions-reporting-bugs

**Comment by urialon** [comment]
Hi,
>What is the error? Copy and paste the error message.

See the full error here:
https://colab.research.google.com/drive/1W2Uww5PilMVTnBuwqyWflVFplwkxHtFK
>What is your environment? 

Ubuntu, python3
>Are you running on CPU or GPU? 

GPU
>What OS? 
>If the problem seems to be related to a specific library (CUDA, Eigen), what version of that library are you using?

I'm not sure which CUDA version the Colab backend is running, because "nvcc" is not installed.
>If possible, it will be really really helpful if you can provide a minimal code example that will cause the 
problem to occur. This way the developers will be able to reproduce the problem in their own environment.

Here is an online Notebook with a GPU backend, with my attempt to install DyNet:
https://colab.research.google.com/drive/1W2Uww5PilMVTnBuwqyWflVFplwkxHtFK

I don't really need it to be solved for myself, I just tried and it failed, and I thought that you guys might want to support this Google Colab environment. It's currently a free GPU environment (the only free GPU environment) which is becoming popular among students / people who want to experiment with Deep Learning before buying expensive hardware.

**Comment by neubig** [comment]
Hmm, if `nvcc` is not installed then it'll be difficult to install DyNet with the current setup, and we'll need to deploy pre-compiled GPU binaries:
> https://github.com/clab/dynet/issues/855

And I do agree that having it be able to work on colab would be nice.

**Comment by anuraglahon16** [comment]
How to install dynet in anaconda
