### ISSUE TITLE
Master doesn't install

### ISSUE THREAD

**Issue by blester125** [clab/dynet#1393]
I was trying to install the most recent version of dynet with:
```
pip install git+https://github.com/clab/dynet#egg=dynet
```
And when I try to run it I get the following error
```
>>> import dynet as dy
```
```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brian/.pyenv/versions/prehashed/lib/python3.6/site-packages/dynet.py", line 15, in <module>
    from _dynet import *
ImportError: /home/brian/.pyenv/versions/prehashed/lib/python3.6/site-packages/_dynet.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTVN5dynet14AmsgradTrainerE 
```

I am on Ubuntu 16.04, using python 3.6, and have gcc 5.4

**Comment by neubig** [comment]
I'm guessing that somehow your libraries have gotten out of sync. Does install work when you do it in a new virtual environment?

**Comment by blester125** [comment]
When I make a new virtual environment that is python 3.6.X (i tried .3 and .5) it doesn't work, I did make a python 2.7 virtual env and it did work
