### ISSUE TITLE
dynet speed vs pycnn speed?

### ISSUE THREAD

**Issue by rasoolims** [clab/dynet#140]
Hi,

I was using pyCNN and it was pretty fast (training time per 100 sentences was about 8 seconds). When I use the same code with Dynet (after small compatibility changes to my code), it is now about 45 seconds per 100 seconds. Is this a natural thing?

Thanks

**Comment by yoavg** [comment]
Shouldn't happen. What did you change?

**Comment by yoavg** [comment]
Shouldn't happen. What did you change?

**Comment by yoavg** [comment]
Shouldn't happen. What did you change?

**Comment by yoavg** [comment]
Shouldn't happen. What did you change?

**Comment by rasoolims** [comment]
I did another evaluation and realized that the problem is with the dropout (the only part that I added). That's actually from the Bist parser code:

```python
#original code
output = (self.outLayer * self.activation(self.hidLayer * input + self.hidBias) + self.outBias)
```

The change is only drop-out on self.hidLayer:

```python
# modified code
dropped = dropout(self.hidLayer, 0.5)
output = (self.outLayer * self.activation(dropped * input + self.hidBias) + self.outBias)
```

Am I applying drop-out incorrectly?

Thanks

**Comment by yoavg** [comment]
Do you find that the dropout was faster in pycnn than in dynet? or is it just very slow in general?

**Comment by rasoolims** [comment]
Never tried that on PyCNN. But now I am sure it is the problem with just dropout. Because that is the only difference.
