### ISSUE TITLE
default device when specifying multiple devices

### ISSUE THREAD

**Issue by smar111** [clab/dynet#1400]
Hi,

I want to know that if I use the --dynet-devices option set to CPU,GPU:0, what is the default device used? I need it to be the GPU and only use CPU for the functions which are not implemented for GPU.

Thanks.

**Comment by FilippoC** [comment]
I think the GPU will always be the default device:
- GPU are added here: https://github.com/clab/dynet/blob/master/dynet/init.cc#L233
- CPU here: https://github.com/clab/dynet/blob/master/dynet/init.cc#L270
- And the default index is 0: https://github.com/clab/dynet/blob/master/dynet/init.cc#L262

You can add a check similar to this one in your code, just in case:
- https://github.com/clab/dynet/blob/master/dynet/init.cc#L273

**Comment by smar111** [comment]
Thanks for the pointer. Another question is: 

I don't need to change the way the code is compiled for the GPU when using multiple devices right, i.e., I just use the GPU build as is with the --dynet-devices option set?

**Comment by FilippoC** [comment]
No, as long as you build dynet with GPU support, you can use multiple GPUs. However, you will have to take care of what is computed on which device in your code yourself.
By default, if you use "--dynet-devices GPU:0, GPU:1, CPU", only GPU:0 will be used. You will have to use dynet::to_device or specify a device when you add parameters to the model, eg. http://dynet.readthedocs.io/en/latest/core.html#_CPPv3N5dynet19ParameterCollection14add_parametersERK3DimfRKNSt6stringEP6Device

**Comment by smar111** [comment]
That's understandable. Thanks for the tip.

**Comment by neubig** [comment]
The ID specified in the code should not be the physical GPU ID, but rather the "0" "1" "2" in order of number of GPUs specified. So, as you hoped, these are de-associated.

**Comment by smar111** [comment]
Great. Thanks for the clarification.
