### ISSUE TITLE
Autobatching problem for dynamic structure TreeLSTM.

### ISSUE THREAD

**Issue by anhad13** [clab/dynet#1407]
I understand that it is generally expected that calls to forward or value must be delayed to the end for autobatching to work. 

However, I wanted to implement a Shift Reduce Parser wherein the decision to shift OR reduce is made dynamically based on the TreeLSTM constructed so far.(this is an implementation of the SPINN paper: https://www.nyu.edu/projects/bowman/spinn.pdf)

My code : https://gist.github.com/anhad13/682a39350695374c3e41e6434a684a91
Line 148 is where the premature np.argmax is called, due to which the autobatching speedup is not observed.

It would be great if you could tell me if it's possible to make autobatching work in such a situation and how.
Thanks!

**Comment by neubig** [comment]
Unfortunately this is not possible at the moment, please see this issue (I'll close this as a duplicate): https://github.com/clab/dynet/issues/719

Autobatching only works when not using things like `npvalue()`. It would be nice if it was supported, but it is not at the moment.
