### ISSUE TITLE
CUBLAS failure in cublasCreate(&cublas_handle)

### ISSUE THREAD

**Issue by hanli91** [clab/dynet#1408]
Hi, I tried to import dynet with GPU support (CUDA9.1, cuDNN7.0.5) and I got the following error. This is running on a conda py2.7 environment.
``` 
(dynet-gpu) > python                                        
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 23:32:55) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dynet_config; dynet_config.set_gpu();
>>> import dynet
[dynet] initializing CUDA
Request for 1 GPU ...
[dynet] Device Number: 0
[dynet]   Device name: GeForce GTX TITAN X
[dynet]   Memory Clock Rate (KHz): 3505000
[dynet]   Memory Bus Width (bits): 384
[dynet]   Peak Memory Bandwidth (GB/s): 336.48
[dynet]   Memory Free (GB): 9.45429/12.8057
[dynet]
[dynet] Device(s) selected: 0CUBLAS failure in cublasCreate(&cublas_handle)
1
terminate called after throwing an instance of 'dynet::cuda_exception'
  what():  cublasCreate(&cublas_handle)
[1]    3576 abort (core dumped)  python
```
Here is the .zshrc setting.

```
(dynet-gpu) > echo $LD_LIBRARY_PATH                         
~/.local/lib:~/src/cudnn7.0.5/lib64:/s/cuda-9.1/lib64
```
 I followed the installation instruction for CUDA and cuDNN, and the procedure seems fine. What could be the reason for this? Thank you!

**Comment by FilippoC** [comment]
Hi,
I have sometimes the same error with the C++ API, launching the program again solves it.

**Comment by neubig** [comment]
I'm going to close this for lack of info, but if it's still a problem please re-open. It would be helpful if you could provide a way to reproduce (although I know this might be difficult).

**Comment by esalesky** [comment]
I've seen this occasionally when cluster machines are restarted and memory hasn't been properly freed - setting the cuda cache to a new location and/or disabling it got me past it.

```
mkdir -p /tmp/ccache
export CUDA_CACHE_PATH='/tmp/ccache'
export CUDA_CACHE_DISABLE=1
```
