### ISSUE TITLE
Forward the whole CG without specifying a goal node

### ISSUE THREAD

**Issue by FilippoC** [clab/dynet#1411]
Hi,

is it possible to compute the value of each node in the CG at once? ie. something like cg.forward()

The current trick I use is to accumulate all the output Expression in a vector and then call forward on its sum. However this can be annoying with very big CG with independent parts.

For example, for learning with structured hinge loss, the algorithm is:
1. first, compute the weight of each part
2. use DP to compute the loss
3. call incremental_forward(loss)
4. call backward
This "bulk forward" is needed for the first step.

**Comment by neubig** [comment]
Here you provided two methods:
1. Accumulate all the expressions in a vector, then sum the vector and call forward/backward.
2. Call incremental forward and backward on each loss.

Both of these are fine, and 1. will be more efficient. I'm not sure why there's a problem here?

**Comment by FilippoC** [comment]
Yes, I accumulate, but this is not convenient for big computational graph.
It would be nice to be able to forward everything.

**Comment by FilippoC** [comment]
As I said, it is not convenient to keep track of a global vector where I push back every output.
My current workflow is the following:
1. build the computational graph: there is O(n^4)~O(n^6) outputs, generated by different modules
2. I accumulate all this outputs and sum them so I can do a bulk forward on the GPU
3. A dynamic program computes the structured hinge loss
4. I call incremental forward on this hinge loss
5. I call backward

I just wanted to know if it possible to get rid of step 2, so I don't have to keep around a global vector but still achieve the efficiency of the "bulk forward". I am not saying that I cannot do it, just that it is not convenient for when I have complicated dynamic networks.

**Comment by neubig** [comment]
OK, just to confirm: you need all of these values in 1. to do your dynamic program, but they are not directly the loss function so you don't need to sum them, correct? In this case, it is sufficient to call "forward" on the *last* of these O(n^4)~O(n^6) outputs, which will result in forward being called for each of the outputs. Also, I believe in Python you can also call forward on the entire list of outputs. Hopefully this solves the problem?

**Comment by FilippoC** [comment]
Hi,
Exactly.
So if I understand correctly, incremental_forward/forward will forward all node with an id lower than the one provided in the argument?
Thank you for the tip, I think it will solve the problem.

(BTW, I use the C++ API)
