### ISSUE TITLE
save model with MKL

### ISSUE THREAD

**Issue by jzlianglu** [clab/dynet#142]
Hi developers,

I installed my dynet with boost 1.53, and can save the model. However, if I install dynet with MKL using the same version of boost, I cannot save the model during training, as it said

saving models...
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Serializing dictionaries is only supported on versions of boost 1.56 or higher

I cannot install dynet with higher version of boost such as 1.58 or 1.60. Any ideas?

Thanks
Liang

**Comment by neubig** [comment]
Are you sure that the only difference is whether you're using MKL or not? This error should always be thrown if you try to serialize a dictionary, regardless of whether it's using MKL or not.

**Comment by jzlianglu** [comment]
Hi Graham,

Sorry, I was confused. The toolkit that I can save model during training was implemented in cnn, not in dynet. I have translated it into dynet, and cannot save model either with or without MKL. The main problem is that I cannot install dynet with higher version of boost. The version that I used to install cnn is boost v1.60.

Thanks,
Liang

**Comment by neubig** [comment]
So this is a side-effect of https://github.com/clab/dynet/issues/129 I guess. I hope we can fix this soon, but it's difficult for me to do unless I can reproduce it, which I can't at the moment.

In the mean time, the work-around is to avoid serializing DyNet dictionaries in your code. (In lamtram I'm not using the dictionary serialization code, and just writing the dictionary out myself.)

Graham
