### ISSUE TITLE
using Java bindings for models trained using Python DyNet bindings? 

### ISSUE THREAD

**Issue by anhinga** [clab/dynet#1423]
A rather typical situation is that one would like to use from Java a model which was trained using Python DyNet bindings, and for which the code using this model from Python (but not from C++) is available.

What is the right approach here, given that Java SWIG recreates C++ bindings, and not Python bindings?

**Comment by pmichel31415** [comment]
The saved model format is the same so for C++ (and I assume Java would be the same), you'll need to recreate the same `ParameterCollection` (with the exact same names and hierarchy) and then load with populate:

```c++
TextFileLoader loader(parameter_collection_file);
loader.populate(parameter_collection);
```

Feel free to reopen if you run into an issue or have any other related questions.
