### ISSUE TITLE
Using built-in layer normalization for BiLSTM?

### ISSUE THREAD

**Issue by Megavoxel01** [clab/dynet#1424]
Hi!
dy.VanillaLSTMBuilder provides built-in support for layer normalization by setting the ln_lstm parameter, but how can I use this feature for BiLSTM? It seems like BiRNN doesn't support that and I couldn't find a way to set up the flag when passing VanillaLSTMBuilder into it.

**Comment by blester125** [comment]
You can use `functools.partialmethod` to get around this.

```python
import functools
import dynet as dy

def partialclass(cls, *args, **kwargs):
    class NewCls(cls):
        __init__ = functools.partialmethod(cls.__init__, *args, **kwargs)
    return NewCls

LNLSTMBuilder = partialclass(dy.LSTMBuilder, ln_lstm=True)

brnn = dy.BiRNNBuilder(layers, isz, osz, pc, LNLSTMBuilder)
```

**Comment by neubig** [comment]
Nice idea @blester125 ! I think this solves the problem.
