### ISSUE TITLE
scala 2.12?

### ISSUE THREAD

**Issue by MihaiSurdeanu** [clab/dynet#1425]
Hi,

Does dynet-scala support scala 2.12? I see that by default it compiles to scala 2.11. If it does, how does one generate the 2.12 jars? I changed DEFAULT_SCALA_VERSION to 2.12.6 in contrib/swig/build.sbt, but this didn't work: it still generated 2.11 jars.

Thanks!
Mihai

**Comment by kwalcock** [comment]
The trick may be to instead define the variable in the cmake command.  I haven't been able to verify this yet, though.  Some tests are failing/crashing.

cmake -DSCALA_VERSION=2.12.6 ...

**Comment by MihaiSurdeanu** [comment]
Thanks @kwalcock! Your suggestion worked.
