### ISSUE TITLE
How to let part of the parameters do not require gradients in the new version

### ISSUE THREAD

**Issue by lixin4ever** [clab/dynet#1429]
Hi,
    After DyNet V2.0.3, there is no need to add the expression dy.parameter() to move the network parameters to the computational graph (CG) and all of them will be automatically added to the CG. My question is that, how to fix part of the networks parameters, e.g., the parameters in the Word Embedding Layer, during the training process in the new version.

**Comment by blester125** [comment]
Assuming by fix part of the network parameters you mean don't update them during training you can solve this for the word embeddings case using `dy.lookup(embedding_weights, idx, update=False)`.

For a more general case of not updating a parameter you can use `const_p = p.expr(update=False)`.

This seems like it will be deprecated soonish though so you might need to do something like using `opt.update_subset(ps, lookup_ps)` leaving the parameter you don't want to update out of the list.

**Comment by lixin4ever** [comment]
@blester125  Thanks a lot
