### ISSUE TITLE
ImportError module Saveable not found in dynet 2.0

### ISSUE THREAD

**Issue by jpainam** [clab/dynet#1432]
Hi!
I'm trying to reproduce some code from last year, but can't find the `Saveable` module anymore.
```python
from dynet import Saveable
ImportError: cannot import name 'Saveable'
````
Thanks for pointing me in the right direction

**Comment by pmichel31415** [comment]
Which version of dynet were you using? Is using the version of dynet you were using then not an option? For example: https://github.com/clab/dynet/releases/tag/v1.1
