### ISSUE TITLE
Sparse Vanilla LSTM

### ISSUE THREAD

**Issue by tiberiu44** [clab/dynet#1434]
Hi @neubig,

I'm trying to implement a WaveRNN model, for a TTS-Project I'm working on (https://tiberiu44.github.io/TTS-Cube/). In order to make it work in realtime, I've already created a C++ backend, which is compatible with the model format stored by DyNet. This is to avoid overhead during the sampling procedure at runtime. I now need to go for the weight pruning technique described here: https://arxiv.org/pdf/1704.05119.pdf. For what I've read, there is no supporting function from this already in place.

Looking over the DyNet code, it seems pretty straight-forward to do this. I just need to create two mask vectors in the VanillaLSTM class for `p_x2i` and `p_h2i`, which I need to add to the `local_model`. Then I just use component-wise multiplication in the forward pass. Just to be sure, these parameters will be saved automatically in the model, right. I don't need to do anything else. 

I have two questions:
1) How do I modify the python bindings to add a new method for setting the pruning percentage;
2) Do you think this will be useful to others (should I create a branch and a pull request, once I'm finished), or do you consider it adds to much overhead to be worthwhile.

**Comment by tiberiu44** [comment]
Update: I managed to implement this feature. Should I do a pull request?

**Comment by neubig** [comment]
We'd be happy to have you send a pull request, but I can't guarantee that
we'll directly incorporate it into DyNet itself (we're a bit conservative
about adding complicated functionality to the builders, simply because we'd
like to keep things simple). If not, we'd be happy if you could prepare a
separate repository or something.

Graham
