### ISSUE TITLE
python 3.7 support

### ISSUE THREAD

**Issue by MartinoMensio** [clab/dynet#1435]
The prebuilt wheel does not support python3.7. In order to reproduce the issue, I created a clean virtual environment with python3.7.0:
```
(venv) martino@arch:~/kmi/annotation_playground$ pip install dynet
Collecting dynet
  Using cached https://files.pythonhosted.org/packages/b7/5f/ceaaf5f3a1d46da33f2182ad4f5ccddd68f2cea33d792ecb3f14e085fc98/dyNET-2.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-z3htjgxt/dynet/setup.py", line 17, in <module>
        from Cython.Distutils import build_ext as _build_ext
    ModuleNotFoundError: No module named 'Cython'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-z3htjgxt/dynet/
```

In the docs I see it should support Python 2.x and 3.x but at the same time I see that on [pypi](https://pypi.org/project/dyNET/) the 3.7 is not mentioned in the supported platforms.
Will it be supported in the near future?
Thanks

**Comment by neubig** [comment]
This is not a good thing, so we should try to fix it. @danielhers would this be easy to do? If so, I might create another release with the latest changes, and then ping you so you could build new wheels.

**Comment by danielhers** [comment]
#1436 should resolve this.
