### ISSUE TITLE
Error after running "make -j 2"

### ISSUE THREAD

**Issue by VytM** [clab/dynet#1440]
Command "make -j 2" gives a massive error:
"""""""""""""""""""""""""""
/usr/bin/cmake -H/home/vytas/dynet -B/home/vytas/dynet/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/bin/cmake -E cmake_progress_start /home/vytas/dynet/build/CMakeFiles /home/vytas/dynet/build/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory '/home/vytas/dynet/build'
make -f dynet/CMakeFiles/dynet.dir/build.make dynet/CMakeFiles/dynet.dir/depend
make[2]: Entering directory '/home/vytas/dynet/build'
cd /home/vytas/dynet/build && /usr/bin/cmake -E cmake_depends "Unix Makefiles" /home/vytas/dynet /home/vytas/dynet/dynet /home/vytas/dynet/build /home/vytas/dynet/build/dynet /home/vytas/dynet/build/dynet/CMakeFiles/dynet.dir/DependInfo.cmake --color=
make[2]: Leaving directory '/home/vytas/dynet/build'
make -f dynet/CMakeFiles/dynet.dir/build.make dynet/CMakeFiles/dynet.dir/build
make[2]: Entering directory '/home/vytas/dynet/build'
[  1%] Building CXX object dynet/CMakeFiles/dynet.dir/aligned-mem-pool.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/aligned-mem-pool.cc.o -c /home/vytas/dynet/dynet/aligned-mem-pool.cc
[  2%] Building CXX object dynet/CMakeFiles/dynet.dir/cfsm-builder.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/cfsm-builder.cc.o -c /home/vytas/dynet/dynet/cfsm-builder.cc
[  3%] Building CXX object dynet/CMakeFiles/dynet.dir/deep-lstm.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/deep-lstm.cc.o -c /home/vytas/dynet/dynet/deep-lstm.cc
[  4%] Building CXX object dynet/CMakeFiles/dynet.dir/devices.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/devices.cc.o -c /home/vytas/dynet/dynet/devices.cc
[  5%] Building CXX object dynet/CMakeFiles/dynet.dir/dict.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/dict.cc.o -c /home/vytas/dynet/dynet/dict.cc
[  6%] Building CXX object dynet/CMakeFiles/dynet.dir/dim.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/dim.cc.o -c /home/vytas/dynet/dynet/dim.cc
[  6%] Building CXX object dynet/CMakeFiles/dynet.dir/dynet.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/dynet.cc.o -c /home/vytas/dynet/dynet/dynet.cc
[  7%] Building CXX object dynet/CMakeFiles/dynet.dir/exec.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/exec.cc.o -c /home/vytas/dynet/dynet/exec.cc
[  8%] Building CXX object dynet/CMakeFiles/dynet.dir/expr.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/expr.cc.o -c /home/vytas/dynet/dynet/expr.cc
/home/vytas/dynet/dynet/expr.cc: In function ‘dynet::Expression dynet::strided_select(const dynet::Expression&, const std::vector<int>&, const std::vector<int>&, const std::vector<int>&)’:
/home/vytas/dynet/dynet/expr.cc:196:74: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for(unsigned d=0;d<range_to.size() && d<x.dim().nd;d++){ if(range_to[d]!=x.dim()[d]) inplaced = false; }
                                                                          ^
[  9%] Building CXX object dynet/CMakeFiles/dynet.dir/fast-lstm.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/fast-lstm.cc.o -c /home/vytas/dynet/dynet/fast-lstm.cc
[ 10%] Building CXX object dynet/CMakeFiles/dynet.dir/globals.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/globals.cc.o -c /home/vytas/dynet/dynet/globals.cc
[ 11%] Building CXX object dynet/CMakeFiles/dynet.dir/grad-check.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/grad-check.cc.o -c /home/vytas/dynet/dynet/grad-check.cc
[ 12%] Building CXX object dynet/CMakeFiles/dynet.dir/graph.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/graph.cc.o -c /home/vytas/dynet/dynet/graph.cc
[ 13%] Building CXX object dynet/CMakeFiles/dynet.dir/gru.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/gru.cc.o -c /home/vytas/dynet/dynet/gru.cc
[ 14%] Building CXX object dynet/CMakeFiles/dynet.dir/hsm-builder.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/hsm-builder.cc.o -c /home/vytas/dynet/dynet/hsm-builder.cc
[ 15%] Building CXX object dynet/CMakeFiles/dynet.dir/init.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/init.cc.o -c /home/vytas/dynet/dynet/init.cc
[ 16%] Building CXX object dynet/CMakeFiles/dynet.dir/io.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/io.cc.o -c /home/vytas/dynet/dynet/io.cc
[ 17%] Building CXX object dynet/CMakeFiles/dynet.dir/lstm.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/lstm.cc.o -c /home/vytas/dynet/dynet/lstm.cc
[ 17%] Building CXX object dynet/CMakeFiles/dynet.dir/mem.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/mem.cc.o -c /home/vytas/dynet/dynet/mem.cc
[ 18%] Building CXX object dynet/CMakeFiles/dynet.dir/model.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/model.cc.o -c /home/vytas/dynet/dynet/model.cc
[ 19%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-activations.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/nodes-activations.cc.o -c /home/vytas/dynet/dynet/nodes-activations.cc
[ 20%] Building CXX object dynet/CMakeFiles/dynet.dir/nodes-affinetransform.cc.o
cd /home/vytas/dynet/build/dynet && /usr/bin/c++   -Ddynet_EXPORTS -I/home/vytas/dynet -I/home/vytas/dynet/external/easyloggingpp/src -I/usr/include/eigen3 -I/home/vytas/dynet/build  -DEIGEN_FAST_MATH -fPIC -fno-finite-math-only -Wall -Wno-missing-braces -std=c++11 -g -funroll-loops -Ofast -march=native -fPIC   -o CMakeFiles/dynet.dir/nodes-affinetransform.cc.o -c /home/vytas/dynet/dynet/nodes-affinetransform.cc
In file included from /home/vytas/dynet/dynet/nodes-affinetransform.cc:4:0:
/home/vytas/dynet/dynet/matrix-multiply.h: In function ‘void dynet::MatrixMultiply(const dynet::Device_CPU&, const dynet::Tensor&, const dynet::Tensor&, dynet::Tensor&, const float*)’:
/home/vytas/dynet/dynet/matrix-multiply.h:47:47: error: no match for ‘operator*’ (operand types are ‘const float’ and ‘Eigen::TensorMap<Eigen::Tensor<float, 2> >’)
   tbvec(y).device(*dev.edevice) = *acc_scalar * tbvec(y);
                                               ^
In file included from /usr/include/eigen3/Eigen/SparseCore:62:0,
                 from /usr/include/eigen3/Eigen/Sparse:26,
                 from /usr/include/eigen3/Eigen/Eigen:2,
                 from /home/vytas/dynet/dynet/tensor-eigen.h:11,
                 from /home/vytas/dynet/dynet/matrix-multiply.h:5,
                 from /home/vytas/dynet/dynet/nodes-affinetransform.cc:4:
/usr/include/eigen3/Eigen/src/SparseCore/SparsePermutation.h:171:1: note: candidate: template<class SparseDerived, class PermutationType> const Eigen::Product<Eigen::Inverse<Rhs>, SparseDerived, 2> Eigen::operator*(const Eigen::InverseImpl<PermutationType, Eigen::PermutationStorage>&, const Eigen::SparseMatrixBase<Derived>&)
 operator*(const InverseImpl<PermutationType,PermutationStorage>& tperm, const SparseMatrixBase<SparseDerived>& matrix)
 ^
/usr/include/eigen3/Eigen/src/SparseCore/SparsePermutation.h:171:1: note:   template argument deduction/substitution failed:
In file included from /home/vytas/dynet/dynet/nodes-affinetransform.cc:4:0:
/home/vytas/dynet/dynet/matrix-multiply.h:47:56: note:   mismatched types ‘const Eigen::InverseImpl<PermutationType, Eigen::PermutationStorage>’ and ‘const float’
   tbvec(y).device(*dev.edevice) = *acc_scalar * tbvec(y);
                                                        ^
In file included from /usr/include/eigen3/Eigen/SparseCore:62:0,
                 from /usr/include/eigen3/Eigen/Sparse:26,
                 from /usr/include/eigen3/Eigen/Eigen:2,
                 from /home/vytas/dynet/dynet/tensor-eigen.h:11,
                 from /home/vytas/dynet/dynet/matrix-multiply.h:5,
                 from /home/vytas/dynet/dynet/nodes-affinetransform.cc:4:
/usr/include/eigen3/Eigen/src/SparseCore/SparsePermutation.h:162:1: note: candidate: template<class SparseDerived, class PermutationType> const Eigen::Product<SparseDerived, Eigen::Inverse<Rhs>, 2> Eigen::operator*(const Eigen::SparseMatrixBase<Derived>&, const Eigen::InverseImpl<PermutationType, Eigen::PermutationStorage>&)
 operator*(const SparseMatrixBase<SparseDerived>& matrix, const InverseImpl<PermutationType, PermutationStorage>& tperm)
 ^
/usr/include/eigen3/Eigen/src/SparseCore/SparsePermutation.h:162:1: note:   template argument deduction/substitution failed:
In file included from /home/vytas/dynet/dynet/nodes-affinetransform.cc:4:0:
/home/vytas/dynet/dynet/matrix-multiply.h:47:56: note:   mismatched types ‘const Eigen::SparseMatrixBase<Derived>’ and ‘const float’
   tbvec(y).device(*dev.edevice) = *acc_scalar * tbvec(y);
                                                        ^
In file included from /usr/include/eigen3/Eigen/SparseCore:62:0,
                 from /usr/include/eigen3/Eigen/Sparse:26,
                 from /usr/include/eigen3/Eigen/Eigen:2,
                 from /home/vytas/dynet/dynet/tensor-eigen.h:11,
                 from /home/vytas/dynet/dynet/matrix-multiply.h:5,
                 from /home/vytas/dynet/dynet/nodes-affinetransform.cc:4:
/usr/include/eigen3/Eigen/src/SparseCore/SparsePermutation.h:154:1: note: candidate: template<class SparseDerived, class PermDerived> const Eigen::Product<PermDerived, SparseDerived, 2> Eigen::operator*(const Eigen::PermutationBase<PermutationDerived>&, const Eigen::SparseMatrixBase<Derived>&)
 operator*( const PermutationBase<PermDerived>& perm, const SparseMatrixBase<SparseDerived>& matrix)
 ^
/usr/include/eigen3/Eigen/src/SparseCore/SparsePermutation.h:154:1: note:   template argument deduction/substitution failed:
In file included from /home/vytas/dynet/dynet/nodes-affinetransform.cc:4:0:
/home/vytas/dynet/dynet/matrix-multiply.h:47:56: note:   mismatched types ‘const Eigen::PermutationBase<PermutationDerived>’ and ‘const float’
   tbvec(y).device(*dev.edevice) = *acc_scalar * tbvec(y);
                                                        ^
In file included from /usr/include/eigen3/Eigen/SparseCore:62:0,
                 from /usr/include/eigen3/Eigen/Sparse:26,
                 from /usr/include/eigen3/Eigen/Eigen:2,
                 from /home/vytas/dynet/dynet/tensor-eigen.h:11,
                 from /home/vytas/dynet/dynet/matrix-multiply.h:5,
                 from /home/vytas/dynet/dynet/nodes-affinetransform.cc:4:
/usr/include/eigen3/Eigen/src/SparseCore/SparsePermutation.h:147:1: note: candidate: template<class SparseDerived, class PermDerived> const Eigen::Product<MatrixDerived, PermutationDerived, 2> Eigen::operator*(const Eigen::SparseMatrixBase<Derived>&, const Eigen::PermutationBase<PermutationDerived>&)
 operator*(const SparseMatrixBase<SparseDerived>& matrix, const PermutationBase<PermDerived>& perm)
 ^
/usr/include/eigen3/Eigen/src/SparseCore/SparsePermutation.h:147:1: note:   template argument deduction/substitution failed:
In file included from /home/vytas/dynet/dynet/nodes-affinetransform.cc:4:0:
/home/vytas/dynet/dynet/matrix-multiply.h:47:56: note:   mismatched types ‘const Eigen::SparseMatrixBase<Derived>’ and ‘const float’
   tbvec(y).device(*dev.edevice) = *acc_scalar * tbvec(y);
                                                        ^
In file included from /usr/include/eigen3/Eigen/Householder:24:0,
                 from /usr/include/eigen3/Eigen/QR:17,
                 from /usr/include/eigen3/Eigen/Dense:4,
                 from /usr/include/eigen3/Eigen/Eigen:1,
                 from /home/vytas/dynet/dynet/tensor-eigen.h:11,
                 from /home/vytas/dynet/dynet/matrix-multiply.h:5,
                 from /home/vytas/dynet/dynet/nodes-affinetransform.cc:4:
/usr/include/eigen3/Eigen/src/Householder/HouseholderSequence.h:439:99: note: candidate: template<class OtherDerived, class VectorsType, class CoeffsType, int Side> typename Eigen::internal::matrix_type_times_scalar_type<typename VectorsType::Scalar, OtherDerived>::Type Eigen::operator*(const Eigen::MatrixBase<Derived>&, const Eigen::HouseholderSequence<VectorsType, CoeffsType, Side>&)
 typename internal::matrix_type_times_scalar_type<typename VectorsType::Scalar,OtherDerived>::Type operator*(const MatrixBase<OtherDerived>& other, const HouseholderSequence<VectorsType,CoeffsType,Side>& h)
                                                                                                   ^
/usr/include/eigen3/Eigen/src/Householder/HouseholderSequence.h:439:99: note:   template argument deduction/substitution failed:
In file included from /home/vytas/dynet/dynet/nodes-affinetransform.cc:4:0:
/home/vytas/dynet/dynet/matrix-multiply.h:47:56: note:   mismatched types ‘const Eigen::MatrixBase<Derived>’ and ‘const float’
   tbvec(y).device(*dev.edevice) = *acc_scalar * tbvec(y);
                                                        ^
In file included from /usr/include/eigen3/Eigen/Core:397:0,
                 from /usr/include/eigen3/unsupported/Eigen/CXX11/Core:14,
                 from /usr/include/eigen3/unsupported/Eigen/CXX11/Tensor:14,
                 from /home/vytas/dynet/dynet/devices.h:14,
                 from /home/vytas/dynet/dynet/nodes-impl-macros.h:4,
                 from /home/vytas/dynet/dynet/nodes-affinetransform.cc:3:
/usr/include/eigen3/Eigen/src/Core/Transpositions.h:350:1: note: candidate: template<class TranspositionsDerived, class MatrixDerived> const Eigen::Product<MatrixDerived, PermutationDerived, 2> Eigen::operator*(const Eigen::TranspositionsBase<TranspositionsDerived>&, const Eigen::MatrixBase<U>&)
 operator*(const TranspositionsBase<TranspositionsDerived> &transpositions,
 ^
/usr/include/eigen3/Eigen/src/Core/Transpositions.h:350:1: note:   template argument deduction/substitution failed:
In file included from /home/vytas/dynet/dynet/nodes-affinetransform.cc:4:0:
/home/vytas/dynet/dynet/matrix-multiply.h:47:56: note:   mismatched types ‘const Eigen::TranspositionsBase<TranspositionsDerived>’ and ‘const float’
   tbvec(y).device(*dev.edevice) = *acc_scalar * tbvec(y);
                                                        ^
In file included from /usr/include/eigen3/Eigen/Core:397:0,
                 from /usr/include/eigen3/unsupported/Eigen/CXX11/Core:14,
                 from /usr/include/eigen3/unsupported/Eigen/CXX11/Tensor:14,
                 from /home/vytas/dynet/dynet/devices.h:14,
                 from /home/vytas/dynet/dynet/nodes-impl-macros.h:4,
                 from /home/vytas/dynet/dynet/nodes-affinetransform.cc:3:
/usr/include/eigen3/Eigen/src/Core/Transpositions.h:338:1: note: candidate: template<class MatrixDerived, class TranspositionsDerived> const Eigen::Product<MatrixDerived, PermutationDerived, 2> Eigen::operator*(const Eigen::MatrixBase<Derived>&, const Eigen::TranspositionsBase<TranspositionsDerived>&)
 operator*(const MatrixBase<MatrixDerived> &matrix,
 ^
/usr/include/eigen3/Eigen/src/Core/Transpositions.h:338:1: note:   template argument deduction/substitution failed:
In file included from /home/vytas/dynet/dynet/nodes-affinetransform.cc:4:0:
/home/vytas/dynet/dynet/matrix-multiply.h:47:56: note:   mismatched types ‘const Eigen::MatrixBase<Derived>’ and ‘const float’
   tbvec(y).device(*dev.edevice) = *acc_scalar * tbvec(y);
                                                        ^
In file included from /usr/include/eigen3/Eigen/Core:396:0,
                 from /usr/include/eigen3/unsupported/Eigen/CXX11/Core:14,
                 from /usr/include/eigen3/unsupported/Eigen/CXX11/Tensor:14,
                 from /home/vytas/dynet/dynet/devices.h:14,
                 from /home/vytas/dynet/dynet/nodes-impl-macros.h:4,
                 from /home/vytas/dynet/dynet/nodes-affinetransform.cc:3:
/usr/include/eigen3/Eigen/src/Core/PermutationMatrix.h:558:1: note: candidate: template<class PermutationDerived, class MatrixDerived> const Eigen::Product<MatrixDerived, PermutationDerived, 2> Eigen::operator*(const Eigen::PermutationBase<PermutationDerived>&, const Eigen::MatrixBase<U>&)
 operator*(const PermutationBase<PermutationDerived> &permutation,
 ^
/usr/include/eigen3/Eigen/src/Core/PermutationMatrix.h:558:1: note:   template argument deduction/substitution failed:
In file included from /home/vytas/dynet/dynet/nodes-affinetransform.cc:4:0:
/home/vytas/dynet/dynet/matrix-multiply.h:47:56: note:   mismatched types ‘const Eigen::PermutationBase<PermutationDerived>’ and ‘const float’
   tbvec(y).device(*dev.edevice) = *acc_scalar * tbvec(y);
                                                        ^
In file included from /usr/include/eigen3/Eigen/Core:396:0,
                 from /usr/include/eigen3/unsupported/Eigen/CXX11/Core:14,
                 from /usr/include/eigen3/unsupported/Eigen/CXX11/Tensor:14,
                 from /home/vytas/dynet/dynet/devices.h:14,
                 from /home/vytas/dynet/dynet/nodes-impl-macros.h:4,
                 from /home/vytas/dynet/dynet/nodes-affinetransform.cc:3:
/usr/include/eigen3/Eigen/src/Core/PermutationMatrix.h:546:1: note: candidate: template<class MatrixDerived, class PermutationDerived> const Eigen::Product<MatrixDerived, PermutationDerived, 2> Eigen::operator*(const Eigen::MatrixBase<Derived>&, const Eigen::PermutationBase<PermutationDerived>&)
 operator*(const MatrixBase<MatrixDerived> &matrix,
 ^
/usr/include/eigen3/Eigen/src/Core/PermutationMatrix.h:546:1: note:   template argument deduction/substitution failed:
In file included from /home/vytas/dynet/dynet/nodes-affinetransform.cc:4:0:
/home/vytas/dynet/dynet/matrix-multiply.h:47:56: note:   mismatched types ‘const Eigen::MatrixBase<Derived>’ and ‘const float’
   tbvec(y).device(*dev.edevice) = *acc_scalar * tbvec(y);
                                                        ^
dynet/CMakeFiles/dynet.dir/build.make:566: recipe for target 'dynet/CMakeFiles/dynet.dir/nodes-affinetransform.cc.o' failed
make[2]: *** [dynet/CMakeFiles/dynet.dir/nodes-affinetransform.cc.o] Error 1
make[2]: Leaving directory '/home/vytas/dynet/build'
CMakeFiles/Makefile2:85: recipe for target 'dynet/CMakeFiles/dynet.dir/all' failed
make[1]: *** [dynet/CMakeFiles/dynet.dir/all] Error 2
make[1]: Leaving directory '/home/vytas/dynet/build'
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
"""""""""""""""""""""""""""

After running "cmake .. -DEIGEN3_INCLUDE_DIR=/path/to/eigen -DENABLE_CPP_EXAMPLES=ON" the build was successful:
"""""""""""""""""""""""""""
-- BACKEND not specified, defaulting to eigen.
-- Eigen dir is /usr/include/eigen3
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vytas/dynet/build
"""""""""""""""""""""""""""

Do you have any idea what is going on after running "make -j 2"?
I think an error has something to do with Eigen.
Thank you in advance!

**Comment by VytM** [comment]
My specs:
16.04 Ubuntu,
Intel® Core™ i7-8700K CPU @ 3.70GHz × 12,
GeForce GTX 1080 Ti/PCIe/SSE2,
64-bit

**Comment by FilippoC** [comment]
This seems to be a problem with Eigen.Did you download the dev version of Eigen?

`hg clone https://bitbucket.org/eigen/eigen/ -r b2e267d`

See https://dynet.readthedocs.io/en/latest/install.html

> To compile DyNet you also need the development version of the Eigen library. If you use any of the released versions, you may get assertion failures or compile errors

**Comment by VytM** [comment]
Thanks, it worked!
