### ISSUE TITLE
no generation of dynet_swigJNI_scala.jar

### ISSUE THREAD

**Issue by nanguoshun** [clab/dynet#1453]
Hi,
would you pls give some suggestions for the follows issue.
I install latest swig, scala on MAC and then execute following command in readme
build$ cmake .. -DEIGEN3_INCLUDE_DIR=/path/to/eigen -DENABLE_SWIG=ON
build$ make

However, only two jar files, dynet_swigJNI.jar,  and dynet_swigJNI_dylib.jar are generated and there are some output errors as follows:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000a0000000a, pid=2976, tid=0x0000000000003903
#
# JRE version: Java(TM) SE Runtime Environment (8.0_171-b11) (build 1.8.0_171-b11)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.171-b11 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  0x0000000a0000000a
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/nnngg/Documents/javaproject/dynet-master/contrib/swig/hs_err_pid2976.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
Exception in thread "Thread-8" java.io.EOFException
	at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2958)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1538)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:798)
	at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:787)
	at java.lang.Thread.run(Thread.java:748)
[info] Run completed in 1 second, 280 milliseconds.
[info] Total number of tests run: 18
[info] Suites: completed 7, aborted 0
[info] Tests: succeeded 18, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[error] Error during tests:
[error] 	Running java with options -classpath /Users/nnngg/Documents/javaproject/dynet-master/build/contrib/swig/target/scala-2.11/test-classes:/Users/nnngg/Documents/javaproject/dynet-master/build/contrib/swig/target/scala-2.11/classes:/Users/ngs/Documents/javaproject/dynet-master/build/contrib/swig/dynet_swigJNI.jar:/Users/nnngg/Documents/javaproject/dynet-master/build/contrib/swig/dynet_swigJNI_dylib.jar:/Users/nnngg/Documents/javaproject/dynet-master/build/contrib/swig/libdynet_swig.jnilib:/Users/nnngg/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.11.jar:/Users/nnngg/.ivy2/cache/org.scalatest/scalatest_2.11/bundles/scalatest_2.11-3.0.0.jar:/Users/nnngg/.ivy2/cache/org.scalactic/scalactic_2.11/bundles/scalactic_2.11-3.0.0.jar:/Users/nnngg/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.11.jar:/Users/nnngg/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.5.jar:/Users/nnngg/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.4.jar:/Users/nnngg/.sbt/boot/scala-2.12.6/org.scala-sbt/sbt/1.2.3/test-agent-1.2.3.jar:/Users/nnngg/.sbt/boot/scala-2.12.6/org.scala-sbt/sbt/1.2.3/test-interface-1.0.jar sbt.ForkMain 50288 failed with exit code 134
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 7 s, completed Sep 19, 2018 4:47:10 PM
make[2]: *** [contrib/swig/scala_helper_uberjar] Error 1
make[1]: *** [contrib/swig/CMakeFiles/scala_helper.dir/all] Error 2
make: *** [all] Error 2

**Comment by shuheik** [comment]
As a workaround, specifying -DSCALA_VERSION=2.12.6 for cmake may solve the problem.

**Comment by shuheik** [comment]
Could you try
`echo "sbt.version=0.13.17" > /path/to/dynet/contrib/swig/project/build.properties`
and build again?

**Comment by nanguoshun** [comment]
I resolved the issue by adding in file /path/to/dynet/contrib/swig/project/build.sbt
javaOptions in Test ++= Seq("-Xms1G","-XX:+CMSClassUnloadingEnabled","-XX:+UseConcMarkSweepGC")


Thanks @shuheik !
