### ISSUE TITLE
Which direcctory should I put the file libdynet_swig.jnilib

### ISSUE THREAD

**Issue by nanguoshun** [clab/dynet#1454]
I am writing java code based on API provided by Swig. Where should I put the file libdynet_swig.jnilib?

Thanks a lot!

**Comment by nanguoshun** [comment]
actually it is unnecessary to consider it! Thanks a lot!

**Comment by pmichel31415** [comment]
Hi @nanguoshun , seems like you've been able to install java in the end. If there's anything you ran into that wasn't clearly explained in the docs, feel free to update it with a pull request: https://github.com/clab/dynet/blob/master/contrib/swig/README.md this would be very useful for future practitioners.
