### ISSUE TITLE
Configuring incomplete error (pthreads?)

### ISSUE THREAD

**Issue by ffancellu** [clab/dynet#1470]
Hi,

I am having problems when installing dynet with GPU support. I am following the instructions for manual installation at: [https://dynet.readthedocs.io/en/latest/python.html#installing-dynet-for-python](url)

I am attaching the cmakerror.log file. Looks like there are two errors (maybe related?): an undefined reference to `pthread_create' and a "cannot find -lpthreads" error.

Thanks!
[CMakeError.log](https://github.com/clab/dynet/files/2455436/CMakeError.log)

**Comment by FilippoC** [comment]
Hi,

on which cluster of Edinburgh are you trying to build it? I did not have any problem on Eddie, Rockall and Stkilda (CPU only, however, but this error does not seems to be related to GPU). If I have access to the cluster I can try to find a fix.

**Comment by ffancellu** [comment]
Hi,
was looking at a previous issue and it looks like it has to do with feeding the absolute path of eigen and not the relative before compiling. Yep, I have no problem installing the CPU version but the GPU is now throwing a different error. I'll close this issue and open another one. Thanks for the offer though, much appreciated!
