### ISSUE TITLE
Exploding gradients when using contract3d_1d

### ISSUE THREAD

**Issue by vered1986** [clab/dynet#1473]
Hi,

I'm using `contract3d_1d` and occasionally getting the following error: "RuntimeError: Magnitude of gradient is bad: -nan" (sometimes with positive nan). 

Here is a minimal example that shows this error:

```python
import dynet as dy
import numpy as np

dim = 3
input_dim = 15

m = dy.ParameterCollection()
trainer = dy.SimpleSGDTrainer(m)

W = m.add_parameters((dim, dim, 15))

instances = [np.random.rand(input_dim) for i in range(10000)]
positive_examples = [(np.random.rand(dim), np.random.rand(dim)) for i in range(10000)]
negative_examples = [np.random.rand(5, dim) for i in range(10000)]

for i, (instance, pos, neg) in enumerate(zip(instances, positive_examples, negative_examples)):
    dy.renew_cg()
    losses = []
    matrix = dy.contract3d_1d(W, dy.inputVector(instance))

    # Positive
    u, v = pos    
    u, v = dy.inputVector(u), dy.inputVector(v)
    losses.append(-dy.log(dy.logistic(dy.transpose(u) * matrix * v)))
        
    # Negative samples
    neg = dy.inputTensor(neg)
    prod = dy.transpose(u) * matrix * dy.transpose(neg)
    losses.append(dy.sum_elems(-dy.log(dy.logistic(-prod))))
    
    loss = dy.esum(losses)
    print(loss.value())
    loss.backward()
    trainer.update()
    print(i)
```

Basically what I'm trying to do is to convert a vector to a matrix efficiently. I could change `input_dim` to `dim**2` and use `reshape`, but it's very slow. So I figured I can learn a tensor that does this mapping. I'm not sure I'm using `contract3d_1d` correctly - if not, I'd be happy to get alternative suggestions. 

I also tried setting `input_dim = dim` and `m` to the outer product of the input vector with itself. When I do this, I don't get this error, but I'm worried I may be needlessly restricting the matrix space. 

Thanks in advance!

**Comment by pmichel31415** [comment]
Hi! So after doing a bit of manual inspection I've noticed that the NaN is caused because your loss becomes infinite at some point. The reason seems to be that one of the `prod` becomes very negative/positive which causes the logistic to be 0 and the log produces a NaN. I could remove the error by replacing `dy.log(dy.logistic(...))` with `dy.log(dy.logistic(...) + 1e-20)`

**Comment by redpony** [comment]
Even better: use dy.log_sigmoid. Using dy.log(dy.sigmoid(x)) is asking for
trouble. Ideally we should identify this pair and rewrite the graph, but ...

**Comment by vered1986** [comment]
`dy.log_sigmoid` indeed works well, thanks @pmichel31415 and @redpony for the quick and helpful replies!
