### ISSUE TITLE
[question][help wanted]How to define a CNN LSTM model to be trained jointly in dynet?

### ISSUE THREAD

**Issue by sabeena1217** [clab/dynet#1475]
Hello @neubig ,

I'm trying to implement a CNN LSTM model using dynet, for my research in NLP. But I could not find any reference on **developing CNN layers in a LSTM**, so that they can be trained jointly. 

It would be really helpful if I could find any reference on this matter.

Thank you.

**Comment by john-hewitt** [comment]
I haven't tried this myself, but it seems that the 2D conv operations with a height of 1 should do the trick for convolution over sequences.

https://dynet.readthedocs.io/en/latest/python_ref.html#dynet.conv2d

**Comment by pmichel31415** [comment]
Hi @sabeena1217 , @john-hewitt 's solution is the way to go for 1d convolution. Feel free to reopen this if you need more info
