### ISSUE TITLE
Need for clarification: batch dimension and underlying layout of the data

### ISSUE THREAD

**Issue by FilippoC** [clab/dynet#1477]
Hi,

Let's assume I have to sentence of size S (i.e. padded sentences if needed) and I want to batch their embeddings (i.e. I am not using autobatch).

How is a tensor of dimension {dim emb, S}x2 stored in memory?
- one couple of embeddings (one for each sentence) after the other ("without batch lookup 1" below")
- one sentence after the other ("without batch lookup 2" below")

if it is option 2, I expect that manually reshaping with the batch dimension is faster than using concatenate_cols after a sequence of batch lookup?

I may have missed this information in the documentation.

```
// with batch lookup
vector<Expression> embs;
for (unsigned i = 0u ; i < S ; ++i)
    embs.push_back(lookup(cg, {sentence1[i], sentence2[i]}))
// this tensor will be of size {dim emb, S}x2
auto e = concatenate_cols(embs)

// without batch lookup 1
vector<Expression> embs;
for (unsigned i = 0u ; i < S ; ++i)
{
    embs.push_back(lookup(cg, sentence1[i]))
    embs.push_back(lookup(cg, sentence2[i]))
}
auto e = concatenate_cols(embs);
// will this give the same results as with batch lookup + concatenate_cols?
auto e = reshape(embs, Dim({dim emb, S}, 2));

// without batch lookup 2
vector<Expression> embs;
for (unsigned i = 0u ; i < S ; ++i)
    embs.push_back(lookup(cg, sentence1[i]))
for (unsigned i = 0u ; i < S ; ++i)
    embs.push_back(lookup(cg, sentence2[i]))
auto e = concatenate_cols(embs)
// will this give the same results as with batch lookup + concatenate_cols?
auto e = reshape(embs, Dim({dim emb, S}, 2));
```

**Comment by neubig** [comment]
The memory layout is such that the entirety of batch element 1 will be before the entirety of batch element 2, etc. So if you have a sentence `[1,2]`, and another sentence `[3,4]`, then `batch_lookup([1,2,3,4])` followed by a reshape would get the same result.

**Comment by FilippoC** [comment]
Alright, thank you!
