### ISSUE TITLE
Warnings during build, including minor bug in examples/segrnn-sup.cc

### ISSUE THREAD

**Issue by jkkummerfeld** [clab/dynet#148]
While building the current version I had a few warnings, one of which looks like a bug:

```
.../dynet/examples/segrnn-sup.cc:848:10: warning: comparison of unsigned expression >= 0 is always true
      [-Wtautological-compare]
```

This is referring to the if statement at the end of this function:

```
void test_only(SegmentalRNN<LSTMBuilder>& segrnn,
          vector<pair<vector<int>,vector<pair<int,int>>>>& test_set,
          int max_seg_len = 0)
{
  for (auto& sent : test_set) {
    ComputationGraph cg;
    vector<pair<int, int>> yz_pred;
    vector<Expression> xins = segrnn.ConstructInput(sent.first, cg);
    segrnn.ViterbiDecode(xins, sent.second, cg, yz_pred, max_seg_len);
    unsigned int i;
    for(i = 0; i < yz_pred.size()-1; ++i){
      auto pred = yz_pred[i];
      cout << segrnn.td.convert(pred.first) << ":" << pred.second << " ";
    }
    if(i >= 0 && (i == yz_pred.size()-1)){
      auto pred = yz_pred[i];
      cout << segrnn.td.convert(pred.first) << ":" << pred.second;
    }
    cout << endl;
  }
}
```

Currently the if statement will always be true as `i` is positive, and will be at `yz_pred.size()-1` after the loop. I suspect it should be `i == 0` rather than `i >= 0` but haven't looked into the SegmentalRNN code yet to understand the behaviour on boundaries (another possibility is that the for loop shouldn't stop 1 before the end as it does now).

The other warnings don't actually look like issues, but I'll include them here just as an FYI:

```
.../dynet/dynet/treelstm.h:103:21: warning: private field 'cg' is not used [-Wunused-private-field]
  ComputationGraph* cg;
.../dynet/dynet/treelstm.h:132:21: warning: private field 'cg' is not used [-Wunused-private-field]
  ComputationGraph* cg;
.../dynet/dynet/hsm-builder.h:24:8: warning: private field 'initialized' is not used [-Wunused-private-field]
  bool initialized;
```

**Comment by jkkummerfeld** [comment]
Brief update - the main point of this issue is still true. However, the first two warnings (` warning: private field 'cg' is not used`) are no longer present.

**Comment by neubig** [comment]
Thanks! I haven't gotten around to doing this, but I'll be happy to incorporate a pull request.

**Comment by ikekonglp** [comment]
Thanks! I checked this. It should be a redundant if statement and I put the thing into the main for loop.

**Comment by jkkummerfeld** [comment]
Ok!
