### ISSUE TITLE
How can I load a pre-trained seq2seq model in Dynet and then fintune the model?

### ISSUE THREAD

**Issue by Calciferl** [clab/dynet#1486]
I can't find an example from Internet, or a more soft intro is very helpful for me. Thank you!

**Comment by neubig** [comment]
It's as easy as calling the `save()` function of the parameter collection (https://dynet.readthedocs.io/en/latest/python_ref.html#dynet.ParameterCollection.save) after you finish your initial training, then calling the `load()` function after declaring all your parameters when you want to load the model. See here for a high-level example: https://dynet.readthedocs.io/en/latest/python_ref.html#dynet.save
