### ISSUE TITLE
Unable to compile with CUDA 8.0.44

### ISSUE THREAD

**Issue by FilippoC** [clab/dynet#1492]
Hi,

I am unable to install Dynet on the new cluster of my university.
```
[levi]v1ccorro: cmake .. -DCUDNN_ROOT=/opt/cuda-8.0.44/ -DBACKEND=cuda -DEIGEN3_INCLUDE_DIR=/disk/greider/v1ccorro/repos/eigen -DCUDA_ARCH=61 -DCUDA_TOOLKIT_ROOT_DIR=/opt/cuda-8.0.44/
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- BACKEND: cuda
-- Found CUDA: /opt/cuda-8.0.44/ (found version "8.0")
CUDA_LIBRARIES: /opt/cuda-8.0.44/lib64/libcudart.so;/opt/cuda-8.0.44/lib64/libcurand.so
-- Found CUDNN (include: /usr/include, library: /usr/lib64/libcudnn.so)
-- Successfully include CUDNN flags
-- Eigen dir is /disk/greider/v1ccorro/repos/eigen
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /disk/greider/v1ccorro/repos/dynet/build
```

Compilation output: http://termbin.com/ni9g

Has anyone any idea why I am not able to compile? Thanks!

**Comment by Hartbook** [comment]
Hello,

I think that there are multiple versions of cuda installed on your cluster, you made sure to link the shared object of cuda-8.0.44, but the compiler import the wrong version of `#include <cudnn.h>`

One fix would probably be to change every instance of `#include <cudnn.h>` in dynet, in favor of the absolute path of the right instance of cudnn.h, before compiling

**Comment by FilippoC** [comment]
Thanks for the hint. There is no better option than manually editing this? :/

**Comment by FilippoC** [comment]
Ok, I succeded with the following trick (I already had the same problem with cuda, didn't know that this applies to cudnn too):

export PATH=/opt/cuda-8.0.44/bin:$PATH
export LD_LIBRARY_PATH=/opt/cuda-8.0.44/lib64:/opt/cuda-8.0.44/extras/CUPTI/lib64/:$LD_LIBRARY_PATH
export LIBRARY_PATH=/opt/cuda-8.0.44/lib64:$LIBRARY_PATH
export CPLUS_INCLUDE_PATH=/opt/cuda-8.0.44/include:$CPLUS_INCLUDE_PATH

export PATH=/opt/cuDNN-7.1_9.1/bin:$PATH
export LD_LIBRARY_PATH=/opt/cuDNN-7.1_9.1/lib64:$LD_LIBRARY_PATH
export LIBRARY_PATH=/opt/cuDNN-7.1_9.1/lib64:$LIBRARY_PATH
export CPLUS_INCLUDE_PATH=/opt/cuDNN-7.1_9.1/include:$CPLUS_INCLUDE_PATH
