### ISSUE TITLE
unable to check gradient from loss

### ISSUE THREAD

**Issue by gailweiss** [clab/dynet#1505]
I am trying to handle a magnitude of gradient is bad: nan error as discussed in various other issues (https://github.com/clab/dynet/issues/1456, https://github.com/clab/dynet/issues/1382, https://github.com/swabhs/open-sesame/issues/13), and recognise that it may be caused by a problem in my model (I will take care to run with check_validity and immediate_compute set to True as advised elsewhere, but this happens some hours into training so it is not immediately doable). 

In the meantime I would like to check the gradients of my model, as in https://github.com/clab/dynet/issues/515. I compute the loss, check the value (it is not problematic), run `backward()`, and attempt to run `gradient()`. Here is a code snippet:

```
trainer = dy.AdamTrainer(rnn.pc)
loss = rnn.loss_on_word(train_set[100])
print(loss.value()) # prints 62.650...
loss.backward()
# trainer.update()   # raises RuntimeError: Magnitude of gradient is bad: nan
loss.gradient()
```

however, I get the following error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-32-ed0cb0da6b4b> in <module>()
      4 loss.backward()
      5 # trainer.update()   # raises RuntimeError: Magnitude of gradient is bad: nan
----> 6 loss.gradient()

_dynet.pyx in _dynet.Expression.gradient()

_dynet.pyx in _dynet.Expression.gradient()

RuntimeError: Requested gradient for node 1191, but backward pass was computed from node 1190
```

I do not change the loss between the `backward()` call and the `gradient()` call, so why does it say it is from different nodes? Attempting to run the same code without the `backward()` call before the `gradient()` simply raises:

```
RuntimeError: Requested gradient for node 1191, but backward pass was computed from node 4294967295
```

How can I find the gradient of my loss?

I am using dynet in python, installed long after May 2017 (which is when https://github.com/clab/dynet/issues/515 was closed)

**Comment by pmichel31415** [comment]
`x.gradient()` will give you `d/dx` of the expression called `.backward()` on. Here you're asking for `d loss / d loss` so dynet is confused. In the second case you haven't called `.backward()` at all so the # of the node to compute the gradient against is not set (4294967295 = 2^32-1).

For your particular use case:
- if you want to ignore iterations NaN gradients just catching the RuntimeError should work I think
- if you want to check the gradient for parameters you should call `.grad_as_array()` on all parameters in your ParameterCollection (you can get those with `pc.parameters_list()` I think).

Hope that helps

**Comment by gailweiss** [comment]
That lets me see everything! Thank you :)
