### ISSUE TITLE
sigmoid gives nans (or 0.5 (!)) on large inputs

### ISSUE THREAD

**Issue by neubig** [clab/dynet#1525]
It looks like there's a problem in the sigmoid function on very large inputs.

On GPU and probably also CPU without optimization,  this line gives NaN whenever the exp overflows:
https://github.com/clab/dynet/blame/master/dynet/simd-functors.h#L81

On CPU with packet math enabled, sometimes it gives "0.5", which is probably a problem with packet math:
https://github.com/clab/dynet/blob/master/dynet/simd-functors.h#L90

Here is code to reproduce:

    import dynet as dy
    x = dy.inputTensor([-1662.72692871,  3212.53930664, -1093.66174316,  2063.79956055,
       91.38743591, -1471.00500488,  1823.1607666,   1935.2911377, 0.0, -0.5])
    y = dy.logistic(x)
    print(y.npvalue())

**Comment by neubig** [comment]
CC: @pmichel31415 I think you might have worked on this, so FYI. I can also take a look.

**Comment by armatthews** [comment]
It looks to me like the "pmin" and "pmax" need switched to deal with the CPU packet math version:
``return psub(padd(pmax(half, pdiv(one, padd(one, pexp(pnegate(x))))), pmin(half, pdiv(pexp(x), padd(one, pexp(x))))), half);``

**Comment by armatthews** [comment]
The threshold for correct vs. incorrect threshold seems to be between 88.0 and 89.0 for both implementations. I get 1.0 for logistic(88.0) but NaN or 0.5 for logistic(89) on tir.

**Comment by armatthews** [comment]
Fixed in [this commit](https://github.com/clab/dynet/commit/e5a1116adb60d4fa47439b74094e5df83f6dee7c).
