### ISSUE TITLE
Embedding matrix of LookupParameter

### ISSUE THREAD

**Issue by duyvuleo** [clab/dynet#153]
I implemented the following code to get the embedding matrix of a LookupParameter:

`cnn::LookupParameter p_wr_W_ = model.add_lookup_parameters(VOCAB_SIZE, {HIDDEN_DIM}); `
`// ... initialize p_wr_W_`
`std::vector<cnn::expr::Expression> vEs(VOCAB_SIZE);`
`for (int i = 0; i < VOCAB_SIZE; i++)`
	`vEs[i] = cnn::lookup(cg, p_wr_W_, i);`
`cnn::expr::Expression  return_we_matrix = concatenate_cols(vEs);`

Is there a faster (and more efficient) way of doing that??? Thanks!

**Comment by neubig** [comment]
No, but there should be. I'll mark this as an enhancement.

**Comment by neubig** [comment]
Fixed by https://github.com/clab/dynet/commit/dd81a851fc1accd2be070efee432eb56f9128a56
