### ISSUE TITLE
LSTM builder is not the standard LSTM

### ISSUE THREAD

**Issue by pmichel31415** [clab/dynet#154]
After looking at the code in lstm.h, it seems that the LSTMBuilder cell has the following update rule : 
![imgtemp-rtc2r2-1](https://cloud.githubusercontent.com/assets/10391785/20528799/9a25d48c-b09b-11e6-8df6-7f97cd859a49.png)

Which is not the common update rule :

![imgtemp-ffi3s1-1](https://cloud.githubusercontent.com/assets/10391785/20528795/96a89092-b09b-11e6-9191-7f6bc5132c81.png)

(i.e. in the dynet implementation the forget and input gate are coupled and there are peaky connections with the cell state c)

What are the reasons behind this choice?

Anyway I think this should be documented.

**Comment by neubig** [comment]
I've heard that the motivation is the results in this paper: https://arxiv.org/abs/1503.04069

But I agree that this should be documented.

**Comment by pmichel31415** [comment]
I see. I started documenting the lstm.

I also started implementing a vanilla LSTM. Would it be interesting to have it in the form of two optional parameters `coupling` and `peepholes` in the constructor? With default values `true` for compatibility.

**Comment by yoavg** [comment]
the LSTMBuilder is quite central. I agree that it would be good to add
these, just need to ensure that:
- no speed penalty
- the values are saved / loaded with the model
- we remain backward compatible with saved models

**Comment by yoavg** [comment]
After staring at the code (admittedly without pen and paper at hand, I'm commuting), I am pretty sure the code implements something else than what's written above -- for example $o_t$ uses $c_t$ (`ct[i]`) and not $c_{t-1}$ (`i_c_tm1`), and `tanh` is applied twice (it is also applied on $c_t$ just prior to computing $h_t$.

**Comment by pmichel31415** [comment]
@yoavg yes you are right this is my mistake, I'll update the original post.

I've been working on implementing the aforementioned options to the LSTMBuilder, but I'll put it on hold until the dropout PR is merged.

**Comment by yoavg** [comment]
this may affect the dropout PR, as I may be introducing dropout in an un-intended place (or effectively introducing it twice) -- and may not be.

**Comment by neubig** [comment]
An alternative VanillaLSTMBuilder is now available, documentation in the "Unorthodox Things" section as of this commit: https://github.com/clab/dynet/commit/7935e794d45607460a4bd5c528f82fd3cf682ce9
