### ISSUE TITLE
Pick indices with values > threshhold

### ISSUE THREAD

**Issue by Adamits** [clab/dynet#1548]
Hello!

Is it currently possible with the python interface to pick all indices of an `Expression` whose value is greater than some threshold? Is this something that should be done with a `Tensor` rather than an `Expression`, if I want it do be done on GPU?

I apologize if this is the wrong place for this quesiton, but I cannot seem to find a forum, and am having some difficulty ensuring that I am looking at up-to-date documentation.

Thanks!

**Comment by neubig** [comment]
This is not something that we have natively in DyNet, and because it's an inherently non-differentiable operation it's likely something that it'd be fine to do in NumPy (or native C++ if you're implementing in C++). That wouldn't be in NumPy, but it'd probably still be sufficiently fast?

**Comment by Adamits** [comment]
Thanks for the quick response! This begs a brief follow up question for me.

In general, is Dynet only interested in implementing operations that will be backpropagated? Relatedly, is it pointless to try to use autobatching at test time?

**Comment by FilippoC** [comment]
@Adamits Autobatch is really helpful at test time even if you predict one sentence a time, e.g. when you have character LSTMs.

**Comment by neubig** [comment]
We're not completely uninterested, but it'd be a major effort in order to do this right. I think we'd probably start out with having to do something more standard (maybe just seq2seq beam decoding?) with autobatching, and then move on to more complicated things like this. Given the resources we have right now we'd need a champion to step up to do it (if you're willing to be one then we could talk more :)).

**Comment by Adamits** [comment]
That makes sense. 

I would definitely be interested in attempting to implement seq2seq beam decoding for autobatching! That is something I was looking for earlier in the week (I am just using a python `List` with `heapq`, but came across https://github.com/clab/dynet/pull/1328).

Of course, there may be a very significant learning curve for me.
