### ISSUE TITLE
Is there a reverse of dy.concatenate_to_batch?

### ISSUE THREAD

**Issue by philip30** [clab/dynet#1556]
Sometimes we combine a single sequence element into a big batch to faster up computation.
To get an equal result by using for loop, we need to pick the element one by one:

```python
batch = dy.concatenate_to_batch(expr_list) #of batch_size 1
result_expr = forward(batch)
result = [dy.pick_batch_elem(result_expr, i) for i in range(result_expr.dim()[1])]
```

which I think is not very efficient. I think toolkits like Chainer or PyTorch support this kind of tensor operation. Does Dynet support this?

**Comment by neubig** [comment]
Nope, that is the only way to do it because dynet operations can only output a single tensor.
