### ISSUE TITLE
Exposing additional RNN builders through Python API

### ISSUE THREAD

**Issue by tjphilpot** [clab/dynet#1566]
I'm working on a project using DyNet that uses a C++ subclass of RNNBuilder that was written as part of the M4 competition. I'd like to expose it with a Python binding so I can do most of the work in Python not C++. The main class is an implementation of ResidualDilatedRNNBuilder from the zip file here: https://github.com/M4Competition/M4-methods/tree/master/118%20-%20slaweks17

I tried using Cython to expose the subclass following the examples of the dynet.pxd and pyx files, but ran in to trouble with trying to access bindings in the dynet python package. According to [this](https://cython.readthedocs.io/en/latest/src/userguide/sharing_declarations.html) I think it should be possible, but I'm not enough of a cython expert to know what, if anything, needs to be modified on the dynet side to allow another cython module to share declarations.

In the end, I ended up forking dynet and putting the .cc files into the dynet C++ source and extending the .pxd and .pxy files to get it to work. I could submit a PR, but I'm not sure that putting every possible flavor of RNNBuilder into dynet is the right way forward.

Thoughts?

**Comment by neubig** [comment]
Thanks for the interest! Long story short, I don't think we'll add this to DyNet itself because each one we have adds maintenance overhead (I feel we already have too many now). But one thing that might be nice is if we could add a link to the doc somewhere about additional examples of builders elsewhere.

**Comment by tjphilpot** [comment]
Thanks. If I figure out how to expose these RNNBuilders via Cython external to dynet source itself, rather than maintaining a private fork, I'll try to post an example for others.
