### ISSUE TITLE
Error after running "make -j 2" for c++

### ISSUE THREAD

**Issue by liycccc** [clab/dynet#1577]
error occurs after command "make -j 2":
___________________________________
[ 49%] Building CXX object examples/CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o
[ 50%] Linking CXX executable transformer-decode
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `load_data(boost::program_options::variables_map const&, std::vector<std::tuple<std::vector<int, std::allocator<int> >, std::vector<int, std::allocator<int> > >, std::allocator<std::tuple<std::vector<int, std::allocator<int> >, std::vector<int, std::allocator<int> > > > >&, dynet::Dict&, dynet::Dict&, transformer::SentinelMarkers&)':
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:/usr/local/include/boost/program_options/variables_map.hpp:155: more undefined references to `boost::program_options::abstract_variables_map::operator[](std::string const&) const' follow
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::typed_value<std::string, char>::xparse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&) const':
/usr/local/include/boost/program_options/detail/value_semantic.hpp:184: undefined reference to `boost::program_options::validate(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, std::string*, int)'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::validation_error::validation_error(boost::program_options::validation_error::kind_t, std::string const&, std::string const&, int)':
/usr/local/include/boost/program_options/errors.hpp:378: undefined reference to `boost::program_options::validation_error::get_template(boost::program_options::validation_error::kind_t)'
/usr/local/include/boost/program_options/errors.hpp:378: undefined reference to `boost::program_options::error_with_option_name::error_with_option_name(std::string const&, std::string const&, std::string const&, int)'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::typed_value<int, char>::name() const':
/usr/local/include/boost/program_options/detail/value_semantic.hpp:22: undefined reference to `boost::program_options::arg'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::typed_value<unsigned int, char>::name() const':
/usr/local/include/boost/program_options/detail/value_semantic.hpp:22: undefined reference to `boost::program_options::arg'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::typed_value<std::string, char>::name() const':
/usr/local/include/boost/program_options/detail/value_semantic.hpp:22: undefined reference to `boost::program_options::arg'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::error_with_option_name::~error_with_option_name()':
/usr/local/include/boost/program_options/errors.hpp:124: undefined reference to `vtable for boost::program_options::error_with_option_name'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::validation_error::~validation_error()':
/usr/local/include/boost/program_options/errors.hpp:124: undefined reference to `vtable for boost::program_options::error_with_option_name'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::invalid_option_value::~invalid_option_value()':
/usr/local/include/boost/program_options/errors.hpp:124: undefined reference to `vtable for boost::program_options::error_with_option_name'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::error_with_option_name::~error_with_option_name()':
/usr/local/include/boost/program_options/errors.hpp:124: undefined reference to `vtable for boost::program_options::error_with_option_name'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::validation_error::~validation_error()':
/usr/local/include/boost/program_options/errors.hpp:124: undefined reference to `vtable for boost::program_options::error_with_option_name'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:/usr/local/include/boost/program_options/errors.hpp:124: more undefined references to `vtable for boost::program_options::error_with_option_name' follow
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::basic_command_line_parser<char>::run()':
/usr/local/include/boost/program_options/detail/parsers.hpp:92: undefined reference to `boost::program_options::detail::cmdline::get_canonical_option_prefix()'
/usr/local/include/boost/program_options/detail/parsers.hpp:93: undefined reference to `boost::program_options::detail::cmdline::run()'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*)':
/usr/local/include/boost/program_options/detail/convert.hpp:79: undefined reference to `boost::program_options::to_internal(std::string const&)'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::basic_command_line_parser<char>::basic_command_line_parser(int, char const* const*)':
/usr/local/include/boost/program_options/detail/parsers.hpp:28: undefined reference to `boost::program_options::detail::cmdline::cmdline(std::vector<std::string, std::allocator<std::string> > const&)'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::variables_map::~variables_map()':
/usr/local/include/boost/program_options/variables_map.hpp:146: undefined reference to `vtable for boost::program_options::variables_map'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `main':
/home/liyu/dynet/examples/transformer/transformer-decode.cc:55: undefined reference to `boost::program_options::variables_map::variables_map()'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:56: undefined reference to `boost::program_options::options_description::m_default_line_length'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:56: undefined reference to `boost::program_options::options_description::options_description(std::string const&, unsigned int, unsigned int)'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:58: undefined reference to `boost::program_options::options_description::add_options()'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:58: undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, char const*)'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:59: undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, boost::program_options::value_semantic const*, char const*)'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:61: undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, boost::program_options::value_semantic const*, char const*)'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:63: undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, boost::program_options::value_semantic const*, char const*)'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:64: undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, boost::program_options::value_semantic const*, char const*)'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:65: undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, boost::program_options::value_semantic const*, char const*)'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:/home/liyu/dynet/examples/transformer/transformer-decode.cc:66: more undefined references to `boost::program_options::options_description_easy_init::operator()(char const*, boost::program_options::value_semantic const*, char const*)' follow
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `main':
/home/liyu/dynet/examples/transformer/transformer-decode.cc:77: undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, char const*)'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:79: undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, char const*)'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:81: undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, char const*)'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:83: undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, char const*)'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:86: undefined reference to `boost::program_options::options_description_easy_init::operator()(char const*, boost::program_options::value_semantic const*, char const*)'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `main':
/usr/local/include/boost/program_options/detail/parsers.hpp:36: undefined reference to `boost::program_options::detail::cmdline::set_options_description(boost::program_options::options_description const&)'
/usr/local/include/boost/program_options/detail/parsers.hpp:54: undefined reference to `boost::program_options::detail::cmdline::style(int)'
/usr/local/include/boost/program_options/detail/parsers.hpp:62: undefined reference to `boost::program_options::detail::cmdline::set_additional_parser(boost::function1<std::pair<std::string, std::string>, std::string const&>)'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `main':
/home/liyu/dynet/examples/transformer/transformer-decode.cc:88: undefined reference to `boost::program_options::store(boost::program_options::basic_parsed_options<char> const&, boost::program_options::variables_map&, bool)'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `main':
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `main':
/home/liyu/dynet/examples/transformer/transformer-decode.cc:92: undefined reference to `boost::program_options::basic_parsed_options<char> boost::program_options::parse_config_file<char>(std::basic_istream<char, std::char_traits<char> >&, boost::program_options::options_description const&, bool)'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:92: undefined reference to `boost::program_options::store(boost::program_options::basic_parsed_options<char> const&, boost::program_options::variables_map&, bool)'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:94: undefined reference to `boost::program_options::notify(boost::program_options::variables_map&)'
/home/liyu/dynet/examples/transformer/transformer-decode.cc:108: undefined reference to `boost::program_options::operator<<(std::ostream&, boost::program_options::options_description const&)'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `main':
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
/usr/local/include/boost/program_options/variables_map.hpp:155: undefined reference to `boost::program_options::abstract_variables_map::operator[](std::string const&) const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:/usr/local/include/boost/program_options/variables_map.hpp:155: more undefined references to `boost::program_options::abstract_variables_map::operator[](std::string const&) const' follow
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::variables_map::~variables_map()':
/usr/local/include/boost/program_options/variables_map.hpp:146: undefined reference to `vtable for boost::program_options::variables_map'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `boost::program_options::error_with_option_name::error_with_option_name(boost::program_options::error_with_option_name const&)':
/usr/local/include/boost/program_options/errors.hpp:94: undefined reference to `vtable for boost::program_options::error_with_option_name'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `void boost::program_options::validate<int, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, int*, long)':
/usr/local/include/boost/program_options/detail/value_semantic.hpp:89: undefined reference to `boost::program_options::validators::check_first_occurrence(boost::any const&)'
/usr/local/include/boost/program_options/detail/value_semantic.hpp:95: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o: In function `void boost::program_options::validate<unsigned int, char>(boost::any&, std::vector<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned int*, long)':
/usr/local/include/boost/program_options/detail/value_semantic.hpp:89: undefined reference to `boost::program_options::validators::check_first_occurrence(boost::any const&)'
/usr/local/include/boost/program_options/detail/value_semantic.hpp:95: undefined reference to `boost::program_options::invalid_option_value::invalid_option_value(std::string const&)'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x20): undefined reference to `boost::program_options::error_with_option_name::what() const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options20invalid_option_valueEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE]+0x28): undefined reference to `boost::program_options::error_with_option_name::what() const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options20invalid_option_valueEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE]+0x20): undefined reference to `boost::program_options::error_with_option_name::what() const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE[_ZTVN5boost16exception_detail19error_info_injectorINS_15program_options16validation_errorEEE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE]+0x28): undefined reference to `boost::program_options::error_with_option_name::what() const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE[_ZTVN5boost16exception_detail10clone_implINS0_19error_info_injectorINS_15program_options16validation_errorEEEEE]+0x38): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTIN5boost15program_options16validation_errorE[_ZTIN5boost15program_options16validation_errorE]+0x10): undefined reference to `typeinfo for boost::program_options::error_with_option_name'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTIN5boost15program_options11typed_valueISscEE[_ZTIN5boost15program_options11typed_valueISscEE]+0x18): undefined reference to `typeinfo for boost::program_options::value_semantic_codecvt_helper<char>'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTIN5boost15program_options11typed_valueIjcEE[_ZTIN5boost15program_options11typed_valueIjcEE]+0x18): undefined reference to `typeinfo for boost::program_options::value_semantic_codecvt_helper<char>'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTIN5boost15program_options11typed_valueIicEE[_ZTIN5boost15program_options11typed_valueIicEE]+0x18): undefined reference to `typeinfo for boost::program_options::value_semantic_codecvt_helper<char>'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTVN5boost15program_options16validation_errorE[_ZTVN5boost15program_options16validation_errorE]+0x20): undefined reference to `boost::program_options::error_with_option_name::what() const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTVN5boost15program_options16validation_errorE[_ZTVN5boost15program_options16validation_errorE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTVN5boost15program_options20invalid_option_valueE[_ZTVN5boost15program_options20invalid_option_valueE]+0x20): undefined reference to `boost::program_options::error_with_option_name::what() const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTVN5boost15program_options20invalid_option_valueE[_ZTVN5boost15program_options20invalid_option_valueE]+0x30): undefined reference to `boost::program_options::error_with_option_name::substitute_placeholders(std::string const&) const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTVN5boost15program_options11typed_valueISscEE[_ZTVN5boost15program_options11typed_valueISscEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTVN5boost15program_options11typed_valueIjcEE[_ZTVN5boost15program_options11typed_valueIjcEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
CMakeFiles/transformer-decode.dir/transformer/transformer-decode.cc.o:(.data.rel.ro._ZTVN5boost15program_options11typed_valueIicEE[_ZTVN5boost15program_options11typed_valueIicEE]+0x38): undefined reference to `boost::program_options::value_semantic_codecvt_helper<char>::parse(boost::any&, std::vector<std::string, std::allocator<std::string> > const&, bool) const'
collect2: error: ld returned 1 exit status
examples/CMakeFiles/transformer-decode.dir/build.make:95: recipe for target 'examples/transformer-decode' failed
make[2]: *** [examples/transformer-decode] Error 1
CMakeFiles/Makefile2:282: recipe for target 'examples/CMakeFiles/transformer-decode.dir/all' failed
make[1]: *** [examples/CMakeFiles/transformer-decode.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
___________________________________
I had  Boost in standard location. location:/usr/local/include/boost ,/usr/local/lib
this seems to be a problem with linking Boost libs
and my specs:
18.04 Ubuntu
Interl core i7 8th,64-bit
Do you have any ideas about this?
Thank you sincerely!

**Comment by FilippoC** [comment]
It seems that you are not linking to boost correctly.
Did you compile it manually or install it from the Ubuntu repo? It seems for example that your linker does not find program_options functions which is **not** a header-only lib: https://www.boost.org/doc/libs/1_66_0/more/getting_started/unix-variants.html#header-only-libraries

**Comment by liycccc** [comment]
I don't known what happens on my computer,but the compile program points to a wrong lib position and i just fixed it up.Thanks for you patient reply!
