### ISSUE TITLE
Can't populate ParameterCollection from old Model

### ISSUE THREAD

**Issue by dimidd** [clab/dynet#1579]
Hello,
I'm trying to load a model file which was saved using `Model.save` in an older version of dynet.
The first two lines of the file look like this:

>22 serialization::archive 14 1 0
>0 0 0 80 0 2 29 dynet::LookupParameterStorage 1 0

As per https://github.com/clab/dynet/issues/642, I've tried to replace `Model.load` with `ParameterCollection.populate`, but it makes the program hang.

**Comment by neubig** [comment]
Unfortunately this is a very old version of DyNet the models will not be backward compatible.
