### ISSUE TITLE
TypeError: '_dynet.LookupParameters' object does not support item assignment

### ISSUE THREAD

**Issue by BUAAChuanWang** [clab/dynet#1581]
when i try to make a embedding matrix with glove, I met this bug.
my code is：
self.word_embedding = self.nnmodel.add_lookup_parameters((num_words, word_embed_dim))
        for word_line in vocab_words:
            word = word_line.split()[0]
            i = word_line.split()[1]
            if(word in glove_word_embeddings_dict):
                self.word_embedding[i] = np.array(glove_word_embeddings_dict[word])

**Comment by BUAAChuanWang** [comment]
i need help...

**Comment by neubig** [comment]
I think the best thing would probably be to pre-create a numpy array with all of the embeddings, then use the following function: https://dynet.readthedocs.io/en/latest/python_ref.html#dynet.LookupParameters.init_from_array

Alternatively you can initialize a single row:
https://dynet.readthedocs.io/en/latest/python_ref.html#dynet.LookupParameters.init_row
