### ISSUE TITLE
rnnlm on GPU problem

### ISSUE THREAD

**Issue by ZhangShiyue** [clab/dynet#160]
Hi, 

I am a dynet user. I have some difficulties in using dynet, and I am really confused. I need your help.

I tried to run "examples/rnnlm" and "rnnlm/lm" on GPU and CPU. I got a surprising result. For "examples/rnnlm", GPU is about 10 times slower than CPU, while for "rnnlm/lm" GPU is about 10 times faster than CPU. As for data, I just use "examples/example-data/train-hsm.txt" as both train and dev set for  "examples/rnnlm". And removed the '\<s>' and \</s>' to use it in "rnnlm/lm".

I have tried very hard to figure the difference between "examples/rnnlm" and "rnnlm/lm", but I think they the same model. So I really don't know why they behave so differently on GPU and CPU, especially I consider why for "examples/rnnlm" GPU is so much slower than CPU?

Btw, I say the speed according to the " [completed in XXX ms]" in log. And I removed the sample process when running. 

Here is the log:
With GPU:
./examples/rnnlm ../examples/example-data/train-hsm.txt ../examples/example-data/train-hsm.txt
[dynet] initializing CUDA
Request for 1 GPU ...
[dynet] Device Number: 0
[dynet]   Device name: GeForce GTX 970
[dynet]   Memory Clock Rate (KHz): 3505000
[dynet]   Memory Bus Width (bits): 256
[dynet]   Peak Memory Bandwidth (GB/s): 224.32
[dynet]   Memory Free (GB): 4.16462/4.22963
[dynet]
[dynet] Device Number: 1
[dynet]   Device name: GeForce GTX 970
[dynet]   Memory Clock Rate (KHz): 3505000
[dynet]   Memory Bus Width (bits): 256
[dynet]   Peak Memory Bandwidth (GB/s): 224.32
[dynet]   Memory Free (GB): 4.16789/4.2329
[dynet]
[dynet] Device(s) selected: 1
[dynet] random seed: 1509578603
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Reading training data from ../examples/example-data/train-hsm.txt...
1000 lines, 10295 tokens, 1251 types
Reading dev data from ../examples/example-data/train-hsm.txt...
1000 lines, 10295 tokens
Parameters will be written to: lm_2_8_24-pid1516.params
**SHUFFLE
[epoch=0 eta=0.1 clips=32 updates=50]  E = 6.20015 ppl=492.823 [completed in 346.65 ms]
[epoch=0 eta=0.1 clips=39 updates=50]  E = 5.5577 ppl=259.226 [completed in 316.366 ms]
[epoch=0 eta=0.1 clips=43 updates=50]  E = 5.27379 ppl=195.154 [completed in 265.346 ms]

./rnnlm/lm -x -s -t ../examples/example-data/train.txt -d ../examples/example-data/train.txt -D 0.3 -H 1024 -i 256 --eta_decay_onset_epoch 10 --eta_decay_rate 0.5
[dynet] initializing CUDA
Request for 1 GPU ...
[dynet] Device Number: 0
[dynet]   Device name: GeForce GTX 970
[dynet]   Memory Clock Rate (KHz): 3505000
[dynet]   Memory Bus Width (bits): 256
[dynet]   Peak Memory Bandwidth (GB/s): 224.32
[dynet]   Memory Free (GB): 4.16462/4.22963
[dynet]
[dynet] Device Number: 1
[dynet]   Device name: GeForce GTX 970
[dynet]   Memory Clock Rate (KHz): 3505000
[dynet]   Memory Bus Width (bits): 256
[dynet]   Peak Memory Bandwidth (GB/s): 224.32
[dynet]   Memory Free (GB): 4.16789/4.2329
[dynet]
[dynet] Device(s) selected: 1
[dynet] random seed: 2699820229
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Reading training data from ../examples/example-data/train.txt ...
1000 lines, 8295 tokens, 1251 types
Reading dev data from ../examples/example-data/train.txt ...
1000 lines, 8295 tokens
Parameters will be written to: lm_0.3_2_256_1024-pid1533.params
**SHUFFLE
#1 [epoch=0.1 eta=0.1] E = 6.70884 ppl=819.623 [completed in 5926.15 ms]
#2 [epoch=0.2 eta=0.1] E = 6.19333 ppl=489.473 [completed in 5695.17 ms]
#3 [epoch=0.3 eta=0.1] E = 5.82569 ppl=338.894 [completed in 5413.28 ms]
#4 [epoch=0.4 eta=0.1] E = 5.53641 ppl=253.766 [completed in 5688.59 ms]

With CPU:
./examples/rnnlm ../examples/example-data/train-hsm.txt ../examples/example-data/train-hsm.txt
[dynet] random seed: 1071335136
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Reading training data from ../examples/example-data/train-hsm.txt...
1000 lines, 10295 tokens, 1251 types
Reading dev data from ../examples/example-data/train-hsm.txt...
1000 lines, 10295 tokens
Parameters will be written to: lm_2_8_24-pid1597.params
**SHUFFLE
[epoch=0 eta=0.1 clips=37 updates=50]  E = 6.16447 ppl=475.548 [completed in 30.0757 ms]
[epoch=0 eta=0.1 clips=48 updates=50]  E = 5.50006 ppl=244.706 [completed in 29.741 ms]
[epoch=0 eta=0.1 clips=48 updates=50]  E = 5.16275 ppl=174.645 [completed in 27.6972 ms]
[epoch=0 eta=0.1 clips=46 updates=50]  E = 5.0406 ppl=154.562 [completed in 27.0428 ms]
[epoch=0 eta=0.1 clips=46 updates=50]  E = 4.90252 ppl=134.628 [completed in 26.3374 ms]

./rnnlm/lm -x -s -t ../examples/example-data/train.txt -d ../examples/example-data/train.txt -D 0.3 -H 1024 -i 256 --eta_decay_onset_epoch 10 --eta_decay_rate 0.5
[dynet] random seed: 2388585473
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Reading training data from ../examples/example-data/train.txt ...
1000 lines, 8295 tokens, 1251 types
Reading dev data from ../examples/example-data/train.txt ...
1000 lines, 8295 tokens
Parameters will be written to: lm_0.3_2_256_1024-pid1562.params
**SHUFFLE
#1 [epoch=0.1 eta=0.1] E = 6.66489 ppl=784.377 [completed in 56794 ms]
#2 [epoch=0.2 eta=0.1] E = 6.1145 ppl=452.371 [completed in 57896.7 ms]
#3 [epoch=0.3 eta=0.1] E = 5.91643 ppl=371.084 [completed in 60360.9 ms]
#4 [epoch=0.4 eta=0.1] E = 5.62771 ppl=278.025 [completed in 54918.5 ms]

**Comment by yoavg** [comment]
Check the matrix sizes. CPU is much faster than GPU for small matrices.

**Comment by ZhangShiyue** [comment]
Yes, you're right. I was a little mislead by the notation:
unsigned INPUT_DIM = 8;  //256
unsigned HIDDEN_DIM = 24;  // 1024
 I thought they should be 2^8, 2^24. I even haven't check that...
Anyway, you're right. Thanks a lot!!! : )

**Comment by ZhangShiyue** [comment]
Yes, you're right. I was kind of mislead by the notation, 2^8=256... Such a silly thought.. 
unsigned INPUT_DIM = 8;  //256
unsigned HIDDEN_DIM = 24;  // 1024
Anyway, thanks a lot!!!
