### ISSUE TITLE
Different answers on different operating systems?

### ISSUE THREAD

**Issue by kwalcock** [clab/dynet#1603]
In a unit test I need to use code like that below to account for differing results when I run the same test program on different operating systems.  Is this expected behavior?  I believe to have built dynet using the same source code on each platform and used the exact same version of eigen.  Has anyone performed such a test before?  These numbers come from a simple Xor example, calling dynet through the Java interface.  On more lengthy runs, the differences accumulate and results can diverge even more.  I'm concerned about the reproducibility of results.

```scala
    if (isWindows) {
      mostRecentLoss.toString should be ("6.168399E-12")
      totalLoss.toString should be ("13.83572")
    }
    else if (isMac) {
      mostRecentLoss.toString should be ("7.2066797E-12")
      totalLoss.toString should be ("13.835721")
    }
    else if (isLinux) {
      mostRecentLoss.toString should be ("5.954348E-12")
      totalLoss.toString should be ("13.83572")
    }
```

**Comment by neubig** [comment]
We've not performed such a test before (AFAIK). A few questions:

1. Is this on GPU?
2. If on CPU, are you using multi-threading?

If the answer is "yes" to either of these, there's a bit of inherent instability in how Eigen handles things in multithreaded environments, including GPUs, so it can even change from run-to-run. I imagine that this would be even more different between operating systems.

If the answer is "no", given that the numbers are this small I'm guessing it's just due to rounding? It'd be good if you could identify the exact input and and output of a single operation that gives a different result, which would make it easier to tell where the difference stems from.

Graham

**Comment by kwalcock** [comment]
This is on CPUs.  I didn't add any multi-threading myself, but there could be some under the hood.  The test program is at https://github.com/clulab/fatdynet/blob/master/src/test/scala/org/clulab/fatdynet/test/TestXorScalaRun.scala, but it goes through several interface levels before getting to the C++ code.  I'll try to get closer to the metal with the C++ version.  Another possibility is different random number sequences.  I hope that people don't have to use my own computer to get the same results as me.

**Comment by kwalcock** [comment]
The runs below were performed on some existing installs on a couple of computers, so there is a chance that some of the source code is different.  I will eventually reinstall to make sure.  Perhaps someone else can chime in with the values they get.  I believe that eigen -r b2e267d is being used in each case.  The command is `./xor --dynet-seed=1234`.  The last line of output on Ubuntu is `E = 0.000558996` and on a Macintosh it is `E = 0.000559092`.  Full output is below:

Ubuntu:
```
[dynet] random seed: 1234
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
digraph G {
  rankdir=LR;
  nodesep=.05;
  N0 [label="v0 = parameters({8,2}) @ 0xc4f5f8"];
  N1 [label="v1 = parameters({8}) @ 0xc4f758"];
  N2 [label="v2 = parameters({1,8}) @ 0xc4f8d8"];
  N3 [label="v3 = parameters({1}) @ 0xc4fa68"];
  N4 [label="v4 = constant({2})"];
  N5 [label="v5 = scalar_constant(0x7ffc1e3be310)"];
  N6 [label="v6 = v0 * v4"];
  N0 -> N6;
  N4 -> N6;
  N7 [label="v7 = v6 + v1"];
  N6 -> N7;
  N1 -> N7;
  N8 [label="v8 = tanh(v7)"];
  N7 -> N8;
  N9 [label="v9 = v2 * v8"];
  N2 -> N9;
  N8 -> N9;
  N10 [label="v10 = v9 + v3"];
  N9 -> N10;
  N3 -> N10;
  N11 [label="v11 = || v10 - v5 ||^2"];
  N10 -> N11;
  N5 -> N11;
}
E = 2.58176
E = 2.14125
E = 1.85408
E = 1.6225
E = 1.35331
E = 1.16468
E = 0.969234
E = 0.745409
E = 0.520823
E = 0.288659
E = 0.108584
E = 0.0313817
E = 0.00756303
E = 0.00146244
E = 0.000335817
E = 9.64881e-05
E = 8.55188e-05
E = 8.56898e-05
E = 0.000102361
E = 0.000117682
E = 0.000138802
E = 0.000161181
E = 0.000189664
E = 0.000220277
E = 0.000259292
E = 0.000300779
E = 0.000354316
E = 0.000410304
E = 0.000483728
E = 0.000558996
```
Mac:
```
[dynet] random seed: 1234
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
digraph G {
  rankdir=LR;
  nodesep=.05;
  N0 [label="v0 = parameters({8,2}) @ 0x7fd37fd002f8"];
  N1 [label="v1 = parameters({8}) @ 0x7fd37fd00418"];
  N2 [label="v2 = parameters({1,8}) @ 0x7fd37fd00558"];
  N3 [label="v3 = parameters({1}) @ 0x7fd37fd006d8"];
  N4 [label="v4 = constant({2})"];
  N5 [label="v5 = scalar_constant(0x7fff5aa79bfc)"];
  N6 [label="v6 = v0 * v4"];
  N0 -> N6;
  N4 -> N6;
  N7 [label="v7 = v6 + v1"];
  N6 -> N7;
  N1 -> N7;
  N8 [label="v8 = tanh(v7)"];
  N7 -> N8;
  N9 [label="v9 = v2 * v8"];
  N2 -> N9;
  N8 -> N9;
  N10 [label="v10 = v9 + v3"];
  N9 -> N10;
  N3 -> N10;
  N11 [label="v11 = || v10 - v5 ||^2"];
  N10 -> N11;
  N5 -> N11;
}
E = 2.58176
E = 2.14125
E = 1.85408
E = 1.6225
E = 1.35331
E = 1.16468
E = 0.969234
E = 0.745409
E = 0.520823
E = 0.288659
E = 0.108584
E = 0.0313816
E = 0.007563
E = 0.00146245
E = 0.000335816
E = 9.64942e-05
E = 8.55305e-05
E = 8.57045e-05
E = 0.000102379
E = 0.000117701
E = 0.000138823
E = 0.000161211
E = 0.000189702
E = 0.000220324
E = 0.000259353
E = 0.00030085
E = 0.0003544
E = 0.000410395
E = 0.000483827
E = 0.000559092
```

**Comment by kwalcock** [comment]
I didn't set any compiler switches myself.  If the compilers are reordering multiplications, the rounding might come out differently.  I would hope that there would be a way to prevent that from happening, if it is at all.

**Comment by kwalcock** [comment]
Now I notice `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DEIGEN_FAST_MATH")` and `-Ofast` which look like they may affect order of operations.

**Comment by kwalcock** [comment]
Eigen itself has at least one /fp:fast.

**Comment by kwalcock** [comment]
After I replace -Ofast with -O3 in CMakeLists.txt, the Linux and Mac results match.

**Comment by kwalcock** [comment]
That Windows /fp:fast switch in Eigen is in a testing and/or benchmarking part of the code that shouldn't affect the main library.

**Comment by neubig** [comment]
Thanks, that's good to know.

**Comment by kwalcock** [comment]
I'm running performance tests to measure the effect on speed with the new settings.  If the effect is minimal, others should probably make the change so that their results are repeatable.

**Comment by kwalcock** [comment]
The effect was minimal.  However, the numbers generated on different platforms for more complicated models still differ.  The change only helped with the relatively simple Xor example.
