### ISSUE TITLE
Could not download Eigen from 'https://bitbucket.org/eigen/eigen/get/b2e267dc99d4.zip'

### ISSUE THREAD

**Issue by KrisWentaoWong** [clab/dynet#1610]
I tried to install dynet for python 2.7 with "pip install git+https://github.com/clab/dynet#egg=dynet" command, and I got "Could not download Eigen from 'https://bitbucket.org/eigen/eigen/get/b2e267dc99d4.zip'" error.

While I also tried to install dynet by anaconda,got the same error.

However,I can successfully download the zip file manually.Does anyone know why?Thanks in advance.

**Comment by hshahdoost** [comment]
Any updates on this issue? Maybe any other way to temporarily solve the problem?

**Comment by G-Thor** [comment]
I have the same issue

**Comment by danielhers** [comment]
Fixed by 9fed65044aff859927c70171423da42a531b5483
