### ISSUE TITLE
ubantu20 make error(eigen)

### ISSUE THREAD

**Issue by hanhao20190402** [clab/dynet#1617]
i did exacitly the same steps i've been told in the 'readme.md' and here is the issue,i tried to find solutions on google but there's none. it seems like something when wrong when it try to convert the matrix. any suggestion to fix it? thanks  
/home/han/dynet/dynet/nodes-concat.cc:147:1:   required from here
/home/han/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorMorphing.h:696:13: error: invalid conversion from ‘Eigen::internal::traits<Eigen::TensorMap<Eigen::Tensor<float, 2> > >::MakePointer<const float>::Type’ {aka ‘const float*’} to ‘Eigen::TensorEvaluator<const Eigen::TensorSlicingOp<const Eigen::DSizes<long int, 2>, const Eigen::DSizes<long int, 2>, const Eigen::TensorMap<Eigen::Tensor<float, 2> > >, Eigen::DefaultDevice>::Scalar*’ {aka ‘float*’} [-fpermissive]
  696 |     Scalar* result = m_impl.data();
      |             ^~~~~~
      |             |
      |             Eigen::internal::traits<Eigen::TensorMap<Eigen::Tensor<float, 2> > >::MakePointer<const float>::Type {aka const float*}
In file included from /home/han/eigen/unsupported/Eigen/CXX11/Tensor:119,
                 from /home/han/dynet/dynet/tensor-eigen.h:13,
                 from /home/han/dynet/dynet/nodes-concat.cc:1:

**Comment by danielhers** [comment]
Should be fixed by 9fed65044aff859927c70171423da42a531b5483
