### ISSUE TITLE
Does DyNet plan to provide Python 3.8+ wheels in PyPI?

### ISSUE THREAD

**Issue by taishi-i** [clab/dynet#1618]
Hello, I am a user of DyNet to develop a Japanese tokenizer [nagisa](https://github.com/taishi-i/nagisa). Thank you for providing us with DyNet.

When I tried to install DyNet in Python 3.8, it failed to install because there is no wheel. I want to provide nagisa for Python 3.8 users, but I can't do this without DyNet providings Python 3.8 wheels. Do you plan to provide Python 3.8+ wheels in [PyPI](https://pypi.org/project/dyNET/#files)?

Thank you and best regards.

**Comment by danielhers** [comment]
Hi @neubig, I added support for building Python 3.8 wheels, but they will only be deployed the next time a tag is created.
Is it time to tag 2.2? Or maybe [2.1.1](https://github.com/clab/dynet/projects)?

**Comment by danielhers** [comment]
There are now wheels for some archs but not x86_64 (https://pypi.org/project/dyNET/2.1.1/#files); see #1620.

**Comment by danielhers** [comment]
Fixed.

**Comment by taishi-i** [comment]
Hi @danielhers, thank you for your support!

**Comment by amirrezasoltan** [comment]
@danielhers , Could you please add a support wheel for python 3.9, 3.10, and other versions? Thanks

**Comment by danielhers** [comment]
Added in c418b09d. They should be deployed on the next tag. @neubig?

**Comment by danielhers** [comment]
OK, it's not that simple because travis.org builds stopped a year ago. Fixing this will require migrating to travis.com or to GitHub Actions. On the same opportunity one might also fix #1651.
