### ISSUE TITLE
Building wheels for x86_64 on Linux doesn't work

### ISSUE THREAD

**Issue by danielhers** [clab/dynet#1620]
See https://travis-ci.org/github/clab/dynet/jobs/737387161#L3318: might be because of bebraw/pypandoc#200.

**Comment by neubig** [comment]
I'll try to take a look at this, but it may take a little while. If you could figure it out @danielhers I'd also welcome a PR

**Comment by danielhers** [comment]
I think I fixed it; testing now.

**Comment by danielhers** [comment]
Fixed by 7be57e6f720599ecfc06b6cdf2e41840fbebb584 - we don't need pandoc because PyPI supports Markdown.
