### ISSUE TITLE
Efficiency of Python API on GPU?

### ISSUE THREAD

**Issue by honnibal** [clab/dynet#164]
Hi,

I've been playing with the Python BiLSTM tagger example. I've refactored it a little and changed it to minibatch the training steps. The output of this looks reasonable, but I'm seeing poor performance on GPU (about 2x slower than CPU. Dynet seems to be picking up the GPU correctly:

```
[dynet] initializing CUDA
Request for 1 GPU ...
[dynet] Device Number: 0
[dynet]   Device name: Tesla M60
[dynet]   Memory Clock Rate (KHz): 2505000
[dynet]   Memory Bus Width (bits): 256
[dynet]   Peak Memory Bandwidth (GB/s): 160.32
[dynet]   Memory Free (GB): 7.90462/7.98301
```

Looking at the way the Python API works, it seems like the data will be copied to and from the device on each word. Could this be why the GPU performance suffers? Should I drop down to C++ or Cython to do GPU training?

You can find the code here: https://github.com/explosion/spaCy/blob/master/examples/spacy_dynet_lstm.py

Ignore the filename for now — it doesn't use spaCy just now (I plan to switch that once I've got it working reasonably well)

**Comment by yoavg** [comment]
Where do you think the copying to device happens?

If you do happen to provide a minimal example in which C++/GPU is substantially faster than python/GPU, I could try and take it from there.

**Comment by honnibal** [comment]
Apologies — I see my assumption didn't make sense. I should've thought this out more carefully.

The behaviour I'm currently seeing is:

    $ time DYNET_GPU=0 python examples/spacy_dynet_lstm.py ~/data/ud-treebanks-v1.3/UD_English/en-ud-train.conllu ~/data/ud-treebanks-v1.3/UD_English/en-ud-dev.conllu models/
    real	0m16.491s
    user	0m16.412s
    sys	0m1.644s

    $ time DYNET_GPU=0 python examples/spacy_dynet_lstm.py ~/data/ud-treebanks-v1.3/UD_English/en-ud-train.conllu ~/data/ud-treebanks-v1.3/UD_English/en-ud-dev.conllu models/
    real	1m24.749s
    user	1m21.848s
    sys	0m4.708s

I'll try minibatching the forward pass as well.

**Comment by yoavg** [comment]
What's the difference between the first and second commands?

**Comment by honnibal** [comment]
Pasted wrong...The second command should have `DYNET_GPU=1`. Fixed.

**Comment by honnibal** [comment]
I think the forward pass should be minibatched now, but the performance is the same.

**Comment by yoavg** [comment]
I have very little knowledge of the GPU implementation (that was really @neubig 's work), but pretty sure that if we have unneeded copies they are not on the python bindings side . I did notice many times that small matrices are noticeably slower on the GPU than the CPU.
(did batching improve your CPU speed somewhat, btw?)

**Comment by honnibal** [comment]
Hmm, okay. I'll try playing with the dimensions.

A theory: this example has 20k embeddings. Maybe the lookup parameters dominate the run-time for this code, and the GPU is not better than the CPU at this. I'll play around with this and see.

**Comment by neubig** [comment]
Your net size looks pretty small, so it may just be the case that you won't be getting much benefit on GPU, because the overhead of launching operations is relatively high. If you're curious about where the GPU is spending it's time, you can try to run the nvprof tool, and paste a log here.

**Comment by honnibal** [comment]
GPU outpaces CPU at 300 hidden, 300 word vector dimension with this model. Closing this.

I'll make a PR when I finish the example, in case it's of interest. I think it'll be nice to have a Python example with minibatching.

**Comment by neubig** [comment]
Yes, I think a Python mini-batching example would be good!

**Comment by honnibal** [comment]
Btw, do you guys regularly use minibatching in your experiments? I was checking the repos from your recent parsers, and I couldn't find minibatching anywhere!

**Comment by neubig** [comment]
Minibatching is used extensively in my machine translation toolkit: https://github.com/neubig/lamtram
Parsing is not as easy to minibatch because the structure of the network can change between every training example (although it is possible with some tricks).
