### ISSUE TITLE
error: Could not download Eigen from 'https://bitbucket.org/eigen/eigen/get/2355b229ea4c.zip'

### ISSUE THREAD

**Issue by davidjlemay** [clab/dynet#1643]
Hi, I'm trying to install version 2.0.3 but pip throws an error because it can't download Eigen from bitbucket. Indeed, the link appears broken. Is there a workaround for the missing Eigen package? Thanks

**Comment by tod97** [comment]
Hi, I found a workaround for this problem.
I've followed the manual installation but cloning from this [repo] (https://gitlab.com/libeigen/eigen)
It is important to avoid the latest tags and use one of the old ones (I've used 3.3.7 and it worked for me)

**Comment by davidjlemay** [comment]
Thanks @tod97 , I’ll try that. Cheers :smile:
