### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by silvianacmp** [clab/dynet#165]
Hi there,

I am trying to build DyNet and can't succeed. (gcc version: 5.4.0, Ubuntu version: 16.04)
When I run "cmake .. -DEIGEN3_INCLUDE_DIR=eigen" I get the following log:

Determining if the pthread_create exist failed with the following output:
Change Dir: /home/silvianacmp/dynet/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_81cff/fast"
/usr/bin/make -f CMakeFiles/cmTC_81cff.dir/build.make CMakeFiles/cmTC_81cff.dir/build
make[1]: Entering directory '/home/silvianacmp/dynet/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_81cff.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_81cff.dir/CheckSymbolExists.c.o   -c /home/silvianacmp/dynet/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_81cff
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_81cff.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_81cff.dir/CheckSymbolExists.c.o  -o cmTC_81cff -rdynamic 
CMakeFiles/cmTC_81cff.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_81cff.dir/build.make:97: recipe for target 'cmTC_81cff' failed
make[1]: *** [cmTC_81cff] Error 1
make[1]: Leaving directory '/home/silvianacmp/dynet/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_81cff/fast' failed
make: *** [cmTC_81cff/fast] Error 2

File /home/silvianacmp/dynet/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/silvianacmp/dynet/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_07dfb/fast"
/usr/bin/make -f CMakeFiles/cmTC_07dfb.dir/build.make CMakeFiles/cmTC_07dfb.dir/build
make[1]: Entering directory '/home/silvianacmp/dynet/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_07dfb.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_07dfb.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_07dfb
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_07dfb.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_07dfb.dir/CheckFunctionExists.c.o  -o cmTC_07dfb -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_07dfb.dir/build.make:97: recipe for target 'cmTC_07dfb' failed
make[1]: *** [cmTC_07dfb] Error 1
make[1]: Leaving directory '/home/silvianacmp/dynet/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_07dfb/fast' failed
make: *** [cmTC_07dfb/fast] Error 2

Any idea what might cause it? Thanks!

**Comment by neubig** [comment]
Sorry, I don't know why you'd be missing the pthread library on Ubuntu. I'm pretty sure it comes standard. Tell us if you figure it out though.

**Comment by neubig** [comment]
No word on this, so I'm closing, but feel free to re-open if necessary.

**Comment by silvianacmp** [comment]
The problem was actually giving a relative path to Eigen. It worked with the absolut path to the Eigen folder.

**Comment by callsty** [comment]
neubig you need to reopen, it's a bug. 
Thx silvianacmp.

**Comment by neubig** [comment]
I'm going to close this issue in favor of the more direct one here: https://github.com/clab/dynet/issues/247
(I do agree this is a bug though, and we'll try to fix, or at least document, it)

**Comment by callsty** [comment]
Thank you neubig for your work :)
