### ISSUE TITLE
MKL problem

### ISSUE THREAD

**Issue by ZhangShiyue** [clab/dynet#166]
Hi, 

I meet a problem when using MKL. I have built dynet given DMKL_ROOT. I hope it could use multi cpu cores to speed up, but it seems that only one core is using, and setting MKL_NUM_THREADS environment variable is no use either. 

Here is the COMMAND I ran:
cmake .. -DMKL_ROOT=/nfs/disk/perm/tools/intel/parallel_studio_xe_2013/composer_xe_2013_sp1.0.080/mkl/
make -j 4
./examples/encdec --dynet-seed 1 --dynet-mem 1000 ../examples/example-data/train-hsm.txt ../examples/example-data/dev-hsm.txt 
[dynet] random seed: 1
[dynet] allocating memory: 1000MB
[dynet] memory allocation done.
Reading training data from ../examples/example-data/train-hsm.txt...
1000 lines, 10295 tokens, 1251 types
Reading dev data from ../examples/example-data/dev-hsm.txt...
10 lines, 110 tokens
Parameters will be written to: bilm_3_500_500-pid2828.params
**SHUFFLE
[epoch=0 eta=0.1 clips=46 updates=50]  E = 6.01214 ppl=408.355 [completed in 12055.4 ms]
[epoch=0 eta=0.1 clips=50 updates=50]  E = 5.34355 ppl=209.253 [completed in 13160.8 ms]
[epoch=0 eta=0.1 clips=50 updates=50]  E = 5.38533 ppl=218.181 [completed in 12174.3 ms]
......

Here is the TOP output：
PID USER          PR  NI    VIRT    RES    SHR S    %CPU %MEM TIME+ COMMAND
2828 zhangsy   20   0  1139096 0.987g   8520 R **100.0**  3.2   0:31.35 encdec 

So, how can I use multi cores to run the code?
Thanks!!

**Comment by neubig** [comment]
I've heard previously that DyNet using MKL works on multiple threads fine. I'm not sure why it's not working here?

**Comment by ZhangShiyue** [comment]
I have solved that. It's ok after I "export MKL_DYNAMIC=FALSE".
