### ISSUE TITLE
Batch manipulation operations

### ISSUE THREAD

**Issue by neubig** [clab/dynet#170]
It would be nice to have operations that allow you to do things like
* concat_batch: concatenate multiple expressions into a single batched expression
* pick_batch_elements: pick only a subset of the elements from a batched expression

**Comment by yoavg** [comment]
+1, but I'd also add:

- concatenate_batch should also work for concatenating batched expressions
into larger batched expression
- special expression for picking the first k items of a batch: this common
use case can have an efficient impl.

**Comment by Oneplus** [comment]
Is anyone working on this? Or has it already been solved?

**Comment by neubig** [comment]
I've heard that someone is working on this, but not sure about the progress.

**Comment by Oneplus** [comment]
Thanks!

**Comment by neubig** [comment]
The `pick_batch` part has been resolved by https://github.com/clab/dynet/pull/369 (thanks @Oneplus !) We still need a `concat_batch` operation before closing this issue.

**Comment by redpony** [comment]
One proposal for this would be to use a generalised concatenate operation
(given a list of vectors, make a matrix, given a list of matrices, make a
tensor, etc) and then provide a "batchify" operation that would strip off
one or more leading indices and turn them into a batch. (I had need of this
recently...)

**Comment by jcyk** [comment]
Hi all, but I am confused by the name of `pick_batch`. 
In fact, there is a `pick_batch` in Python API (and it is not #369), which I think that the batch dim of its output equals to its input.
We need to differentiate these two methods.
1. pick different samples from a batch.
2. pick the same part of all samples in a batch.

**Comment by jcyk** [comment]
@neubig  In addition to the above, I also find `sum_batches` confusing, `sum_batch_elems` may be better.
Actually, I think we are processing data batch by batch. There is never ***batches*** in our computational graph.
I suggest names like `pick_batch_elems`, `concat_batch_elems` to distinguish from `pick_batch`, `pickneglogsoftmax_batch`, `lookup_batch`, etc.

The point is to differentiate operations can or cannot change batch dimension.

**Comment by neubig** [comment]
@jcyk I totally agree that we should fix the naming here, and I think your proposal is a good one. I'd welcome a pull request. One thing is that we should probably make `sum_batches` print a message saying that it is deprecated, as a lot of code is probably using it.

**Comment by neubig** [comment]
I'm going to close this because we finished the major parts. @redpony @yoavg if you still think that the "pick first batches" and "batchify" operations are useful (I think they might be, particularly batchify), then I can open another issue.

**Comment by yoavg** [comment]
I think "batchify"(list of exps to batch) and "unbatchify" (batch to list of exps) operations are needed. Not sure what "pick first batches" is.

**Comment by jcyk** [comment]
@yoavg 
Just try to clarify what haven't be implemented.  
`pick_batch_elems(xs)` now concatenates list of expressions `xs` along the batch dimension. 
The only restriction is that the dims of original expressions must be same except for the batch dimension.

So, I think "list of exps to batch" should already be addressed if not consider allowing broadcasting.

Only to split expression along the batch dimension, `unbatchify(x)` can be something like `pick_batch_elems(x, range(x.bd))`. Further enhancement may allow splitting along arbitrary dimension.

**Comment by neubig** [comment]
@yoavg Here's how to do what you want with the current framework:

    exp = concat_batch_elems(list_of_expressions)
    list_of_expressions = [pick_batch_elem(exp, i) for i in range(exp.d.batch_elems())]

Chris's "batchify" is basically "reshape" where you can specify one dimension as the batch dimension. Your "select first batches" was mentioned at the beginning of this thread.

**Comment by yoavg** [comment]
Ah, cool, I didn't realize that. Thanks!

1) if "batchify" is actually reshape, then we support this already, right? Just need to write a very thin wrapper?

2) The name "concat_batch_elems" is kind of confusing, I think. I'd expect `concat_to_batch` or `concat_elems_to_batch`, no? (I can live with this name, but if its still very fresh, maybe would be a good time to change?)

**Comment by jcyk** [comment]
For the name, note the expression to concatenated can already be a batched expression.

**Comment by neubig** [comment]
Yes, I think concat_to_batch would be a good candidate. Maybe we can change
it to this.

**Comment by jcyk** [comment]
@neubig @yoavg  I can work on that if you all agree. By the way, like I mentioned before, do you think it would be good to change name `sum_batches` to `sum_batch_elems`? but with the old name being preserved with a "deprecated" warning?

**Comment by neubig** [comment]
@jcyk Yes, I think `concat_to_batch` and `sum_batch_elems` are good. Thanks!
