### ISSUE TITLE
Masking for minibatches with RNN

### ISSUE THREAD

**Issue by vered1986** [clab/dynet#171]
I'm trying to train an LSTM with minibatches. I've been using the [tutorial example](https://github.com/clab/dynet_tutorial_examples/blob/master/tutorial_rnnlm_minibatch.py) which is very helpful. I have a question about the masking, which I think should be different in my use case. In the tutorial, the loss is computed at each timestamp (when predicting the next word), and the loss is masked. In my use case, I use only the last LSTM state, feed it to an MLP and compute the loss once. 

I had another idea: for each input I feed to the LSTM, if some of the instances are shorter than the current timestamp (and have zeros in the current mask, accordingly), it just pushes forward their previous states. Something like the following:

```python
mask_matrix = np.tile(mask, (1, max_length))
curr_state = mask_matrix * new_state + (1 - mask_matrix) * curr_state
```
This is just to exemplify, it of course doesn't work because it tries to multiply a matrix with a state. Is there something similar or a possible workaround? Does this make sense at all to do it like that?

Thanks in advance!

**Comment by zhang-wen** [comment]
i also use masking in my system, i think following code will be helpful for you.

```
trg_mask_expr = inputVector(trg_mask)
curr_state = new_state * trg_mask_expr + curr_state * (1. - trg_mask_expr)
```

**Comment by vered1986** [comment]
Thanks @zhang-wen! It seems to be exactly what I need, but I get a NotImplementedError:
```File "/dynet.pyx", line 669, in _dynet.Expression.__mul__ (dynet.cpp:19271)```
I think it is because ```curr_state``` and ```new_state``` are state objects that cannot be multiplied by an expression. Can you please share a minimal working example / the code that created ```curr_state``` and ```new_state```? Thanks very much!

**Comment by zhang-wen** [comment]
oh, i think you can not directly use state object to multiple, instead of that, you should call state.h() of state.s() to get the expression first, then multiple the mask expression.

actually i do not use the LSTMBuilder, i implement a GRU unit myself, like this:

```
h_t = cwise_multiply((1 - z), s_tm1) + cwise_multiply(z, _h_t)

if trg_mask_expr is not None:
       h_t = h_t * trg_mask_expr + s_tm1 * (1. - trg_mask_expr)
```

**Comment by vered1986** [comment]
I see, thank you!

**Comment by vered1986** [comment]
I think I've found a way to do it externally without changing the LSTM code. In case anyone else needs it, it seems to work (not sure how efficient it is, though).

```python
curr_state = init_state
output = None

for wid, mask in zip(word_ids, masks):
	new_state = curr_state.add_input(dy.lookup_batch(word_lookup, wid))
	new_output = dy.reshape(new_state.output(), (output_dim, batch_size))

	mask_matrix = np.reshape(np.tile(mask, (1, output_dim)), batch_size * output_dim)

	if output != None:
		output = dy.cwise_multiply(new_output, dy.inputMatrix(mask_matrix, (output_dim, batch_size))) + \
				 dy.cwise_multiply(output, dy.inputMatrix(1. - mask_matrix, (output_dim, batch_size)))
	else:
		output = new_output

output = dy.reshape(output, (output_dim, 1), batch_size)
```
It's supposed to return the last actual output for each training instance in the batch.
