### ISSUE TITLE
Error when using composites of parameter and batch

### ISSUE THREAD

**Issue by odashi** [clab/dynet#172]
I met an error when trying to use a concatenated value consisting of a parameter and a batch input. Following code reproduces the error:
```c++
Model m;
LookupParameter lp(m.add_lookup_parameters(10, {20}));
Parameter pp(m.add_parameters({30}));
ComputationGraph cg;
auto i1 = lookup(cg, lp, {1, 2, 3});
auto i2 = parameter(cg, pp);
auto i3 = concatenate({i1, i2});
auto i4 = transpose(i3) * i3;
auto i5 = sum_batches(i4);
cg.forward(i5);
cg.backward(i5);
```
I guess this code should work, but it dies due to an Eigen assertion error when the program reached at `cg.backward()`. If I swapped the 6th line for `i2 = input(cg, {30}, vector<float>(30));` then it looks to be working fine.

**Comment by neubig** [comment]
Fixed by this commit: https://github.com/clab/dynet/commit/5ce7e53edb4a9edc7057e29ce2c6523c441b6f49
