### ISSUE TITLE
Python Dynet module compilation failure

### ISSUE THREAD

**Issue by srajana** [clab/dynet#173]
Hey,

I have been trying to run this code that used pycnn and when I faced a lot of issues, I decided to work with DyNet instead and change the code to use DyNet wherever it had pycnn previously. I am following the installation instructions on http://dynet.readthedocs.io/en/latest/python.html. My cmake command seems to have had no failures and found all the required files but make fails with an error similar to the one I had seen with pycnn's make command. I don't really know cython so I am not sure what is wrong. Output shown below. I am sort of on a time crunch so any help is greatly appreciated.

cythoning dynet.pyx to dynet.cpp
[ 83%] Linking CXX executable embed-cl
[ 83%] Built target embed-cl

Error compiling Cython file:
------------------------------------------------------------
...
    cdef Expression _expr
    def __cinit__(self):
        #self.thisptr = p
        self._version = -1
        pass
    @staticmethod
   ^
------------------------------------------------------------

dynet.pyx:85:4: Cdef functions/classes cannot take arbitrary decorators.
building '_dynet' extension
creating build
creating build/temp.linux-x86_64-2.7
gcc -pthread -fno-strict-aliasing -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DOPENSSL_LOAD_CONF -fPIC -I/home1/s/srajana/RA-Fall16/HypeNET-master/train/dynet-base/dynet -I/mnt/castor/seas_home/s/srajana/RA-Fall16/HypeNET-master/train/dynet-base/eigen -I/usr/include -I/usr/include/python2.7 -c dynet.cpp -o build/temp.linux-x86_64-2.7/dynet.o -std=c++11
dynet.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
error: command 'gcc' failed with exit status 1
python/CMakeFiles/target.dir/build.make:64: recipe for target 'python/timestamp' failed
make[2]: *** [python/timestamp] Error 1
CMakeFiles/Makefile2:1173: recipe for target 'python/CMakeFiles/target.dir/all' failed
make[1]: *** [python/CMakeFiles/target.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 84%] Linking CXX executable rnnlm
[ 85%] Linking CXX executable tok-embed
[ 87%] Linking CXX executable poisson-regression
[ 87%] Built target rnnlm
[ 87%] Built target tok-embed
[ 88%] Linking CXX executable rnnlm-cfsm
[ 88%] Built target poisson-regression
[ 89%] Linking CXX executable tag-bilstm
[ 89%] Built target rnnlm-cfsm
[ 90%] Linking CXX executable rnnlm-aevb
[ 91%] Linking CXX executable rnnlm-batch
[ 91%] Built target tag-bilstm
[ 91%] Built target rnnlm-aevb
[ 91%] Built target rnnlm-batch
[ 92%] Linking CXX executable textcat
[ 92%] Built target textcat
[ 94%] Linking CXX executable encdec
[ 95%] Linking CXX executable rnnlm-mp
[ 95%] Built target encdec
[ 95%] Built target rnnlm-mp
[ 96%] Linking CXX executable xor-mp
[ 96%] Built target xor-mp
[ 97%] Linking CXX executable test-dynet
[ 97%] Built target test-dynet
[ 98%] Linking CXX executable lm
[ 98%] Built target lm
[100%] Linking CXX executable segrnn-sup
[100%] Built target segrnn-sup
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by danielhers** [comment]
I think you need to upgrade your Cython:

    pip install --upgrade cython

**Comment by srajana** [comment]
Thank you, that fixed the issue! and now 'make' succeeds. But when I try to run the examples, I get the following error:

Snehas-MacBook-Pro:python sneharajana$ cd $PATH_TO_DYNET
Snehas-MacBook-Pro:dynet sneharajana$ cd pyexamples
Snehas-MacBook-Pro:pyexamples sneharajana$ python xor.py
Traceback (most recent call last):
  File "xor.py", line 1, in <module>
    from dynet import *
  File "build/bdist.macosx-10.11-intel/egg/dynet.py", line 17, in <module>
  File "build/bdist.macosx-10.11-intel/egg/_dynet.py", line 7, in <module>
  File "build/bdist.macosx-10.11-intel/egg/_dynet.py", line 6, in __bootstrap__
ImportError: dlopen(/Users/sneharajana/.python-eggs/dyNET-0.0.0-py2.7-macosx-10.11-intel.egg-tmp/_dynet.so, 2): Library not loaded: @rpath/libdynet.dylib
  Referenced from: /Users/sneharajana/.python-eggs/dyNET-0.0.0-py2.7-macosx-10.11-intel.egg-tmp/_dynet.so
  Reason: image not found

**Comment by pcyin** [comment]
refer to #146

**Comment by neubig** [comment]
This was probably fixed by this commit: https://github.com/clab/dynet/commit/aa03883a18d80984c02c9469058275a66e865839

Could you try it out and close the issue if so?
