### ISSUE TITLE
DyNet Compilation Error

### ISSUE THREAD

**Issue by elikip** [clab/dynet#174]
Hi,

I am trying to install dynet on my laptop and get the following error while running 'make':

> [ 32%] Building CXX object dynet/CMakeFiles/dynet.dir/saxe-init.cc.o
> In file included from /home/elki/dynet-base/eigen/Eigen/Core:409:0,
>                  from /home/elki/dynet-base/eigen/Eigen/Dense:1,
>                  from /home/elki/dynet-base/eigen/Eigen/Eigen:1,
>                  from /home/elki/dynet-base/dynet/dynet/tensor.h:25,
>                  from /home/elki/dynet-base/dynet/dynet/saxe-init.cc:2:
> /home/elki/dynet-base/eigen/Eigen/src/Core/functors/AssignmentFunctors.h: In instantiation of ‘struct Eigen::internal::sub_assign_op<float, void>’:
> /home/elki/dynet-base/eigen/Eigen/src/Core/AssignEvaluator.h:814:49:   required from ‘void Eigen::internal::call_assignment_no_alias(Dst&, const Src&, const Func&) [with Dst = Eigen::Matrix<float, -1, -1>; Src = Eigen::PermutationMatrix<-1, -1, int>; Func = Eigen::internal::assign_op<float, void>]’
> /home/elki/dynet-base/eigen/Eigen/src/Core/AssignEvaluator.h:782:27:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&, const Func&, typename Eigen::internal::enable_if<(! Eigen::internal::evaluator_assume_aliasing<Src>::value), void*>::type) [with Dst = Eigen::Matrix<float, -1, -1>; Src = Eigen::PermutationMatrix<-1, -1, int>; Func = Eigen::internal::assign_op<float, void>; typename Eigen::internal::enable_if<(! Eigen::internal::evaluator_assume_aliasing<Src>::value), void*>::type = void*]’
> /home/elki/dynet-base/eigen/Eigen/src/Core/AssignEvaluator.h:760:18:   required from ‘void Eigen::internal::call_assignment(Dst&, const Src&) [with Dst = Eigen::Matrix<float, -1, -1>; Src = Eigen::PermutationMatrix<-1, -1, int>]’
> /home/elki/dynet-base/eigen/Eigen/src/Core/Assign.h:75:28:   required from ‘Derived& Eigen::MatrixBase<Derived>::operator=(const Eigen::EigenBase<OtherDerived>&) [with OtherDerived = Eigen::PermutationMatrix<-1, -1, int>; Derived = Eigen::Matrix<float, -1, -1>]’
> /home/elki/dynet-base/eigen/Eigen/src/Core/PlainObjectBase.h:564:22:   required from ‘Derived& Eigen::PlainObjectBase<Derived>::operator=(const Eigen::EigenBase<OtherDerived>&) [with OtherDerived = Eigen::PermutationMatrix<-1, -1, int>; Derived = Eigen::Matrix<float, -1, -1>]’
> /home/elki/dynet-base/eigen/Eigen/src/Core/Matrix.h:238:29:   required from ‘Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>& Eigen::Matrix<_Scalar, _Rows, _Cols, _Options, _MaxRows, _MaxCols>::operator=(const Eigen::EigenBase<OtherDerived>&) [with OtherDerived = Eigen::PermutationMatrix<-1, -1, int>; _Scalar = float; int _Rows = -1; int _Cols = -1; int _Options = 0; int _MaxRows = -1; int _MaxCols = -1]’
> /home/elki/dynet-base/eigen/Eigen/src/SVD/JacobiSVD.h:235:40:   required from ‘bool Eigen::internal::qr_preconditioner_impl<MatrixType, 2, 0, true>::run(Eigen::JacobiSVD<MatrixType, 2>&, const MatrixType&) [with MatrixType = Eigen::Matrix<float, -1, -1>]’
> /home/elki/dynet-base/eigen/Eigen/src/SVD/JacobiSVD.h:680:5:   required from ‘Eigen::JacobiSVD<MatrixType, QRPreconditioner>& Eigen::JacobiSVD<MatrixType, QRPreconditioner>::compute(const MatrixType&, unsigned int) [with _MatrixType = Eigen::Matrix<float, -1, -1>; int QRPreconditioner = 2; Eigen::JacobiSVD<MatrixType, QRPreconditioner>::MatrixType = Eigen::Matrix<float, -1, -1>]’
> /home/elki/dynet-base/eigen/Eigen/src/SVD/JacobiSVD.h:544:14:   required from ‘Eigen::JacobiSVD<MatrixType, QRPreconditioner>::JacobiSVD(const MatrixType&, unsigned int) [with _MatrixType = Eigen::Matrix<float, -1, -1>; int QRPreconditioner = 2; Eigen::JacobiSVD<MatrixType, QRPreconditioner>::MatrixType = Eigen::Matrix<float, -1, -1>]’
> /home/elki/dynet-base/dynet/dynet/saxe-init.cc:20:64:   required from here
> /home/elki/dynet-base/eigen/Eigen/src/Core/functors/AssignmentFunctors.h:70:46: error: forming reference to void
>    EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE void assignCoeff(DstScalar& a, const Sr
>                                               ^

Could please advise on how to proceed from this point?

**Comment by danielhers** [comment]
This is because of a bug with Eigen: https://bitbucket.org/eigen/eigen/commits/0e78c04fea691588a7c882826c6523447a3bd66a#comment-4027909
Try checking out an older commit:

    cd eigen
    git reset --hard 25c392f

**Comment by neubig** [comment]
The problem in the Eigen upstream should be fixed now.
https://bitbucket.org/eigen/eigen/commits/eb30762a5baef5f9e67c43aab64129726e079c35
