### ISSUE TITLE
Mini-batched input in python

### ISSUE THREAD

**Issue by pcyin** [clab/dynet#175]
Hi, I am trying to create a mini-batched input of shape (batch_size, data_dim). E.g., the following code has `x` with shape (batch_size=3, data_dim=3). However, this gives me an error `uncaught exception of type std::invalid_argument: Mismatched input dimensions in Sum: [{3,2} {2}]`

```
model = Model()

param_W = model.add_parameters((3, 2))
param_b = model.add_parameters((2))

renew_cg()

x = dn.inputMatrix([1,2,3,4,5,6,7,8,9], (3, 3))
W = dn.parameter(param_W)
b = dn.parameter(param_b)
y_ = x * W + b
```

I checked `dynet_viz.py` and I'm not sure if mini-batched input is supported by the python bining. Any suggestions? Thanks!

**Comment by neubig** [comment]
Actually, while python supports lookup_batch, etc., I don't believe it has something like support for regular batch inputs yet. We're working on an easy-to-use API and it should be ready soon, along with documentation.

**Comment by yoavg** [comment]
until we have the nicer API (and documentation), you can try with this temporary workaround which I believe should work:

```
import dynet as dn
model = dn.Model()

param_W = model.add_parameters((2,3))
param_b = model.add_parameters((2))

dn.renew_cg()

x = dn.reshape(
        dn.inputVector([1,2,3,4,5,6,7,8,9]),
        (3,),batch_size=3)

W = dn.parameter(param_W)
b = dn.parameter(param_b)
y_ = W*x + b

```

**Comment by neubig** [comment]
Fixed by: https://github.com/clab/dynet/pull/340
