### ISSUE TITLE
Time-consuming backward function

### ISSUE THREAD

**Issue by zhang-wen** [clab/dynet#176]
hi, guys, 

i have a following network parameters and structure:

```
    src_emb_lookuptable : (30000, 256)
    trg_emb_lookuptable : (30000, 256)
    GRU_Enc_fwd_1_W_z   : (512, 768)
    GRU_Enc_fwd_1_W_r   : (512, 768)
    GRU_Enc_fwd_1_W_h   : (512, 768)
    GRU_Enc_fwd_1_h0    : 512
    GRU_Enc_bwd_2_W_z   : (512, 768)
    GRU_Enc_bwd_2_W_r   : (512, 768)
    GRU_Enc_bwd_2_W_h   : (512, 768)
    GRU_Enc_bwd_2_h0    : 512
    GRU_Dec_Wz_1        : (512, 768)
    GRU_Dec_Wr_1        : (512, 768)
    GRU_Dec_Wh_1        : (512, 768)
    attention_W_1       : (128, 1024)
    attention_W_2       : (128, 512)
    attention_v         : (1, 128)
    GRU_Dec_Wz_2        : (512, 1536)
    GRU_Dec_Wr_2        : (512, 1536)
    GRU_Dec_Wh_2        : (512, 1536)
    GRU_Dec_h0_2        : 512
    combine_out_W       : (256, 1792)
    combine_out_b       : 256
    logistic_W          : (30000, 256)
    logistic_b          : 30000
```

i train it on GPU and use mini-batch,  batch size is 80, i test the time of `forward` calculation, `backward` calculation and `update` calculation by using following code: 

```
nwk_start = time.time()
batch_error = get_loss(input)
t_nwk = time.time() - nwk_start

fwd_start = time.time()
batch_error_val = batch_error.scalar_value()
t_fwd = time.time() - fwd_start

bwd_start = time.time()
batch_error.backward()
t_bwd = time.time() - bwd_start

upd_start = time.time()
trainer.update()
t_upd = time.time() - upd_start
```

i found a problem, as the increasing of sentence length, it makes sense that all three times increase, the time of `forward` calculation and `update` calculation increase slowly and they are not time-consuming, which is reasonable; however, the time of `backward` increases rapidly and very time-consuming, can anyone give some explanation about the rapidly increasing of `backward`'s time ? i think gradients formula should be constructed in the Computation Graph in advance, right ?

```
batch:1, sent_len:12, nwk:0.038s fwd:0.750s, bwd:2.006s, upd:0.659s
batch:2, sent_len:14, nwk:0.049s fwd:0.997s, bwd:2.910s, upd:0.069s
batch:3, sent_len:15, nwk:0.049s fwd:1.010s, bwd:2.847s, upd:0.072s
batch:4, sent_len:17, nwk:0.068s fwd:1.512s, bwd:4.741s, upd:0.073s
batch:5, sent_len:19, nwk:0.073s fwd:1.620s, bwd:4.970s, upd:0.078s
batch:6, sent_len:21, nwk:0.094s fwd:2.242s, bwd:7.374s, upd:0.091s
batch:7, sent_len:23, nwk:0.098s fwd:2.361s, bwd:7.670s, upd:0.092s
batch:8, sent_len:25, nwk:0.112s fwd:2.767s, bwd:9.116s, upd:0.095s
batch:9, sent_len:27, nwk:0.125s fwd:3.134s, bwd:10.420s, upd:0.101s
batch:10, sent_len:29, nwk:0.127s fwd:3.195s, bwd:10.390s, upd:0.111s
batch:11, sent_len:30, nwk:0.135s fwd:3.447s, bwd:11.359s, upd:0.115s
batch:12, sent_len:31, nwk:0.155s fwd:4.074s, bwd:13.894s, upd:0.118s
batch:13, sent_len:33, nwk:0.155s fwd:4.070s, bwd:13.535s, upd:0.120s
batch:14, sent_len:35, nwk:0.169s fwd:4.502s, bwd:15.099s, upd:0.122s
batch:15, sent_len:37, nwk:0.191s fwd:5.201s, bwd:17.845s, upd:0.129s
batch:16, sent_len:39, nwk:0.203s fwd:5.598s, bwd:19.250s, upd:0.136s
batch:17, sent_len:41, nwk:0.222s fwd:6.212s, bwd:21.516s, upd:0.138s
batch:18, sent_len:43, nwk:0.227s fwd:6.350s, bwd:21.766s, upd:0.147s
batch:19, sent_len:47, nwk:0.249s fwd:7.136s, bwd:24.370s, upd:0.149s
batch:20, sent_len:50, nwk:0.272s fwd:7.886s, bwd:27.018s, upd:0.158s
batch:21, sent_len:12, nwk:0.037s fwd:0.701s, bwd:1.889s, upd:0.059s
batch:22, sent_len:15, nwk:0.051s fwd:1.053s, bwd:2.992s, upd:0.069s
batch:23, sent_len:17, nwk:0.075s fwd:1.701s, bwd:5.562s, upd:0.074s
......
```

**Comment by neubig** [comment]
Thanks for the report! Although it's conceivable that backward could take more time than forward, it does seem a bit strange that it's taking about 4x the time of forward. Do you have some example code/data that we could debug this with?

**Comment by zhang-wen** [comment]
i have code and data, but the network is a little complicated and data is a little large , i can put it on github, you can run it directly, is that easy for you guys to debug ?

**Comment by danielhers** [comment]
I don't know if it's related (perhaps related to #120), but `backward` also consumes a lot of memory: I'm training a BiLSTM model, and using [memory_profiler](https://pypi.python.org/pypi/memory_profiler) I found that `backward` takes an additional 10~20MB in each call. Does that make sense?

**Comment by zhang-wen** [comment]
yes, you are right, backward takes additional memory, but i do not know why. @neubig told me that using "--dynet_mem 2000,2000,1000" is a better choice in #120

**Comment by neubig** [comment]
@zhang-wen if you have the data, code, and command used to run it, this will make it easier to debug. Alternatively (and more likely to get a quick response), if you can run `nvprof` on the program and see if there are any particular CUDA calls that are easting up most of the time, that might help us pinpoint more exactly.

**Comment by zhang-wen** [comment]
@neubig sounds nice, i will put the data , code and run script on github, and let you know, and i will also try to run nvprof, let you know if i have some results.

**Comment by zhang-wen** [comment]
@neubig hi, i just do once update for one batch, and i use `nvprof` to profile the memory usage, following command: 

`nvprof --print-api-trace python main.py --dynet-gpu --dynet_mem 3000,6000,1000 --dynet-gpu-ids 1 -DHAVE_CUDA`

maybe because my network size is kind of large, it output lots of logs, actually i do not understand the meaning of the log, i can show you some of the log, and there are some errors:

```
16.6828s  6.1880us  cudaLaunch (void axpy_kernel_ref<float, int=0>(cublasAxpyParamsRef<float>) [1775387])
16.6828s     157ns  cudaGetLastError
16.6828s     153ns  cudaGetLastError
16.6828s     189ns  cudaConfigureCall
16.6828s     178ns  cudaSetupArgument
16.6828s  6.0900us  cudaLaunch (void axpy_kernel_ref<float, int=0>(cublasAxpyParamsRef<float>) [1775392])
16.6828s     175ns  cudaGetLastError
16.6828s     153ns  cudaGetLastError
16.6828s     188ns  cudaConfigureCall
16.6828s     184ns  cudaSetupArgument
```


```
16.0918s  6.2650us  cudaLaunch (sgemm_sm35_ldg_tn_32x16x64x8x16 [1590573])
16.0918s     174ns  cudaGetLastError
16.0918s     187ns  cudaConfigureCall
16.0918s     175ns  cudaSetupArgument
16.0918s     170ns  cudaSetupArgument
16.0918s     165ns  cudaSetupArgument
16.0918s     158ns  cudaSetupArgument
16.0918s     159ns  cudaSetupArgument
16.0918s     160ns  cudaSetupArgument
16.0918s     162ns  cudaSetupArgument
16.0918s     161ns  cudaSetupArgument
16.0918s     159ns  cudaSetupArgument
16.0918s     168ns  cudaSetupArgument
16.0918s     166ns  cudaSetupArgument
16.0918s     157ns  cudaSetupArgument
16.0918s     157ns  cudaSetupArgument
16.0918s     160ns  cudaSetupArgument
16.0918s  5.9950us  cudaLaunch (sgemm_sm35_ldg_tn_32x16x64x8x16 [1590590])
16.0918s     175ns  cudaGetLastError
16.0918s     189ns  cudaConfigureCall
```

```
18.0805s  6.5260us  cudaMemsetAsync
18.0805s  6.5070us  cudaMemsetAsync
18.0805s  6.4280us  cudaMemsetAsync
18.0805s  6.0690us  cudaMemsetAsync
18.0805s  6.0070us  cudaMemsetAsync
18.0806s  6.0810us  cudaMemsetAsync
18.0806s  6.3070us  cudaMemsetAsync
18.0806s  7.1970us  cudaMemsetAsync
18.0806s  6.3140us  cudaMemsetAsync
18.0806s  6.0470us  cudaMemsetAsync
18.0806s  6.3150us  cudaMemsetAsync
18.1036s  68.884us  cudaFree
```

do this logs show some useful informations , can they help us to pinpoint more exactly ?

**Comment by neubig** [comment]
No, this is not enough. We'd need to see that aggregate statistics of which methods are taking more time.

**Comment by neubig** [comment]
Recently there have been a number of speed improvements to DyNet (particularly on GPU with mini-batches). If slow training is still an issue, I'd suggest trying the newest version, and if you're still having problems there is probably something up with the implementation.
