### ISSUE TITLE
is there max-out API for one dimension ?

### ISSUE THREAD

**Issue by zhang-wen** [clab/dynet#177]
i have following code to get a 3-D matrix with batch size is 4

```
m = Model()
lp = m.add_lookup_parameters((10,6))
batch_emb = lookup_batch(lp, [1,2,3,9])
batch_emb = reshape(batch_emb, (2, batch_emb.npvalue().shape[0] / 2), 4)
```

the shape of batch_emb is (2, 3, 4)

i want to get the result of 
```
n1 = batch_emb.npvalue()
numpy.max(n1, axis=0)
```

it there this API for Expression ?

**Comment by neubig** [comment]
There is the `kmax_pooling` expression, but its axis is not configurable. Being able to configure the axis is something that would be nice to have, so a pull request would be welcome.

**Comment by Peilun-Li** [comment]
It seems `kmax_pooling` doesn't support batching and only handles 2-d tensor. Wouldn't it be more general to add another function `maxout` supporting 3-d tensor and batching like the way `PickElement` does?

**Comment by neubig** [comment]
Resolved by: https://github.com/clab/dynet/pull/449
