### ISSUE TITLE
Mini-batched "sum" operation is not working as expected?

### ISSUE THREAD

**Issue by neubig** [clab/dynet#178]
There have been reports that the mini-batched sum operation is not working properly. This needs to be investigated.

**Comment by pmichel31415** [comment]
Is it a python-only bug? I haven't had any problem in c++

**Comment by neubig** [comment]
To be accurate, this only applies to "sum(a,b,c)" and not "a + b + c". I've only had a report and not had time to investigate it yet. It will affect both c++ and python if it is indeed a bug.

**Comment by neubig** [comment]
Hmm, minimal unit tests were not able to reproduce the problem. Setting to "needs more info" for now.
https://github.com/clab/dynet/commit/cfa20d4cd95fd98a8ff7044cb30c46a3010612cb

**Comment by neubig** [comment]
A new implementation of sum has been created, and it works appropriately on mini-batches, so this is probably not an issue in the most recent code.
