### ISSUE TITLE
non-standard dropout behavior

### ISSUE THREAD

**Issue by yoavg** [clab/dynet#186]
The `dropout` node implementation is non-standard: it drops nodes with prob (1-p) but also multiplies the remaining nodes by 1/(1-p) to compensate. This is indeed very convenient as you don't have to do anything special at test time (other than not applying dropout), but I'd imagine 99% of the users (those who don't wrote the function or looked closely at its code) don't know this, and will apply their own additional scaling at test time, hurting their results. I know I was bitten by this.

The least we could do is add this to the documentation, but I suspect most users will still miss this (as they assume they already know what dropout does and won't read). So I am in favor of changing the dropout node such that the internal-scaling behavior is controlled by a parameter that is *off* by default (i.e., make it opt-in, not opt-out).

Or we could have a VERY visible doc page on "Unorthodox things", and make sure to document it there.

**Comment by neubig** [comment]
I'm actually a pretty big fan of the current implementation, and probably with proper documentation of the dropout expression we can minimize confusion? I'd vote for keeping it as it is. I'm going through and documenting all the expressions, and will get to the dropout-related ones soon.

I also think that the "unorthodox things" documentation is a great idea, including the simplified LSTM implementation, handling of sparse updates/weight decay, and dropout.

**Comment by yoavg** [comment]
We can keep the current behavior, but it must be documented in a VERY visible way, with huge bold red letters in flushy fonts.

(and batching should probably also be part of the unrothodox page)

**Comment by neubig** [comment]
OK, added an unorthodox page here: http://dynet.readthedocs.io/en/latest/unorthodox.html

Dropout documentation is pending.

**Comment by zeeeyang** [comment]
As far as I know,  the current implementation of dropout is so called **inverted dropout**. Some descriptions can be found at [http://cs231n.github.io/neural-networks-2/#reg](http://cs231n.github.io/neural-networks-2/#reg). Hope this information is useful for the documentation of the Dropout Node.

**Comment by neubig** [comment]
OK, this has been documented on the dropout page: http://dynet.readthedocs.io/en/latest/operations.html#_CPPv2N5dynet4expr7dropoutERK10Expression4real
