### ISSUE TITLE
Python attention example is broken?

### ISSUE THREAD

**Issue by neubig** [clab/dynet#189]
The Python attention example (https://github.com/clab/dynet/blob/master/pyexamples/attention.py) is probably broken, as it doesn't look like it is re-inputting the generated output to the decoder LSTM. This is an important part of attentional models, and probably should be fixed.

**Comment by yoavg** [comment]
if I remember correctly this code is by @talbaumel .
Tal, can you fix this?

**Comment by talbaumel** [comment]
It inputs the previous decoder state not the output
Do you want me to replace it?

**Comment by talbaumel** [comment]
Done, added a pull request

Thanks!

**Comment by neubig** [comment]
https://github.com/clab/dynet/pull/190
