### ISSUE TITLE
Better organized examples, and parity between C++ and Python

### ISSUE THREAD

**Issue by neubig** [clab/dynet#191]
At the moment, the examples that are implemented are kind-of random, and there is no parity between the Python and C++ examples. I think we should re-organize the example section to make sure that:

1. The examples cover all the functionality of DyNet and demonstrate interesting things that it can do.
2. All examples are simple and canonical. For example, they don't contain anything that would be unexpected based on the models they are implementing (https://github.com/clab/dynet/issues/141).
3. There is parity between the C++ and python examples, so neither language is left out.
4. There are not examples that are overly complicated and hard to maintain.

**Comment by neubig** [comment]
I have a proposal for fixing this:

1. Restructure the examples so it is `examples/MODEL_NAME/LANGUAGE_NAME` (e.g. `examples/rnnlm/py`)
2. Create a `README.md` in `examples` that briefly describes each example, and explains which language it is available for.
3. Create a `README.md` in each `examples/MODEL_NAME` directory. All `README.md` files should explain how to a) get data with which to test the model, and b) run the example.

In addition, we should be proactive about adding new examples. Having examples is very useful for people just starting out with the toolkit.

**Comment by zhisbug** [comment]
Will start looking at this issue soon.

**Comment by neubig** [comment]
The examples are now better organized by #927, so I'll close this.
