### ISSUE TITLE
Error in gpycnn model parameters load_array

### ISSUE THREAD

**Issue by KiroSummer** [clab/dynet#192]
When I try to use gpu, I get a error "Segmentation fault (core dumped)"
My code is here, very simple:
 ```
#!/usr/bin/python
#coding: utf-8
   
import gpycnn as G
import pycnn as C
import numpy as np
   
model = G.Model()
model.add_parameters('w', (2, 2))
  
w = model['w']
matrix = np.random.uniform(-0.01, 0.01, w.shape())
w.load_array(matrix)
```
My code use the pycnn is ok, but when I convert to gpycnn, it will crash and will catch such problem 
"Segmentation fault (core dumped)"

By the way, the line with __load\_ array__  can cause the error. 
Did I use gpu model parameters with the wrong function?

Could you help me deal with it?
Thank you!

**Comment by neubig** [comment]
Hi @KiroSummer, just one sanity check: does this error still happen when you comment out the `import pycnn as C` line?

**Comment by yoavg** [comment]
Hi, this looks like the previous version of cnn/pycnn, which we know has incomplete GPU support, and is generally not supported.

Could you please try this with the new version (dynet) in this repo?

**Comment by KiroSummer** [comment]
Hi, @neubig , I tried your suggesstion, but it still doesn't work and cause the same error.
And I decide to try with dynet@yoavg. : )

Thank you for your help!

**Comment by KiroSummer** [comment]
Hi, @neubig , I tried your suggesstion, but it still doesn't work and cause the same error.
And I decide to try with dynet. @yoavg  : )

Thank you for your help!
