### ISSUE TITLE
Left multiplication of a matrix by a vector

### ISSUE THREAD

**Issue by mitchellstern** [clab/dynet#196]
DyNet currently supports matrix-vector multiplication, but does not support vector-matrix multiplication.

For example, we can multiply a 2x3 matrix and a length-3 vector to obtain a length-2 vector,
```
>>> import dynet as dy
>>> v = dy.inputVector([0, 0, 0])
>>> w = dy.inputMatrix([0, 0, 0, 0, 0, 0], (2, 3))
>>> result = w * v
>>> result.npvalue()
array([ 0.,  0.])
```
but we cannot multiply a length-2 vector and a 2x3 matrix to obtain a length-3 vector,
```
>>> import dynet as dy
>>> v = dy.inputVector([0, 0])
>>> w = dy.inputMatrix([0, 0, 0, 0, 0, 0], (2, 3))
>>> result = v * w
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: Mismatched input dimensions in MatrixMultiply: [{2} {2,3}]
Abort trap: 6
```

Using `dynet.transpose`, we can write
```
>>> import dynet as dy
>>> v = dy.inputVector([0, 0])
>>> w = dy.inputMatrix([0, 0, 0, 0, 0, 0], (2, 3))
>>> result = dy.transpose(w) * v
>>> result.npvalue()
array([ 0.,  0.,  0.])
```
but `dynet/expr.h` mentions that `transpose` is an O(n) operation, so this seems like it would be an inefficient workaround.

Alternatively, we can also write
```
>>> import dynet as dy
>>> v = dy.inputVector([0, 0])
>>> w = dy.inputMatrix([0, 0, 0, 0, 0, 0], (2, 3))
>>> result = dy.transpose(v) * w
>>> result.npvalue()
array([[ 0.,  0.,  0.]])
```
but this returns a 1x3 matrix instead of a length-3 vector. We could then use `dynet.reshape` to turn this back into a vector, but that requires knowing the length of the vector, which may be inconvenient.

Would it be possible to add support for this? Or does the existing API already support vector-matrix multiplication by other means?

**Comment by neubig** [comment]
At the moment, I believe the most efficient way to do this would be `result = dy.transpose( dy.transpose(v) * w )`. Transposing matrices is expensive, but transposing vectors is cheap.

I think vector-matrix multiply may be something that people might want though, so we could potentially add support for this, either through the standard multiplication operation (which I sort-of hesitate to do, because it might cause people to accidentally make programming errors), or through a specialized function.

**Comment by mitchellstern** [comment]
Thanks for the tip! However, transposing the result back seems to give a 3x1 matrix:
```
>>> import dynet as dy
[dynet] random seed: 2128111805
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
>>> v = dy.inputVector([0, 0])
>>> w = dy.inputMatrix([0, 0, 0, 0, 0, 0], (2, 3))
>>> result = dy.transpose(dy.transpose(v) * w)
>>> result.npvalue()
array([[ 0.],
       [ 0.],
       [ 0.]])
```
Is there any easy (and efficient) way to convert this back into a vector? `dynet/expr.h` mentions that `dynet.reshape` is O(1) in the forward pass but O(n) in the backward pass.

To be more specific about my intended use case, bilinear scoring functions have been applied successfully in machine translation [1] and dependency parsing [2]. If you have a decoder hidden state u and encoder hidden states v_1, ..., v_n, you could imagine computing the attention-weighted context vector by forming the column-concatenation V = [v_1; ...; v_n], computing the attention vector a = softmax(u\*W\*V) = [score_1, ..., score_n], and returning V\*a. Transposing these expressions would avoid the vector-matrix product in computing a, but would introduce one in the final step. It would also require a function for creating a matrix from a list of row vectors, which to my knowledge doesn't yet exist.

If you think there's a better way to go about implementing this in DyNet, I'd be happy to hear your suggestions. Thanks!

1. Minh-Thang Luong, Hieu Pham, Christopher D. Manning. 2015. Effective Approaches to Attention-based Neural Machine Translation. https://arxiv.org/pdf/1508.04025v5.pdf
2. Timothy Dozat, Christopher D. Manning. 2016. Deep Biaffine Attention for Neural Dependency Parsing. https://arxiv.org/pdf/1611.01734v2.pdf

**Comment by yoavg** [comment]
This is not a solution, but for your use case can you do

**Comment by mitchellstern** [comment]
I think your reply may have gotten cut off. Could you repeat your suggested workaround?

**Comment by germinator237** [comment]
Good morning!
I'am new learner in neural machine learning.

I tried to implement a word embedding algorithm to predict word with a giving context but I have this error: Traceback (most recent call last):
  File "word_predict.py", line 61, in <module>
    y = calc_function(x)
  File "word_predict.py", line 49, in calc_function
    h_val = dy.tanh(dy.transpose((w_xh * dy.transpose(x_val) + b_x_h)))
  File "_dynet.pyx", line 1641, in _dynet.Expression.__mul__
  File "_dynet.pyx", line 1363, in _dynet._mul
ValueError: Mismatched input dimensions in MatrixMultiply: [{11,4} {1,11}]


This is my code:
import dynet as dy
import numpy as n
import data_utils

X, en_word2idx, en_idx2word, en_vocab = data_utils.create_dataset(data_utils.read_sentences('data_training.txt'))

num_epochs = 100
WDIM = 4
V = len(en_vocab)

model = dy.Model()
W_x_h = model.add_parameters((V,WDIM))
b_x = model.add_parameters(V)
W_h_y = model.add_parameters((WDIM,V))
b_h_y = model.add_parameters(WDIM)
data = en_vocab
liste = en_vocab
trainer = dy.SimpleSGDTrainer(model)

def one_hot_vec(elt, vec):
    x =[]
    for v in vec:
	if elt == v:
	   x.append(1)
	else:
	   x.append(0)
    print len(x) 
    return x

def train_data(liste):
    couple = []
    for l in liste:
	try:
	  couple.append((l, liste[liste.index(l)+1]))
	except IndexError:
	  break
    return couple


def calc_function(x):
	dy.renew_cg()
	w_xh = dy.parameter(W_x_h)
	print w_xh.value()
	b_x_h = dy.parameter(b_x)
	W_hy = dy.parameter(W_h_y)
	b_y = dy.parameter(b_h_y)
	x_val = dy.inputVector(x)
	print x_val.value()
	h_val = dy.tanh(dy.transpose((w_xh * dy.transpose(x_val) + b_x_h)))
	y_val = W_hy * h_val + b_y
	return dy.softmax(y_val)



# Perform training
for epoch in range(num_epochs):
	epoch_loss = 0
	data = train_data(data)
	for x, ystar in data:
		x = one_hot_vec(x,liste)
		y = calc_function(x)
		loss = -dy.log(y, ystar)
		epoch_loss += loss.value()
		loss.backward()
		trainer.update()
	print("Epoch %d: loss=%f" % (epoch, epoch_loss))
# Print results of prediction
	y = calc_function(x)
	print("%r -> %f" % (x, y.value()))
