### ISSUE TITLE
Test Python bindings on Travis CI

### ISSUE THREAD

**Issue by danielhers** [clab/dynet#198]
As far as I understand, `.travis.yml` currently only compiles the C++ library and runs C++ tests.
It should also install the Python bindings and run Python tests.
Both 2.7 and 3.5 should be [specified](https://docs.travis-ci.com/user/languages/python/#Choosing-Python-versions-to-test-against) in order to test both.

**Comment by neubig** [comment]
Yes, this is a good idea!

**Comment by neubig** [comment]
This is done by e.g.: https://github.com/clab/dynet/commit/4127a363821f52ad095317bb14bd416e0bd93b21
