### ISSUE TITLE
Inconsistent usage of pointers and references

### ISSUE THREAD

**Issue by mitchellstern** [clab/dynet#201]
As it stands, most of the builder classes in `dynet/` use `Model*` in their constructors, whereas most of the builder-like classes in `examples/` use `Model&`. On the other hand, `ComputationGraph`s are largely used as references throughout the code base, whereas there are a small number of pointers (some of which are unused, as in `dynet/treelstm.h`). There's even a mismatch in the current version of `c2w.h`, where (among other issues) a `ComputationGraph*` is being used where a `ComputationGraph&` is expected by `RNNBuilder`.

I'm not sure I can speak for the internal DyNet code, but for all of the builders and example models, is there any compelling reason why we shouldn't be using references to `Model`s and `ComputationGraph`s throughout? If not, I'd be happy to make a pull request to this effect for consistency.

(Possibly related to issue #90.)

**Comment by neubig** [comment]
Thanks for taking a look and offering to help with this! It is indeed related to missing coding guidelines of https://github.com/clab/dynet/issues/90 .

I propose that we use the following as the coding standard for pointer vs. reference in DyNet, and welcome any pull requests to fix things:
http://stackoverflow.com/a/114351

**Comment by pmichel31415** [comment]
@mitchellstern are you currently working on this? I can start working on it later this week so let me know what I can do

**Comment by mitchellstern** [comment]
Thanks for offering to help! I started making some changes to this effect earlier this week -- let me get back to you here in the next day or two with an update and we can see whether it would make sense to parallelize.

**Comment by mitchellstern** [comment]
@pmichel31415: I've made an initial pass at this in #207. I tried to be fairly comprehensive, but please feel free to supplement wherever needed in case I missed something.

**Comment by neubig** [comment]
This has been fixed in: https://github.com/clab/dynet/commit/97867c5e29a0be7bf7a893c9cf78224b89fc9a15

Thanks @mitchellstern !
