### ISSUE TITLE
Unused `edecay` parameter in `AdadeltaTrainer` and `AdamTrainer` constructors

### ISSUE THREAD

**Issue by mitchellstern** [clab/dynet#208]
Currently the `AdadeltaTrainer` and `AdamTrainer` constructors ignore their `real edecay = 0.0` learning rate decay parameters. Is this intentional? If so, the documentation should be updated accordingly, and perhaps these parameters should be removed altogether since the base class constructor has the same default value.

**Comment by neubig** [comment]
Thanks for the report! Fixed here:
https://github.com/clab/dynet/commit/8889f15be064098e3fd535b5ae464c73a8ef45aa
