### ISSUE TITLE
python examples

### ISSUE THREAD

**Issue by yoavg** [clab/dynet#213]
The new org structures of the examples where the C++ and Python versions are mixed is annoying for users who only care about one of the languages. This would have been better if we had python versions of all the examples, but as it stands now a user needs to hunt and peck for the python examples.

Any chance of reverting back the old organization, where the first division was by language and not by example?

**Comment by pmichel31415** [comment]
OK I'll submit a pull request with two separate folders within the example folder, does that seem OK?

**Comment by yoavg** [comment]
yup, that'd be great.
