### ISSUE TITLE
Floating point bug in logistic function

### ISSUE THREAD

**Issue by mitchellstern** [clab/dynet#220]
When the input to the function `logistic(x) = 1 / (1 + exp(-x))` is large and negative (say below -100), `exp(-x)` will overflow and the resulting value should be 0. However, I'm instead getting the following results.

MacBook Pro running OS X El Capitan:
```
>>> dy.logistic(dy.scalarInput(-100)).value()
0.0
>>> dy.logistic(dy.inputVector([-100] + [0] * 6)).npvalue()
array([ 0. ,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5])
>>> dy.logistic(dy.inputVector([-100] + [0] * 7)).npvalue()
array([ 0.00990099,  0.49999997,  0.49999997,  0.49999997,  0.49999997,
        0.49999997,  0.49999997,  0.49999997])
```

EC2 c4.4xlarge instance, default Ubuntu AMI (Ubuntu Server 16.04 LTS (HVM), SSD Volume Type - ami-b7a114d7):
```
>>> dy.logistic(dy.scalarInput(-100)).value()
0.0
>>> dy.logistic(dy.inputVector([-100] + [0] * 6)).npvalue()
array([ 0. ,  0.5,  0.5,  0.5,  0.5,  0.5,  0.5])
>>> dy.logistic(dy.inputVector([-100] + [0] * 7)).npvalue()
array([        nan,  0.49999997,  0.49999997,  0.49999997,  0.49999997,
        0.49999997,  0.49999997,  0.49999997])
```

In particular, I'm getting a `nan` on Linux for vectors of length 8 or greater. Comparable C++ tests give the same results, as do MKL and non-MKL installations of DyNet.

This bug has appeared in an organic setting during several long-running experiments involving LSTMs or other RNNs that use the `logistic` function for gating. The `nan` value immediately propagates to the other parameters through the trainer and causes a hard failure.

Any suggestions or workarounds would be much appreciated!

**Comment by mitchellstern** [comment]
For reference, I've tried the above code on a few other non-EC2 machines running Ubuntu and haven't been able to replicate the bug, but have seen the buggy behavior on every EC2 instance I've tried. Let me know if you need any more details to reproduce the issue.

**Comment by mitchellstern** [comment]
Update: It's possible this is related to newer versions of g++. Correct behavior was observed on Ubuntu machines with g++ 4.8.4, 4.8.5, and 4.9.4; the erroneous behavior was observed on Ubuntu machines with g++ 5.4.0 and 5.4.1.

**Comment by neubig** [comment]
Thanks for the report @mitchellstern ! This sounds like it might be a bug with Eigen. I don't have time to look at this immediately, but if you could look at the underlying code in nodes.cc, cut it out, and create an example that uses only Eigen (no DyNet) and fails similarly, then it could be reported to the Eigen people and fixed. If not, I'll take a look when I have time, probably not for a week or two.

**Comment by yv** [comment]
1) this seems to be a by-product of vectorization, as you can do
```
>>> dy.logistic(dy.inputVector([-100] + [0]*7 + [-100])).npvalue()
array([        nan,  0.49999997,  0.49999997,  0.49999997,  0.49999997,
        0.49999997,  0.49999997,  0.49999997,  0.        ])
```
and the 9th element is not using the vectorized code. Dynet compiles code with "-march=native", which turns on (AVX-something) vectorization in Eigen. A minimal C++ example would be
```
#include <iostream>                                                             
#include <Eigen/Core>                                                           
using namespace Eigen;                                                          
using namespace std;                                                            
Vector4f foo(Vector4f& v)                                                       
{                                                                               
      EIGEN_ASM_COMMENT("begin");                                                 
      Vector4f u = 1.0 / (1.0 + (-v).array().exp());                              
      EIGEN_ASM_COMMENT("end");                                                   
      return u;                                                                   
  }                                                                               
                                                                                  
int main(int argc, char **argv) {                                               
    Vector4f v = {-100, 0, 0, 0};                                               
      cerr << v << endl;                                                          
      Vector4f w = foo(v);                                                        
      cerr << w << endl;                                                          
      exit(0);                                                                    
  }
```
which you can compile with `g++ -I . bla.cc -std=c++11 -march=native -Ofast -o bla` or get the assembly code with `g++ -I . bla.cc -std=c++11 -march=native -Ofast -S` (don't have a mac, so I can't tell what code is generated there).

Tensorflow uses Eigen's internal sigmoid function, which in turn looks exactly like dynet's.

2. A workaround I used in C++ was to use a function like the following (to call before `sgd.update()`):
```
/** returns true if gradients don't show sign of nan-ness
 * otherwise gives some debugging output and returns false
 */
bool check_for_nan(ComputationGraph &hg, Model &model) {
  float result;
  auto p = model.parameters_list()[0];
  p->g_squared_l2norm(&result);
  if (isfinite(result)) {
    return true;
  } else {
    cerr << "Invalid gradient: " << result << endl;
    hg.PrintGraphviz();
    for (auto p: model.parameters_list()) {
      p->clear();
    }
    for (auto p: model.lookup_parameters_list()) {
      p->clear();
    }
    return false;
  }
}
```
(with some code added to PrintGraphviz to output the magnitudes of forward and backward values for each node). This works only if the nan gradient flows to the first parameter, OTOH it can run with negligible overhead. An alternative would be to integrate this with clip_gradients() which normally just aborts with no useful output.

**Comment by neubig** [comment]
Great sleuthing @yv ! Do you have any idea of the speed implications of -ffinite-math-only? If they are negligible then maybe we can pull this as-is. Otherwise, we might only enable it for problematic versions (with a warning at compile time)

**Comment by yv** [comment]
Ok, I've built a sample corpus based on the NLTK MASC corpus (which a liberal license and some English words in it), and used the train_encdec example with the first/second 2500 updates as a measuring yardstick.
```
grep CXX_FLAGS examples/CMakeFiles/train_encdec.dir/flags.make
examples/train_encdec --dynet-seed 42 -t ../examples/utils/masc_train.txt -d ../examples/utils/masc_dev.txt
```
Case 1: -Ofast (all optimizations enabled)
```
CXX_FLAGS =  -DEIGEN_FAST_MATH -fPIC -funroll-loops -Wall -Wno-missing-braces -std=c++11 -Ofast -g -march=native
[epoch=0 eta=0.001 clips=2489 updates=3353]  E = 7.94199 ppl=2812.95 [completed in 33445.1 ms]
[epoch=0 eta=0.001 clips=2742 updates=3353]  E = 7.28905 ppl=1464.17 [completed in 33676.3 ms]
[epoch=0 eta=0.001 clips=2830 updates=3353]  E = 7.27188 ppl=1439.25 [completed in 33398.7 ms]
```

Case 2: (-Ofast with -fno-finite-math-only)
```
CXX_FLAGS =  -DEIGEN_FAST_MATH -fPIC -funroll-loops -Wall -Wno-missing-braces -std=c++11 -fno-finite-math-only -Ofast -g -march=native
[epoch=0 eta=0.001 clips=2489 updates=3353]  E = 7.94199 ppl=2812.95 [completed in 33999.1 ms]
[epoch=0 eta=0.001 clips=2742 updates=3353]  E = 7.28905 ppl=1464.17 [completed in 34151.3 ms]
[epoch=0 eta=0.001 clips=2830 updates=3353]  E = 7.27187 ppl=1439.25 [completed in 34254.6 ms]
```

Case 3: (-O3, no fast-math)
```
CXX_FLAGS =  -DEIGEN_FAST_MATH -fPIC -funroll-loops -Wall -Wno-missing-braces -std=c++11 -O3 -g -march=native
[epoch=0 eta=0.001 clips=2489 updates=3353]  E = 7.94199 ppl=2812.95 [completed in 40865 ms]
[epoch=0 eta=0.001 clips=2742 updates=3353]  E = 7.28905 ppl=1464.17 [completed in 40900.2 ms]
[epoch=0 eta=0.001 clips=2830 updates=3353]  E = 7.27187 ppl=1439.25 [completed in 40908.7 ms]
```
So there is a ~1.5% difference (with no guarantees of exactness), which is small in comparison to the difference between -O3 and -Ofast, but maybe enough to have a look at the differences. Comparing the assembly files is not particular telling, though - there are differences in lots and lots of places.

My guess is that most people are willing to sacrifice 1.5% performance (i.e., for a week's worth of runtime, about an hour and a half extra) if it lets them sleep more soundly.

**Comment by neubig** [comment]
@yv Thanks for the tests! I agree the +1.5% is a reasonable tradeoff, and finite-math-only probably isn't a good idea in the first place, as the functions we use should probably be able to handle +inf/-inf. I'll go ahead and incorporate the pull request.

**Comment by mitchellstern** [comment]
Thanks a bunch for helping resolve this, @yv!
