### ISSUE TITLE
Initializing lookup matrix

### ISSUE THREAD

**Issue by chaitanyamalaviya** [clab/dynet#224]
Hi everyone,

Is there a way to initialize the dynet lookup matrix with a numpy matrix?
I know that the lookup parameter object does not support item assignment, but I was hoping there would be a workaround to this.
Would appreciate any help!

**Comment by mitchellstern** [comment]
Currently DyNet supports two methods of initializing `LookupParameters` from a `numpy` array:
```
>>> import numpy as np
>>> import dynet as dy

# Create a model
>>> model = dy.Model()

# Generate some sample embeddings
>>> array = np.arange(15.0).reshape((3, 5))
>>> array
array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.]])

# Method 1: the embeddings should be arranged as rows
>>> lp1 = model.add_lookup_parameters((3, 5))
>>> lp1.init_from_array(array)
>>> lp1[0].npvalue()
array([ 0.,  1.,  2.,  3.,  4.])
>>> lp1[1].npvalue()
array([ 5.,  6.,  7.,  8.,  9.])
>>> lp1[2].npvalue()
array([ 10.,  11.,  12.,  13.,  14.])

# Method 2: the embeddings should be arranged as columns
>>> lp2 = model.add_lookup_parameters((3, 5), init=dy.NumpyInitializer(array.T))
>>> lp2[0].npvalue()
array([ 0.,  1.,  2.,  3.,  4.])
>>> lp2[1].npvalue()
array([ 5.,  6.,  7.,  8.,  9.])
>>> lp2[2].npvalue()
array([ 10.,  11.,  12.,  13.,  14.])
```

**Comment by chaitanyamalaviya** [comment]
Thanks a lot!

**Comment by yoavg** [comment]
When were initializers added to add_lookup_parameters?

I recall that I left it out on purpose, because the init_from_array() method was sufficient.

The current behavior, requiring the the embeddings to be arranged in columns, looks like a buggy/counterintuitive behavior to me. It is also inconsistent with initializing regular parameters, when we do not require this transpose.

**Comment by mitchellstern** [comment]
Evidently they were added in https://github.com/clab/dynet/commit/1ec1c82e9ebb296896e4457ae24269314fb3f8ff.

**Comment by neubig** [comment]
In light of this: https://github.com/clab/dynet/pull/340

Is it time to revisit this issue? At least this should be documented I guess.

**Comment by yoavg** [comment]
What is the fix you are you proposing?

I think a fix would be:
1) remove the initializer option
2) potentially allow passing a numpy array instead of a shape to .add_lookup_parameters

**Comment by neubig** [comment]
I don't think 1. is a good choice, because we probably still want the ability to have GlorotInitializer, UniformInitializer, NormalInitializer, etc. for both Parameters and LookupParameters. (I added this because I needed it to compare with other toolkits.)

Intuitively, I like the idea of all initialization-related things being handled through an Initializer class, instead of having two separate APIs for setting values directly vs. Glorot, Uniform, etc. 

I was thinking that inputTensor now assumes that the highest dimension is the batch dimension, it might be OK to assume that the highest dimension in LookupParameter was the "parameter ID" dimension. The behavior seems relatively consistent to me, if documented properly. We could remove the .init_from_array() option to remove API overload. What do you think?

**Comment by yoavg** [comment]
re (1): I think once we have an option to initialize from python array, we can then easily implement the initialization in very compact numpy code. And once people do that, now we have two ways to initialize again, which is confusing. So I guess what I am suggesting is, have the python initialization API (for both LookupParameters and Parameters) take *only* numpy arrays, and supply python code for creating Glorot, Uniform, Normal etc. While this departs from the C++ interface, I think in the long run it will be more flexible and extendable (as well as more uniform) for the users who use only python. The Initializer classes will be used only in the C++ version.

While this may mean double-initialization of the parameters in python (first default, then override), I think this is negligible. We only create parameters once at the beginning.

The proposed interface will be something like:
```
p = m.add_parameters((3,5)) # add parameters with given size and default behavior (likely Glorot).
p = m.add_parameters(np.zeros((3,5)))  # any numpy array, shape taken from array 
p = m.add_parameters(GlorotInit(3,5))   # GlorotInit is a function returning a numpy array
```

The assuming the highest dimension is the parameter ID, I am not sure what `highest` means, but currently we have `m.add_lookup_paramters(vocabSize, ndims)`, and I'd like to keep the same order when passing in an array.

**Comment by neubig** [comment]
I'm doing a cleanup of old issues. Do you think this needs to be fixed? Or is the status quo good enough?

**Comment by pmichel31415** [comment]
OK I'm tired of writing `dy.ConstInitializer(0)` whenever I want to initialize a parameter to 0 so I'm going to go ahead and tackle this. Here's my solution:

```python
p = m.add_parameters((3,5), init=0) # Creates 3x5 matrix filled with 0 (or any other float)
p = m.add_parameters((3,5), init=[a, b]) # Creates 3x5 matrix initialized with U([a,b])
p = m.add_parameters((3,5), init=(a, b)) # Creates 3x5 matrix initialized with N(a, b)
p = m.add_parameters((5,5), init='identity') # Creates 5x5 identity matrix (maybe also saxe)
p = m.add_parameters((3,5), init='glorot') # Creates 3x5 matrix with glorot init (maybe also do he init)
p = m.add_parameters(np.zeros((3,5))) # Creates 3x5 matrix from a numpy array (size is inferred)
p = m.add_parameters((3,5), init=dy.***Initializer()) # For backward compatibility
```

Does that sound reasonable? This would make the code less verbose and easier to read I think

**Comment by neubig** [comment]
I think that in general this is nice, but I really don't like the list and tuple notation distinction having hidden effects changing between the distributions. One option would be when init is a string, also take optional keyword arguments specifying the range, etc.

**Comment by pmichel31415** [comment]
OK this is what I'm going for:


```python
p = m.add_parameters((3,5), init=0) # Creates 3x5 matrix filled with 0 (or any other float)
p = m.add_parameters((3,5), init='uniform', scale=a) # Creates 3x5 matrix initialized with U([-a,a])
p = m.add_parameters((3,5), init='normal', mean=a, std=b) # Creates 3x5 matrix initialized with N(a, b)
p = m.add_parameters((5,5), init='identity') # Creates 5x5 identity matrix (maybe also saxe)
p = m.add_parameters((3,5), init='glorot') # Creates 3x5 matrix with glorot init (maybe also do he init)
p = m.add_parameters(np.zeros((3,5))) # Creates 3x5 matrix from a numpy array (size is inferred)
p = m.add_parameters((3,5), init=dy.***Initializer()) # For backward compatibility
```
