### ISSUE TITLE
Out-of-memory messages are cryptic

### ISSUE THREAD

**Issue by neubig** [clab/dynet#233]
Currently out-of-memory messages are hard to understand because they don't explain the concept of DyNet's fine-grained memory management explained here: http://dynet.readthedocs.io/en/latest/commandline.html

If possible, the message should explain which memory pool ran out of memory, and add a pointer to this doc.

**Comment by chaitanyamalaviya** [comment]
As a suggested improvement, It would be really nice if out-of-memory messages either said something about the required amount of memory for each pool or if the required amount of memory was automatically allocated without the need for a dynet-mem argument. 
There are issues training large models, and I never know whether reducing the minibatch size, or reducing the vocab size/hidden dimension sizes will solve it. 
(Specifically, training a seq2seq model with ~4.5m sentences (with vocab size ~ 41K) and a minibatch_size=16 requires much more than 20GB.)

**Comment by neubig** [comment]
Yes, these are all good suggestions. Thanks!

> As a suggested improvement, It would be really nice if out-of-memory messages either said something about the required amount of memory for each pool or if the required amount of memory was automatically allocated without the need for a dynet-mem argument.
I agree that this would be really nice to have, but it's not trivial to implement, especially without making breaking API changes or complicating the interface. It might be possible though, so if anyone is willing to champion this I could talk about the details.

> There are issues training large models, and I never know whether reducing the minibatch size, or reducing the vocab size/hidden dimension sizes will solve it.
This will be solved to some extent by fixing the error messages. At least you'll be able to tell this.

> (Specifically, training a seq2seq model with ~4.5m sentences (with vocab size ~ 41K) and a minibatch_size=16 requires much more than 20GB.)
I've trained models with vocabulary and minibatch sizes much bigger than this using lamtram or nmtkit, so I suspect that something is using more memory than it should in the particular implementation that you're using. Perhaps to debug this, it would be nice to have functionality that at least allows you to print which parts of the model, and which parts of the computation graph are using how much memory?  This is something that could certainly be done relatively easily. (If you want to hack it, you can do it by adding debug messages in `exec.cc`, but it'd also be nice to have a permanent and easily usable solution)

**Comment by chaitanyamalaviya** [comment]
Thanks! I will try your suggestion to add debug messages in exec.cc first.

**Comment by neubig** [comment]
The original problem has been fixed by this commit:
https://github.com/clab/dynet/commit/9db3d0581b99d4d2aace463d4e0515e0f21d2bb2

DyNet now reports which memory pool ran out of memory, and provides a link to the command line options.
