### ISSUE TITLE
Python Attention Example Correctness

### ISSUE THREAD

**Issue by emanjavacas** [clab/dynet#238]
I am currently working through the examples to get familiar with this interesting library and I've noticed that currently the decode method of the attention network requires the output sequence as input.
Once it decodes a character, the decoder is fed the embedding of the last character in order to proceed.
Wouldn't this mean that the network is always being passed the correct output embedding (instead of the embedding of the character it actually predicted), and that it is therefore being "illegally" helped with the decoding?
I wonder if this actually influences generalization, because this behavior is only there for training.

**Comment by pmichel31415** [comment]
In the probabilistic setting it makes sense : you want to maximize the conditional likelihood P(y_m,...,y_1 | x_n,...x_1) where x is the input sequence and y the output.

You decompose it as  
![codecogseqn 1](https://cloud.githubusercontent.com/assets/10391785/21941551/4d544966-d997-11e6-8af4-a6250623688e.gif)

(Actually you look at the log likelihood)

Now at each timestep 
![codecogseqn 2](https://cloud.githubusercontent.com/assets/10391785/21941600/829f5318-d997-11e6-9427-01f10f6be219.gif) 
is actually the probability output by the RNN at time t with the true output for time 1 to t-1

Now this is only possible at training time. This is why decoding at test time is so important, ie beam search works better than greedily take the most probable word at each time step.

This can also be tackled at training time and I think that's what you're looking for specifically. One recent paper at NIPS did that http://papers.nips.cc/paper/6099-professor-forcing-a-new-algorithm-for-training-recurrent-networks.pdf but there are others.

Hopefully that answers your question

**Comment by emanjavacas** [comment]
Yes, that's indeed very helpful!
I kind of got confused with the fact that the attention example calls `decode` to a function that actually does decoding AND computes the loss, and calls `generate` to another one that does decoding too but no loss.
In fact, decoding is done differently at testing (calling the loss-computing `decode` function) than at testing (where the decoding of `generate` is used instead). 

I am closing this issue.

**Comment by yoavg** [comment]
Hi, thanks for noticing, I agree the current naming is a bit confusing -- if you create a pull request with an alternative naming we'll merge it.

**Comment by emanjavacas** [comment]
I guess the decoding logic could be factored out to a function that optionally takes the output sequence, and then if the output sequence is given it does use the true targets for the recursion (otherwise it just uses the prediction). And then the loss can be computed inside the `get_loss` function.

I actually have code that does this as I describe, so I could create a pull request if something like that would be merged.

**Comment by yoavg** [comment]
I'll merge this, but note also #242 , which may be related or even conflicting? (I didn't look at the current attention example code yet)

**Comment by emanjavacas** [comment]
Yeh, I don't think it will be conflicting. I will create the pull request tomorrow, since it's already beer o'clock at my latitude.
