### ISSUE TITLE
KMaxPooling not implemented on CUDA

### ISSUE THREAD

**Issue by yoavartzi** [clab/dynet#245]
Can you implemented the forward/backward passes for KMaxPooling on CUDA?

I get this error when using it:
![image](https://cloud.githubusercontent.com/assets/3289873/21957908/78e4a700-da6f-11e6-8c12-b1b29d9a81be.png)

**Comment by neubig** [comment]
See also: https://github.com/clab/dynet/issues/158

KMaxPooling is not trivial on GPU because the KMax operation is not implemented in Eigen (AFAIK), and not super-easy to write a CUDA Kernel for. This is something that would be nice to have though.

**Comment by yoavartzi** [comment]
There are some implementation of convolutional nets using Eigen ([this one](https://github.com/TorontoDeepLearning/convnet/blob/4ae77c04e898643bb476e0604fab5682f23069d7/cudamat/cudamat_conv_others.cu#L3685) came up). Any chance some code can be adapted from there? 

Personally, I am more interested in MaxPooling rather than KMaxPooling.

**Comment by neubig** [comment]
FYI, max pooling is now available via the `max_dim()` function. kmax is still pending.

**Comment by neubig** [comment]
I'm going to close this as it's already covered in #158.
