### ISSUE TITLE
Intel MKL-DNN open source library

### ISSUE THREAD

**Issue by yoavartzi** [clab/dynet#246]
Any plans to support Intel MKL-DNN open source library?
https://github.com/01org/mkl-dnn

They claim to have similar functionality to MKL, but it's open source. Unfortunately, they do say the API is different. 

Thanks

**Comment by neubig** [comment]
I think the answer to this is basically "we likely won't be supporting it unless Eigen supports it". Currently the way we use MKL is by telling our up-stream matrix/tensor math library Eigen to use MKL, and make no changes to the DyNet code itself. In interest of ease of maintenance this is probably the best we can do, but if you or someone else wants to step up and both: 1) provide convincing benchmarks that MKL-DNN is a big win, 2) commit to maintaining the code, then we could certainly consider it.

**Comment by neubig** [comment]
I'm going to close this for now, just because it's not likely to happen unless there is a champion, but if a champion arrives I'll be happy to consider it :)
