### ISSUE TITLE
CMake requires the full Eigen path in some environments

### ISSUE THREAD

**Issue by yoavartzi** [clab/dynet#247]
In some environments, the [installations script](http://dynet.readthedocs.io/en/latest/python.html) fails. CMake seems to require the full path for Eigen, and not the relative one. I couldn't figure out why it happens in some environments and not others. Maybe worth adding a note.

**Comment by stepelu** [comment]
I confirm it's failing on latest OSX + brew.

**Comment by neubig** [comment]
Haven't had time to try this, but maybe this could solve the problem? http://stackoverflow.com/questions/39027269/cmake-convert-relative-path-to-absolute-path-with-build-directory-as-current-d

Pull requests welcome!
