### ISSUE TITLE
Questions about L2 regularization on lookup parameters

### ISSUE THREAD

**Issue by Oneplus** [clab/dynet#25]
Hi, all

Thanks for the great tool. I enjoyed both using it and reading the code.

When looking into the SGD training part, I met a question in `cnn/training.cc`. More specifically, it's about the L2 regularization on lookup parameters.

According to my understanding, the `cnn::LookupParameters` stores a sparse representation of the training example. For each instance, only a few dimensions are fired and filled into the `cnn::LookupParameters::non_zero_grads`. When using SGD to train a model, the original form of L2 regularization require updates over all the parameters (not only the non_zero_grads). But codes in the `cnn/training.cc` (line:48 to line:57) seems only updates on the non_zero_grads. So I am a bit confused if there is any thing I missed?

According to section 5.1 in http://research.microsoft.com/pubs/192769/tricks-2012.pdf, there is a trick which guarantees correct L2 regularization updates on sparsely represented training example. I am not sure if this trick is employed. Could anyone kindly advise on this? Thanks so much.

**Comment by redpony** [comment]
Hi Yijia, yes, this is indeed a problem with CNN that hasn't been well
documented at all. It's high on the list of things to fix (using the trick
you pointed out)-- I hope to get to it in the next couple of weeks since a
number of people have raised concerns about this. In the mean time- dropout
and gaussian noise are available. :)

**Comment by Oneplus** [comment]
@redpony Hi Chris, Thanks for quick reply. Hope it can be fixed in near future :-)

**Comment by neubig** [comment]
This is fixed in the v2 branch, but is pending merging into the main branch.
