### ISSUE TITLE
Saveable with a list or Parameter trying to pickle the Parameter objects 

### ISSUE THREAD

**Issue by yoavartzi** [clab/dynet#252]
I have an MLP class (see below) with a flexible number of hidden layers. The Parameter objects of the hidden layers are stored in a list. When saving, it tries to pickle the items in `self._hidden_layers` and `self._hidden_layers_bias`. This throw an exception. 

```py
class MLP(dy.Saveable):
	def __init__(self, model, in_dim, hid_dim, out_dim, num_hidden, non_lin = dy.tanh):
		self._input_layer = model.add_parameters((hid_dim, in_dim))
		self._input_layer_bias = model.add_parameters(hid_dim)
		self._num_hidden = num_hidden
		self._hidden_layers = range(num_hidden)
		self._hidden_layers_bias = range(num_hidden)
		for i in range(num_hidden):
			self._hidden_layers[i] = model.add_parameters((hid_dim, hid_dim))
			self._hidden_layers_bias[i] = model.add_parameters(hid_dim)
		self._output_layer = model.add_parameters((out_dim, hid_dim))
		self._output_layer_bias = model.add_parameters(out_dim)
		self._non_lin = non_lin

	def __call__(self, input, training):
		...
	def get_components(self):
		comps = [self._input_layer, self._input_layer_bias, self._output_layer, self._output_layer_bias]
		comps.extend(self._hidden_layers)
		comps.extend(self._hidden_layers_bias)
		return tuple(comps)

	def restore_components(self, components):
		self._input_layer = components[0]
		self._input_layer_bias = components[1]
		self._output_layer = components[2]
		self._output_layer_bias = components[3]
		self._hidden_layers = list(components[4:self._num_hidden + 4])
		self._hidden_layers_bias = list(components[self._num_hidden + 4:])

```

**Comment by danielhers** [comment]
I tried out your code (in Python 3) but it doesn't work because it's trying to modify a `range` object, which is immutable. Having changed `__init__` to the following:

    def __init__(self, model, in_dim, hid_dim, out_dim, num_hidden, non_lin = dy.tanh):
      self.model = model
      self._input_layer = model.add_parameters((hid_dim, in_dim))
      self._input_layer_bias = model.add_parameters(hid_dim)
      self._num_hidden = num_hidden
      self._hidden_layers = []
      self._hidden_layers_bias = []
      for i in range(num_hidden):
        self._hidden_layers.append(model.add_parameters((hid_dim, hid_dim)))
        self._hidden_layers_bias.append(model.add_parameters(hid_dim))
      self._output_layer = model.add_parameters((out_dim, hid_dim))
      self._output_layer_bias = model.add_parameters(out_dim)
      self._non_lin = non_lin

I can run this without an exception:

    m = MLP(dy.Model(), 100, 100, 100, 100)
    m.model.save("test.model")
    m.model.load("test.model")

**Comment by yoavartzi** [comment]
I modified it to remove some stuff, and probably broke it. Sorry for it

Maybe the issue was fixed.
