### ISSUE TITLE
Glorot initialization not quite right for sigmoids and ReLUs

### ISSUE THREAD

**Issue by pmichel31415** [clab/dynet#262]
I think the Glorot initialization is not quite right for sigmoids, and in general for any function that does not satisfy

![codecogseqn 2](https://cloud.githubusercontent.com/assets/10391785/22168023/f4952236-df37-11e6-9fd9-781b2bf1bca3.gif)

near 0. which is true for the tanh but not for the sigmoid (![codecogseqn 3](https://cloud.githubusercontent.com/assets/10391785/22168056/2e838258-df38-11e6-8cf0-9b0bb011cd07.gif))

(See (2) through (7) in [the original paper](http://www.jmlr.org/proceedings/papers/v9/glorot10a/glorot10a.pdf?hc_location=ufi),)

Relu seems to be a special case as well (see [He et al. (2015)](http://www.cv-foundation.org/openaccess/content_iccv_2015/papers/He_Delving_Deep_into_ICCV_2015_paper.pdf)).

One solution would be to mimmick the interface in lasagne (see [here](http://lasagne.readthedocs.io/en/latest/modules/init.html#lasagne.init.Glorot))

**Comment by neubig** [comment]
Nice catch! Yes, I think we should fix this. If I remember correctly a lot of other toolkits separate the Glorot and He methods, right? Eventually (maybe not necessarily in this issue?) we'll probably want to add HeNormal as well.

**Comment by neubig** [comment]
Fixed by https://github.com/clab/dynet/pull/295
