### ISSUE TITLE
fatal error: mm_malloc.h: No such file or directory on ARM64

### ISSUE THREAD

**Issue by stefan-it** [clab/dynet#266]
Hi dynet-users,

I tried to compile the latest `dynet` version on ARM64. I got the following error message:

```bash
 20%] Building CXX object dynet/CMakeFiles/dynet.dir/mem.cc.o
/media/ubuntu/speicher/repositories/dynet/dynet/mem.cc:13:24: fatal error: mm_malloc.h: No such file or directory
compilation terminated.
```

I could reproduce this error on two ARM64 systems:

* NVIDIA Jetson TX1 with Ubuntu 16.04 and GCC 5.4.0
* ODROID-C2 with Arch Linux and GCC 6.2.1

I guess it has something to do with the following macro defined in `mem.cc`:

```cpp
#if !_WINDOWS
	#include <mm_malloc.h>
#endif
```

As a temporary workaround I removed the `!_Windows` define and added these lines instead:

```cpp
#define _mm_free(p) free(p)
#define _mm_malloc(a, b) malloc(a)
```

inspired from [here](https://github.com/Microsoft/CNTK/blob/master/Source/Common/Include/ssefloat4.h). But this would lead to a core dump e.g. when executing the `./train_xor` test and other test cases.

But I guess we need a more sophisticated solution here :)

**Comment by neubig** [comment]
It looks like `aligned_malloc` might work on C++11: http://stackoverflow.com/questions/32612881/why-use-mm-malloc-as-opposed-to-aligned-malloc-alligned-alloc-or-posix-mem

Does this work in your environment? (It looks like you have to swap the order of arguments, so be careful to do so)

**Comment by stefan-it** [comment]
Hi @neubig , thanks for your reply! Here's one possible explanation:

On e.g. Ubuntu the `mm_malloc.h` can be found in the filelist of [libgcc-5-dev](http://packages.ubuntu.com/de/xenial-updates/amd64/libgcc-5-dev/filelist) for *am64*.

For the *arm64* package of `libgcc-5-dev` it's [missing](http://packages.ubuntu.com/de/xenial-updates/arm64/libgcc-5-dev/filelist).

So I tried compiling `dynet` with clang. The following error message appeared:

```bash
Scanning dependencies of target dynet
[  1%] Building CXX object dynet/CMakeFiles/dynet.dir/cfsm-builder.cc.o
clang: error: the clang compiler does not support '-march=native'
```

So I removed the `-march=native` option in `CMakeLists.txt` and the compilation works fine (except a linker error message with boost for `train_rnnlm`.

**Comment by neubig** [comment]
Because there is a workaround, I'll close this for now.

**Comment by Kiona0405** [comment]
With my Mac book air(arm64, Apple M1 chip), below modifications works. Thank you @neubig!

```diff 
$ git diff
diff --git a/dynet/mem.cc b/dynet/mem.cc
index 700da14c..bcf8b5e7 100644
--- a/dynet/mem.cc
+++ b/dynet/mem.cc
@@ -10,7 +10,7 @@

 #include <fcntl.h>
 #if !_WINDOWS
-#include <mm_malloc.h>
+/* #include <mm_malloc.h> */
 #endif
 #include "dynet/except.h"
 #include "dynet/devices.h"
@@ -27,7 +27,8 @@ namespace dynet {
 MemAllocator::~MemAllocator() {}

 void* CPUAllocator::malloc(size_t n) {
-  void* ptr = _mm_malloc(n, align);
+  /* void* ptr = _mm_malloc(n, align); */
+  void* ptr = aligned_alloc(align, n);
   if (!ptr) {
     show_pool_mem_info();
     cerr << "CPU memory allocation failed n=" << n << " align=" << align << endl;
@@ -37,7 +38,8 @@ void* CPUAllocator::malloc(size_t n) {
 }

 void CPUAllocator::free(void* mem) {
-  _mm_free(mem);
+  /* _mm_free(mem); */
+    free(mem);
 }
```
