### ISSUE TITLE
abort to exception

### ISSUE THREAD

**Issue by karlstratos** [clab/dynet#270]
Right now dynet calls abort when it runs into problems , for example: https://github.com/clab/dynet/blob/ddc9253bdc39d2d17b583d9809d08d0835b13f44/dynet/aligned-mem-pool.h#L42. 

This is problematic when dynet's being used as part of a larger system.  One way to address it is to replace all abort calls with throw runtime_error (with whatever message printed to sterr) and catch it somewhere else (possibly outside dynet). 

But is there an issue in terms of memory allocation, etc.? That is, do we have to deallocate before we throw an error to avoid keep allocating more memory? Thanks.

**Comment by neubig** [comment]
Yes, this is something that would be excellent to have, but it's a duplicate with this one:
https://github.com/clab/dynet/issues/139

If you're willing to help out with this, we'd really appreciate it!
