### ISSUE TITLE
Problems with Loading VanillaLSTM Saved model

### ISSUE THREAD

**Issue by elikip** [clab/dynet#271]
Hi,

I am trying to load a VanillaLSTM from a file I saved to the disk earlier. When I attempt to use the LSTM to encode a sequence I get the following error:
  what():  Bad dimensions for AffineTransform: [{400} {400,144} {144} {400,100} {0}]

The python line in my code causing the crash is:
for entry, flstm, rlstm in zip(sentence, fwState.add_inputs(wembds), reversed(bwState.add_inputs(reversed(wembds)))):

I am using the master branch and the sha1 is a6452ef7237b9499dfa500a99d9c75689e3c462d

Thanks in advance for your help.

**Comment by pmichel31415** [comment]
Hi, it seems like the first hidden state of your LSTM fails to initialize. I see 2 resons for this : 

- Did you call `.initial_state()` on your two states fw and bw?
- Did you save the model with the same version of Dynet? For ~1 week there was a bug in VanillaLSTM for serialization

**Comment by elikip** [comment]
Hi, I indeed used the routine you mentioned in the first bullet. I also pulled the lastest version last night and used it both to train and load the model.

**Comment by pmichel31415** [comment]
Oh OK then seems like it is a bug. I'll look into it, do you have a minimal code snippet I can use to reproduce the error? Thanks!

**Comment by elikip** [comment]
The code below produces a different error, but also related to loading a model file containing a VanillaLSTMBuilder.

import dynet as D
 
 model = D.Model()
 
 lstm = D.VanillaLSTMBuilder(1, 10, 10, model)
 #lstm = D.LSTMBuilder(1, 10, 10, model) # Uncomment this line for the bug to disappear
 invec = D.inputVector([0.0 for _ in range(10)])
 
 lState = lstm.initial_state()
 res =lState.add_inputs([invec])
 print res[0].output().npvalue()
 
 model.save('dummy_model', [lstm])
 
 model = D.Model()
 [lstm] = model.load('dummy_model')
 invec = D.inputVector([0.0 for _ in range(10)])
 
 lState = lstm.initial_state()
 res =lState.add_inputs([invec])
 print res[0].output().npvalue()

**Comment by danielhers** [comment]
I tried out your code and it runs without an error:

```
[dynet] random seed: 3323997059
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
[-0.00320667 -0.00186251 -0.02668336 -0.04373051 -0.0032957   0.0735959
 -0.04084149 -0.03242191 -0.05999433  0.00158646]
loading model
done 3
[-0.00320667 -0.00186251 -0.02668336 -0.04373051 -0.0032957   0.0735959
 -0.04084149 -0.03242191 -0.05999433  0.00158646]
```

**Comment by neubig** [comment]
@elikip could you give us a bit more info on the environment in which the bug occurs? Version of DyNet, boost, Eigen, compiler, OS.

**Comment by elikip** [comment]
Sure, sorry for my delayed response.
I think that the error I encountered when running the python code I attached is connected to my Eigen version. The output I received is:

> [dynet] random seed: 482286987
> [dynet] allocating memory: 512MB
> [dynet] memory allocation done.
> [-0.07342962  0.09033553 -0.03602226  0.04766677 -0.06262479  0.0358988
>  0.00993776  0.02281265 -0.03149629  0.01426104]
> loading model
> done 3
> python: /home/nlp/kiperwe/dynet-base/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorIntDiv.h:148:  Eigen::internal::TensorIntDivisor<T, div_gt_one>::TensorIntDivisor(T) [with T = long int; bool div_gt_one  = false]: Assertion `divider > 0' failed.

Regarding the first error I mentioned in the thread, it's a little tricky to synthesis a minimal code snippet in which this bug happens. I will do my best and hopefully I will attach such code it to this thread soon.

Regarding information on the environment:
OS - CentOS Linux release 7.3.1611 (Core) 
DyNet ver - a6452ef7237b9499dfa500a99d9c75689e3c462d
Boost - 1.53
Eigen - parent: 9700:24abf9a98b53 tip
and I forgot to mention that I am using MKL

**Comment by elikip** [comment]
I managed to change the bilstmtagger.py from DyNet's official python examples to work with VanillaLSTMBuilder and got the same error when trying to load the model (when using the old LSTMBuilder the model loads without difficulties):
> terminate called after throwing an instance of 'std::invalid_argument'
>  what():  Bad dimensions for AffineTransform: [{256} {256,128} {128} {256,64} {0}]

The code can be downloaded from https://www.dropbox.com/s/xb59atgybzr7efc/bilstmtagger.py?dl=0
I wrote the code quickly, so I am sorry for the code quality.. You can set the boolean variable Test to False in order to train a model and save it, or True to load the model and use it to predict. The boolean variable Vanilla could be set to False to use the old LSTMBuilder or True for the new vanilla version.

**Comment by pmichel31415** [comment]
Can you also provide sample data files and your util.py?

**Comment by elikip** [comment]
You can download util.py from the following link: https://raw.githubusercontent.com/clab/dynet/master/examples/python/util.py
I modified the code to generate its own data randomly, so there is no longer need for sample data files. You can use the same link to download the code.

**Comment by pmichel31415** [comment]
Hi I tried your code and it ran without problem.

I first ran with test=False and saved the model after 100 iterations, then ran with test=True and got : 

    [dynet] random seed: 2030827761
    [dynet] allocating memory: 1024MB
    [dynet] memory allocation done.
    loading model
    done 14
    0.626914778857

All this with MLP=True and Vanilla=True

**Comment by elikip** [comment]
Hmm.. Is it possible that the problem is something related to the Intel MKL package I am using? Did you try to run my script with the same git version as I did? With Intel MKL?

**Comment by neubig** [comment]
The most likely culprit is the version of Boost, so if people who have run this could confirm the version of Boost that might be helpful.

**Comment by danielhers** [comment]
I use Boost 1.62, without MKL.

**Comment by pmichel31415** [comment]
I use Boost 1.58 without MKL (on ubuntu 15.04)

**Comment by neubig** [comment]
This will probably be fixed by https://github.com/clab/dynet/issues/84
