### ISSUE TITLE
Only single core for DyPy CPU version?

### ISSUE THREAD

**Issue by keruimin** [clab/dynet#273]
I installed DyNet (without CUDA) as described in the install doc. It seems that, however, the implementation only use 1 core for computation. Is it possible to take advantage of multi-core in current implementation?

**Comment by neubig** [comment]
See this post for more information:
https://groups.google.com/forum/#!topic/dynet-users/U9B_wFRJXZ8

We also have an issue open about letting forward and backward run in a threadpool without MKL:
https://github.com/clab/dynet/issues/33
