### ISSUE TITLE
boost::archive::archive_exception loading BiRNNBuilder

### ISSUE THREAD

**Issue by danielhers** [clab/dynet#274]
The following code fails:
```
import dynet as dy
              
m = dy.Model()
b = dy.BiRNNBuilder(2, 100, 200, m, dy.LSTMBuilder)
m.save("bilstm.model", [b])
m2 = dy.Model()
m2.load("bilstm.model")
```
Getting this error:
```
loading model 
done 44       
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error
Abort
```
It's not clear from this error message what the problem is, but it seems to happen after initializing the loader ("done 44").

**Comment by danielhers** [comment]
A version of DyNet from 6 days ago didn't have this problem, so apparently it was introduced since then.

**Comment by pmichel31415** [comment]
OK I think I've located the problem, I introduced this bug with the dropout pull request.

As a hotfix I can disable the serialization of a bunch of new fields in LSTMBuilders. This will make it impossible to store different dropout rates but at least it will be backward compatible.

**Comment by danielhers** [comment]
I don't mind updating my code, but at least make it clear what should be
changed and make the error message clear. It's not a problem with loading
an old model; it's right after saving it.

**Comment by danielhers** [comment]
Thanks, fixed.
