### ISSUE TITLE
installation issues on Cuda 8.0

### ISSUE THREAD

**Issue by DevSinghSachan** [clab/dynet#280]
I am getting the following error on this command
cmake .. -DEIGEN3_INCLUDE_DIR=$PATH_TO_EIGEN -DPYTHON=$PATH_TO_PYTHON -DBACKEND=cuda 

Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (found
  version "8.0")

**Comment by chaitanyamalaviya** [comment]
Did you try adding the -DCUDA_TOOLKIT_ROOT_DIR flag to cmake? 
as specified here: http://dynet.readthedocs.io/en/latest/python.html#gpu-mkl-support

**Comment by DevSinghSachan** [comment]
Yes, I tried, but it didn't work.
Here is the complete error log,
devendra@devendra:~/dynet-base/dynet/build$ cmake .. -DEIGEN3_INCLUDE_DIR=/home/devendra/dynet-base/eigen -DPYTHON=`which python` -DBACKEND=cuda -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0/
-- Boost version: 1.54.0
-- Found the following Boost libraries:
--   program_options
--   regex
--   serialization
-- Boost dir is /usr/include
-- BACKEND: cuda
CMake Error at /usr/local/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (found
  version "8.0")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.4/Modules/FindCUDA.cmake:953 (find_package_handle_standard_args)
  CMakeLists.txt:146 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/devendra/dynet-base/dynet/build/CMakeFiles/CMakeOutput.log".

**Comment by neubig** [comment]
Hi @DevSinghSachan , could you try to set the following environmental variable (assuming you are using bash) `export CUDA_ROOT=/usr/local/cuda-8.0/`, then remove `-DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0/` from your command line?

**Comment by DevSinghSachan** [comment]
Hello Prof. @neubig .
I tried the above suggested modification, but the same error message is coming as indicated above.
Also, here are the some lines in my .bashrc file
export PATH=/usr/local/cuda-8.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:/usr/local/cuda-8.0/extras/CUPTI/lib64:$LD_LIBRARY_PATH

Also, tensorflow 0.12.1 gpu version is working fine with above settings.

**Comment by neubig** [comment]
@DevSinghSachan Hmm, I'm actually stumped on this one. Could you try to ask people on the cmake mailing list about this, can you create a minimal `CMakeLists.txt` file such as the one on this page:
https://cmake.org/examples/

then add `find_package(CUDA REQUIRED)` to the end and see if this still breaks cmake? If it does, I think you could ask the cmake mailing list and they might be able to help find the answer.

**Comment by DevSinghSachan** [comment]
@neubig I was able to fix this problem.
Actually, I installed the CUDA 8.0 using dpkg installer, but someone files in the include directory were missing. So the cmake was showing errors.
I installed the missing lib files using .run installer for cuda-8.0 .
After that, Dynet gpu installation worked fine and I am able to run the gpu codes in dynet.

Thanks!!

**Comment by kalgiz** [comment]
I am getting the same problem. I was installing the CUDA via the cuda_9.0.176_384.81_linux.run script, tough. Could you explain me what you exactly did to get rid of the problem?
