### ISSUE TITLE
Segmentation fault in Expression::value() CUDA in LSTMBuilder

### ISSUE THREAD

**Issue by pmichel31415** [clab/dynet#284]
I finally managed to install dynet with CUDA but now I get a segfault when I try to retrieve the value of the output of a LSTMBuilder (I seem to have the same problem with VanillaLSTMBuilder).

Here's a minimal example (works when compiled for CPU, not for GPU) : 

    #include "dynet/nodes.h"
    #include "dynet/dynet.h"
    #include "dynet/lstm.h"
    #include "dynet/expr.h"
    #include <iostream>

    using namespace std;
    using namespace dynet;

    int main(int argc, char** argv) {
        auto dyparams = dynet::extract_dynet_params(argc, argv);
        dynet::initialize(dyparams);
        cerr<<"Declare variables"<<endl;
        ComputationGraph cg;
        Model m;
        VanillaLSTMBuilder lstm(1, 10, 10, m);
        Expression v = zeroes(cg, {10});

        cerr << "Init LSTM" << endl;
        lstm.new_graph(cg);
        lstm.start_new_sequence();
        cerr << "Run LSTM" << endl;
        Expression output = lstm.add_input(v);
        cerr << "Segfault happens here (probably in SimpleExecutionEngine::get_value(VariableIndex i) )"<<endl;
        Tensor ov = output.value();
        cerr << "This won't be printed on GPU because of the error" << endl;

    }

**Comment by neubig** [comment]
@pmichel31415 Hmm, I wasn't able to reproduce this. Could you try again with the latest master? If so, maybe we can debug this directly on your machine.

**Comment by pmichel31415** [comment]
Unable to reproduce this, I'll close the issue
