### ISSUE TITLE
Question: padding and LSTM

### ISSUE THREAD

**Issue by rasoolims** [clab/dynet#285]
Hi,
Do we always need padding for LSTM? For example, if the LSTM output is concatenated to another vector and the concatenated vector is fed to a MLP?
Thanks

**Comment by neubig** [comment]
This question is a bit vague. Could you please provide a minimal code example of what you're trying to do?

**Comment by rasoolims** [comment]
```python
# fw[-1] and bw[-1] are the foward and backward lstm final outputs.
# i is another input (average of word embeddings) 
input = concatenate(filter(None,[fw[-1],bw[-1], i]))
r_t = O * (self.activation(dropout(H1 * input,self.dropout)))
```

My question is do I still need to pad the fw and bw lstms? Because they are concatenated to another input and then fed to a MLP.

**Comment by neubig** [comment]
No, I don't think you need to do padding here. This code looks valid as-is.
