### ISSUE TITLE
dynet is out of memory

### ISSUE THREAD

**Issue by anglil** [clab/dynet#292]
Hi, I am building a language model using the dynet c++ API. After training the model for a little while, I got the following message:

dynet is out of memory, try increasing with --dynet-mem (current capacity: 178257920)
Aborted

How should I use that argument in the c++ code (How to allocate more memory for backward, forward and parameters, basically)? Thanks.

-Angli

**Comment by neubig** [comment]
Hi @anglil , you can take a look here for more info about how to increase memory: http://dynet.readthedocs.io/en/latest/commandline.html

On a related note, I also made the error reporting a bit more verbose so you can now tell which of the three DyNet memory pools is running out of memory. Please pull the latest version for a slightly more easy-to-understand error message.
