### ISSUE TITLE
misleading minibatch documentation?

### ISSUE THREAD

**Issue by nsaphra** [clab/dynet#294]
In the minibatch [documentation](http://dynet.readthedocs.io/en/latest/minibatch.html), the following line appears in the examples:

```python
scores_sym = dy.softmax(W*dy.concatenate([word_1, word_2])+b)
loss_sym = dy.pickneglogsoftmax(scores_sym, out_label)
```

I came away with this with the impression that soft max has to be performed before `pickneglogsoftmax`, but I had assumed that the soft max operation happens inside the picking function here. Assuming the intuitive thing that this function combines the soft max with the pick, this documentation is somewhat misleading. Can someone confirm that this is a double softmax?

**Comment by pmichel31415** [comment]
Yes I think you're right, 
this is a double softmax according to the doc on [pickneglogsoftmax](http://dynet.readthedocs.io/en/latest/operations.html#_CPPv2N5dynet4expr17pickneglogsoftmaxERK10Expressionj) (and looking by the implementation too)

**Comment by neubig** [comment]
Yes, this was a bug. Fixed by: https://github.com/clab/dynet/commit/c1106a1e7fffaa9b3e01f90714dfe0ed3bc205e0

Thanks for pointing it out!

**Comment by jihelhere** [comment]
The bug is also present in the technical report on Arxiv (Fig. 1 lines 13 and 14)
