### ISSUE TITLE
Stale expressions should throw error, not segmentation fault

### ISSUE THREAD

**Issue by neubig** [clab/dynet#308]
In Python, when we try to use an expression that has been invalidated by `dy.renew_cg()` we get a segmentation fault. For example, this will crash with a segmentation fault:

    model = dy.Model()
    W_p = model.add_parameters((16,16))
    W = dy.parameter(W_p)
    dy.renew_cg()
    print('W.dim()=', W.dim())

This is confusing, especially for people who are not familiar with the DyNet paradigm of loading parameters into the computation graph for every training instance.

**Comment by yoavg** [comment]
They do throw an exception in most cases. I see this is not implemented for ".dim()".
I do not have time to do this now (and not working from my own laptop) but the fix should be to add:
```
        if self.cg_version != _cg._cg_version: raise RuntimeError("Stale Expression (created before renewing the Computation Graph).")
```
in line 631:
https://github.com/clab/dynet/blob/master/python/_dynet.pyx#L631

**Comment by yoavg** [comment]
fixed (for .dim()).

**Comment by neubig** [comment]
Thanks a lot!
