### ISSUE TITLE
Bus Error 10 - Any ideas?

### ISSUE THREAD

**Issue by iamyoungjo** [clab/dynet#317]
I recently got installed dynet with gpu option but I'm seeing this error whenever I run the actual code with _gdynet.

```
[dynet] initializing CUDA
Request for 1 GPU ...
[dynet] Device Number: 0
[dynet]   Device name: GeForce GTX 980 Ti
[dynet]   Memory Clock Rate (KHz): 3505000
[dynet]   Memory Bus Width (bits): 384
[dynet]   Peak Memory Bandwidth (GB/s): 336.48
[dynet]   Memory Free (GB): 6.29501/6.44225
[dynet]
[dynet] Device(s) selected: 0
[dynet] random seed: 227952754
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
Bus error: 10
```

Anyone had this error before? I searched similar errors in the issues but not able to find any. The same code works flawlessly with 'dynet' (non-gpu) import.

Could possibly be related to my rare system setup (OS X 10.11.8 + GPU enabled). 

Thank,
YJ

**Comment by neubig** [comment]
Hmm, I've never heard of anyone encountering this, but as you suspect it might be an error that only occurs on Mac with CUDA, which is a rather unusual setting. Could you please attach an example of the code that you're running, and also the command line arguments you're using?

Also, you mentioned you're importing `_gdynet` directly. Are you following the instructions here http://dynet.readthedocs.io/en/latest/python.html#usage including running `dynet.init()`?

**Comment by iamyoungjo** [comment]
I tweaked a bit on the tutorial_bilstm_viterbi_tagger in order to use command line inputs (for file inputs) and python3 compatible, but nothing major has changed. About "dy.init()", I tried to include the dy.init() but it showed very weird error: 
>AttributeError: module '_gdynet' has no attribute 'init'

I went through the instruction again but wasn't able to find the solution.
If I've done anything wrong on my setup, let me know. 
[tutorial_bilstm_viterbi_tagger_py3.py.zip](https://github.com/clab/dynet/files/784820/tutorial_bilstm_viterbi_tagger_py3.py.zip)

**Comment by neubig** [comment]
OK, if ``init()'' is missing from ``_gdynet'' this seems like a bug. Could you get it to work by doing the standard ``import dynet'' and adding the ``--dynet-gpu'' command line argument?

**Comment by iamyoungjo** [comment]
I tried --dynet-gpu but it shows the similar behavior.
> AttributeError: module 'dynet' has no attribute 'init'

I pulled out dy.init() from the code and tried, but no luck.
>  [dynet] initializing CUDA
> Request for 1 GPU ...
> [dynet] Device Number: 0
> [dynet]   Device name: GeForce GTX 980 Ti
> [dynet]   Memory Clock Rate (KHz): 3505000
> [dynet]   Memory Bus Width (bits): 384
> [dynet]   Peak Memory Bandwidth (GB/s): 336.48
> [dynet]   Memory Free (GB): 6.29611/6.44225
> [dynet]
> [dynet] Device(s) selected: 0
> [dynet] random seed: 3074500781
> [dynet] allocating memory: 4098MBMB
> [dynet] memory allocation done.
> Bus error: 10

Strangely, I figured that if I put more memory size (e.g. 6114MB), it shows a bit different error.
> [dynet] initializing CUDA
> Request for 1 GPU ...
> [dynet] Device Number: 0
> [dynet]   Device name: GeForce GTX 980 Ti
> [dynet]   Memory Clock Rate (KHz): 3505000
> [dynet]   Memory Bus Width (bits): 384
> [dynet]   Peak Memory Bandwidth (GB/s): 336.48
> [dynet]   Memory Free (GB): 6.29611/6.44225
> [dynet]
> [dynet] Device(s) selected: 0CUDA failure in cudaMalloc(&ptr, n)
> out of memory
> libc++abi.dylib: terminating with uncaught exception of type dynet::cuda_exception: cudaMalloc(&ptr, n)
> Abort trap: 6

I don't think it's because of "out of memory" is indicating system memory as I know it works in non-gpu dynet flawlessly with lower size allocation. Or, could it be related to my GPU memory allocation?

**Comment by neubig** [comment]
Is this still a problem? Or has it been resolved?
