### ISSUE TITLE
"cout" of expressions doesn't work with batched expressions

### ISSUE THREAD

**Issue by neubig** [clab/dynet#324]
In the C++ API, attempting to print batched expressions causes a cryptic error:

    Assertion failed: (d.batch_elems() == 1), function operator*,

This should be fixed to actually print out the expression in the standard format for Eigen tensors.

**Comment by sunalbert** [comment]
Anyone is working on this bug or it has been fixed?

**Comment by Arkadipta-Chatterjee** [comment]
Can i work on this?

**Comment by xonx4l** [comment]
i would like to work on this . can you give me more context about the issue.
