### ISSUE TITLE
Picking and setting values of tensors at particular batch

### ISSUE THREAD

**Issue by pcyin** [clab/dynet#325]
Hi,

It would be nice that `pick` could support retrieving values from a specific batch. Similarly, we could have a `set` operation to allow setting values of particular rows/columns/batches. This is extremely useful to allow for mixed batching/unbatching operations. E.g.,

```
1. Batched LSTM encoding of inputs
2. Use `pick` to get encoding results for each batch. Build operations for each batch dynamically.
3. Use `set` to merge data from different batches and continue with batched operation for efficiency.
```

**Comment by neubig** [comment]
Yes, I think this is definitely useful, but maybe we can merge the comments into this already-open issue: https://github.com/clab/dynet/issues/170

**Comment by neubig** [comment]
Should be fixed by: https://github.com/clab/dynet/pull/389
