### ISSUE TITLE
Input with numpy.ndarray or tensors

### ISSUE THREAD

**Issue by pmichel31415** [clab/dynet#326]
It would be a real quality of life improvement if one could input expressions as numpy multidimensional arrays directly without flattening + specifying the dimension. This is tricky currently especially since it looks like numpy [is row major by default](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html) whereas [dynet expects column major ordering](https://github.com/clab/dynet/blob/master/python/_dynet.pyx#L859-L863) (If I understand correctly)

Similarily in c++ it would be nice to be able to input a tensor directly, ie : 

    Tensor t = ... ;
    x = input(cg,t);

instead of (currently) : 

    Tensor t = ... ;
    x = input(cg,t.dim(),t.vec());

**Comment by neubig** [comment]
Simultaneously, I'd like to fix this:
https://github.com/clab/dynet/issues/175

You're correct that the difference between the row-major and column-major difference is annoying, but I imagine that we'll just have to re-map row major format (in numpy) into column major (in the computation graph).

**Comment by pmichel31415** [comment]
Yes it can be done easily, actually you only need to call `numpy.flatten(_,order='F')` but it should probably be invisible to the end python user.

**Comment by neubig** [comment]
Yes, totally agree on this. And actually, because inputting things to the computation graph is causing a memory copy anyway this probably shouldn't be a huge performance hit.

**Comment by pmichel31415** [comment]
Fixed by #340
