### ISSUE TITLE
Dynet accepts only weight decay between 0 and 1

### ISSUE THREAD

**Issue by pmichel31415** [clab/dynet#329]
I tried to set the weight decay parameter to 1 and it gave me an exception : is there a rationale behind this choice?

The only constraint that I see is that the weight decay parameter be >=0, there is no probabilistic interpretation that justifies that it should be 0 < . < 1

Let me know and I'll fix this

**Comment by neubig** [comment]
I actually think weight decay sets the weights W to be equal to: `W <- (1 - weight_decay) * W`. I don't think values more than 1 make sense here?

**Comment by pmichel31415** [comment]
So my intuition was that it corresponded to the coefficient of the l2 penalty but that doesn't seem to be the case.

However it still seems fishy, the only place I see it used is [here (SimpleSGDTrainer for example)](https://github.com/clab/dynet/blob/master/dynet/training.cc#L123) the weight decay seems to be used to _divide_ the gradient. Is there something I'm missing?

**Comment by pmichel31415** [comment]
OK I was mistaken aout how weight decay worked apparently
