### ISSUE TITLE
Select_rows bugged on gpu

### ISSUE THREAD

**Issue by pmichel31415** [clab/dynet#335]
I get a segmentation fault using select_rows on a matrix when running on gpu (works on CPU).

I will try to upload unit tests for select operations later.

Is there another way to select submatrices on GPU without picking each parameter individually? pickrange seems to work only for vectors.

**Comment by neubig** [comment]
Hmm, once you get the unit tests I'll debug this ASAP. I thought this was working.

Regarding the second, the answer is "at the moment no, but this is something we should definitely have and would not be hard to add".

**Comment by pmichel31415** [comment]
I submitted a pull request.

After double checking here's what I've found : 

- only select_rows creates problem (not select_cols)
- here's the error on the GPU for the unit tests : 
    unknown location(0): fatal error: in "node_test/select_rows_gradient": memory access violation at address: 0x1020dc00004: invalid permissions
- looking at the code, the only difference between select_rows and select_cols is a missing  `.device(*dev.edevice)` here : https://github.com/clab/dynet/blob/master/dynet/nodes.cc#L1693 could that be it?

**Comment by neubig** [comment]
Thanks! I think the missing device is quite possibly the problem. Also I realized that these are not doing proper bounds checking, so I'll send an update to the pull request with these two problems fixed.

**Comment by neubig** [comment]
OK, should be done in the updated version of https://github.com/clab/dynet/pull/336
Will merge pending passing tests.

**Comment by pmichel31415** [comment]
Thanks for the quick help!

I can confirm that it works on my end.
