### ISSUE TITLE
Can not find cwise_multiply

### ISSUE THREAD

**Issue by speedcell4** [clab/dynet#338]
```python
>>> x = dy.vecInput(3)
>>> y = dy.vecInput(3)
>>> x.set(np.arange(3))
>>> y.set(np.arange(3))
>>>
>>> print(dy.cwise_multiply(x, y).npvalue())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'dynet' has no attribute 'cwise_multiply'
```

**Comment by neubig** [comment]
As noted in the [documentation](http://dynet.readthedocs.io/en/latest/operations.html#_CPPv2N5dynet4expr5cmultERK10ExpressionRK10Expression), this has been renamed to `cmult()`. There were still a couple places in the code examples where `cwise_multiply()` remained though, so I fixed them here: https://github.com/clab/dynet/commit/05521c66deae17929e3982f4c67e0d3b9f79a33e
