### ISSUE TITLE
Python bindings only allow tensors up to rank 2

### ISSUE THREAD

**Issue by pmichel31415** [clab/dynet#339]
For instance, `Expression.npvalue()` launches an assertion error if the number of dimensions per batch is >2.

One should be able to retrieve a `np.ndarray` of shape of length > 2 for a higher ranked tensor (this would probably also simplify the code)

**Comment by neubig** [comment]
Yeah, this should be fixed.

**Comment by pmichel31415** [comment]
Yes I am working on it right now. It might incur some performance overhead but I think it's negligible compared to the cost of forward/backward

**Comment by neubig** [comment]
Cool. And even if it is a little bit slow, having an implementation (possibly with a comment in the doc + issue filed to make sure that people realize that it's sub-optimal) is better than none at all.

**Comment by yoavg** [comment]
I didn't know we supported higher-order tensors in dynet. what are we using them for?

In any case, if we support them, it should be reflected in python of course. I think the only place this may get tricky is with memory oredering. So I'd pay attention to that.

**Comment by pmichel31415** [comment]
@yoavg Yes theoretically dynet supports them up to order 4 I think.

I have no particular application in mind, but it could be useful for someone one day.

As far as ordering is concerned I believe using `order='F'` when reshaping/reordering should do the trick right? Anyway I'll write tests to make sure nothing breaks.

**Comment by yoavg** [comment]
cool.

order='F' should work, yes. Do we also have a way of creating such tensors from data? if so, this should also be supported I guess.

**Comment by pmichel31415** [comment]
My recent pull request #340 adds a function to create a tensor from an arbitrary numpy ndarray

**Comment by pmichel31415** [comment]
Fixed by #340
