### ISSUE TITLE
debugging documentation

### ISSUE THREAD

**Issue by nsaphra** [clab/dynet#342]
Currently the [debugging documentation](http://dynet.readthedocs.io/en/latest/debugging.html) claims that in python you can add parameters when calling `renew_cg()`. That doesn't seem to be the case with the current version. Perhaps this is a future feature? Either way, maybe this should be removed from the docks until it is in the current release.

**Comment by neubig** [comment]
I believe it does?
https://github.com/clab/dynet/blob/master/python/_dynet.pyx#L559

Graham

**Comment by nsaphra** [comment]
My mistake, I was actually running an old version.
