### ISSUE TITLE
i got an error about cython when i execute 'make -j 2'

### ISSUE THREAD

**Issue by zhang-wen** [clab/dynet#347]
cythoning _dynet.pyx to _dynet.cpp

Error compiling Cython file:
------------------------------------------------------------
...
        self.thisptr.backward(index)

    cpdef print_graphviz(self):
        self.thisptr.print_graphviz()

    cpdef void checkpoint(self):
         ^
------------------------------------------------------------

_dynet.pyx:590:10: Return with value in void function

Error compiling Cython file:
------------------------------------------------------------
...
        self.thisptr.backward(index)

    cpdef print_graphviz(self):
        self.thisptr.print_graphviz()

    cpdef void checkpoint(self):
         ^
------------------------------------------------------------

_dynet.pyx:590:10: Cannot convert 'void' to Python object

Error compiling Cython file:
------------------------------------------------------------
...
        self.thisptr.print_graphviz()

    cpdef void checkpoint(self):
        self.thisptr.checkpoint()

    cpdef void revert(self):
         ^
------------------------------------------------------------

_dynet.pyx:593:10: Return with value in void function

Error compiling Cython file:
------------------------------------------------------------
...
        self.thisptr.print_graphviz()

    cpdef void checkpoint(self):
        self.thisptr.checkpoint()

    cpdef void revert(self):
         ^
------------------------------------------------------------

_dynet.pyx:593:10: Cannot convert 'void' to Python object
building '_dynet' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/home/wen/2.tools/dynet-base/dynet -I/home/wen/2.tools/dynet-base/eigen -I/usr/include -I/usr/include/python2.7 -c _dynet.cpp -o build/temp.linux-x86_64-2.7/_dynet.o -std=c++11
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
_dynet.cpp:1:2: error: #error Do not use this file, it is the result of a failed Cython compilation.
 #error Do not use this file, it is the result of a failed Cython compilation.
  ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
python/CMakeFiles/target.dir/build.make:55: recipe for target 'python/timestamp' failed
make[2]: *** [python/timestamp] Error 1
CMakeFiles/Makefile2:2277: recipe for target 'python/CMakeFiles/target.dir/all' failed
make[1]: *** [python/CMakeFiles/target.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by neubig** [comment]
What is your version of Cython? Are you using the latest version of DyNet?

**Comment by zhang-wen** [comment]
@neubig  hi, i have fixed this problem, because the Cython version is too low, after i upgrade the Cython, it works, yes, i am using the latest version of DyNet. 
but i used command `pip install Cython` to install Cython 0.25, but when i input `cython --version`, it always showed 0.21, when i `pip install Cython==0.24`, now the version of Cython is 0.24.1, finally  the compling of DyNet works!
