### ISSUE TITLE
Glorot initialization is not good in VanillaLSTMBuilder

### ISSUE THREAD

**Issue by pmichel31415** [clab/dynet#348]
The parameters are created as two big `4*d_hid x d_hid`, `4*d_in x d_in` matrices so the implicit Glorot Initialization is done accordingly, whereas it should be done separately for each gate (and differently for tanh and sigmoid gates).

I don't know of any easy way to do this. Ideally one would create the four parameters separately and then stack them together but this doesn't seem easy to do with the current interface.

**Comment by neubig** [comment]
How about we just use UniformInitializer and calculate the appropriate Glorot initialization coefficient inside the builder?

**Comment by pmichel31415** [comment]
Well the problem is not as much the coefficient as the fact that the four parts of the matrix should be initialized with different coefficients. Is there an efficient way of doing this without manipulating eigen tensors directly?

**Comment by neubig** [comment]
You wouldn't need to manipulate Eigen tensors, but you would need to manipulate DyNet tensors. Just fetch the pointer to the memory of the main parameter object, and do a bit of pointer math, create a new DyNet Tensor that points to this with the appropriate size, then call TensorTools::Uniform. It's not the prettiest solution, but it's correct and efficient.

**Comment by yoavg** [comment]
Nice catch!

I am curious how much this will affect the results.

As a possible less-ugly solution, perhaps write an initializer for this? ("JointMatrixGlorotInitializer" or something?)

**Comment by pmichel31415** [comment]
Yes I will try to benchmark the results on language modelling.

I am not 100% sure what you mean by "JointMatrixGlorotInitializer", what would the interface look like?

**Comment by neubig** [comment]
I'm guessing that you would basically give the number of rows in each matrix and ID of whether the output is a sigmoid or tanh. So for example, if we have a joint matrix for the LSTM where each matrix is of size n, it would be something like the following (in Python syntax):

    JointMatrixGlorotInitializer([(n,TANH), (n,SIGMOID), (n,SIGMOID), (n,SIGMOID)])

Of course, the sum of the dimensions that are the first element in the tuple would have to add to the matrix size. Look reasonable?

**Comment by yoavg** [comment]
Right, this is what I meant.

But why do we care if its SIGMOID or TANH at this stage?

**Comment by neubig** [comment]
Glorot initialization varies depending on the activation function used afterwards. See here: https://github.com/clab/dynet/pull/295

**Comment by yoavg** [comment]
I didn't realize this. Good to know!

**Comment by yoavg** [comment]
Actually maybe the better Initalization interface here is not 

`JointMatrixGlorotInitializer([(n,TANH), (n,SIGMOID), (n,SIGMOID), (n,SIGMOID)])`

But rather `JointMatrixInit([(n, GlorotInitializer(...)), (n, GlorotInitializer(...)),...])`

That is, it gets a list of `(int, Initializer)` items.

**Comment by neubig** [comment]
+1 on this. Good idea!

**Comment by pmichel31415** [comment]
OK albeit the joint initializer thing would still be relevant, experiments I ran suggest that the per-gate glorot initialization is not useful.

More to come later when I do more experiments.

**Comment by neubig** [comment]
If I remember correctly, perhaps we're not going to fix this, as the current behavior seems to be better than the "correct" behavior? Shall I close the issue?

**Comment by pmichel31415** [comment]
Yes let's close it
