### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by zhang-wen** [clab/dynet#350]
hello, everyone,
i updated the DyNet, but when i run

```
from _gdynet import *
m = Model() 
m.add_parameters((8, 8))
```

it showed  `Segmentation fault (core dumped)`  error

**Comment by neubig** [comment]
I think you're missing a call to `dy.init()`. Please take a look here for proper usage: http://dynet.readthedocs.io/en/latest/python.html#usage

Please confirm whether this fixes your problem. If it does, we should probably need to have a check whether `dy.init()` has been called or not.

**Comment by yoavg** [comment]
The "official" way (at least the way I intended it) is to use `import dynet` always, and indicate cpu/gpu via the commandline. `_dynet` and `_gdynet` are implementation details.

While (I think) we do not have a way to enforce this, maybe we should at least remove this option from the documentation?

**Comment by pmichel31415** [comment]
There is one use case of the `import _dynet` option and it's when you want to set the dynet parameters (memory, random seed, gpus) programmatically (eg. in a jupyter notebook) as described [here](http://dynet.readthedocs.io/en/latest/python.html#usage) 

I think it might still be useful to some people, we had an issue regarding that (#255)

**Comment by neubig** [comment]
@yoavg @pmichel31415 Is there any idea about a good solution for this? Or should we leave this as-is and close this issue?

**Comment by pmichel31415** [comment]
I'm in favor of keeping it as-is, maybe rewrite the docs if it's not clear enough

**Comment by neubig** [comment]
OK, I'll close this then.

**Comment by alexanderkoller** [comment]
Hi, I just wanted to mention that the link in the documentation to http://dynet.readthedocs.io/en/latest/commandline, which probably explains how to select cpu/gpu from the command line, is broken.

By contrast, the documentation mentions the _dynet vs. _gdynet choice in a prominent place (http://dynet.readthedocs.io/en/latest/python.html#usage). So if you want to encourage us to use the command line as the default method, maybe change the emphasis in the documentation. :)

Also, thanks for implementing dynet. This seems like a very cool library, and I look forward to using it.

**Comment by pmichel31415** [comment]
Hi @alexanderkoller I fixed the link.

If you have a better idea of how to emphasize the command line usage could you do a pull request/send it to me ? 

Having an external point of view helps, thanks!

**Comment by alexanderkoller** [comment]
Hi, thanks for the quick fix!

I made a pull request for you with a suggestion for rephrasing the documentation. I'm not familiar with the ReST text format, so maybe double-check that I didn't mess anything up.
