### ISSUE TITLE
Should have ability to read LookupParameters as matrix

### ISSUE THREAD

**Issue by neubig** [clab/dynet#352]
In some cases, we will want to use parameters like LookupParameters during training time, then as a simple matrix during test time (e.g. when implementing sampling-based approximations to a Softmax, such as NCE). This is not currently supported, but should be easy to add by allowing the `parameter()` expression to take LookupParameters as input as well.

**Comment by yoavg** [comment]
+1 on having `parameter()` work also on LookupParameters.

Coming to think about it, what is the cost of allowing every 2dim parameter to have the LookupParameter functionality? Maybe we can just unify these two classes?

**Comment by neubig** [comment]
I guess it would add an extra bool+vector to each parameter. The bool would be "whether this parameter has been used as a whole" and vector would be "if the parameter has been used as a lookup, which elements in this parameter have been used". The difficulty here though is that the intuitive layout of LookupParameters and Parameters is different because DyNet (Eigen) uses column-major order. I think it wouldn't be super-intuitive if we completely unified them.

**Comment by yoavg** [comment]
Ok, so lets not.
