### ISSUE TITLE
which GPU to use

### ISSUE THREAD

**Issue by anglil** [clab/dynet#354]
Hi, I'm wondering if I intend to use GPU, do I have to set --dynet-gpu-ids to select a specific GPU, or can I leave this unset and dynet will randomly choose a GPU?
Thanks,
Angli

**Comment by anglil** [comment]
Btw, I selected one GPU for training my model but got the following error:

[dynet] initializing CUDA
[dynet] Request for 1 specific GPU ...
[dynet] Device Number: 0
[dynet]   Device name: Tesla K80
[dynet]   Memory Clock Rate (KHz): 2505000
[dynet]   Memory Bus Width (bits): 384
[dynet]   Peak Memory Bandwidth (GB/s): 240.48
[dynet]   Memory Free (GB): 11.927/11.9956
[dynet]
[dynet] Device(s) selected: 0CUDA failure in cudaMalloc(&ptr, n)
out of memory
terminate called after throwing an instance of 'dynet::cuda_exception'
  what():  cudaMalloc(&ptr, n)
Aborted

Has anyone encountered this? Could it be because of problems with cuda setup on my aws ami p2 instance?

**Comment by yoavg** [comment]
If you use `--dynet-gpu` it will use the first one. If you use `--dynet-gpu-ids 3` it will use the one with id=3.

**Comment by neubig** [comment]
And how much memory are you asking the GPU for? If you're asking for too much memory then you'll possibly get an error like above. I've also seen errors like this happen when there was some problem with the configuration of the CUDA drivers, which was solved with a reboot. It's difficult to debug the exact case though.

**Comment by anglil** [comment]
Thanks. It turns out the GPU memory is ~12GB and I tried to allocate more than one GPU has to offer. I tried --dynet-gpu but got the following message:

Task: --dynet-gpu
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Task --dynet-gpu not supported.

Guess this flag is not supported anymore? After I switched to using --dynet-gpu-ids, the training started properly.

**Comment by yoavg** [comment]
Oh, are you using the python or the c++ version? `--dynet-gpu` is a python flag.

**Comment by anglil** [comment]
Oh that's why... I'm using the c++ version. Thanks for the clarification!
