### ISSUE TITLE
about broadcasting multiplication

### ISSUE THREAD

**Issue by zhang-wen** [clab/dynet#355]
here i have two expressions whoses shapes are {1X80} and  {512X80} with batch size 80

i want to do pair-wise multiplication, so i should broadcast the {1X80} by row, what should i do ? when i use cmult function to multiply them, it showed following error:

```
Mismatched input dimensions in CwiseMultiply: [{1X80} {512X80}]
```

**Comment by yoavg** [comment]
What is the source of these expressions? I suspect the real solution would be to create them differently and not get to this situation. (for example, perhaps the 512x80 should actually be a batch of 512 elements of size 80?)

**Comment by zhang-wen** [comment]
yes, your are right, the {512x80} matrix is a hidden state of one GRU, and it is a batch of 512 elements of size 80.
about the {1x80} matrix, firstly i created a mask expression `mask_expr` which is {lenx80}, and i use `mask_expr[index]` to get the {1x80} matrix.

**Comment by yoavg** [comment]
Try using the DyNet minibatching mechanism. It is a bit different than in other toolkits.
http://dynet.readthedocs.io/en/latest/minibatch.html

If this does not fit your use case, explain why and we can try and figure out a workaround.

**Comment by pmichel31415** [comment]
Just adding to this I still think there are case where having `cmult` automatically broadcasting would be useful (if not necessary). Some I've encountered are : 

- Doing dropout on the embedding matrix for RNNLM, it's better to have a Bernoulli array of size {size of vocabulary,1}
- Multiplying a matrix/vector with a scalar expression (for instance : reparametrization trick when the standard deviation is a parameter)

**Comment by neubig** [comment]
OK. I'm a little bit cautious of broadcasting because I think it can cause you to accidentally do things you weren't expecting if you're not very careful with it. That being said, I think it's worth having the ability to do so.

For number one in your examples, I didn't understand this completely. You mean you're setting the embeddings of some words to zero? Is there a reference for this?

For number two, we should definitely make it possible to broadcast scalar expressions, as we already have this for scalar consts, and this has many obvious use cases.

**Comment by pmichel31415** [comment]
For number one see https://arxiv.org/abs/1512.05287 section 4.2

This is basically applying dropout to the words (but the same words within one sentence)

**Comment by neubig** [comment]
OK, but: "For T ≪ V it is therefore more efficient to first map the words to the word embeddings, and only then to zero-out word embeddings based on their word type." We would probably just do this with an "if" statement in DyNet, right?

**Comment by zhang-wen** [comment]
ok, thank you guys, let me explain my use cases in detail.

my task is machine translation, because the length of source sentences in training data are different, so we usually need to make zero padding for those shorter sentences, the use a 0-1 mask matrix to remove those padding part.  which is definitey what i want to do:

i use one mask {1X80} (one batch words) to remove the encoded source sentence matrix {256X80}, so i need to do multiplication between mask {1X80} and encoded matrix {256X80}. is there python interface to do this automaticlly broadcasting multiplication now ?

can you guys understand what i want ? if you have some questions, please let me know, thank you.

**Comment by neubig** [comment]
@zhang-wen OK, I understand now. What you actually want to do is multiplication of a length-256 vector (word embedding) with a scalar (mask) over 80 mini-batch elements. As mentioned above, scalar multiplication using expressions is not supported yet, but it should be. We'll try to do this soon.

**Comment by zhang-wen** [comment]
@neubig yes , i think so, you guys have implement cmult() operation which i think is automatically broadcast by column, but why don't you implement row_mult() operation which will be automatically broadcast by row.

**Comment by zhang-wen** [comment]
@neubig , yes, correct, that is what i want to do. 
i have tried to scalar multiplication , but failed:

3 * e1
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-bc04f1e6e9f9> in <module>()
----> 1 3 * e1

_gdynet.pyx in _gdynet.Expression.__mul__ (_gdynet.cpp:23371)()

TypeError: Cannot convert int to _gdynet.Expression

**Comment by yoavg** [comment]
Try `e1 * 3`

(and we should consider implementing `__rmul__` for expressions)

**Comment by zhang-wen** [comment]
@yoavg thank you `e1 * 3` works！

**Comment by zhang-wen** [comment]
@neubig  i think i find a solution way, 

embedding: {256X80}
mask:           {1X80}

i can use `embedding * mask ` to do broadcasting multiplication

**Comment by neubig** [comment]
Broadcasting of multiplication is now possible.
