### ISSUE TITLE
Assertion error from Eigen

### ISSUE THREAD

**Issue by pcyin** [clab/dynet#356]
Hi,

I am getting a strange assertion error from Eigen when calling `trainer.update()`:

```
python: /projects/tir1/users/pengchey/apps/eigen/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceCuda.h:149: virtual void* Eigen::CudaStreamDevice::allocate(std::size_t) const: Assertion `err == cudaSuccess' failed.
```
It seems to be an allocation error, but to my knowledge dynet mangages its own memory. Any suggestions? Thanks!

**Comment by neubig** [comment]
Hmm, this may be a somewhat difficult error to debug. If you could send an example of your program in a separate mail I might be able to debug.

**Comment by pcyin** [comment]
It seems dynet is having trouble with CUDA ver 8.0.61_375, which causes this error. Rolling back to an older version solved this issue

**Comment by neubig** [comment]
We have reason to believe that this might have been a problem in the host environment with mismatched CUDA versions.
