### ISSUE TITLE
Questions about expr::pick with vector arguments

### ISSUE THREAD

**Issue by Oneplus** [clab/dynet#367]
Hi, I've seen the dynet [document](http://dynet.readthedocs.io/en/latest/operations.html?highlight=pick#_CPPv2N5dynet4expr4pickERK10ExpressionRKNSt6vectorIjEEj) saying

> Expression dynet::expr::pick(const Expression &x, const std::vector<unsigned> &v, unsigned d = 0)
Batched pick.
> Pick elements from multiple batches.
> Return
> A mini-batched expression containing the picked elements

I parsed this as picking `v` slices from the tensor and store them into a tensor with `v` batches. However, the following code 
```
  unsigned max_values = 4 * 2 * 3;
  std::vector<float> x_values(max_values);
  for (unsigned x_ = 0; x_ < max_values; x_++) {
    x_values[x_] = static_cast<float>(x_);
  }
  dynet::ComputationGraph cg;
  dynet::expr::Expression x = dynet::expr::input(cg, dynet::Dim({ 2, 3 }, 4), x_values);
  dynet::Tensor z = cg.get_value(x);
  dynet::expr::Expression picked_x = dynet::expr::pick(x, { 0, 1 });
  dynet::Tensor picked_z = cg.get_value(picked_x);
```
gives me an assertion error.
`In PickElement::forward, number of elements in the passed-in index vector (2) did not match number of elements in mini-batch elements in expression (of dimension {3X4} )`

Did I misunderstand the function of `pick`?

**Comment by pmichel31415** [comment]
According to the documentation : 

> v: A vector of indicies to choose, one for each batch in the input expression.

pick only allows you to pick one slice for each batch so you would have to do tomething like

    dynet::expr::Expression picked_x = dynet::expr::pick(x, { 0, 0, 0, 0},0); // Pick first element along first dimension in each batch

Does that make sense? I agree it's maybe not the most intuitive

**Comment by Oneplus** [comment]
@pmichel31415 Ah! I've been thinking the `v` means the indices along one axis! That make sense. Thanks!

One more word, it seems related with https://github.com/clab/dynet/issues/170. I am not quite sure about whether is solves the pick_batch_elements problem in that issue.
