### ISSUE TITLE
Is there a alternative way to save model besides the boost?

### ISSUE THREAD

**Issue by iamyoungjo** [clab/dynet#370]
Hi, 

Currently I am facing problem to create a model loader in different languages(e.g. Java).
Is there a better way to serialize the model (or parameters) in more human-readable way?
It would be great to be more widely-used in many ways.
Any kind of suggestions  will be appreciated!

Thanks,
YJ

**Comment by neubig** [comment]
Hi @iamyoungjo , we are literally working on this right now, under this issue: https://github.com/clab/dynet/issues/84

Follow this issue and we'll post updates there as they are made.

**Comment by iamyoungjo** [comment]
Oh, I am so sorry about posting duplicated question on this.
@neubig , can you give me an advice to serialize the parameters besides the enhancement now? Just a simple brief advice would be so much appreciated.

Thanks,
YJ

**Comment by pmichel31415** [comment]
Depending on what you're using you can serialize the parameter values directly.

In python that would be something like

	model = dy.Model()
	# save
	W = model.add_parameters((2, 2))
	W_value = W.as_array()
	np.savetxt('file.txt', W_value)

In c++ you can retrieve the Tensor holding the parameter values and then output it : 

    Parameter W = model.add_parameters({2, 2});
    Tensor W_values = *(W.values());
    cout << W_values << endl;

(Or something like that, check [this part of the docs for more details](http://dynet.readthedocs.io/en/latest/core.html#))

**Comment by iamyoungjo** [comment]
Thanks @pmichel31415 so much!! That works flawlessly for the parameters saving. Actually now I am looking at the instructions for getting the parameter values from LSTMBuilder but I can't find a good way from the documents. Is there a way to extract parameters from Builders in python? If I'm missing something here, please let me know!

**Comment by pmichel31415** [comment]
If you're using c++ : you can access the parameters of the LSTMBuilder through the `params` field.

This returns a 2d vector. For more details about how it is structured you can peek directly in [this part of the code](https://github.com/clab/dynet/blob/master/dynet/lstm.cc#L22-L43)

For python.. I'm not sure you can right now

**Comment by iamyoungjo** [comment]
Thank you so much @pmichel31415 ! I tried to put some lines in _dynet.pyx in order to access parameters from model.

```python
    cpdef param_list(self):
        cdef vector[CParameterStorage] vals
        vals = self.thisptr.parameters_list()
```

any hint to pull out the vector as a python object such as list/array?

**Comment by iamyoungjo** [comment]
@pmichel31415 , any small hint that I can start from? Thanks in advance!

**Comment by pmichel31415** [comment]
Hmm so if you have a list of CParameters you can wrap it into a Parameter using Parameter.wrap_ptr (here)[https://github.com/clab/dynet/blob/master/python/_dynet.pyx#L235] is that what you want to do?

**Comment by iamyoungjo** [comment]
@pmichel31415 , yes. but it keeps giving me errors because of private variables.
for example, if I define param_list like below,

```python
    cpdef param_list(self):
        cdef vector[CParameterStorage] vals
        vals.reserve(self.thisptr.parameters_list().size())
        for ps in self.thisptr.parameters_list():
            vals.push_back(ps)
        return np.vstack([c_tensor_as_np(t.values).reshape(1,-1,order='F') for t in vals])
```

It gives me following err:

```
_dynet.cpp:12286:27: error: calling a private constructor of class
      'dynet::ParameterStorage'
  dynet::ParameterStorage __pyx_v_ps;
                          ^
/Users/youngjokim/Development/dynet/dynet_plist/dynet/dynet/model.h:113:3: note: 
      declared private here
  ParameterStorage() {}
  ^
_dynet.cpp:12287:27: error: calling a private constructor of class
      'dynet::ParameterStorage'
  dynet::ParameterStorage __pyx_v_t;
                          ^
/Users/youngjokim/Development/dynet/dynet_plist/dynet/dynet/model.h:113:3: note: 
      declared private here
  ParameterStorage() {}
  ^
_dynet.cpp:12296:27: error: calling a private constructor of class
      'dynet::ParameterStorage'
  dynet::ParameterStorage __pyx_t_7;
                          ^
/Users/youngjokim/Development/dynet/dynet_plist/dynet/dynet/model.h:113:3: note: 
      declared private here
  ParameterStorage() {}
  ^
_dynet.cpp:12351:13: error: assigning to
      'std::vector<dynet::ParameterStorage> *' from incompatible type 'const
      std::vector<ParameterStorage *> *'
  __pyx_t_6 = &__pyx_v_self->thisptr->parameters_list();
```

And it makes sense to me, too. I am just wondering if there's a better way to do this besides of touching class definitions.

Thanks for the reply!

**Comment by pmichel31415** [comment]
Oh this is in the Model class right?

OK so there's definitely a way to do this and I've been meaning to do it for 1-2 weeks now but I just don't have the time, it's to create methods to access the parameters of a RNNBuilder in c++ and then import the code to python.

Here's the interface I'd come up with : 

    /**
    * @brief Returns the parameters of the network
    * @details To access the i-th parameter of layer l, do :
    * 
    *     auto p=rnn.get_parameters();
    *     p[l][i]
    * 
    * See the subclass specific implementations for for the organization of parameters
    * @return Array of parameters for each layers
    */
    virtual vector<vector<Parameters>> get_parameters();
    /**
    * @brief Returns the parameters for a specific layer of the network
    * @details To access the i-th parameter of layer l, do :
    * 
    *     auto p=rnn.get_layer_parameters(l);
    *     p[i]
    * 
    * See the subclass specific implementations for for the organization of parameters
    * 
    * @param l Layer index
    * @return Array of parameters for layer l
    */
    virtual vector<Parameters> get_layer_parameters(unsigned l);
    /**
    * @brief Returns the expressions holding parameters for each layer
    * @details The structure of the output is the same than `get_parameters` except that each element of the output is now the expression of the parameter loaded in the computation graph.
    * 
    * If the parameters weren't loaded in the computation graph (ie `new_graph` hasn't been called), this throws a `runtime_error`
    * 
    * 
    * @return [description]
    */
    virtual vector<vector<Expression>> get_parameters_expression();
    virtual vector<Expression> get_layer_parameters_expression(unsigned i);

This would then need to be implemented  for the various builder, although the SimpleRNNBuilder, LSTMBuilder and VanillaLSTMBuilder would be the most urgent I think.

Unfortunately Idon't really gave the time to do it this week but if you want to give it a try I can help.

**Comment by iamyoungjo** [comment]
Thanks for the approach! I can definitely try and let you know! Will give you an update!

**Comment by iamyoungjo** [comment]
@pmichel31415 , thanks to your advice, I put get_parameters() method in LSTMBuilder (C++). However, still it's not that easy to pull out thru Python (I think it's because of my lack of knowledge in python bindings). 

Here's the c++ implementation:
```C
std::vector<std::vector<Parameter>> LSTMBuilder::get_parameters() {
  std::vector<std::vector<Parameter>> t;
  t.reserve(layers);
  for (unsigned i = 0; i < layers; ++i) {
    for (auto p : params[i]) {
      t[i].push_back(p);
    }
  }
  return t;
}
```

As I created this as 2d Vector, this would be good if it can be imported to python as np.array(2d). 
But in order to access this value, I need to put get_parameters() in CLSTMBuilder (_dynet.pxd) like this:

```python
cdef extern from "dynet/lstm.h" namespace "dynet":
    cdef cppclass CLSTMBuilder "dynet::LSTMBuilder" (CRNNBuilder):
        CLSTMBuilder()
        CLSTMBuilder(unsigned layers, unsigned input_dim, unsigned hidden_dim, CModel &model)
        vector[vector[CParameters]] get_parameters()
```

And then, I might need to create a method to call this get_parameters() in the class declaration of CLSTMBuilder in _dynet.pyx. Is this the way you expected? It's a bit confusing as I need to modify quite a lot of lines. If I'm doing anything wrong here, please let me know.

Thanks,

**Comment by redpony** [comment]
Let's mark this as provisional ("use at your own risk"), even just as a
comment. We are working on a longer term solution to this, and it would be
sensible to avoid creating interfaces like this that might be difficult to
maintain backward compatibility with in the future.

**Comment by iamyoungjo** [comment]
@redpony 100% agreed. This will be at my own risk. @pmichel31415 Any suggestion on my last comment?

**Comment by pmichel31415** [comment]
@iamyoungjo Yes you would need to add the method in the LSTMBuilder class in _dynet.pyx and you should be good to go.

I thought you wanted to import the parameters' expression, but if you only need the Parameter values you can probably just add the field params (which is publi iirc) in CLSTMBuilder in _dynet.pxd and then write a function which retrieves the tensors and returns them as np arrays using c_tensor_as_np (which you would put directly in _dynet.pyx.

this would look like 

In _dynet.pxd : 

    cdef cppclass CSimpleRNNBuilder  "dynet::SimpleRNNBuilder" (CRNNBuilder):
        CSimpleRNNBuilder()
        CSimpleRNNBuilder(unsigned layers, unsigned input_dim, unsigned hidden_dim, CModel &model)
        vector[vector[CParameters]] params

In _dynet.pyx : 

    cdef class LSTMBuilder(_RNNBuilder): # {{{
        def __cinit__(self, unsigned layers, unsigned input_dim, unsigned hidden_dim, Model model):
            if layers > 0:
                self.thisptr = new CLSTMBuilder(layers, input_dim, hidden_dim, model.thisptr[0])
            else:
                self.thisptr = new CLSTMBuilder()
            self.cg_version = -1

        def whoami(self): return "LSTMBuilder"
        def get_parameters():
            param_values=[]
            for layer in self.thisptr.params:
                for p in layer:
                    param_values.append(c_tensor_as_np(p.values))
            return param_values

(modulo cython errors)

sorry for the misunderstanding.

@redpony I agree, my main motivation to try this was that I needed the expression of the parameters of the RNN (for a custom L2 regularization scheme), I think it would be useful to be able to access that as well somehow (in python, it's straightforward in c++)

**Comment by iamyoungjo** [comment]
@pmichel31415 , Thanks for the advice of simpler modification. But can I ask you what's the reason of put params in CSimpeRNNBuilder instead of CRNNBuilder? Confusing part is that as CLSTMBuilder's inheritance is related to CRNNBuilder rather than CSimpleRNNBuilder, I think we need to put declaration of params in CRNNBuilder. But this will be tough as well because there's no member variable param in RNNBuilder (in C++). Maybe I'm in my own deadlock here.

**Comment by pmichel31415** [comment]
Ah sorry my bad this is a failed copy paste on my end of course you should do it directly for CLSTMBuilder, sorry about that

**Comment by iamyoungjo** [comment]
@pmichel31415 , thanks for the quick clarification! I tried again and faced this build err:

```
cythoning _dynet.pyx to _dynet.cpp

Error compiling Cython file:
------------------------------------------------------------
...
        self.cg_version = -1

    def whoami(self): return "LSTMBuilder"
    def get_parameters(self):
        param_values=[]
        for layer in self.thisptr.params:
                                ^
------------------------------------------------------------

_dynet.pyx:1773:33: Object of type 'CRNNBuilder' has no attribute 'params'
```

So basically the self.thisptr indicates CRNNBuilder instead of CLSTMBuilder.
Here's the get_parameters() method that I created based on your advise:
```
    def get_parameters(self):
        param_values=[]
        for layer in self.thisptr.params:
            for p in layer:
                param_values.append(c_tensor_as_np(p.get().values))
        return param_values
```
I think it's almost there but still I'm stuck in this because of this reference problem.

**Comment by iamyoungjo** [comment]
@pmichel31415 , can you check if this is what you meant? Thanks!

**Comment by iamyoungjo** [comment]
@pmichel31415 Thanks for the reply!! I am currently trying to add get_parameter function in RNNBuilder in C++. Will give you an update once it works.
