### ISSUE TITLE
set UNK words for dynet::Dict

### ISSUE THREAD

**Issue by anglil** [clab/dynet#381]
Hi, dynet team, I'm wondering if dynet::Dict sets a default cut-off word frequency? I always observed that my dictionary (dynet::Dict) after the training data is loaded has less words than in the training data. Is there a rule implemented in the dictionary that says that words that appear less than say, 3, times in the training data are set to UNK?

Thanks!

**Comment by neubig** [comment]
No, as long as you are not using `freeze()`, this should not happen and your dictionary should be the same size as the unique words in the training data. If you're observing different behavior and can create a minimal example, we could take a look.

**Comment by anglil** [comment]
I see. Good to know. I think I understand what's happened now:
I was using dynet to build a lattice decoder (on which you sent me a pointer to a paper a while ago) for translating OOV words in MT results. So in decoding, some candidate words are recognized as UNK by the dict established using the training data, whose vocabulary doesn't subsume the entirety of the candidate words for the OOV words.
