### ISSUE TITLE
documentation about the way dynet assignes loss to the graph

### ISSUE THREAD

**Issue by thebeancounter** [clab/dynet#386]
Hello, 
I am using the python version of dynet with python 2.7 
and can't find documentation about how to create a custom loss function and assign it it the model...
how can i "tell" it, that this is the loss that needs to be back propagated? 
Is there a forum or a mailing list for this kind of questions? 
thanks

**Comment by pmichel31415** [comment]
There is one example in here http://dynet.readthedocs.io/en/latest/tutorials_notebooks/API.html towars the end.

Basically in python you call `objective.backward()` and it will automatically compute the gradients with respect to this objective.

Hope that helps.

**Comment by neubig** [comment]
And yes, there is a mailing list here: https://groups.google.com/forum/#!forum/dynet-users
