### ISSUE TITLE
`_cdiv(Expression a, float b)` doesn't work with `from __future__ import division`

### ISSUE THREAD

**Issue by jcyk** [clab/dynet#391]
Hi, I just found that
```
from __future__ import division
import dynet as dy
x = dy.scalarInput(3)
x / 3
```
will produce
```
TypeError: unsupported operand type(s) for /: '_dynet._inputExpression' and 'int'
```
But if I delete the line `from __future__ import division`, everything will go fine.

Any idea to fix that?

**Comment by yoavg** [comment]
Not sure, but try copy-pasting __div__ and rename the duplicate to __truediv__

**Comment by yoavg** [comment]
`__div__` and `__truediv__` above.

**Comment by jcyk** [comment]
@yoavg Yes! That solved the problem. I am pulling a request. #392

**Comment by yoavg** [comment]
Great, thanks!
