### ISSUE TITLE
clip the values in a parameter

### ISSUE THREAD

**Issue by jcyk** [clab/dynet#393]
It's useful to keep model parameters in a small fixed range, say \[-0.01, 0.01\], like WassersteinGAN.

Is there a way to do that (in place)?

if no, I think it may be good to create some API like [`numpy.clip`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.clip.html) (i.e., `dynet.clip(parameter, left, right)`)

After some research on the source code, I found there may be various ways to do that. Not sure to make it a member function of `Parameter` or `Tensor` or `TensorTools` or `ParameterStorage` ....

**Comment by yoavg** [comment]
Hmm... I worry `dynet.clip(...)` will be confused with the other dynet operations that work on expressions and produce expressions, and can be backproped through. I think something like `param.clip_inplace(left, right)` might be better in terms of the external API.

**Comment by neubig** [comment]
I think this sounds like something that would be useful to have, and agree with Yoav on the API.
