### ISSUE TITLE
cc1plus error while installing Python DyNet Module

### ISSUE THREAD

**Issue by aminianmary** [clab/dynet#396]
Hello everyone,
I'm trying to install Python DyNet module on Linux following [these steps](http://dynet.readthedocs.io/en/latest/python.html). Cmake is run without any errors and all the build files are written into dynet/build directory. But I'm getting the following error messages while running "make - j 2":

_cc1plus: error: invalid option argument ‘-Ofast’_
_cc1plus: error: unrecognized command line option "-std=c++11"_
_make[2]: *** [dynet/CMakeFiles/dynet.dir/cfsm-builder.cc.o] Error 1_
_make[1]: *** [dynet/CMakeFiles/dynet.dir/all] Error 2__

My g++ (GCC) version is 4.9.2 and I'm using Python version 2.6. 
Do you have any idea how I should address the error? Thanks!

**Comment by rasoolims** [comment]
I also had this problem: sometimes there are different versions of gcc and g++ in a machine and Cmake picks the older version. You can set the following paths to the newer versions of GCC and G++ before running cmake:
export CC=$GCCPATH
export CXX=$G++PATH

**Comment by neubig** [comment]
@aminianmary Hmm, could you please give us more info? Specifically, please send us the output of `cmake`, the full output of `make`, and the output of the `env` command.

**Comment by neubig** [comment]
I'm closing this for now, feel free to re-open if this is still an issue.

**Comment by bmurali1994** [comment]
any suggestions on how to resolve this: #956

**Comment by rasoolims** [comment]
If you look at the output of cmake and see that the gcc/g++ path (and version) differs from ```which gcc```  and ```which g++``` command, you have to run ```export CC=$GCCPATH``` and ```export CXX=$G++PATH``` before running cmake.

**Comment by bmurali1994** [comment]
I tried that, but it did not help!

**Comment by bmurali1994** [comment]
quick update: upgrading gcc and following this link solved the above issue: https://gist.github.com/stephenturner/e3bc5cfacc2dc67eca8b
