### ISSUE TITLE
an error occur when compile dynet【error: ‘size_type’ is not a member of ‘boost::interprocess::message_queue’】

### ISSUE THREAD

**Issue by xc-kiwiberry** [clab/dynet#403]
i have successfully run：

```
cd dynet
mkdir build
cd build
cmake .. -DEIGEN3_INCLUDE_DIR=/path/to/eigen
```

but when：
`make -j 2`
error occur ：

```

[ 30%] Building CXX object dynet/CMakeFiles/dynet.dir/mp.cc.o
……
/path/to/dynet/dynet/mp.h:222:7: error: ‘size_type’ is not a member of ‘boost::interprocess::message_queue’
boost::interprocess::message_queue::size_type recvd_size;
^
```

there is the 'make.log' : http://paste.ubuntu.com/24245846/  

I have update the g++ and gcc to 4.8.
And I don't know wether the problem is about 【the version or the path of 'Boost'】?

really appreciate~!~

**Comment by neubig** [comment]
Hmm, can you also send the output of the `cmake` command? Thanks!

**Comment by xc-kiwiberry** [comment]
Thank you for you response！
I think I have fixed this problem by specify the path of ‘Boost’ :)
I will close this issue.
