### ISSUE TITLE
OpenCL Support

### ISSUE THREAD

**Issue by neubig** [clab/dynet#405]
It would be nice if DyNet supported OpenCL in addition to CUDA. Recently, Eigen is moving in the direction of supporting OpenCL which would make this much more realistic: https://www.codeplay.com/portal/tensorflow™-for-opencl™-using-sycl™

However, this would still require a major engineering effort, so this issue would need a champion who really wants to see it get done. We're happy to have contributions!

**Comment by neubig** [comment]
Cool, it looks like the OpenCL support has been integrated in the Eigen upstream:
https://github.com/RLovelett/eigen/blob/master/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceSycl.h

DyNet's current setup still has a lot of code based on "CPU or CUDA" as opposed to "choose your device", but with a bit of engineering we should be able to resolve this and make OpenCL an option.

**Comment by neubig** [comment]
Now that multi-device support is active this might be possible (CC: @xunzhang  )?

**Comment by dseddah** [comment]
Hi Graham,
do you know if someone has ever tried dynet with opencl ?

**Comment by neubig** [comment]
AFAIK, no. If someone's interested we'd be very happy to have a PR though.

**Comment by xunzhang** [comment]
not yet, welcome PR and discussion

**Comment by dseddah** [comment]
would be cool to have a mac's mlx  port one of those days :)
