### ISSUE TITLE
asynchronous or synchronous parallelism?

### ISSUE THREAD

**Issue by anglil** [clab/dynet#407]
Hi, does dynet support training with multiple GPUs now? If so, does it do parallelism in an asynchronous or synchronous manner? Thanks!

**Comment by neubig** [comment]
No, multi-device is not supported yet. Multi-processer is supported however: take a look at mp.h, mp.cc, and the corresponding examples.
We're working on multi-device support and it should be ready in the near future: https://github.com/clab/dynet/issues/92
