### ISSUE TITLE
"import dynet" only works in dynet/build/python 

### ISSUE THREAD

**Issue by anglil** [clab/dynet#411]
Hi I'm following http://dynet.readthedocs.io/en/latest/python.html to add python support to dynet. 
"cmake" and "make" succeeded with DPYTHON properly set. I've also run "python setup.py install", which also succeeded. However, as noted in the title, "import dynet" only works in the directory "dynet/build/python", out of which the import won't work. My python is from anaconda. What should I do to make "import dynet" work system-wide?
Thanks!

**Comment by vicmak** [comment]
Try to the the directory under **external libraries** at your IDE. I added this to external libraries tree in PyCharm ,and it works.

**Comment by anglil** [comment]
I'm sorry - could you elaborate on "to the directory under external libraries at your IDE"? I'm just doing everything in vim. Thanks very much!
-Angli

**Comment by vicmak** [comment]
1) I suggest that unless you are a "code-master" you develop the program in your favourite IDE. For example PyCharm. These IDEs commonly have a GUI based structure where you can organize all the libraries you use in your code.
 When you wish to run the code on some server where you have only ssh connection and vim, run from the directory on the server where dynet is installed.
2) Try to use the Dynet-Users group (maybe it is a more suitable place for this question) to ask: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/dynet-users

**Comment by anglil** [comment]
Thanks for suggesting the user group, Victor.

**Comment by neubig** [comment]
Asking questions about problems with DyNet here is fine too. But actually, if you're using anaconda, `python setup.py install` should allow DyNet to work from any directory whenever you have that Anaconda module loaded. Did you do compilation and install all with your Anaconda environment active? If you did compilation and install with the environment active, then tried to run it without Anaconda active, for example, that could cause problems.

**Comment by anglil** [comment]
Hi Graham, dynet python binding has been installed to the system python which is python 2.7. I wonder why that is? I already set -DPYTHON to the anaconda python, and also it's prioritized over the system python in $PATH. Nevertheless, when running `python setup.py install` I still saw messages that indicate that the binding is being installed to the system python.. Thanks!

**Comment by neubig** [comment]
Hi @anglil, I'm not sure why this is happening, as it's never happened to me. So unfortunately I can't be of much help. If you figure it out, it'd be great if you could post an explanation or pull request though.

**Comment by anglil** [comment]
OK, the way I got it to work in another directory with anaconda python (3.6; default) is to insert `build/python` to the sys directory (similar to what @vicmak did in pyCharm I guess) despite the fact that `python setup.py install` only got the python binding to work with system python (2.7).

**Comment by neubig** [comment]
Thanks for the explanation! I'm going to close this as this work-around will work for now (but people will hopefully be able to find this through Google for posterity). We're hoping to get DyNet installable through pip soon, which may make these problems less of an issue.
