### ISSUE TITLE
undefined reference to boost::archive::archive_exception

### ISSUE THREAD

**Issue by attardi** [clab/dynet#413]
Building on ubuntu 14, gcc 4.8.4, boost 1.54, the make step fails with:

Linking CXX executable test-dynet
../dynet/libgdynet.so: undefined reference to `boost::archive::archive_exception::archive_exception(boost::archive::archive_exception const&)'
collect2: error: ld returned 1 exit status

Someone suggests that the -lboost_serialization might be needed.

**Comment by neubig** [comment]
Sorry about this! I'm not sure the work-around at the moment, but we're currently working hard on getting rid of the dependency on boost, which should resolve this problem.

**Comment by neubig** [comment]
Should be fixed by https://github.com/clab/dynet/pull/637
