### ISSUE TITLE
Multiple instances of same word in the distribution of RNNLM

### ISSUE THREAD

**Issue by vicmak** [clab/dynet#415]
Hello,

I would be very grateful for a help with some strange issue, or bug, I encounter when I use the RNNLM, exactly as it appears at the python examples.
Specifically the problem is that I get the same word several (!) times in the distribution that is received from predict_next_word function.
What I am doing wrong?

I extract the most probable words in the following way:

distribution = predict_next_word(isent).npvalue()
for i in range(0,n):

    max_index = np.argmax(distribution)
    prediction = vocab.w2i.keys()[vocab.w2i.values().index(max_index)]
    distribution = np.delete(distribution, max_index)

for example for some LM i've trained on large conference proceeding corpus, and the following sentence prefix : "our results show that the deployment strategy that is" 
the top predictions are: "used,used,ment,but,m,smoothness,the,convex,platform,uncertainties,models,models,written,written,..."

Thank anyone a lot for the help!

Victor

**Comment by pmichel31415** [comment]
When you use np.delete it reduces the size of the `distribution` vector so the next argmax doesn't correspond to the index of a word.

Maybe you should use `np.argsort(distribution)[:-n]` instead

**Comment by vicmak** [comment]
Thank you so much @pmichel31415 !
