### ISSUE TITLE
Are tensor operations safe to use ?

### ISSUE THREAD

**Issue by FilippoC** [clab/dynet#416]
Hello,

the documentation section "Tensor operations" is empty : http://dynet.readthedocs.io/en/latest/operations.html#tensor-operations
However, they do appear in the code with description in comments : https://github.com/clab/dynet/blob/master/dynet/expr.h#L1569

Is it safe to use them ?
Thanks.

**Comment by pmichel31415** [comment]
Hi,

FWIW they pass unit tests here : https://github.com/clab/dynet/blob/master/tests/test-nodes.cc#L385-L405

Can't comment about speed though

**Comment by neubig** [comment]
Yes, they are safe to use. They need documentation though.

**Comment by FilippoC** [comment]
Nice, thanks for the answer !
