### ISSUE TITLE
Mul NotImplementedError?

### ISSUE THREAD

**Issue by talbaumel** [clab/dynet#421]
Installed latest version on a new machine (ubuntu, gpu, python3)
Got error when trying to multiple <class '_dynet.Parameters'> and <class '_dynet.Expression'>

_dynet.pyx in _dynet.Expression.__mul__ (_dynet.cpp:25878)()

NotImplementedError: 

Code works on older version (mac, cpu, python3)

**Comment by pmichel31415** [comment]
Are you sure you have loaded the parameter in the computation graph (using `dy.parameter`) for instance?

Otherwise do you have a minimal reproducable example?

**Comment by talbaumel** [comment]
My bad
