### ISSUE TITLE
Need a channel-wise operation to get average from a mini-batch

### ISSUE THREAD

**Issue by sunalbert** [clab/dynet#425]
A channel-wise or depth-wise average operation is useful in some scenarios such as batch normalization. I find a similar operation called Average. But it seems that the Average operation does not meet expectation.  Is a new pull request about channel-wise average welcome?

**Comment by neubig** [comment]
Sure, but DyNet has no concept of "Channel", only "Dimension". There is already the `sum_dim` operation, which you could modify to calculate the average.

**Comment by pmichel31415** [comment]
I think this was solved with the introduction of mean_dim/mean_batches
