### ISSUE TITLE
Error in Scala serialization test

### ISSUE THREAD

**Issue by jflanigan** [clab/dynet#426]
When building the Scala bindings, I got an error during the SerializationSpec at the test "model saver and model loader" should "handle byte[] correctly".  Here's the full error log:

[info] SerializationSpec:
[info] dynet
[info] - should create models with the right number of parameters
[info] model saver and model loader
[info] - should handle simplernnbuilder correctly
[info] model saver and model loader
[info] - should handle vanillalstmbuilder correctly
[info] model saver and model loader
[info] - should handle lstmbuilder correctly
[info] model saver and model loader
/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java: symbol lookup error: /tmp/dynet7486893757265447650: undefined symbol: _ZN5boost13serialization10make_arrayImEEKNS0_13array_wr
apperIcEEPcT_
Exception in thread "Thread-6" java.io.EOFException
        at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:2598)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1318)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
        at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1$React.react(Framework.scala:798)
        at org.scalatest.tools.Framework$ScalaTestRunner$Skeleton$1.run(Framework.scala:787)
        at java.lang.Thread.run(Thread.java:744)
[info] Run completed in 3 seconds, 543 milliseconds.
[info] Total number of tests run: 8
[info] Suites: completed 3, aborted 0
[info] Tests: succeeded 8, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[error] Error during tests:
[error]         Running java with options -classpath /disk2/work/dynet/dynet-2017.04.04/build/contrib/swig/target/scala-2.11/test-classes:/disk2/work/dynet/dynet-2017.04.04/
build/contrib/swig/target/scala-2.11/classes:/disk2/work/dynet/dynet-2017.04.04/build/contrib/swig/libdynet_swig.so:/disk2/work/dynet/dynet-2017.04.04/build/contrib/swig/dyn
et_swigJNI_dylib.jar:/disk2/work/dynet/dynet-2017.04.04/build/contrib/swig/dynet_swigJNI.jar:/home/jmflanig/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.
8.jar:/home/jmflanig/.ivy2/cache/org.scalatest/scalatest_2.11/bundles/scalatest_2.11-3.0.0.jar:/home/jmflanig/.ivy2/cache/org.scalactic/scalactic_2.11/bundles/scalactic_2.11
-3.0.0.jar:/home/jmflanig/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.8.jar:/home/jmflanig/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/sca
la-xml_2.11-1.0.5.jar:/home/jmflanig/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.4.jar:/home/jmflanig/.sbt/boo
t/scala-2.10.6/org.scala-sbt/sbt/0.13.13/test-agent-0.13.13.jar:/home/jmflanig/.sbt/boot/scala-2.10.6/org.scala-sbt/sbt/0.13.13/test-interface-1.0.jar sbt.ForkMain 54086 fai
led with exit code 127
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful 
[error] Total time: 5 s, completed Apr 5, 2017 12:30:27 AM
make[2]: *** [contrib/swig/scala_helper_uberjar] Error 1
make[1]: *** [contrib/swig/CMakeFiles/scala_helper.dir/all] Error 2
make: *** [all] Error 2

It's difficult to follow the error log, since it says "All tests passed", even though one test appears to have had an error.  However, disabling the SerializationSpec tests allows the bindings to be built properly.  My guess at the failing test (based on where the error first occurs), is "model saver and model loader" should "handle byte[] correctly".

**Comment by neubig** [comment]
Any ideas @joelgrus ?

**Comment by joelgrus** [comment]
let me look into it. from the error message, it seems like maybe the `dynet_swig.i` needs to include

`<boost/serialization/array.hpp>`

but if that's the problem I can't imagine why it would have ever worked.

**Comment by joelgrus** [comment]
still looking into this, and at the same time trying to figure out how to keep the code in sync. it looks like recently `RmsPropTrainer` got renamed to `RMSPropTrainer`, so I need to update the bindings for that before this will even compile.

Let me pull together a PR to fix that, and then after that I'll dig deeper into this issue.

**Comment by joelgrus** [comment]
sorry, that was an early thought, now that I know the issue I wouldn't expect that to fix it.

in the short term, I think the only way to fix it is to use Boost 1.59 or earlier (or to remove that binding, as you did).

in the longer term I need to figure out how to modify the bindings to work correctly both with old boost and new boost.

**Comment by neubig** [comment]
@joelgrus We're going to hopefully be getting rid of boost altogether very soon, once the new save/load interface is done, e.g.: https://github.com/clab/dynet/pull/435

Hopefully this will resolve the problem.

**Comment by neubig** [comment]
Here is the upstream issue: https://github.com/clab/dynet/issues/84

**Comment by neubig** [comment]
This should be fixed by https://github.com/clab/dynet/pull/637
