### ISSUE TITLE
replicate a ComputationGraph

### ISSUE THREAD

**Issue by anglil** [clab/dynet#437]
Is it possible to replicate everything in a ComputationGraph to a copy, modify this ComputationGraph for other use, and afterwards copy the replica back to this ComputationGraph?
The motivation for doing this is that when I created two ComputationGraphs, I go the following error 
"Memory allocator assumes only a single ComputationGraph at a time"
"Attempted to create >1 CG"
So it seems that the natural thing to do is somehow save the existing graph somewhere while computing using another graph, and come back to the existing graph after the job with another graph is done. (The two graphs ought to operate on the same instance.)

**Comment by neubig** [comment]
I'm not sure exactly what you're trying to do, but would the `cg.checkpoint()` and `cg.revert()` functionality work for this? `cg.checkpoint()` allows you to save a checkpoint of what the current computation graph looks like at this point, and `cg.revert()` allows you to rewind back to the checkpoint, throwing out any additional computation that occurred beyond it.s

**Comment by anglil** [comment]
Thanks. The checkpoint mechanism should work for me.
