### ISSUE TITLE
error : replace LSTMBuilder with GRUBuilder in example EncDec and 'MatrixMultiply' error occur

### ISSUE THREAD

**Issue by xc-kiwiberry** [clab/dynet#439]
I'm learning dynet by examples ~ I replace LSTMBuilder with GRUBuilder in examples/cpp/EncDec.cc and add #include "dynet/gru.h" and compile is successful but an error occur in runtime:

`terminate called after throwing an instance of 'std::invalid_argument'
  what():  Mismatched input dimensions in MatrixMultiply: [{8,16} {8}]`

Apparently it is a error about dimensions Mismatch in MatrixMultiply, but i just think that i can replace any RNNBuilder by another RNNBuilder, because they have the same interface. I'm sure i just replace LSTMBuilder with GRUBuilder and add #include "dynet/gru.h". 
Could you please point out my mistake? Thank everyone sincerely! :)

**Comment by pmichel31415** [comment]
Hi by the look of it it seems that the encoder decoder expects an LSTM because it assumes the hidden state will be of size `2 * hidden_dim` (with `h` and `c`)

This is not your mistake then.

The bug should go away if you either

- Set bidirectional to false
- Replace these lines
        if (bidirectional) {
            rev_enc_builder = Builder(LAYERS, INPUT_DIM, HIDDEN_DIM, model);
            p_ie2oe = model.add_parameters({unsigned(HIDDEN_DIM * LAYERS * 2),
                                            unsigned(HIDDEN_DIM * LAYERS * 4)
                                           });
            p_boe = model.add_parameters({unsigned(HIDDEN_DIM * LAYERS * 2)});
        }

by 

        if (bidirectional) {
            rev_enc_builder = Builder(LAYERS, INPUT_DIM, HIDDEN_DIM, model);
            p_ie2oe = model.add_parameters({unsigned(HIDDEN_DIM * LAYERS ),
                                            unsigned(HIDDEN_DIM * LAYERS * 2)
                                           });
            p_boe = model.add_parameters({unsigned(HIDDEN_DIM * LAYERS)});
        }

in the constructor in `encdec.h`

Of course a long term solution would be preferable

**Comment by xc-kiwiberry** [comment]
Thank you for your comment!~
emm...I tried both of your suggestion just now. And it seems like occur another error : 
`Parameters will be written to: encdec_lm_1_2_4.params
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Bad input dimensions or range in PickRange: [{4}] range(4, 8)`
thank you anyway.

**Comment by xc-kiwiberry** [comment]
maybe i should change the pickrange in decode and generate too, because of the 2 * hidden_dim.

**Comment by pmichel31415** [comment]
Hi sorry I haven't had a lot of time to look into this, did the pickrange change solve the problem?

**Comment by xc-kiwiberry** [comment]
yes！It runs successfully~ After understand the difference between final_s() of GRU and final_s() of LSTM，things become easy，thank u very much~
