### ISSUE TITLE
Convolution doc is_valid is difficult to understand

### ISSUE THREAD

**Issue by neubig** [clab/dynet#456]
The doc for the is_valid parameter here is difficult to understand. Could we explain it more clearly? https://github.com/clab/dynet/blob/master/dynet/expr.h#L1618

**Comment by zhisbug** [comment]
Assume:
- Input feature maps: XH x XW x XC x N
- Filters: FH x FW x XC x FC 
- Strides: strides[0] and strides[1] are row (h) and col (w) stride, respectively.

For the **SAME** convolution:  the output height (YH) and width (YW) are computed as:

- YH = ceil(float(H) / float(strides[0]))
- YW  = ceil(float(W) / float(strides[1]))

and the paddings are computed as:

- pad_along_height = max((YH - 1) * strides[0] + FH - XH, 0)
- pad_along_width = max((YW - 1) * strides[1] + FW - XW, 0)
- pad_top = pad_along_height / 2
- pad_bottom = pad_along_height - pad_top
- pad_left = pad_along_width / 2
- pad_right = pad_along_width - pad_left


For the **VALID** convolution:  the output height (YH) and width (YW) are computed as:

- YH = ceil(float(XH - FH + 1) / float(strides[0]))
- YW  = ceil(float(XW - FW + 1) / float(strides[1]))

and the paddings are always zeros.

Think about when stride is 1, the distinction:

**SAME**: output size is the same with input size. To do so, one needs to pad the input so the filter can sweep outside of the input maps
**VALID**: output size shrinks by filter_size - 1, and the filters always sweep at valid positions inside the input maps. No padding needed.

**Comment by neubig** [comment]
Thanks! This is awesome. Could we add something to this effect to the doc?

**Comment by zhisbug** [comment]
@neubig Sure, let me file a PR to update the documents.

**Comment by pmichel31415** [comment]
Hi @zhisbug can you also update the python doc [here](https://github.com/clab/dynet/blob/master/python/_dynet.pyx#L1934) and [here](https://github.com/clab/dynet/blob/master/python/_dynet.pyx#L1953)

thanks!

**Comment by zhisbug** [comment]
We can close this issue now as the documents have been fixed.
