### ISSUE TITLE
KMaxPooling mini-batch support

### ISSUE THREAD

**Issue by gth879w** [clab/dynet#457]
Is it right that kmax_pooling() doesn't support mini batching?
https://github.com/clab/dynet/blob/master/dynet/nodes-conv.cc#L349

If so, is it possible to add such support? In light of #388, batching in k-max pooling will be very useful. Thank you.

**Comment by neubig** [comment]
Yes, this should definitely be added. This is also related to this:
https://github.com/clab/dynet/issues/158

**Comment by gth879w** [comment]
For k=1, I noticed that max_dim(), which supports batching, was recently introduced. This is helpful. Thanks!

**Comment by neubig** [comment]
Resolved by #457, although GPU support for kmax is still pending (#245)
