### ISSUE TITLE
conv2d failed assertion when input size is smaller than filter size even with "SAME" strategy

### ISSUE THREAD

**Issue by ccsasuke** [clab/dynet#459]
It seems there is an assertion in conv2d that fails when input size is smaller than filter size even with "SAME" convolution.

  if (xs[0].ndims() != 3 || xs[1].ndims() != 4 ||
      xs[1].d[2] != xs[0].d[2] || xs[0].d[0] < xs[1].d[0] ||
      xs[0].d[1] < xs[1].d[1]) {
    ostringstream s; s << "Bad input dimensions in Conv2D: " << xs;
    throw std::invalid_argument(s.str());
  }

This fails in 1d convolution for very short sentences (shorter than the filter size).

**Comment by neubig** [comment]
Fixed by #460
