### ISSUE TITLE
How can I get absolute value of Tensor?

### ISSUE THREAD

**Issue by speedcell4** [clab/dynet#462]
How can I get absolute value like this `abs([[1,-2],[3,-4]])` => `[[1,2],[3,4]]`

**Comment by neubig** [comment]
Actually, surprisingly we don't have this yet, but we should. If someone wants to help add this, see the coding tips here: http://dynet.readthedocs.io/en/latest/code_style.html#coding-tips

about how to add new operations.

**Comment by neubig** [comment]
This was fixed by: https://github.com/clab/dynet/pull/463
