### ISSUE TITLE
Easier-to-understand naming for LSTMBuilder

### ISSUE THREAD

**Issue by neubig** [clab/dynet#474]
LSTMBuilder currently represents a relatively unorthodox implementation of LSTMs using coupled input and forget gates: http://dynet.readthedocs.io/en/latest/unorthodox.html#lstm-implementation

I think very few people will realize this, and this could have a significant impact on results (for example, the DyNet LSTMBuilder will never have a cell state with abs(c)>1, but vanilla LSTMs can). It'd probably be best to have the basic LSTMBuilder represent something that looks more like what people expect, so I propose the following change:

* Rename LSTMBuilder to CoupledLSTMBuilder
* Make LSTMBuilder a typedef for VanillaLSTMBuilder

If there aren't any objections, maybe we'll do this in the upcoming 1.1 release: https://github.com/clab/dynet/projects

**Comment by vicmak** [comment]
Can you please please please elaborate a little more?
So, is it correct to say that the only difference in DyNet LSTMBuilder implementation, is the equation of the forget gate, that becomes: f_t = 1 - i_t ? And the rest equations remain the same ?

More specifically, is there a place where I can see a documentation of the exact equations that are used by LSTMBuilder ? (Except for code in cpp)

Thanks a lot!

**Comment by roeeaharoni** [comment]
You can see the equations here:
https://github.com/clab/dynet/issues/154

**Comment by vicmak** [comment]
**Thanks** @roeeaharoni !

However,  from these equations I fail to understand, how is there one gate to control _forget_ and _input_ , as CIFG is described here: https://arxiv.org/pdf/1503.04069.pdf
All the gates are still computed with their parameters W and non-linear transformations. Confused.

**Comment by pmichel31415** [comment]
@neubig I agree.

Also another quirk of the current LSTMBuilder is that since `-1 < c_t < 1`, `-tanh(1) < h_t < tanh(1)`.

Probably not a big problem though since a subsequent linear layer would take care of scale issues

**Comment by neubig** [comment]
Fixed by #637
