### ISSUE TITLE
Access to Input Gradients?

### ISSUE THREAD

**Issue by ccsasuke** [clab/dynet#476]
Hi,

I'm new to DyNet and I'm wondering whether it is possible to get the gradients w.r.t. some input (or intermediate) X?
The only API I found was to get the gradients w.r.t. parameters.

**Comment by neubig** [comment]
Are you using the Python API, or C++? In C++ I believe you can get it with `expr.value().g`, but I'm not sure if this works in Python.

**Comment by ccsasuke** [comment]
Thanks for the reply. I'm using the Python API. Is there a way to expose this C++ API to Python?

**Comment by pmichel31415** [comment]
@neubig I don't think this works in c++ because `expr.value()` is a tensor. It would require some tweaking in `exec.h` to write a `get_gradient` function but ~~I believe it should be pretty straightforward~~ we'll see.

Opening it up to python would be easy though.

I can try to do that tomorrow

**Comment by pmichel31415** [comment]
Solved by #484
