### ISSUE TITLE
Changes to dynet.concatenate_cols break previously working code

### ISSUE THREAD

**Issue by tjppires** [clab/dynet#491]
Hi!

Commit 4ca75ed8a3395d247b52cd77871a4dfc6bafc801 made some changes to how dynet.concatenate_cols works. Before, I could concatenate a minibatch of vectors (n rows, 1 column, b = batch_size) with a minibatch of matrices (n rows, m columns, b = batch_size). After this commit, however, this does not work anymore and I get an error: "Out of bounds exception in Dim::set".

Was this intended? If yes, how can I do the same as before, but without getting this error?

**Comment by neubig** [comment]
Sorry about the bug! This was definitely not intended, so I'll try to fix this ASAP.

**Comment by tjppires** [comment]
Thanks! :)

**Comment by neubig** [comment]
Fixed by #492
