### ISSUE TITLE
pip Integration

### ISSUE THREAD

**Issue by neubig** [clab/dynet#496]
It would be really nice to be able to install DyNet through pip. Currently we are working on removing the dependency on Boost, which will make this easier, and are almost done: https://github.com/clab/dynet/issues/84

If there is anyone in the community who is familiar with setting up the pip build system, @xunzhang and I would greatly appreciate your help in getting DyNet set up with it.

**Comment by pmichel31415** [comment]
Maybe we could ask on twitter/reddit to reach a broader audience if there is no answer?

**Comment by neubig** [comment]
Yeah, I'll send something to the DyNet mailing list as well in a bit.
