### ISSUE TITLE
cuDNN cannot be found by CMake

### ISSUE THREAD

**Issue by jeanm** [clab/dynet#509]
I noticed CMake was consistently failing to find cuDNN for me, even though all other CUDA libraries and include files (which are located in the same places) are found.

From a quick skim of `CMakeLists.txt`, it seems that on [line 155](https://github.com/clab/dynet/blob/91431dc16e2844e090f45b4ddb367dd9286b9964/CMakeLists.txt#L155) it is checking whether the `CUDNN_ROOT` variable is set, and if it is it proceeds to call the `find_cudnn()` function.  I don't really understand the `CMakeLists.txt` format, but if I am reading it correctly then `CUDNN_ROOT` is only ever set inside `find_cudnn()`, so the `if` on line 155 has no chance of succeeding.

Setting `CUDNN_ROOT` manually solves the problem for me.

**Comment by neubig** [comment]
Any ideas, @zhisbug ?

**Comment by zhisbug** [comment]
please refer to issue #488
