### ISSUE TITLE
`_RNNBuilder` does not support multiple initial_states in ONE computational graph.

### ISSUE THREAD

**Issue by jcyk** [clab/dynet#511]
Now initial_state is considered as the member variable (`_init_state` ) of  `_RNNBuilder` instances, which means that only one initial state could be used in one computational graph using the same RNNBuilder. 
 `_init_state`  is declared [here](https://github.com/clab/dynet/blob/master/python/_dynet.pyx#L3212), used [here](https://github.com/clab/dynet/blob/master/python/_dynet.pyx#L3334) and [here](https://github.com/clab/dynet/blob/master/python/_dynet.pyx#L3357).

But what if we want to model two different sentences using the same RNN simultaneously but conditioned on different situations (initial states)?

Here is my idea.
1. Remove `_init_state` from `_RNNBuilder` as its member variable, 
2. Let the functional `initial_state` be a simple function to produce a specified or unspecified `RNNState` whose shape matches the RNNBuilder

**Comment by neubig** [comment]
I agree that we should probably fix this. Actually (IMHO), the RNN interface in Python is nicer than the interface in the upstream C++ library, so we should probably fix the C++ library as well. Basically the C++ library maintains state internally in RNNBuilder, but it would be nice if the `add_input` function took a state is input and returned the modified state as output.

**Comment by neubig** [comment]
This is also related to this: https://github.com/clab/dynet/issues/226

**Comment by pcyin** [comment]
I was super lucky enough to catch this issue in my code :)

**Comment by jcyk** [comment]
🤝It is no easy to find out if you don’t look at the result closely.

I tried my idea posted earlier ( actually just a few lines of modification
) and it works fine with python.

I didn’t pull a request because it is kind of tricky and only easy for
python.

**Comment by pcyin** [comment]
Would this suffice?

```
init_state = rnn_builder.initial_state().set_s((cell_0, hidden_0))
# use init_state afterwards.
```

**Comment by neubig** [comment]
Actually, I guess this is not an enhancement, but a bug, as it gives hard-to-understand errors when you try to do it otherwise. This should definitely be fixed.

**Comment by neubig** [comment]
Fixed by https://github.com/clab/dynet/pull/1228
