### ISSUE TITLE
Can't compile with CUDNN support

### ISSUE THREAD

**Issue by alexanderkoller** [clab/dynet#517]
Hi,

I can compile DyNet on my system (Ubuntu 16.04, current CUDA 8.0 and CUDNN 6) just fine, but when I try to compile with CUDNN support, "make" aborts with the following error message:

```
[ 24%] Building NVCC (Device) object dynet/CMakeFiles/gdynet.dir/gdynet_generated_cudnn-ops.cu.o
/tmp/dynet/dynet/cudnn-ops.cu(107): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_00005763_00000000-15_cudnn-ops.compute_52.cpp1.ii".
CMake Error at gdynet_generated_cudnn-ops.cu.o.cmake:262 (message):
  Error generating file
  /tmp/dynet/build/dynet/CMakeFiles/gdynet.dir//./gdynet_generated_cudnn-ops.cu.o


dynet/CMakeFiles/gdynet.dir/build.make:1107: recipe for target 'dynet/CMakeFiles/gdynet.dir/gdynet_generated_cudnn-ops.cu.o' failed
make[2]: *** [dynet/CMakeFiles/gdynet.dir/gdynet_generated_cudnn-ops.cu.o] Error 1
CMakeFiles/Makefile2:124: recipe for target 'dynet/CMakeFiles/gdynet.dir/all' failed
make[1]: *** [dynet/CMakeFiles/gdynet.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

Can someone help me figure out what's going on, or (if it's a bug) fix it? 

Thanks!

Best,
Alexander.

**Comment by zhisbug** [comment]
@alexanderkoller Could you use cuDNN 5.1 instead? cuDNN 6.0 was recently released and we are working on supporting it.

**Comment by alexanderkoller** [comment]
With cuDNN 5.1 it works. Thanks!

**Comment by pmichel31415** [comment]
I think there should be an option in cmake to disable cudnn without disabling all of cuda, it can happen that cuda is the right version but not cudnn and that the user isn't able to change the cudnn version directly (eg on a cluster)

For now the only option is to comment out https://github.com/clab/dynet/blob/master/CMakeLists.txt#L155

**Comment by neubig** [comment]
This might be fixed with this pull request:
https://github.com/clab/dynet/pull/554

Could someone please confirm?

**Comment by socaty** [comment]
@neubig I still can't complie successfully.
 With the following error message:
`[ 68%] Building CXX object dynet/CMakeFiles/gdynet.dir/weight-decay.cc.o
[ 69%] Building CXX object dynet/CMakeFiles/gdynet.dir/cuda.cc.o
Linking CXX shared library libgdynet.so
/usr/bin/ld:/usr/local/cuda/lib64/libcudnn.so: file format not recognized; treating as linker script
/usr/bin/ld:/usr/local/cuda/lib64/libcudnn.so:1: syntax error
collect2: error: ld returned 1 exit status
make[2]: *** [dynet/libgdynet.so] Error 1
make[1]: *** [dynet/CMakeFiles/gdynet.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by neubig** [comment]
Thanks @socaty , this looks like a different problem though...
Could you please tell me about your environment? What version of what compiler you're using, and what version of cudnn?

**Comment by socaty** [comment]
@neubig  
With Ubuntu 14.04.5 LTS (GNU/Linux 3.16.0-77-generic x86_64)   CUDA 8.0.61 
But I do not know what version of cudnn, because our server has both libcudnn.so.5 and libcudnn.so.6. I don't it choose which one,CUDNN 5 or CUDNN 6?

**Comment by zhisbug** [comment]
@socaty we currently support CUDNN5.1, could you try to put cudnn5.1 in a standalone folder and pass the directory to CMAKE using -CUDNN_ROOT=/path/to/cudnn5.1?

**Comment by socaty** [comment]
@zhisbug OK,let me try.
Thanks!

**Comment by socaty** [comment]
Compiled successfully! Thanks! @zhisbug @neubig

**Comment by neubig** [comment]
Glad to hear, @socaty !
