### ISSUE TITLE
1d convulsions with multiple channels

### ISSUE THREAD

**Issue by talbaumel** [clab/dynet#519]
Hi, is it possible to support multiple channels when using 'conv1d_wide' or 'conv1d_narrow'?

Also, since the input of the convolution layer is usually a list of embedding, wouldn't it be better if the 1st argument would be a list of vectors instead of a matrix?

Thanks! Tal

**Comment by pmichel31415** [comment]
Hmm so conv1D ops got deprecated .

The good news is that now we have conv2d on cudnn and you can use it to do conv1d (with several channels).

We'd probably have to code a specific conv1d expression but here's how I do it with conv2d.

Assuming my batch of sentences (of the same length L) are concatenated into a big `M` of shape `(L, D)` (where `D` is the word embedding dimension (the channel dimension if you want), I do

    # Reshape the matrix into a "1D image"
    (l, d), _ = M.dim()
    M = dy.reshape(M, (1, l, d))
    # Do the convolution
    y = dy.conv2d(M, K, [1, 1], is_valid=False)
    # Reshape back into a matrix (if you don't need to do more convolutions)
    z = dy.reshape(y, (L, D))

Where

    K = model.add_parameters((1, kernel_width, D, number_of_kernels))

Are the kernels.

This should also be pretty fast if you have cudnn.

Hope that helps

**Comment by neubig** [comment]
Isn't the easier way to do:
`y = dy.conv2d(M, K, [1,1] is_valid=True)`

Where M is a `{d, l}` matrix, and K is a `{d, w, 1, f}` Tensor, where `w` is the convolution width and `f` is the number of filters? I believe this will be equivalent to `conv1d_narrow`. To get `conv1d_wide` behavior, you can pad the left and right sides of the input matrix `M` with `w-1` zero vectors.

**Comment by talbaumel** [comment]
Thanks for the quick response!!

Didn't had a test yet, but is there a way to use lists as input and output?
It will enable to seamlessly switch between rnns and convs

**Comment by talbaumel** [comment]
Thanks! That's great

**Comment by pmichel31415** [comment]
@neubig Yes, I think my method is just easier if you want to stack a lot of `conv_wide` ops because you only have to reshape at the beginning and the end instead of padding at each layer.

**Comment by yoavg** [comment]
is there any objection to wrapping this in a python op that will take a list and do the concat and select_cols internally?

also, I think we can have an efficient implementation of `concatenate_cols` that will not do a copy if the list of expressions to concatenate are already contiguous in memory, and we can have the splitting-back-into-expressions keep them contiguous in memory. this way we will not have a big overhead for the to-and-from-list back and forth.

**Comment by talbaumel** [comment]
I'm getting: ValueError: Bad input dimensions in Conv2D: [{10,4}
{10,3,1,30}]10 is embedding size
4 is sequence length
3 is filter length
1 is 1
30 is number of filters

y = dy.conv2d(M, f, [1,1], is_valid=True)

**Comment by talbaumel** [comment]
I'm getting the same error for sizes:
[{4, 10} {10,3,1,30}],
[{1, 10,4} {10,3,1,30}],
[{1, 4,10} {10,3,1,30}]

Any help or reference would be greatly appreciated

**Comment by pmichel31415** [comment]
Have you tried {10,4,1} ? Maybe conv2d requires a 3d tensor even if the channel size is 1 (in which case it should be fixed)

**Comment by talbaumel** [comment]
Didn't work
I know that in torch it(number of channels, image height, image width)

**Comment by pmichel31415** [comment]
What error does it give you for `[{10,4,1}, {10,3,1,30}]`? 

According to the code [here](https://github.com/clab/dynet/blob/master/dynet/nodes-conv2d.cc#L39-L43) it shouldn't give you the `ValueError: Bad input dimensions in Conv2D:` error

**Comment by talbaumel** [comment]
I used different size filter
Assumed it's:
(kernel hieght = 1, kernel_width = 3, embedding size = 4, number_of_kernels = 30)

**Comment by neubig** [comment]
Is this issue resolved? Or are you still stuck. I think the dimensions that @pmichel31415 suggested should work.

**Comment by talbaumel** [comment]
Yes it worked for:
input size = (10, 4, 1)
filter size = (10, 3, 1, 30)

Thanks!

Any documentation for `SelectCols`?
For `dy.select_cols(y, [0])` got:
`ValueError: Bad arguments in SelectCols: [{10,4,30}]`

**Comment by neubig** [comment]
Sorry about being so slow on this, but I've opened a new issue about `select_cols`: https://github.com/clab/dynet/issues/823

I'll close this one as the core issue is resolved.
