### ISSUE TITLE
File structure refactoring

### ISSUE THREAD

**Issue by neubig** [clab/dynet#522]
Currently compiling DyNet takes a long time for a couple of reasons:
* Inclusion of header files is not clean, and header files are included when not necessary in a number of places.
* `nodes.cc` is a super-huge file that implements virtually all operations.

I think we should refactor the file structure so that

- [x] `nodes.cc` is split into a finer-grained divisions, perhaps similar to the doc: http://dynet.readthedocs.io/en/latest/operations.html
- [x] `nodes-common.cc` is removed, with all the functionality being moved to the appropriate files from the previous bullet point. This will make sure that the code implementing a particular node will all be in the same file.
- [ ] All header file includes that are not necessary are removed.
- [ ] Other files that have lots of different classes implemented (e.g. `dynet.h` have the functionality split into different files named after the classes so that they're easier to find (e.g. `computation-graph.h` and `node.h`)

**Comment by pmichel31415** [comment]
Would it also be a good opportunity to separate the files in different subfolders? Like all the builders in one folder, all the nodes in another, etc...

Would make it easier to navigate the source code.

Also (but maybe this is a separate issue) we should probably split `_dynet.pyx` in several files as well.

**Comment by neubig** [comment]
This is basically done.
