### ISSUE TITLE
Out of memory error in conv2d

### ISSUE THREAD

**Issue by pmichel31415** [clab/dynet#528]
When using conv2d on large matrices I get this error

    terminate called after throwing an instance of 'std::runtime_error'
    what():  aux_mem_pool allocate memory failed: exceed maximally allowed size

aren't dynamic memory pools supposed to take care of these errors?

**Comment by zhisbug** [comment]
Looks like you are allocating more memory than an upper bound predefined by this function https://github.com/clab/dynet/blob/master/dynet/nodes-conv2d.cc#L70

Could you try to modify this function to increase the aux_storage_size() for conv2d and try again?

**Comment by jcyk** [comment]
I also encounter this problem.  Say matrices with size `a <b`, I found it very strange that `b` works well, but `a` fails.  There must be a bug? Any idea to fix that?

**Comment by zhisbug** [comment]
As the memory used by conv2d is hard to estimate before the computation, I set an upper bound in its aux_storage_size() function. If you encounter this error, try to increase the upper bound in this function. Later I will figure out a better solution for it.
