### ISSUE TITLE
DyNet needs a cool logo

### ISSUE THREAD

**Issue by neubig** [clab/dynet#535]
Due to my dire lack of graphic design skills, DyNet still doesn't have a nice logo. Someone interested in making one? If you do I'll make stickers and send you the first one

**Comment by wang-chenyu** [comment]
I'd like to contribute. Thanks @zhisbug  for the briefing~ :- )

**Comment by neubig** [comment]
Hi @wang-chenyu , thanks so much for volunteering to help with this! But actually, we already have someone working on this (and almost finished) behind the scenes, so I don't want to waste your time by duplicating work. Sorry, I should have posted something here earlier.
