### ISSUE TITLE
[Help] Forcing a lookup parameter to be zero

### ISSUE THREAD

**Issue by tjppires** [clab/dynet#539]
Hi!

I want to compute the following function:
s = dy.tanh(W*x + A*z + b), where A and W are parameter matrices, x the input vector, b the bias vector and z an embedding vector (obtained from a lookup_parameter)

The thing is that for some training cases, I want z to be a zero vector. I obviously could do it like this:
```
if condition for z being zero:
    z = dy.zeroes(...)
else:
    z = dy.lookup(...)
s = dy.tanh(...)
```
But this hurts performance when working with batches, because I need to have a python loop doing this, instead of using directly the function dy.lookup_batch. Is there a way of "adding" a vector of zeroes to the lookup parameter? That is, I want to force one of the embeddings to always be zero (start zero and no backprop, but just for one embedding). So if E is the lookup parameter, I could do E[0] (or other index) and get the zero vector.

This way I could do the following:
```
indices = [0, 0, ... other non-zero indices]
z = dy.lookup_batch(E, indices)
```
So the first two elements of the batch would be zero and the others would be normal embeddings.

Any ideas?

Edit: another way to do this would be to be able to get a default value from the lookup table (just like with python's dict method .get).

**Comment by neubig** [comment]
There's not an easy way to do this only with lookup parameters, but probably the easiest is to add a mask. This would work by doing something like the following (note the Python syntax might not be exactly correct, but this should give the basic idea):

    indices = [0, 0, x, y ,z]
    mask = [0, 0, 1, 1, 1]
    z = dy.lookup_batch(E, indices)
    m = dy.inputTensor(np.array(mask), batched=True)
    z = cmult(z, m)

Hope this helps!

**Comment by tjppires** [comment]
That seems to do it, at least in the quick tests I made. However, this way I need to use numpy, which doesn't have GPU support, and it may hurt speed. Is there a way of doing it directly in dynet?

**Comment by neubig** [comment]
Cool, glad it worked!

**Comment by liesun1994** [comment]
nice ~
