### ISSUE TITLE
Dropout speed issues

### ISSUE THREAD

**Issue by tjppires** [clab/dynet#542]
Hi there!

I have been experiencing some issues using dropout. The thing is that it makes my system many times slower to train. Before dropout it took ~6h in GPU to run a full epoch. Now, it takes ~24h. That's a 4 fold increase. The only change in my code was do use dropout in the hidden layers of the net. Also, GPU usage is now way down, and a lot of time it actually reaches 0, which didn't happen before.

Any clues?

**Comment by pmichel31415** [comment]
Hmm that is interesting, I certainly never had such slowdown with dropout. Maybe this issue is linked to this one #438 ?

**Comment by tjppires** [comment]
That seems a plausible explanation.

**Comment by pmichel31415** [comment]
I will see if I can address this this week

**Comment by pmichel31415** [comment]
Could you provide some minimal reproducible code so that I can test the changes?

**Comment by tjppires** [comment]
I just used the standard dropout. i.e., something like this:
```
import dynet as dy
...
y_dropped = dy.dropout(y, dropout_prob)
```

**Comment by pmichel31415** [comment]
So upon more discussion, it seems that this problem needs some work upstream in eigen, so it'll probably take more time to fix.

**Comment by tjppires** [comment]
Ok, thanks.
