### ISSUE TITLE
Accessing parameters of LSTMBuilder in Python

### ISSUE THREAD

**Issue by sebastianruder** [clab/dynet#544]
Hey all, thank you for the effort in creating and maintaining this library! I would like to access the parameters of the `LSTMBuilder` in Python in order to place a constraint on them. Is this possible?

**Comment by pmichel31415** [comment]
Yes, see [this](http://dynet.readthedocs.io/en/latest/python_ref.html#dynet.LSTMBuilder.get_parameter_expressions) for instance

**Comment by sebastianruder** [comment]
Thanks a lot for the fast reply! This is great! Just what I was looking for.

**Comment by neubig** [comment]
@pmichel31415 The link is broken here. Would you mind telling me where the best place to look would be? (cc: @pcyin )

**Comment by pmichel31415** [comment]
http://dynet.readthedocs.io/en/latest/python_ref.html#dynet.VanillaLSTMBuilder.get_parameter_expressions

Apparently LSTMBuilder disappeared from the documentation...
