### ISSUE TITLE
Multivariate Gaussian Distribution

### ISSUE THREAD

**Issue by duyvuleo** [clab/dynet#546]
Hi,

I understand that dynet currently supports **univariate** Gaussian/Normal Distribution via TensorTools::randomize_normal(...) or "noise" node. 

I wonder whether it is easy to implement **multivariate** Gaussian/Normal Distribution, something similar to https://github.com/beniz/eigenmvn. 

Thanks!

**Comment by pmichel31415** [comment]
The [random_normal](http://dynet.readthedocs.io/en/latest/operations.html#_CPPv2N5dynet4expr13random_normalER16ComputationGraphRK3Dim) operation allows you to generate multivariate gaussian noise from `N(0,I)`, then you can multiply by a matrix and add a bias to get any multivariate gaussian you want using

`y=Ax+b ~ N(b,A^TA)` if `x ~ N(0,I)`

Would that be sufficient for your needs?

**Comment by duyvuleo** [comment]
That's cool. This is exactly what I wanted.

Thanks Paul.


--
Cheers,
Vu

**Comment by duyvuleo** [comment]
Thanks to Paul.
