### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by weidler** [clab/dynet#548]
**I am getting an CMake Error if I try to cmake with the python bindings:**

-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   program_options
--   regex
--   serialization
-- Boost dir is /usr/include
-- BACKEND not specified, defaulting to eigen.
-- Eigen dir is /home/weidler/dynet-base/eigen
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   unit_test_framework
--   serialization
CMake Error at python/CMakeLists.txt:15 (if):
  if given arguments:

    "VERSION_LESS" "0.23"

  Unknown arguments specified
Call Stack (most recent call first):
  python/CMakeLists.txt:28 (check_cython_version)

-- Configuring incomplete, errors occurred!

**ErrorLog is the following:**

Determining if the pthread_create exist failed with the following output:
Change Dir: /home/weidler/dynet-base/dynet/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec2248776151/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec2248776151.dir/build.make CMakeFiles/cmTryCompileExec2248776151.dir/build
make[1]: Entering directory '/home/weidler/dynet-base/dynet/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/weidler/dynet-base/dynet/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec2248776151.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTryCompileExec2248776151.dir/CheckSymbolExists.c.o   -c /home/weidler/dynet-base/dynet/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTryCompileExec2248776151
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec2248776151.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTryCompileExec2248776151.dir/CheckSymbolExists.c.o  -o cmTryCompileExec2248776151 -rdynamic 
CMakeFiles/cmTryCompileExec2248776151.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTryCompileExec2248776151.dir/build.make:88: recipe for target 'cmTryCompileExec2248776151' failed
make[1]: *** [cmTryCompileExec2248776151] Error 1
make[1]: Leaving directory '/home/weidler/dynet-base/dynet/build/CMakeFiles/CMakeTmp'
Makefile:118: recipe for target 'cmTryCompileExec2248776151/fast' failed
make: *** [cmTryCompileExec2248776151/fast] Error 2

File /home/weidler/dynet-base/dynet/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/weidler/dynet-base/dynet/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTryCompileExec1900330757/fast"
/usr/bin/make -f CMakeFiles/cmTryCompileExec1900330757.dir/build.make CMakeFiles/cmTryCompileExec1900330757.dir/build
make[1]: Entering directory '/home/weidler/dynet-base/dynet/build/CMakeFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /home/weidler/dynet-base/dynet/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec1900330757.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTryCompileExec1900330757.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.0/Modules/CheckFunctionExists.c
Linking C executable cmTryCompileExec1900330757
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec1900330757.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTryCompileExec1900330757.dir/CheckFunctionExists.c.o  -o cmTryCompileExec1900330757 -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTryCompileExec1900330757.dir/build.make:88: recipe for target 'cmTryCompileExec1900330757' failed
make[1]: *** [cmTryCompileExec1900330757] Error 1
make[1]: Leaving directory '/home/weidler/dynet-base/dynet/build/CMakeFiles/CMakeTmp'
Makefile:118: recipe for target 'cmTryCompileExec1900330757/fast' failed
make: *** [cmTryCompileExec1900330757/fast] Error 2

**Comment by TanYufei** [comment]
Have you solved this problem? I get this problem too!!!

**Comment by rubenkruiper** [comment]
I had the same problem. Homebrew wasn't able to install some python dependencies; readline, sqlite, gdbm, openssl. The following worked for me, may be worth having a look at;

> cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update

[https://github.com/homebrew/homebrew-core#update-bug](https://github.com/homebrew/homebrew-core#update-bug)

This may require permission for homebrew to write in usr/local
> sudo chown -R $USER:admin /usr/local/include

https://stackoverflow.com/questions/14527521/brew-doctor-says-warning-usr-local-include-isnt-writable

**Comment by Vyso** [comment]
Hey, did any of Y'all get a solution to the issue?

**Comment by rubenkruiper** [comment]
@Vyso Is the problem that brew won't update? Maybe try:
```
sudo chown -R $(whoami):admin /usr/local
cd $(brew --prefix) && git fetch origin && git reset --hard origin/master
```
[https://github.com/Homebrew/legacy-homebrew/issues/49879#issuecomment-196294820](url)
