### ISSUE TITLE
Error loading saved models (unsupported version)

### ISSUE THREAD

**Issue by irshadbhat** [clab/dynet#552]
Hi there,

I trained some model using dynet in one machine. When I load these models in the same machine, it works fine. But when a copy these models in other machine, I get the following error.

```
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  unsupported version
Aborted (core dumped)
```
Both the machine use the same dynet version (both cloned 5 days ago).

**Comment by miguelballesteros** [comment]
You need to use the same boost version in both machines. 

Miguel

**Comment by pmichel31415** [comment]
Hi, until boost is completely removed from dynet there is a small trick if you don't have the same boost version on both machines : often the difference is only in the first line of the file, where you have something like that : 

    22 serialization::archive 14 1 0

Usually the difference between boost versions will only be in the number after `archive` (here 14) so if you know it for your other machine just edit the file and you should be good to go

**Comment by irshadbhat** [comment]
@pmichel31415 seems an easy workaround. But I already upgraded my boost. Will definitely try this out on some other machine. Thanks for the help.
