### ISSUE TITLE
Autobatch bug for ConstantPlusX (?)

### ISSUE THREAD

**Issue by mattr1** [clab/dynet#555]
I don't have a test case for this, but it appears (to me) that ConstantPlusX::autobatch_sig is incorrectly implemented. It calls s.add_node(c) for the constant "c" being added, but c is a dynet::real whereas add_node assumes an int. If I understand autobatch correctly, this means nodes adding different float values such as 1.1, 1.2, 1.3, would end up all autobatched together and incorrectly add just one of these to all values.

**Comment by yoavg** [comment]
I've confirmed that this is indeed a bug. Thanks for the catch!
I've added a fix as part of PR #556 , which I believe will be merged soon.

**Comment by neubig** [comment]
Fixed by #556
