### ISSUE TITLE
something went wrong when i wanted to use conv2d

### ISSUE THREAD

**Issue by CathyW77** [clab/dynet#558]
Hi,
    Recently, I started to using conv2d.
My input x looks like:
```
      vector<dynet::real> data_x_conv2d(2*3*2*1,-std::numeric_limits<dynet::real>::infinity());
      for(int j=0;j<2*3*2*1;j++){
        data_x_conv2d[j]=0.0;
      }
Expression x_conv2d=input(cg,dynet::Dim({2,3,2},1),&data_x_conv2d);
```

and my filter looks like:
     ```
vector<dynet::real> data_f_conv2d(24,-std::numeric_limits<dynet::real>::infinity());
      for(int j=0;j<24;j++){
        data_f_conv2d[j]=0.0;
      }
Expression f_conv2d=input(cg,dynet::Dim({2,2,2,3}),&data_f_conv2d);
```

and my strides looks like:
```
      vector<unsigned> stride_conv2d(2);
      stride_conv2d[0]=1;
      stride_conv2d[1]=1;
```

finally, I use:
`Expression out_conv2d=conv2d(x_conv2d,f_conv2d,stride_conv2d,true);`

then, my computation went wrong when I am wanna to print out_conv2d.value() with gdb:
`The program being debugged entered a std::terminate call, most likely caused by an unhandled C++ exception. GDB blocked this call in order to prevent the program from being terminated, and has restored the context to its original state befor the call. To change this behaviour use "set unwind-on-terminating-exception off". Evaluation of the expression containing the function (dynet::expr::Expression::value() const) will be abandoned.`

I feel so confused, please help me ~~~

looking forward to you ! thanks!

Cathy W

**Comment by zhisbug** [comment]
Could you share your full code here?

**Comment by zhisbug** [comment]
It would be good if you could give me your full code that will produce the error (including the main function) so that I can take a look. Looks like the code snippet you gave me won't result in the error you mentioned.

**Comment by CathyW77** [comment]
Oh,sorry. I'm a Newbie in this field. 
Actually, I don't know how to create a  "ComputationGraph cg" , which used in creating "Expression".
So I just added my code in lamtraim-train.cc:LamtramTrain::BilingualTraining ,after "cg" appeared, after line777.
I  "gdb"  to that line, want to print the "out_conv2d.value()" ,then error comes up.
All I wanna to know is the  result of "conv2d"
