### ISSUE TITLE
Explicitly Mention Where to 'renew_cg'

### ISSUE THREAD

**Issue by talbaumel** [clab/dynet#563]
Hi, in the auto batch demo can you mention if the `dy.renew_cg()` call should be in the bath loop or outside?
http://dynet.readthedocs.io/en/latest/minibatch.html#automatic-mini-batching

Thanks, Tal

**Comment by neubig** [comment]
Good point! This should be fixed by this commit: https://github.com/clab/dynet/commit/55266dc7fed7b3fc90dab0b2d2a7223b41c541db
