### ISSUE TITLE
AutoBatch problem in cpp

### ISSUE THREAD

**Issue by elikip** [clab/dynet#567]
Hi,

We have been trying to run autobatch on a seq2seq model. The code works perfectly without autobatch, however when with add the autobatch parameter we encounter an error:

>terminate called after throwing an instance of 'std::invalid_argument'
>  what():  Out-of-bounds attempt to access index 78990 for LookupParameter of size 60985

The line of the code causing the crash is trying to lookup for the embedding of the next word in the sequence. If we remove this line then the code runs even with autobatch but we would like to use the embedding of the next word as well. Is this something that auto batch might break? Is it possible that autobatch somehow concatenates the bits of two (or more) lookup indices?

Thanks

**Comment by neubig** [comment]
Thanks for testing out the new functionality! This looks like a bug... Do you have a simple example (in either C++ or Python that could reproduce this)?

**Comment by neubig** [comment]
Actually, looking at the code I might know the source of the problem, will try to push a fix quickly.

**Comment by elikip** [comment]
Thank you very much!

**Comment by neubig** [comment]
This pull request may fix your problem (it will be merged once CI test check out):
https://github.com/clab/dynet/pull/570

Could you try running with this? If not, I'll probably need an example that causes things to crash to debug further.

**Comment by elikip** [comment]
It solved the problem. Thanks for the quick fix!
