### ISSUE TITLE
is there a standard noise contrastive estimation layer?

### ISSUE THREAD

**Issue by anglil** [clab/dynet#569]
To make training faster, is there a noise contrastive estimation layer in dynet in place of softmax, or pickneglogsoftmax?

**Comment by neubig** [comment]
There is an example of training RNNs with NCE here, which could probably help you figure it out:
https://github.com/clab/dynet/blob/master/examples/cpp/rnnlm-batch-nce/train_rnnlm-batch-nce.cc
