### ISSUE TITLE
CUDA out-of-memory message is hard to understand

### ISSUE THREAD

**Issue by neubig** [clab/dynet#577]
Since we have dynamically increasing memory pools: https://github.com/clab/dynet/pull/364

the CUDA out-of-memory message is hard to understand, just noting that `cudaMalloc` failed. This should be fixed to be easier to understand.

**Comment by jeticg** [comment]
I created a pull request #1131 to output a bit more messages in case of a cudaMalloc failure.
(err == cudaErrorMemoryAllocation)

**Comment by neubig** [comment]
Fixed by #1131
