### ISSUE TITLE
Query regarding saving and loading model

### ISSUE THREAD

**Issue by smar111** [clab/dynet#583]
I am using dynet through C++.
I have two models S and D. Model S has parameters Sp and model D has parameters Dp which include Sp and some parameters X of its own. Both models use the same class definition.
I want to train S first so that I get the values of Sp, save them in a file using save_dynet_model() and then load them using load_dynet_model() when I train model D.
My question is should I only add parameters Sp to the model when I am training the model S?
Or should I add all parameters Dp (both Sp and X) to the model even when I am training S? 
If I do the former will Sp be initialized correctly, from the model S that I have already saved?

**Comment by neubig** [comment]
Currently, the answer is the latter: the easiest way to do this is to initialize D with all the parameters, then train only Sp during the pre-training step.

Very soon, we will be making a major update of model saving and loading that will make it easier to load specific parts of a saved model, which will make it easier to do the former: https://github.com/clab/dynet/issues/84

I'm going to close this issue, but feel free to monitor #84 as I'll post an update there when it's ready.
