### ISSUE TITLE
Installation error gcc version

### ISSUE THREAD

**Issue by patata3000** [clab/dynet#587]
Hello I'm on arch linux, I installed cuda using yaourt package manager.
I'm trying to install dynet with gpu support with:
sudo cmake .. -DEIGEN3_INCLUDE_DIR=/opt/eigen -DBACKEND=cuda DCUDNN_ROOT="/opt/cuda"
Which gives me:

> -- The C compiler identification is GNU 7.1.1
-- The CXX compiler identification is GNU 7.1.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   program_options
--   regex
--   serialization
-- Boost dir is /usr/include
-- BACKEND: cuda
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /opt/cuda (found version "8.0") 
CUDA_LIBRARIES: /opt/cuda/lib64/libcudart_static.a;-lpthread;dl;/usr/lib/librt.so
-- Found CUDNN (include: /opt/cuda/include, library: /opt/cuda/lib64/libcudnn.so)
-- Successfully include CUDNN flags
-- Eigen dir is /opt/eigen
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   unit_test_framework
--   serialization
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/dynet/build

C and CXX compilers are 7.1.1 and I thought it should be 5. When make -j 8, I get errors like:

> #error -- unsupported GNU version! gcc versions later than 5 are not supported!

What should I do?

I've got gcc -> gcc-5 in /opt/cuda/bin/
I don't know how to switch to it
Sorry for my newbieness

**Comment by neubig** [comment]
This isn't an error with DyNet itself, but an error with your upstream CUDA environment (i.e. any CUDA program you try to compile will result in the same message). Take a look here for more info: https://stackoverflow.com/questions/6622454/cuda-incompatible-with-my-gcc-version
