### ISSUE TITLE
Segfault on CUDA when using GCC 4.9.3 and optimization -O2

### ISSUE THREAD

**Issue by neubig** [clab/dynet#59]
Currently, when using cnn on CUDA, compiling with GCC 4.9.3, segfaults occur when using the default optimization setting of -O2. This is not a problem on GCC 4.8.*, but may be a problem on other versions of GCC.

We don't currently know the cause, but a patch fixing the bug would be welcome. If you want a quick fix, find the line including `APPEND CUDA_NVCC_FLAGS` in `cnn/CMakeLists.txt` and change `-O2` to `-O1`.

**Comment by trevorcohn** [comment]
I'm seeing this bug with the current version of Dynet, compiling against CUDA 8.0 and GCC 5.4.0. The -O1 workaround dodges the segfault.

**Comment by neubig** [comment]
@trevorcohn thanks for the note! We merged a fix to check the GCC version and switch to O1 for more recent versions: https://github.com/clab/dynet/pull/133

**Comment by trevorcohn** [comment]
Thanks @neubig. Does O1 come attract much of a speed penalty cf O2 (inlining, loop unrolling etc)? Or is this immaterial given the real time is spent bossing around the GPU using CUDA?
