### ISSUE TITLE
Error While Training

### ISSUE THREAD

**Issue by talbaumel** [clab/dynet#602]
Hi, while training the network I'm getting the following error `RuntimeError: Magnitude of gradient is bad: -nan` from the command `opt.update()`

Any idea how can I avoid/solve this error?

Thanks

**Comment by neubig** [comment]
We'll need a bit more information about this to help debug. First, have you tried the immediate computation on the debugging page?
http://dynet.readthedocs.io/en/latest/debugging.html

If you can try this, it'd help to know which node has caused the problem.

**Comment by talbaumel** [comment]
I'm trying to create a mock GAN
One that tries to forge a distribution

When the distribution yields high values (normal distribution with variance ~20 crash it instantly) the error appears at the first few iterations of training the discriminator
the discriminator is defined as follows:
```
x = add_variance(x)
logistic(w_3 * ELU(w_2 *(ELU(w_1*x +b_1) +b_2) + b_3)

def add_variance(x):
    mean = dy.average(x)
    var = dy.concatenate([mean-val for val in x])
    var = dy.cmult(var, var)
    return  dy.concatenate([var, dy.concatenate(x)])

def ELU(x):
    ones = dy.vecInput(hidden_size)
    ones.set([1.]*hidden_size)
    return dy.rectify(x) - dy.rectify(-dy.exp(x)+ones)

w_1 => 100 x 100 b_1 => 100
w_2 => 100 x 100 b_2 => 100
w_3 => 1 x 100 b_3 => 1
```
For low values it works
For medium (~10) values it crashes after a while

**Comment by neubig** [comment]
My guess is that you're getting numerical stability problems in the dy.exp(x) function when x is a very big value.

**Comment by pmichel31415** [comment]
Yes maybe try the native ELU I just added, if the problem persists maybe try to use log variance instead of variance directly?

**Comment by talbaumel** [comment]
It seams like my ELU causedthe problem

Thanks
