### ISSUE TITLE
ELU and SELU

### ISSUE THREAD

**Issue by speedcell4** [clab/dynet#603]
How can I use [ELU](https://arxiv.org/pdf/1511.07289) and [SELU](https://arxiv.org/abs/1706.02515)?

**Comment by miradel51** [comment]
see readme

**Comment by neubig** [comment]
These are not implemented in DyNet yet, but we'd certainly welcome any contributions. Take a look here about information on contributing new nodes: http://dynet.readthedocs.io/en/latest/code_style.html#coding-tips

**Comment by speedcell4** [comment]
@miradel51 could you please show clearly which README you are referring to?

**Comment by pmichel31415** [comment]
Solved by #607
