### ISSUE TITLE
How can I use trigonometric functions in DyNet?

### ISSUE THREAD

**Issue by speedcell4** [clab/dynet#610]
`sin`, `cos`, `tan`, `cot`, `sec`, `csc`
`asin`, `acos`, `atan`, `acot`, `asec`, `acsc`

**Comment by neubig** [comment]
These are not implemented, but would be great to have.

**Comment by neubig** [comment]
Done by https://github.com/clab/dynet/commit/910379a9d91d92c84aa91bb9e7bf8a246acb463c

**Comment by DanielPhoton** [comment]
I’m attempting to use Hyperbolic trigonometric functions using python, and as of today, none except dynet.tanh. 

Also, please implement inverse/arc variations of all Hyperbolic functions!

**Comment by redpony** [comment]
These should all be available (well the standard ones, not sec, csc, cot).
The naming convention is optional “a” means “inverse” followed by one of
sin/cos/tan then optional “h” if you want hyperbolic.
