### ISSUE TITLE
use conv2d in GPU & memory increased a lot 

### ISSUE THREAD

**Issue by CathyW77** [clab/dynet#613]
when I used conv2d  in GPU, I found it used a lot of memory , is that normal ?
 
'''' 
 int  conv_layer=2;
  for(int i=0;i<conv_layer;i++)
  {
        A=conv2d(B, filter, stride,false);
  }
''''
 B matrix is 94*1*1*1 and filter is 3*1*1 and stride[0]=1,stride[1]=1
 It is so simple but used a lot of memory ,  I wanna know is that normal?

**Comment by zhisbug** [comment]
Yes, it is normal, because a workspace will be allocated beforehand.

**Comment by neubig** [comment]
@zhisbug Just out of curiosity, is the memory temporary (does it need to be saved for the entire forward-backward process, or can it be scratched afterwards)? We might be able to make memory allocation more efficient by making this allocation temporary.

**Comment by CathyW77** [comment]
is there any way to release the memory after I use it ?

Actually , I have  " vecort<Expression> DATA"

for( int i = 0; i < DATA.size(); i++)
{
    " then I use DATA[i] in conv2d  and add each result into a new vecot<Expression> NEW_DATA"
}
I saw the GPU memory , it consumed a lot more than just add DATA[i] in to NEW_DATA without using conv2d

**Comment by CathyW77** [comment]
sorry  I mean vector<Expression> DATA &   vector<Expression> NEW_DATA

**Comment by zhisbug** [comment]
@neubig I don't allocate new memory, all memory used in conv2d/maxpooling is from the aux_mem pointer (i.e. the memory is managed and pre-allocated by the framework). Then, why there is an allocation efficiency issue?

**Comment by zhisbug** [comment]
@CathyW77 I think the size of memory needed is only determined by two factors: (1) how many conv2d in your graph (2) the size of your (batched) input to the conv2d node. So in your case, the memory shall be determined by the size of DATA[i], not DATA.

**Comment by zhisbug** [comment]
@CathyW77 While I am not sure what causes your problem, could you try this pull request: https://github.com/clab/dynet/pull/612

**Comment by neubig** [comment]
@zhisbug Auxiliary memory is saved in the computation graph, but it might not be necessary to save this memory for the entire forward and backward pass. DyNet memory pools have save_used() and set_used() functionality that can be used to roll-back allocation of temporary memory. It might also be nice to create a standard way for allocating temporary memory in DyNet. Maybe we can discuss this in person later.

**Comment by CathyW77** [comment]
@zhisbug thank you ,I will try later

**Comment by zhisbug** [comment]
@neubig Sure, we can discuss the memory allocation later. My latest PR https://github.com/clab/dynet/pull/612 does not save memory for the entire forward and backward pass -- backward will rewrite the aux_mem pointer from the start, so forward and backward are independent now, one can call backward without calling forward first.

**Comment by jcyk** [comment]
I found the memory use behavior of conv2d is weird.
Sometime when I raise the batch size, it works. But when I lower the batch size, it use too much memory.

Don't understand that.

**Comment by zhisbug** [comment]
Could any of you post a piece of code so that I can find which line of code leads to the memory consumption? @jcyk @CathyW77

**Comment by CathyW77** [comment]
dynet::Expression image=a;   //a's dimension:20*1, a is an element of an image sequence whose length is around 100
  filter= mod.add_parameters({3,1,1,1}); 
  int  conv_layer=1;
  for(int i=0;i<conv_layer;i++)
  {
      //make image into  20*1*1*batch_size, where batch_size=1
      image=reshape(image,dynet::Dim({image.value().d.rows(),image.value().d.cols(),1},image.value().d.batch_elems()));
      vector<unsigned> stride_conv2d(2,1);
      image=conv2d(image,filter,stride_conv2d,false);
      //transform 20*1*1*batch_size into 20*1
      image=reshape(image,dynet::Dim({image.value().d[0],image.value().d[1]},image.value().d.batch_elems()));
  }

 It caused  "out of  memory " error in beam searching the image sequence with beam size 5.

**Comment by neubig** [comment]
This issue should be fixed by https://github.com/clab/dynet/pull/692
