### ISSUE TITLE
bugs in function average()

### ISSUE THREAD

**Issue by liesun1994** [clab/dynet#614]
hi,
I am trying to use function average(), but it seems something wrong with it, my input is a list of expression which shape remains the same. c++ version ~
thanks ,neubig~

**Comment by neubig** [comment]
Please be more specific than "something wrong". What error are you getting? Please provide as much information as possible, and hopefully a minimal code example that can be used to reproduce the problem.

**Comment by liesun1994** [comment]
it occurs when I am using lamtram.
I modified the 225th and  the 166th line  in  encoder-attentional.cc  to use mean pooling for computing target 0th hidden states.
here is my change: 
i_h_last_ = *hs_comb.rbegin();   ==>    i_h_last_ = average(hs_comb);
But it pops up SIGSEGV error: Segmentation fault. I debuged it and the backtrace show that the error happens at:
dynet::Average::forward_impl (this=0x51c2db0, xs=std::vector of length 24, capacity 24 = {...}, fx=...)
    at ~/dynet/dynet/nodes.cc:436

questions were listed here.
https://groups.google.com/forum/#!topic/lamtram-users/sOjuV8zqSDo

**Comment by rasoolims** [comment]
I am also having troubles with the average function in Python. When I give an average of a list of embedding values, the forward method gives segmentation fault. I am pretty sure it is the problem with this function. Because when I pass the first embedding in the list instead of averaging of them, it works fine.

```python
# word_input_indices: a set of word ids
my_input = average([w_embed[index] for index in word_input_indices])
# When calling forward, it throws Segmentation fault (core dumped) error

# The below line works fine!
my_input = w_embed[0] 

```

**Comment by neubig** [comment]
I was able to confirm this breaks on GPU, so I'll mark this as a bug.

**Comment by liesun1994** [comment]
Thx ~~
