### ISSUE TITLE
Install problem with 'make -j 2'

### ISSUE THREAD

**Issue by ghost** [clab/dynet#616]
haixu@my-machine:~/dynet-base/dynet/build$ make -j 16
[ 23%] Built target dynet
[ 24%] Linking CXX executable 1_linear_regression
[ 25%] Linking CXX executable 0_multiply
../dynet/libdynet.so: undefined reference to `boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::save(std::string const&)'
../dynet/libdynet.so: undefined reference to `boost::archive::basic_binary_iprimitive<boost::archive::binary_iarchive, char, std::char_traits<char> >::load(std::string&)'
../dynet/libdynet.so: undefined reference to `boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::save(std::string const&)'
collect2: error: ld returned 1 exit status
tutorial/CMakeFiles/0_multiply.dir/build.make:101: recipe for target 'tutorial/0_multiply' failed
make[2]: *** [tutorial/0_multiply] Error 1
CMakeFiles/Makefile2:2539: recipe for target 'tutorial/CMakeFiles/0_multiply.dir/all' failed
make[1]: *** [tutorial/CMakeFiles/0_multiply.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../dynet/libdynet.so: undefined reference to `boost::archive::basic_binary_oprimitive<boost::archive::binary_oarchive, char, std::char_traits<char> >::save(std::string const&)'
../dynet/libdynet.so: undefined reference to `boost::archive::basic_binary_iprimitive<boost::archive::binary_iarchive, char, std::char_traits<char> >::load(std::string&)'
../dynet/libdynet.so: undefined reference to `boost::archive::text_oarchive_impl<boost::archive::text_oarchive>::save(std::string const&)'
collect2: error: ld returned 1 exit status
tutorial/CMakeFiles/1_linear_regression.dir/build.make:101: recipe for target 'tutorial/1_linear_regression' failed
make[2]: *** [tutorial/1_linear_regression] Error 1
CMakeFiles/Makefile2:2502: recipe for target 'tutorial/CMakeFiles/1_linear_regression.dir/all' failed
make[1]: *** [tutorial/CMakeFiles/1_linear_regression.dir/all] Error 2
[ 56%] Built target gdynet
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by neubig** [comment]
This is a problem with not finding the "boost" library. A release of DyNet is coming up that will get ride of the dependency on the boost library, so probably the easiest way to resolve this problem is to install this release candidate. Try

    git fetch origin v2rc
    git checkout v2rc

then delete your `build` directory and restart the steps from `mkdir build`. In about a week this release candidate will be merged into the master branch, and this problem should be resolved.

**Comment by wuhaixutab** [comment]
Thank you for your reply! I tried your solution but new problems appeared:



haixu@my-machine:~/dynet-base/dynet/build$ git fetch origin v2rc
From https://github.com/clab/dynet
 * branch            v2rc       -> FETCH_HEAD
haixu@my-machine:~/dynet-base/dynet/build$ git checkout v2rc
Branch v2rc set up to track remote branch v2rc from origin.
Switched to a new branch 'v2rc'
haixu@my-machine:~/dynet-base/dynet/build$ cd ..
haixu@my-machine:~/dynet-base/dynet$ rm build/
rm: cannot remove 'build/': Is a directory
haixu@my-machine:~/dynet-base/dynet$ rmdir build/
rmdir: failed to remove 'build/': Directory not empty
haixu@my-machine:~/dynet-base/dynet$ rm -rf build/
haixu@my-machine:~/dynet-base/dynet$ mkdir build 
haixu@my-machine:~/dynet-base/dynet$ cd build/
haixu@my-machine:~/dynet-base/dynet/build$ cmake .. -DEIGEN3_INCLUDE_DIR=../../eigen -DPYTHON=`which python` -DBACKEND=cuda
-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- BACKEND: cuda
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr (found version "7.5") 
CUDA_LIBRARIES: /usr/lib/x86_64-linux-gnu/libcudart_static.a;-lpthread;dl;/usr/lib/x86_64-linux-gnu/librt.so
-- Found CUDNN (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Successfully include CUDNN flags
-- Eigen dir is /home/haixu/dynet-base/eigen
-- Found Cython version 0.25.2

--- CUDA: CUBLAS: /usr/lib/x86_64-linux-gnu/libcublas.so RT: /usr/lib/x86_64-linux-gnu/libcudart_static.a;dl;/usr/lib/x86_64-linux-gnu/librt.so;/usr/local/cuda/lib64/libcudnn.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/haixu/dynet-base/dynet/build
haixu@my-machine:~/dynet-base/dynet/build$ make -j 16
[  1%] Building NVCC (Device) object dynet/CMakeFiles/gdynet.dir/gdynet_generated_cudnn-ops.cu.o
[  1%] Building NVCC (Device) object dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-nodes-contract.cu.o
[  2%] Building NVCC (Device) object dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-nodes-conv.cu.o
[  3%] Building NVCC (Device) object dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-nodes-maxpooling2d.cu.o
Scanning dependencies of target dynet
[  3%] Building NVCC (Device) object dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-model.cu.o
[  5%] Building NVCC (Device) object dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-ops.cu.o
[  5%] Building NVCC (Device) object dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-param-nodes.cu.o
[  5%] Building NVCC (Device) object dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-nodes.cu.o
[  6%] Building NVCC (Device) object dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-nodes-conv2d.cu.o
[  7%] Building NVCC (Device) object dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-tensor.cu.o
[  8%] Building NVCC (Device) object dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-training.cu.o
[  9%] Building CXX object dynet/CMakeFiles/dynet.dir/aligned-mem-pool.cc.o
[ 10%] Building CXX object dynet/CMakeFiles/dynet.dir/dynet.cc.o
[ 11%] Building CXX object dynet/CMakeFiles/dynet.dir/cfsm-builder.cc.o
[ 11%] Building CXX object dynet/CMakeFiles/dynet.dir/deep-lstm.cc.o
[ 12%] Building CXX object dynet/CMakeFiles/dynet.dir/devices.cc.o
/usr/local/cuda/include/surface_functions.h(134): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(135): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(136): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(137): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(138): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(139): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(140): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(141): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(142): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(143): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(144): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(145): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(146): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(147): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(148): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(149): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(150): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(151): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(152): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(153): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(154): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(155): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(156): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(157): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(158): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(159): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(160): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(161): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(162): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(163): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(164): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(228): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(229): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(230): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(231): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(294): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(295): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(296): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(297): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(298): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(299): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(300): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(301): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(302): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(303): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(304): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(305): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(306): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(307): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(308): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(309): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(310): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(311): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(312): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(313): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(314): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(315): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(316): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(317): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(318): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(319): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(320): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(321): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(322): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(323): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(324): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(390): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(391): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(392): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(393): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(456): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(457): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(458): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(459): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(460): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(461): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(462): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(463): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(464): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(465): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(466): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(467): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(468): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(469): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(470): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(471): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(472): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(473): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(474): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(475): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(476): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(477): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(478): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(479): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(480): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(481): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(482): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(483): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(484): error: expected a ";"

/usr/local/cuda/include/surface_functions.h(485): error: expected a ";"

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_000002d6_00000000-19_gpu-ops.compute_52.cpp1.ii".
Compilation terminated.
CMake Error at gdynet_generated_gpu-ops.cu.o.cmake:262 (message):
  Error generating file
  /home/haixu/dynet-base/dynet/build/dynet/CMakeFiles/gdynet.dir//./gdynet_generated_gpu-ops.cu.o

dynet/CMakeFiles/gdynet.dir/build.make:70: recipe for target 'dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-ops.cu.o' failed
make[2]: *** [dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-ops.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 13%] Building CXX object dynet/CMakeFiles/dynet.dir/dict.cc.o
[ 14%] Building CXX object dynet/CMakeFiles/dynet.dir/dim.cc.o
[ 14%] Building CXX object dynet/CMakeFiles/dynet.dir/exec.cc.o
[ 15%] Building CXX object dynet/CMakeFiles/dynet.dir/expr.cc.o

**Comment by neubig** [comment]
Hmm, I tried compiling with CUDA and didn't encounter this bug in particular. I did fix a couple other compile issues though, so it might be worth pulling the most recent version and trying again.

**Comment by wuhaixutab** [comment]
I tried the latest version but it failed again. I hope the installation of DyNet can be as easy as PyTorch some day.

**Comment by neubig** [comment]
Sorry about being late on this. Are you still running into compile problems? If so, can you please tell me more about your environment? i.e. what OS, what version of the compiler, what version of CUDA? What version of CUDNN if it's installed?
