### ISSUE TITLE
Illegal instruction Error

### ISSUE THREAD

**Issue by YujiOshima** [clab/dynet#617]
I tried the train_xor-autobatch example in the Docker container, but the following error appears.

```
$ /opt/dynet/build/examples/train_xor-autobatch
[dynet] random seed: 3412173849
[dynet] allocating memory: 512MB
Illegal instruction (core dumped)
```

Even if I set parameters explicitly, the same error will occur.

```
$ /opt/dynet/build/examples/train_xor-autobatch --dynet-mem 4096 --dynet-autobatch
[dynet] random seed: 560679062
[dynet] using autobatching
[dynet] allocating memory: 4096MB
Illegal instruction (core dumped)
```

My Dockerfile is  below.

```
FROM ubuntu:16.04

# Build dependencies
RUN echo "deb-src http://archive.ubuntu.com/ubuntu/ xenial main restricted" >> /etc/apt/sources.list && \
       apt-get update && \
       apt-get install -y wget git mercurial libgoogle-perftools-dev libsparsehash-dev libboost-all-dev autoconf libtool
RUN apt-get build-dep -y cmake

# CMake 3.8.2
RUN cd /opt && \
        wget "https://cmake.org/files/v3.8/cmake-3.8.2.tar.gz" && \
        tar xf cmake-3.8.2.tar.gz && \
        cd cmake-3.8.2 && \
        ./configure && \
        make -j16 install

# Eigen version 3.3.4
ENV EIGEN_VERSION 3.3.4
RUN cd /opt && \
        hg clone https://bitbucket.org/eigen/eigen/ && \
        cd eigen && \
        hg update -r ${EIGEN_VERSION}

# DyNet version latest
ENV DYNET_VERSION master
RUN cd /opt && \
        git clone https://github.com/clab/dynet.git && \
        cd dynet && \
        git checkout ${DYNET_VERSION} && \
        mkdir build && \
        cd build && \
        cmake .. -DEIGEN3_INCLUDE_DIR=/opt/eigen && \
        make -j16 install
```
Do you have any ideas?

**Comment by neubig** [comment]
This problem will sometimes happen when the compiler attempts to use advanced instructions on the CPU that are not supported for some reasons. For example, I've seen this happen when DyNet is run in virtualization environments.

One way to fix this is to turn off the use of advanced instructions. This will make things slower (particularly when running on CPU, not GPU), but can probably fix this problem. The way to do so is to open `CMakeLists.txt` in the main DyNet directory, find the string `-march=native`, delete it, then delete your `build` directory and compile DyNet from scratch.

Does this fix the problem? This happens from time-to-time, so we might want to add a compile-time option to make it possible to turn off these advanced instructions.

**Comment by YujiOshima** [comment]
@neubig Thank you so much!!
It worked on both of CPU and GPU!

>  I've seen this happen when DyNet is run in virtualization environments.

Yes, I ran this docker container on AWS EC2 instance (g2.xlarge).

**Comment by YujiOshima** [comment]
@neubig By the way, I guess there is no official docker images for DyNet.
I set up the DyNet docker images [here](https://hub.docker.com/r/yujioshima/dynet/)!
There are images for python, c++, CPU, GPU.
I could provide image for virtualization environments thanks for your advice!
