### ISSUE TITLE
Getting product of v1 * mi * v2 for multiple i

### ISSUE THREAD

**Issue by shuheik** [clab/dynet#619]
I have two _d_-dimensional vectors v1 and v2, and k _d*d_ dimensional matrices m1 ... mk.
I want to calculate transpose(v1) * mi * v2 for all k, and obtain a _k_-dimensional vector whose _i_-th element is the result of transpose(v1) * mi * v2.

One straightforward way to do this would be to loop over k, or possibly compute transpose(v1) * mi for all k 
and concatenate k resulting vectors to a _k * d_ matrix (say m') to reuse it and then do m' * v2.

Are there more efficient ways to do the same thing in dynet?

**Comment by liesun1994** [comment]
yeap.
of course you can do it as follows:
middle = affine_transform(m, v2, k);
result = transpose(v1, middle);
where  m means total  k  d*d dimensional matrices.
:)

**Comment by neubig** [comment]
Perhaps `contract_3d_1d_1d` will do the trick? http://dynet.readthedocs.io/en/latest/operations.html#_CPPv2N5dynet4expr16contract3d_1d_1dERK10ExpressionRK10ExpressionRK10Expression

**Comment by shuheik** [comment]
@neubig 
Yes, it does what I want, and for the precompute and reuse case I could do m' = contract3d1d(m, v1) first and then do m' * v2.
Thank you so much!

@liesun1994 
In my case m, v2 and k's dimensions doesn't seem to meet what affineTransform requires.
Maybe I'm missing something or my explanation wasn't clear enough.
Anyway, thank you for your response!
