### ISSUE TITLE
What are the corresponding flags to the cmake for non-standard Boost location?

### ISSUE THREAD

**Issue by yuchenlin** [clab/dynet#620]
Hi, I am trying to install DyNet locally from scratch without ``sudo'' and thus my Boost location is non-standard. I know I have to add some flags to cmake but the link in the documentation is not working 
now.

> If Boost is installed in a non-standard location, you should add the corresponding flags to the cmake commandline, see the **DyNet installation instructions page**(http://dynet.readthedocs.io/en/latest/install.rst).

(from http://dynet.readthedocs.io/en/latest/python.html)

I know that the new version without dependencies on Boost from the user group, which is very exciting and I am looking forward to it!  
While, if my issue is just a change of the link, providing a new link could be easier.

Thank you very much.

**Comment by neubig** [comment]
Sure, take a look here:
http://dynet.readthedocs.io/en/latest/install.html#non-standard-boost-location

**Comment by yuchenlin** [comment]
Thank you very much!
