### ISSUE TITLE
v2 read/write API needs updated SWIG Bindings

### ISSUE THREAD

**Issue by neubig** [clab/dynet#623]
As announced on the DyNet users mailing list, we're heading towards a release of DyNet v2.0. One of the major features will be an updated read/write interface that doesn't require boost is simplified in many ways (we only read/write parameters and parameter collections), but also allows for the reading/writing of named parameters.
https://github.com/clab/dynet/tree/v2rc

Currently, the SWIG bindings are not supported for this new version. @joelgrus @jayantk @shuheik , would it be possible to have one of you help out with updating the bindings?

**Comment by shuheik** [comment]
Unfortunately I'm not so familiar with SWIG enough to be confident about something beyond trivial re-writes, but I think I can try if nobody is going to do this.

**Comment by joelgrus** [comment]
I can own this.

**Comment by neubig** [comment]
Great, thanks @joelgrus

**Comment by neubig** [comment]
@joelgrus FYI, we're planning on releasing v2 no later than Friday morning (eastern time). While it'd be ideal to have the updated SWIG bindings by then, I don't view it as a blocking problem (as the users of the SWIG bindings are a bit of a minority, and they can stay on v1 until the bindings are ready). So if you have time to do it by then that's great, if not we'll go ahead with the release and update the SWIG bindings in a future minor release.

**Comment by joelgrus** [comment]
https://github.com/clab/dynet/pull/631
