### ISSUE TITLE
contract3d_1d_1d doesn't work on GPU?

### ISSUE THREAD

**Issue by shuheik** [clab/dynet#624]
Hi, 
It seems that contract3d1d1d works only on CPU but not on GPU, at least when it's called from Scala bindings.
For example, when I do this inside sbt console on CPU,

> import edu.cmu.dynet._
> Initialize.initialize()
> 
> val vDim = 8
> val nClass = 4
> val v1 = Expression.randomNormal(Dim(vDim))
> val v2 = Expression.randomNormal(Dim(vDim))
> val m = Expression.randomNormal(Dim(nClass, vDim, vDim))
> val e = Expression.contract3d1d1d(m, v1, v2)
> println(e.value.toSeq)

the last line prints something like FloatVector(-0.09226055, 12.335046, 0.41495594, -18.316467).
However on GPU it fails with errors like this inside a native method.

> java.lang.RuntimeException: unknown exception
>  at edu.cmu.dynet.internal.dynet_swigJNI.Expression_value(Native Method)
>  at edu.cmu.dynet.internal.Expression.value(Expression.java:61)
>  at edu.cmu.dynet.Expression.value(Expression.scala:17)
>  ... 42 elided

Is this Scala-specific or common to C++/python?

**Comment by neubig** [comment]
By default tensor contractions are not compiled on GPU because compilation takes a long time. When you run in C++ or Python you get the following error:

    InnerProduct3D_1D_1D::forward_dev_impl disabled on CUDA. Comment out DYNET_SKIP_CUDA_CONTRACTIONS in nodes-contract.cc to enable this function.

I'm not sure why this error doesn't show up in Scala, but if you follow the directions, the contractions should work.

**Comment by shuheik** [comment]
It worked.
Thank you for quick response!
