### ISSUE TITLE
rnnlm needs to remove boost for v2

### ISSUE THREAD

**Issue by neubig** [clab/dynet#625]
Currently we are moving towards the v2 release, which no longer requires boost:
https://github.com/clab/dynet/tree/v2rc

Currently the `rnnlm` example is not compiled because it makes profuse use of boost commands. Because this is a pretty central example, it'd be nice to remove boost. Could you take a look @pmichel31415 ?

**Comment by pmichel31415** [comment]
I can take a look yeah.

**Comment by neubig** [comment]
Thanks!
