### ISSUE TITLE
Weight clipping

### ISSUE THREAD

**Issue by talbaumel** [clab/dynet#629]
Hi,
I'm trying to implement WGAN and need to be able to set the value of weights.
Didn't find any documentation, only able to read them using `npvalue()`

Thanks, Tal

**Comment by pmichel31415** [comment]
Seems like [`set_value`](http://dynet.readthedocs.io/en/latest/python_ref.html#dynet.Parameters.set_value) would do the trick? For weight clipping more specifically you could use [`clip_inplace`](http://dynet.readthedocs.io/en/latest/python_ref.html#dynet.Parameters.clip_inplace)

**Comment by talbaumel** [comment]
Thanks
