### ISSUE TITLE
Unable to initialize 2 LSTMs in one Model Object (Python)

### ISSUE THREAD

**Issue by johntzwei** [clab/dynet#632]
Hi, I just started using Dynet and I am a big fan. I am building a simple seq2seq model with LSTM encoder and decoders. However, initializing two models with this code:

`DEPTH = (1, 1)
ENC_HIDDEN_DIM = 100
DEC_HIDDEN_DIM = 100
MLP_HIDDEN_DIM = 30

 vocab = 'a'
 vocab_size = len(vocab) + 2

#architecture
 model = dy.Model()
 encoder = dy.LSTMBuilder(DEPTH[0], vocab_size, ENC_HIDDEN_DIM, model)
 decoder = dy.LSTMBuilder(DEPTH[1], vocab_size, DEC_HIDDEN_DIM, model)
 builders = (encoder, decoder)`

gives me this error:

`terminate called after throwing an instance of 'std::invalid_argument'
  what():  LSTMBuilder must be initialized with 2 times as many expressions as layers (hidden state and cell for each layer). However, for 1 layers, 1 expressions were passed in`

This code does not fail if I use only one LSTM builder, and the other a SimpleRNN/GRU builder. It also fails with the same message when a VanillaLSTMBuilder is used. Hope this helps!

Am I doing something wrong or is this a problem with Dynet? Any help would be greatly appreciated. Thanks!

**Comment by neubig** [comment]
This code is not enough to cause an error (it ran on my machine fine). I suspect that somewhere later in the code you are calling something the `set_s()` function? Please check where you called this function, and read the doc carefully. If you still can't figure it out feel free to ask.

**Comment by johntzwei** [comment]
Hi,

I figured it out, sorry for bothering! I was giving the decoder the initial state with encoder.s() instead of encoder.h(). Didn't realize that the error wasn't coming from the initialization. Thanks for helping!
