### ISSUE TITLE
Use CPU implementation of function but GPU for all other operations

### ISSUE THREAD

**Issue by chaitanyamalaviya** [clab/dynet#635]
Hi everyone, 

Is there a way to use the CPU implementation of a function while still using GPU for the remaining dynet operations? 

[When I use a function that does not have a GPU implementation and set the dynet-gpu flag, I get an error saying  'module' object has no attribute '<the_function_name>'. ]

**Comment by neubig** [comment]
This is a good idea, but is basically reliant on multi-device support: https://github.com/clab/dynet/issues/92

I'll close this as it's essentially a duplicate but I agree that this is important functionality to have.
