### ISSUE TITLE
THIS_TYPE_IS_NOT_SUPPORTED error when compiling on

### ISSUE THREAD

**Issue by rtachi** [clab/dynet#654]
Windows 
Visual Studio 2015 (Community)
Eigen 3.3.4
boost 1.64.0

I am having a trouble of installing DyNet on Windows.
 After running cmake with all necessary cmake flags and parameters got a dynet sln solution file.
 The solution in VS does not compile after I try to build it. I get 1 error as bellow:

Error C2338 error : static assertion failed with "THIS_TYPE_IS_NOT_SUPPORTED" This error occurrs many times in difeerent lines of: SpecialFunctionsImpl.h (Compiling  nodes.cc)
for example:
1>  c:\libs\eigen3\eigen\unsupported\eigen\src/SpecialFunctions/SpecialFunctionsImpl.h(107): note: 'float Eigen::internal::lgamma_impl<float>::run(const Scalar)' 
1>          with
1>          [
1>              Scalar=float
1>          ] (C:\libs\dynet-base\dynet-base\dynet\nodes.cc)

Please help!
 thanks in advance

R.T

**Comment by neubig** [comment]
I'm not sure about this, but maybe @mattr1 or someone has encountered this error on Windows?

**Comment by mattr1** [comment]
Hi rtachi, when I pull the very latest version of Eigen and dynet, I'm not seeing this compiler error. This error used to occur in an old version of eigen, and required manually setting EIGEN_HAS_C99_MATH (this was removed at this commit: https://github.com/clab/dynet/commit/b34914f3b090d691b179b126b534aacbe8da2a5c). Perhaps the problem still occurs with VS2015 Community edition? Can you try (1) pull the very latest version of Eigen and dynet and compile to see if the problem still occurs, and if it does, try (2) setting EIGEN_HAS_C99_MATH similarly to the way it was done in the above commit and see if that fixes the problem.

**Comment by Oneplus** [comment]
@mattr1 I came across the same problem, I am using VS2015 Community edition update 3 and my dynet only works when setting -DEIGEN_HAS_C99_MATH.

**Comment by neubig** [comment]
I'm closing this as a work-around seems to be possible.

**Comment by allanj** [comment]
use the latest Eigen will do
