### ISSUE TITLE
Changing the activation functions of LSTMBuilders

### ISSUE THREAD

**Issue by johntzwei** [clab/dynet#658]
Is there any straightforward way to change the activation functions? If not, I can try to add in the functionality. Thanks!

**Comment by oserikov** [comment]
@johntzwei, did you found a way to change the activation? I'm googling for such an opportunity for the whole day

**Comment by FilippoC** [comment]
@oserikov  You can easily copy the code of the Compact LSTM Builder and change them yourself ! :-)

**Comment by oserikov** [comment]
@FilippoC actually i'm looking for a pythonic way to do this and with another(simpleRNN) buider, but thought the things will be similar for RNN and LSTM builders :\
