### ISSUE TITLE
GPU installation failed with V1.1 - catastropic error

### ISSUE THREAD

**Issue by BhaskarNallani** [clab/dynet#674]
Hi ,
I am using a parser application which is working with dynet V1.1.

while compiling the dynetv1.1 for GPU I am getting following error. 

/usr/include/c++/5/ext/new_allocator.h(99): internal error: assertion failed at: "/dvs/p4/build/sw/rel/gpu_drv/r361/r361_00/drivers/compiler/edg/EDG_4.10/src/types.c", line 7543

1 catastrophic error detected in the compilation of "/tmp/tmpxft_00004572_00000000-15_gpu-model.compute_52.cpp1.ii".
Compilation aborted.
Aborted
CMake Error at gdynet_generated_gpu-model.cu.o.cmake:278 (message):
  Error generating file
  /home/isdgenomics/users/nbhaskar/CNN/dynet-1.1/build/dynet/CMakeFiles/gdynet.dir//./gdynet_generated_gpu-model.cu.o

dynet/CMakeFiles/gdynet.dir/build.make:133: recipe for target 'dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-model.cu.o' failed
make[2]: *** [dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-model.cu.o] Error 1
CMakeFiles/Makefile2:87: recipe for target 'dynet/CMakeFiles/gdynet.dir/all' failed
make[1]: *** [dynet/CMakeFiles/gdynet.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  3%] Building CXX object dynet/CMakeFiles/dynet.dir/dynet.cc.o
[  3%] Building CXX object dynet/CMakeFiles/dynet.dir/deep-lstm.cc.o
[  4%] Building CXX object dynet/CMakeFiles/dynet.dir/devices.cc.o
[  5%] Building CXX object dynet/CMakeFiles/dynet.dir/dict.cc.o
[  5%] Building CXX object dynet/CMakeFiles/dynet.dir/dim.cc.o
[  6%] Building CXX object dynet/CMakeFiles/dynet.dir/exec.cc.o
[  7%] Building CXX object dynet/CMakeFiles/dynet.dir/expr.cc.o
[  7%] Building CXX object dynet/CMakeFiles/dynet.dir/fast-lstm.cc.o
[  8%] Building CXX object dynet/CMakeFiles/dynet.dir/globals.cc.o
[  8%] Building CXX object dynet/CMakeFiles/dynet.dir/grad-check.cc.o
^Cdynet/CMakeFiles/dynet.dir/build.make:278: recipe for target 'dynet/CMakeFiles/dynet.dir/fast-lstm.cc.o' failed
make[2]: *** [dynet/CMakeFiles/dynet.dir/fast-lstm.cc.o] Interrupt
dynet/CMakeFiles/dynet.dir/build.make:326: recipe for target 'dynet/CMakeFiles/dynet.dir/grad-check.cc.o' failed
make[2]: *** [dynet/CMakeFiles/dynet.dir/grad-check.cc.o] Interrupt
CMakeFiles/Makefile2:124: recipe for target 'dynet/CMakeFiles/dynet.dir/all' failed
make[1]: *** [dynet/CMakeFiles/dynet.dir/all] Interrupt
Makefile:140: recipe for target 'all' failed
make: *** [all] Interrupt

I am using Cuda.8-0 on Ubuntu-16.04. 
It is compiling for CPU with out any issues.
Dynet v2.0 is working for CPU and GPU .

The application has a dependency on dynet v1.1.

$sudo cmake .. -DEIGEN3_INCLUDE_DIR=/usr/local/include/eigen3/ -DPYTHON=python -DBACKEND=cuda -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-8.0/
$sudo make -j2

Regards.
Bhaskar

**Comment by neubig** [comment]
Are you using CuDNN v 6.0? We're currently working on 6.0 support, but at the moment only 5.1 is supported

**Comment by BhaskarNallani** [comment]
I tried using CuDNN v 5.1 but the error is caused by CUDA 8.0 and BOOST 1.64 which are incompatible.

Others who are using both cuda and boost also encountered this same error.
https://github.com/ComputationalRadiationPhysics/picongpu/issues/2048

**Comment by BhaskarNallani** [comment]
I am able to compile now with configuration Dynet V1.1/ CuDnn v5.1/ CUDA 8.0/BOOST 1.63/Ubunutu 16.04/ Tesla GPU Card P100 when I give boost path -DBOOST_ROOT=path/boost_1_63_0/.

But I am getting below run time error  while loading the input model:

File name:./Test/bestarchybrid4B.model
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  input stream error
  Aborted  

The error is thrown in model.cc 

boost::archive::text_iarchive ia(in);
 ia >> (*model);

Does anyone came across this? I checked the permissions and I tried running in sudo mode too.

Regards,
Bhaskar

**Comment by neubig** [comment]
This error tends to occur when either `model` has a different shape than the parameters stored in `in`, or or when you're using a different version of Boost to save the model than the version that is used to load the model. These errors are unfortunately hard to debug in DyNet v 1.1, so it might be worth considering transitioning to v 2.0.

**Comment by BhaskarNallani** [comment]
Thank you neubig. 
Yes we like to move to V2.0 but the application has to change completely. 
I trained the model in using boost 1.63 and now it is loading. 
Thank you.
Regards,
Bhaskar
