### ISSUE TITLE
cmake ignores CUDNN_ROOT

### ISSUE THREAD

**Issue by jhasegaw** [clab/dynet#676]
I've set CUDNN_ROOT as requested, but cmake is ignoring the environment variable.  I don't know if that's what's causing all of the subsequent compile errors.  Here is the output:

[hasegawa@br006 build]$ export CUDNN_ROOT=/opt/packages/cuda/7.5/
[hasegawa@br006 build]$ ls $CUDNN_ROOT/lib64/*cudnn*
/opt/packages/cuda/7.5//lib64/libcudnn.so
/opt/packages/cuda/7.5//lib64/libcudnn.so.4
/opt/packages/cuda/7.5//lib64/libcudnn.so.4.0.7
/opt/packages/cuda/7.5//lib64/libcudnn_static.a

[hasegawa@br006 build]$ cmake .. -DEIGEN3_INCLUDE_DIR=/pylon2/ci560op/odette/tools/dynet/eigen -DPYTHON=`which python` -DBACKEND=cuda
-- BACKEND: cuda
CUDA_LIBRARIES: /opt/packages/cuda/7.5/lib64/libcudart.so
-- Failed to find CUDNN in path: /usr/local/cuda (Did you set CUDNN_ROOT properly?)
-- CUDNN not found, some dependent functionalities will be disabled
-- Eigen dir is /pylon2/ci560op/odette/tools/dynet/eigen
CMake Error: Error in cmake code at
/pylon2/ci560op/odette/tools/dynet/dynet/build/dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-param-nodes.cu.o.depend:1:
Parse error.  Expected a command name, got unquoted argument with text "".
CMake Error at /usr/share/cmake/Modules/FindCUDA.cmake:365 (include):
  include could not find load file:

    /pylon2/ci560op/odette/tools/dynet/dynet/build/dynet/CMakeFiles/gdynet.dir//gdynet_generated_gpu-param-nodes.cu.o.depend
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindCUDA.cmake:1214 (cuda_include_nvcc_dependencies)
  /usr/share/cmake/Modules/FindCUDA.cmake:1419 (CUDA_WRAP_SRCS)
  dynet/CMakeLists.txt:153 (cuda_add_library)

CMake Error: Error in cmake code at
/pylon2/ci560op/odette/tools/dynet/dynet/build/dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-tensor.cu.o.depend:1:
Parse error.  Expected a command name, got unquoted argument with text "".
CMake Error at /usr/share/cmake/Modules/FindCUDA.cmake:365 (include):
  include could not find load file:

    /pylon2/ci560op/odette/tools/dynet/dynet/build/dynet/CMakeFiles/gdynet.dir//gdynet_generated_gpu-tensor.cu.o.depend
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindCUDA.cmake:1214 (cuda_include_nvcc_dependencies)
  /usr/share/cmake/Modules/FindCUDA.cmake:1419 (CUDA_WRAP_SRCS)
  dynet/CMakeLists.txt:153 (cuda_add_library)

CMake Error: Error in cmake code at
/pylon2/ci560op/odette/tools/dynet/dynet/build/dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-training.cu.o.depend:1:
Parse error.  Expected a command name, got unquoted argument with text "".
CMake Error at /usr/share/cmake/Modules/FindCUDA.cmake:365 (include):
  include could not find load file:

    /pylon2/ci560op/odette/tools/dynet/dynet/build/dynet/CMakeFiles/gdynet.dir//gdynet_generated_gpu-training.cu.o.depend
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindCUDA.cmake:1214 (cuda_include_nvcc_dependencies)
  /usr/share/cmake/Modules/FindCUDA.cmake:1419 (CUDA_WRAP_SRCS)
  dynet/CMakeLists.txt:153 (cuda_add_library)

CMake Error: Error in cmake code at
/pylon2/ci560op/odette/tools/dynet/dynet/build/dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-nodes-matrixmultiply.cu.o.depend:1:
Parse error.  Expected a command name, got unquoted argument with text "".
CMake Error at /usr/share/cmake/Modules/FindCUDA.cmake:365 (include):
  include could not find load file:

    /pylon2/ci560op/odette/tools/dynet/dynet/build/dynet/CMakeFiles/gdynet.dir//gdynet_generated_gpu-nodes-matrixmultiply.cu.o.depend
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindCUDA.cmake:1214 (cuda_include_nvcc_dependencies)
  /usr/share/cmake/Modules/FindCUDA.cmake:1419 (CUDA_WRAP_SRCS)
  dynet/CMakeLists.txt:153 (cuda_add_library)

-- Found Cython version 0.25.2

--- CUDA: CUBLAS: /opt/packages/cuda/7.5/lib64/libcublas.so RT: /opt/packages/cuda/7.5/lib64/libcudart.so
-- Configuring incomplete, errors occurred!
[hasegawa@br006 build]$

**Comment by zhisbug** [comment]
You are using 4.0. Please use 5.1 instead.

**Comment by jhasegaw** [comment]
5.1 of what?  My CUDA is 7.5.  I just now updated cmake from 2.8.11 to 3.7, and gcc from 4.8 to 5.3.  These changes reduce my errors to just the following.  ... If you look at the CMakeError.log, it seems to indicate that it can't find libpthread.so.  That exists as /usr/lib/libpthread-2.17.so.  

Command line output:____________________________________________________________________________
$ cmake .. -DEIGEN3_INCLUDE_DIR=/pylon2/ci560op/odette/tools/dynet/eigen -DPYTHON=`which python3` -DBACKEND=cuda
-- BACKEND: cuda
CUDA_LIBRARIES: /opt/packages/cuda/7.5/lib64/libcudart_static.a;-lpthread;dl;/usr/lib64/librt.so
-- Failed to find CUDNN in path: /usr/local/cuda (Did you set CUDNN_ROOT properly?)
-- CUDNN not found, some dependent functionalities will be disabled
-- Eigen dir is /pylon2/ci560op/odette/tools/dynet/eigen
CMake Error at build/dynet/CMakeFiles/gdynet.dir/gdynet_generated_gpu-param-nodes.cu.o.depend:1:
  Parse error.  Expected a command name, got unquoted argument with text "".
Call Stack (most recent call first):
  /opt/packages/cmake-3.7.2/share/cmake-3.7/Modules/FindCUDA.cmake:418 (include)
  /opt/packages/cmake-3.7.2/share/cmake-3.7/Modules/FindCUDA.cmake:1493 (cuda_include_nvcc_dependencies)
  /opt/packages/cmake-3.7.2/share/cmake-3.7/Modules/FindCUDA.cmake:1723 (CUDA_WRAP_SRCS)
  dynet/CMakeLists.txt:153 (cuda_add_library)


-- Configuring incomplete, errors occurred!


CMakeError.log______________________________________________________________________________________
Determining if the pthread_create exist failed with the following output:
Change Dir: /pylon2/ci560op/odette/tools/dynet/dynet/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/gmake "cmTryCompileExec1335634892/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec1335634892.dir/build.make CMakeFile
s/cmTryCompileExec1335634892.dir/build
gmake[1]: Entering directory `/pylon2/ci560op/odette/tools/dynet/dynet/build/CMa
keFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /pylon2/ci560op/odette/tools/dynet/dynet
/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec1335634892.dir/CheckSymbolExists.c.
o
/usr/lib64/ccache/cc    -o CMakeFiles/cmTryCompileExec1335634892.dir/CheckSymbol
Exists.c.o   -c /pylon2/ci560op/odette/tools/dynet/dynet/build/CMakeFiles/CMakeT
mp/CheckSymbolExists.c
Linking C executable cmTryCompileExec1335634892
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec1335634892.dir/li
nk.txt --verbose=1
/usr/lib64/ccache/cc         CMakeFiles/cmTryCompileExec1335634892.dir/CheckSymb
olExists.c.o  -o cmTryCompileExec1335634892 -rdynamic
CMakeFiles/cmTryCompileExec1335634892.dir/CheckSymbolExists.c.o: In function `ma
in':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTryCompileExec1335634892] Error 1
gmake[1]: Leaving directory `/pylon2/ci560op/odette/tools/dynet/dynet/build/CMak
eFiles/CMakeTmp'
gmake: *** [cmTryCompileExec1335634892/fast] Error 2

File /pylon2/ci560op/odette/tools/dynet/dynet/build/CMakeFiles/CMakeTmp/CheckSym
bolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with th
e following output:
Change Dir: /pylon2/ci560op/odette/tools/dynet/dynet/build/CMakeFiles/CMakeTmp

Run Build Command:/usr/bin/gmake "cmTryCompileExec2530733324/fast"
/usr/bin/gmake -f CMakeFiles/cmTryCompileExec2530733324.dir/build.make CMakeFile
s/cmTryCompileExec2530733324.dir/build
gmake[1]: Entering directory `/pylon2/ci560op/odette/tools/dynet/dynet/build/CMa
keFiles/CMakeTmp'
/usr/bin/cmake -E cmake_progress_report /pylon2/ci560op/odette/tools/dynet/dynet
/build/CMakeFiles/CMakeTmp/CMakeFiles 1
Building C object CMakeFiles/cmTryCompileExec2530733324.dir/CheckFunctionExists.
c.o
/usr/lib64/ccache/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cm
TryCompileExec2530733324.dir/CheckFunctionExists.c.o   -c /usr/share/cmake/Modul
es/CheckFunctionExists.c
Linking C executable cmTryCompileExec2530733324
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTryCompileExec2530733324.dir/li
nk.txt --verbose=1
/usr/lib64/ccache/cc     -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cm
TryCompileExec2530733324.dir/CheckFunctionExists.c.o  -o cmTryCompileExec2530733
324 -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTryCompileExec2530733324] Error 1
gmake[1]: Leaving directory `/pylon2/ci560op/odette/tools/dynet/dynet/build/CMak
eFiles/CMakeTmp'
gmake: *** [cmTryCompileExec2530733324/fast] Error 2

**Comment by zhisbug** [comment]
Of course, I am saying cuDNN, as the caption of your issue indicates :)

**Comment by jhasegaw** [comment]
Oh, that worked - thank you!

**Comment by Aditi138** [comment]
Hey, I am facing a similar issue and I have 5.1 cudnn files under my CUDNN_ROOT folder, yet it seems to say that its unable to find CUDNN_ROOT. 
When I do ls $CUDNN_ROOT/ I see the files in that folder.
<img width="145" alt="screen shot 2018-02-15 at 8 44 13 pm" src="https://user-images.githubusercontent.com/29302213/36289964-16283aae-1291-11e8-93b6-02470b67920c.png">
