### ISSUE TITLE
SerializationSpec fails during build

### ISSUE THREAD

**Issue by shuheik** [clab/dynet#683]
With current master.

> [info] SerializationSpec:
[info] dynet
[info] - should create models with the right number of parameters
[info] model saver and model loader
/var/folders/41/1rxgyck52f5c72_h11lscr_m0000gn/T/dynet_test7800056718491685052serialization_spec
[info] - should handle simplernnbuilder correctly *** FAILED ***
[info]   0.0 was not -0.5364716 plus or minus 1.0E-5 (SerializationSpec.scala:13)
[info] model saver and model loader
[info] - should handle vanillalstmbuilder correctly *** FAILED ***
[info]   0.0 was not 0.27130622 plus or minus 1.0E-5 (SerializationSpec.scala:13)

Maybe related to #663?

**Comment by neubig** [comment]
Just to confirm, this is using the Scala bindings, correct?

**Comment by shuheik** [comment]
Yes. Built with -DENABLE_SWIG=ON.

**Comment by shuheik** [comment]
This was caused by saver.done() missing from SerializationSpec.scala.
I sent a pull request #702 which solves this one.
