### ISSUE TITLE
update_epoch changes eta regardless of current eta

### ISSUE THREAD

**Issue by shuheik** [clab/dynet#684]
Trainer.eta can be modified directly as in
https://github.com/clab/dynet/blob/master/examples/cpp/rnnlm/train_rnnlm.cc#L271-L272
```
if (eta_decay_onset_epoch && completed_epoch >= (int)eta_decay_onset_epoch)
  sgd->eta *= eta_decay_rate;
```

Trainer.update_epoch() increments epoch and changes eta according to eta0, epoch and eta_decay, regardless of current eta.
https://github.com/clab/dynet/blob/master/dynet/training.h#L72
```
void update_epoch(real r = 1) {
  epoch += r;
  eta = eta0 / (1 + epoch * eta_decay);
  }
```

So it looks that if eta is changed directly and update_epoch is called after that, the first change to eta is cancelled.
Maybe it's intended but it looks confusing to me.

**Comment by neubig** [comment]
I agree this is confusing. I'll think about a good way to simplify the interface.

**Comment by neubig** [comment]
OK, we simplified the interface and hopefully made it more intuitive, see here: https://github.com/clab/dynet/pull/695
