### ISSUE TITLE
make with GPU fails

### ISSUE THREAD

**Issue by weidler** [clab/dynet#685]
[make.txt](https://github.com/clab/dynet/files/1150292/make.txt)

make -j 4 exits like that:

```
[ 24%] Building CXX object dynet/CMakeFiles/dynet.dir/weight-decay.cc.o  
[ 24%] Building CXX object dynet/CMakeFiles/dynet.dir/treelstm.cc.o  
[ 25%] Linking CXX shared library libdynet.so  
[ 25%] Built target dynet  
Makefile:138: recipe for target 'all' failed  
make: *** [all] Error 2  
```
I ran cmake like this:
`cmake .. -DEIGEN3_INCLUDE_DIR=/home/weidler/dynet-base/eigen -DPYTHON=/usr/bin/python3 -DBACKEND=cuda`

which finished without errors.

Installing **without** GPU support works perfectly fine.
I use 
- Debian 9.0 (stretch)
- dynet 2.0
- Cuda 8
- cuDNN 5.1

I added the verbose log file of the make process to the issue.

What appears "fishy" to me:

```
/usr/include/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 5 are not supported!
```
which may be caused by debian stretch, as this version now uses gcc 6.xx

```
CMake Error at gdynet_generated_gpu-ops.cu.o.cmake:218 (message):
Error generating
/home/weidler/dynet-base/dynet/build/dynet/CMakeFiles/gdynet.dir//./gdynet_generated_gpu-ops.cu.o
```
that looks a little strange too...

**Comment by neubig** [comment]
Could you please take a look here, follow the directions, and send the entire error log? http://dynet.readthedocs.io/en/latest/debugging.html#asking-questions-reporting-bugs

**Comment by weidler** [comment]
Ok, it somehow works now. Probably Cuda/cuDNN needed a reboot. Sorry for bothering.

**Comment by weidler** [comment]
I just noticed I was wrong about my assumption, I just messed up some stuff in the background such that it worked because I installed without GPU support. I added the verbose error log to the initial question.

**Comment by weidler** [comment]
Ok I managed to install dynet 2.0 after getting gcc4.9 from the old debian jessie repositories. Though, now, when I try to import dynet this error occurs:

```
import dynet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/weidler/dynet-base/dynet/build/python/dynet.py", line 17, in <module>
    from _dynet import *
ImportError: /home/weidler/dynet-base/dynet/build/python/_dynet.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN5dynet13TextFileSaver4saveERKNS_19ParameterCollectionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

This was already mentioned similarly in issue #649 but hasnt been resolved yet. Following your suggestion there, i tried to remove any old installs of dynet, but it changed nothing.

**Comment by philip30** [comment]
Hey, could you try to do the cmake once again and make sure to include the -DPYTHON=`which python` in the command line parameter. This was once my problem. Also, make sure you remove the old dynet first.

**Comment by weidler** [comment]
I did the whole thing again on a fresh install of Debian 9, first trying the pip installation which failed on an issue already mentioned in another issue. I then wen through the manual installation, which still fails with the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/weidler/dynet-base/dynet/build/python/dynet.py", line 17, in <module>
    from _dynet import *
ImportError: /home/weidler/dynet-base/dynet/build/python/_dynet.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN5dynet13TextFileSaver4saveERKNS_19ParameterCollectionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

I used 
- gcc-4.9 from the jessie repositories
- cuda 8
- cudnn 7

The Error occurs not only when trying to use the library after runnin setup.py but also if just trying to call it from within /home/weidler/dynet-base/dynet/build/python/

I added `export DYLD_LIBRARY_PATH=/home/weidler/dynet-base/dynet/build/dynet/:$DYLD_LIBRARY_PATH` to my `.profile and `.bashrc`

**Comment by neubig** [comment]
I think probably this is fixed with recent changes to the install script. If not, please re-open.
