### ISSUE TITLE
Can't run DyNet after installing with pip

### ISSUE THREAD

**Issue by vicmak** [clab/dynet#690]
Hi !
I am running Mac with OS 10.12.5
It is a new machine without any previous installations of DyNet on it.
I installed DyNet with pip. The installation was successful, and everything was looking good, without any errors or exceptions.

However, I can't run a DyNet program now.
already on the line of:

    from dynet import *

I get the following exception
/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/macbook/PycharmProjects/stamproject/setup_dynet.py

Traceback (most recent call last):
  File "/Users/macbook/PycharmProjects/stamproject/setup_dynet.py", line 1, in <module>
    from dynet import *
  File "build/bdist.macosx-10.12-x86_64/egg/dynet.py", line 17, in <module>
  File "build/bdist.macosx-10.12-x86_64/egg/_dynet.py", line 7, in <module>
  File "build/bdist.macosx-10.12-x86_64/egg/_dynet.py", line 6, in __bootstrap__
ImportError: dlopen(/Users/macbook/Library/Caches/Python-Eggs/dyNET-0.0.0-py2.7-macosx-10.12-x86_64.egg-tmp/_dynet.so, 2): Library not loaded: /private/var/folders/0b/bjty_21d5wxb2d3d3rjgzzvr0000gn/T/pip-build-hdlNus/dynet/build/py2.7-64bit/dynet/libdynet.dylib
  Referenced from: /Users/macbook/Library/Caches/Python-Eggs/dyNET-0.0.0-py2.7-macosx-10.12-x86_64.egg-tmp/_dynet.so
  Reason: image not found

Thanks a lot for help!

**Comment by vicmak** [comment]
I found the solution here:

https://github.com/clab/dynet/blob/master/doc/source/python.rst

However, I would suggest that path/to/dynet would be more explicitly specified near the explanation about the error. That is , it is the folder where ibdynet.dylib resides.

The following solved to problem for me:

export DYLD_LIBRARY_PATH=/Users/macbook/anaconda/lib/:$DYLD_LIBRARY_PATH

**Comment by mayinggator** [comment]
Hi, I have the same problem with you 

    from _dynet import *

ImportError: dlopen(/Applications/anaconda/lib/python2.7/site-packages/_dynet.so, 2): Library not loaded: libdynet.dylib
  Referenced from: /Applications/anaconda/lib/python2.7/site-packages/_dynet.so
  Reason: image not found

I tried your method, which is write the following sentence in bash:
export DYLD_LIBRARY_PATH=/Users/macbook/anaconda/lib/:$DYLD_LIBRARY_PATH

But it still not works. Also I did not find ibdynet.dylib  in my computer, is it in the same folder as _dynet.so? 

Do you have any suggestion?
