### ISSUE TITLE
no member named serialize in dynet 2.0

### ISSUE THREAD

**Issue by anglil** [clab/dynet#698]
I encountered the following error:
‘class dynet::Dict’ has no member named ‘serialize’
when compiling with dynet 2.0 the code which was developed under dynet 1.1. What change should I make to make the original code compilable?

**Comment by neubig** [comment]
I'd suggest using the `get_words()` member of Dict to get the vector of words and save them to a file one line at a time. Then, at test time, you can read this file one word at a time and call `convert()` to re-create the vocabulary.
