### ISSUE TITLE
Dynet Softmax does not sum up to 1 for certain inputs.

### ISSUE THREAD

**Issue by philip30** [clab/dynet#699]
This is the counter test case:
``` python
import dynet

x = dynet.vecInput(2)
x.set([-0.14982196688652039, 0.28194859623908997])
y = dynet.softmax(x)
assert(sum(y.value()) == 1)
```

**Comment by pmichel31415** [comment]
Yes I have encountered this issue as well but i think it's just floating point inaccuracies. For me the above code gives an error of order 3e-8

**Comment by philip30** [comment]
It's a bit problematic if it produces a probability that does not sum up to 1 actually. For example, we can't put that to numpy.random.choice(2, p=softmax_from_dynet()) because the above's assertion failed.

Previously I used chainer and chainer does not have this problem. Maybe we can do better?

**Comment by pmichel31415** [comment]
Yes, usually I manually renormalize before using choice.

I am not sure if we should change the logsumexp code or just round the values when calling `.values()`. The tolerance in the tests is 1e-3...

Maybe @neubig can tell us

**Comment by neubig** [comment]
I'd recommend using `categorical_sample_log_prob()` in DyNet instead: https://github.com/clab/dynet/blob/master/python/_dynet.pyx#L1327

Note that this functionality is only lightly tested. Also it's not in the Python documentation at readthedocs yet, and should probably be added, so I won't close the issue until it is.

**Comment by philip30** [comment]
It gives me this error when using that. It seems that it is a tensor method? I think it would be nice if we can also call that from dynet package.

Way of calling:
```
softmax.tensor_value().categorical_sample_log_prob()
```

Error:
```
libc++abi.dylib: terminating with uncaught exception of type std::invalid_argument: Dynet does not support both dynamic increasing of memory pool size, and automatic batching or memory checkpointing. If you want to use automatic batching or checkpointing, please pre-allocate enough memory using the --dynet-mem command line option (details http://dynet.readthedocs.io/en/latest/commandline.html).
```

**Comment by neubig** [comment]
As you can see in the error, this problem could have been solved by using the `--dynet-mem` command line option. However, it can also be solved permanently by the small change I just sent a PR for in #700, so once I merge this to master (pending unit tests), this problem should be fixed without specifying the command line argument.

**Comment by philip30** [comment]
Got it, thank you :)

**Comment by neubig** [comment]
OK, #700 is merged. Not exactly summing to one due to numerical precision issues is not really a bug (it'd be better if it did for compatibility with numpy, but it's not trivial to implement and not super-important), so I'll close this issue.
