### ISSUE TITLE
Sparse update for embedding matrix technically incorrect for momentum (but probably better)

### ISSUE THREAD

**Issue by honnibal** [clab/dynet#70]
Hi,

I noticed this issue in my own implementation, and remembered that your solvers also use a sparse update implementation for the embedding matrix. I thought I'd drop you a note.

The issue is that most momentum-based solvers involve some sort of exponential decay on the momentum vector. In my implementation, this decay was being applied unevenly, because the solver would only be called for words present in the minibatch. If I'm reading your implementation right, I think the same is true for you.

The technically correct solution is pretty obvious --- we can just track a timestamp, and do the update lazily as `momentum ** (current_time - time_of_last_update)`.

However, in practice I think this solution might be worse than the "bug". It would mean rare words get no momentum, because we can expect them to have a long time between updates. Alternatively we could set the momentum decay really low, which would make the gradients of the rare words too sticky.

For the classical momentum, the "bug" version means that the momentum is simply the EMA of the _active_ gradients for that word. I'm satisfied with this.

However, I think there might be some problem for other solvers, such as Adam, which also take the number of overall updates as a parameter. We might consider using the number of updates for the feature, instead. In my implementation, I happen to have the timestamp of the last change to the feature, and I didn't want to track another book keeping variable for a minor thing. So I'm guessing the number of updates using the time since last change, `time / (time-last_upd)`.

I doubt that there's a huge difference in results from this issue, either way. But it might be good to note ways in which the implementation behaves differently from others. A similar situation occurs for regularization penalties. I saw from another issue that you're aware of that.

Best,
Matt

**Comment by neubig** [comment]
Hi Matt,
Thanks for the heads up on this! I'm pretty sure your analysis is correct, but it may be a while before we actually have some time to go in and fix and/or document it.

**Comment by neubig** [comment]
It is now possible to optimize using a dense update that considers momentum exactly correctly, and the behavior is (nominally) documented: https://github.com/clab/dynet/commit/3b60eec570672a3b5088e21b3849deaeb980ab18
