### ISSUE TITLE
colwise_add for conv

### ISSUE THREAD

**Issue by talbaumel** [clab/dynet#705]
Hi,
I want to write a convolution with bias.
After running `conv2d` the output is:
`(1 x sentence_size x num_of_channels)`
The bias should be of size `num_of_channels`
When using `colwise_add` to add the bias it requires me to transpose before

Any chance I can do it without the transpose?

Thanks, Tal

*According to the documentation of `colwise_add`:
```
x: An MxN matrix
bias: A length M vector
```

**Comment by pmichel31415** [comment]
Maybe [conv2d_bias](http://dynet.readthedocs.io/en/latest/python_ref.html#dynet.conv2d_bias) would solve your problem.

**Comment by talbaumel** [comment]
Yes
