### ISSUE TITLE
[Python] Categorical sample log softmax.

### ISSUE THREAD

**Issue by philip30** [clab/dynet#708]
It turns out that the function just sample "0" all the time in this bellow code. Maybe I am using the function incorrectly?

``` python
import dynet

x = dynet.inputVector([1, 2, 3, 4, 5, 6, 7])
log_softmax = dynet.log_softmax(x)

# [ 0.0015683   0.00426308  0.01158826  0.03150016  0.0856263   0.23275644 0.63269758]
print(dynet.exp(log_softmax).npvalue())

for i in range(1000):
  # sample
  sample = log_softmax.tensor_value().categorical_sample_log_prob()
  # printing [0] all the times?
  print(sample.as_numpy())
```
I want to try to debug it though. But I really can't understand the code in tensor.cc ....

**Comment by neubig** [comment]
I'll take a look at this (and I can explain the code in `tensor.cc` etc. later.
