### ISSUE TITLE
Segmentation fault in save (v2)

### ISSUE THREAD

**Issue by vered1986** [clab/dynet#71]
Saving any non-empty model results in "Segmentation fault (core dumped)":

The following code produces this error:

```python
from gpycnn import *
m = Model()
m.save('model')
bilstm_builder = BiRNNBuilder(1, 2, 100, m, LSTMBuilder)
m.save('model')
```

The first save operation works well, and the second causes a segmentation fault. It also happens when `bilstm_builder = BiRNNBuilder(1, 2, 100, m, LSTMBuilder)` is replaced with a lookup table initialization.

Thanks in advance!

**Comment by yoavg** [comment]
thanks for the report. does this happen also with the non-gpu version?

**Comment by vered1986** [comment]
No, the same code worked when I replaced gpycnn with pycnn.

**Comment by yoavg** [comment]
thanks, I will look into it.

**Comment by nsantacruz** [comment]
Note, I'm also getting a segmentation fault even when using pycnn using the same code in v2.
```python
from pycnn import *
m = Model()
m.save('model')
bilstm_builder = BiRNNBuilder(1, 2, 100, m, LSTMBuilder)
m.save('model')
```

**Comment by yoavg** [comment]
Try the current master branch of clab/dynet.
It is v2, with the fix for the current bug.
Let us know if you still have problems.

The installation instructions for the python module in this branch may not be 100% accurate, but will be fixed in the coming days.

**Comment by nsantacruz** [comment]
Thanks. Can I just switch branches? Or do I need to reinstall? I know that the v2 branch requires the updated version of eigen.

**Comment by yoavg** [comment]
any change requires a re-install (because you will need to recompile the
cpp parts).

The following should probably work:

git clone https://github.com/clab/dynet.git
hg clone https://bitbucket.org/eigen/eigen
cd dynet
mkdir build
cmake .. -DEIGEN3_INCLUDE_DIR=../eigen -DPYTHON=`which python`
-DBACKEND=cuda
make -j 2
cd python
python setup.py install

**Comment by nsantacruz** [comment]
I'm getting 
```
error: non-constant-expression cannot be
      narrowed from type 'unsigned int' to 'value_type' (aka 'int') in initializer list [-Wc++11-narrowing]
```

when running `make -j 2`
I know I can get rid of this error/warning by including `-Wno-narrowing` in the compiler flags, but I can't find where to add that in the makefile. I'm running OSX

**Comment by neubig** [comment]
Hi @nsantacruz, could you try again with the latest version. If you still are having problems, could you delete the whole build directory to build from scratch, then when you run make, do `make VEBOSE=1 &> make.log` and attach the `make.log` file to your response? Thanks!

**Comment by nsantacruz** [comment]
Attached the make log file. Again, it seems to have been the same `narrowing` C++ error. Thanks again.
[make.txt](https://github.com/clab/dynet/files/521118/make.txt)

**Comment by neubig** [comment]
This is potentially fixed by this patch: https://github.com/clab/dynet/commit/7fbde7c63452deff265969477adb0e7b2c5f4047

Could you download this and try again?

**Comment by neubig** [comment]
I'm guessing that this fixes the compile problem, so I'm going to close this bug. If the problem still exists, let's create a new issue with a more descriptive name.

**Comment by nsantacruz** [comment]
Thanks a lot. That fixed my issue

**Comment by vered1986** [comment]
Hi,
I installed the new version following the instructions in [PYINSTALL.md](https://github.com/clab/dynet/blob/master/PYINSTALL.md) (currently the CPU version; the instructions for the GPU version haven't been updated). Now I get the segmentation fault whenever I call save:

```python
from dynet import *
m = Model()
m.save('model')
```

I get the following error:
```
terminate called after throwing an instance of 'boost::archive::archive_exception'
  what():  output stream error
Aborted (core dumped)
```

Thanks!
