### ISSUE TITLE
how to handle "Magnitude of gradient is bad: nan" in Python?

### ISSUE THREAD

**Issue by rasoolims** [clab/dynet#711]
Hi, 

This happens very infrequently so I am not able to reproduce it in small examples. I guess that happens because of some division by zero after some underflow.

My question is that is there anyway to handle this in python?

Thanks

**Comment by neubig** [comment]
Yes, anywhere where you think you might be dividing by zero, you can add a small constant (e.g. 1e-6) to prevent NaNs. This should solve your problem.

**Comment by rasoolims** [comment]
What if I don't know a priori which part is making the nan problem?

I mean I want something like this:

```python
if CONDITION:
     trainer.update()
```

**Comment by neubig** [comment]
Try immediate computation and gradient checking: http://dynet.readthedocs.io/en/latest/debugging.html#immediate-computation

**Comment by rasoolims** [comment]
I know. But what if having NAN is inevitable and I just want to skip those batches that give NAN or INF? I tried the solution in this issue https://github.com/clab/dynet/issues/515, but it gave me error.

**Comment by neubig** [comment]
I would say NaN is not inevitable, but an indication that there is something wrong with your model that will cause problems down the road. It'd be better to fix the core of the issue than attempt to ignore it.
