### ISSUE TITLE
Need to precisely set the amount of memory for FOR,BACK,PARAM?

### ISSUE THREAD

**Issue by jcyk** [clab/dynet#714]
Hi, 
Initial memory allocation really matters!
Though the memory use for Dynet will be expanded automatically,  I found I need to precisely set the memory allocation at the initialization stage (```--dynet-mem MEM```) to get my code work through my dataset. Otherwise, I will see `CUDA failure in cudaMalloc(&ptr, n)
out of memory`

It is a pain to do so. 
Also the command line actually accepts either one or four arguments
`--dynet-mem MEM`
`--dynet-mem FOR,BACK,PARAM,SCRATCH`
The document should be updated.

**Comment by jcyk** [comment]
I am running on the GPU version.
Manually attempts to set `--dynet-mem FOR,BACK,PARAM,SCRATCH`.

**Comment by liesun1994** [comment]
mark :)

**Comment by neubig** [comment]
Yes, we should fix the documentation. In the current implementation it is necessary to split the memory in this way.

Could you try setting `--dynet-mem 4` and seeing whether this fixes your problem? This will allocate one megabyte to each memory pool, and expand them dynamically, which may be better than the default of 512 in terms of memory efficiency. Also, what are the values of `--dynet-mem` that finally allowed it to work?

**Comment by jcyk** [comment]
setting `--dynet-mem 4` will fix my problem.
I am using  `--dynet-mem 3000, 3000, 500, 500`, (total memory of my GPU is 8G) and everything works fine.
Is it because, by default, the amount of memory for each use has to be same?

**Comment by neubig** [comment]
By default the amount of memory given to each pool should be the same. `--dynet-mem 4` should solve the problem because it would start each pool with 1MB, and increase each pool by 1MB every time you exceed the allotted amount. We'll need to look into this further to try to figure out the problem.

**Comment by jcyk** [comment]
Hi, @neubig . I think I found the reason.
In fact, when exceed the allotted amount, the memory pool will always increase by the **initial capacity by command line or by default** every time, because it changes.
See [here] (https://github.com/clab/dynet/blob/master/dynet/aligned-mem-pool.cc#L37).
The initial capacity will be reset when `free()` is called. After that, expanding at each time will be way too aggressive.

I note `cap` is not used to indicate the capacity of the mem pool. Should be renamed to something like "expanding_unit"?

**Comment by jcyk** [comment]
Also I think it may be better to break the binding between `expanding_unit` and `initial capacity` unless there is a good strategy.

**Comment by neubig** [comment]
Ahh, good catch! This is a logic error in the code. I basically agree with all your comments, so a pull request would be welcome. I'm not sure the best way to choose `expanding_unit`, but perhaps a constant of 16 or 32 would be reasonable.

**Comment by jcyk** [comment]
Take a look at #730. I set the default `expanding_unit` to be 16MB. 
I choose the smaller one because I think it is generally safer. And the inefficiency problem can be solved once `free()` is called, so it should just hurt in the beginning. 
`cap` is now tracking the real total memory use.
