### ISSUE TITLE
pip install does not support GPU

### ISSUE THREAD

**Issue by neubig** [clab/dynet#717]
I wasn't able to find any documentation about how to install via pip with GPU support. Is this possible? If so, the doc should probably be updated. @danielhers, any ideas?

**Comment by danielhers** [comment]
Sorry, this is not possible yet. Should be possible to implement either by
adding flags, environment variables or a separate PyPI entry.

**Comment by neubig** [comment]
@danielhers OK, thanks. We're going to have multi-device support ( #92 ) soon, which will probably change the overall compile pipeline to be simpler. I think we can revisit it at that point.

**Comment by neubig** [comment]
Fixed by https://github.com/clab/dynet/pull/795

**Comment by danielhers** [comment]
Has this been verified?

**Comment by neubig** [comment]
Yes, I checked it and it works in my environment.

**Comment by danielhers** [comment]
Excellent! Thanks!
