### ISSUE TITLE
Example of integrating DyNet with TensorBoard

### ISSUE THREAD

**Issue by neubig** [clab/dynet#727]
TensorBoard provides really nice visualization capability for learning models, and it would be nice to have an example of interfacing a DyNet learning process with TensorBoard. It looks like this package might be nice a nice way of doing so (although other options would be welcome): https://github.com/torrvision/crayon

Contributions are welcome!

**Comment by neubig** [comment]
FYI: @antoniovilarinholopes and @pmichel31415 . We talked about this, and a quick example would be nice if you have time to try it out.

**Comment by antoniovilarinholopes** [comment]
@neubig I gave a look at crayon and it should do the integration with tensorboard, I tested it locally and I think it should be enough. Can I use one of the examples from dynet and just add the tensorboard support with crayon?

**Comment by neubig** [comment]
Yep, the xor or rnnlm examples might be good ones to use.
