### ISSUE TITLE
Force GPU/CPU use

### ISSUE THREAD

**Issue by talbaumel** [clab/dynet#732]
Hi, 
Installed latest version (finally using only pip, THANKS!!)
And I wanted to verify everything with the GPU vs CPU example: `https://github.com/clab/dynet/blob/master/examples/python/cpu_vs_gpu.py`

I got an error: `ImportError: No module named '_gdynet'`

**Comment by talbaumel** [comment]
When manually installing with GPU support it is working fine

**Comment by neubig** [comment]
As noted here, unfortunately installing on pip does not support GPU: https://github.com/clab/dynet/issues/717

We'll be working on this shortly, but for the time being you'll have to do manual install. (I'll close this because it's a duplicate, but that doesn't mean it's not important :) )
