### ISSUE TITLE
vanilla lstm without layer normalization

### ISSUE THREAD

**Issue by Oneplus** [clab/dynet#734]
if the layer normalization is not activated in VanillaLSTM (aka `ln_lstm=false`), the size of `ln_param_vars` is zero, but it's still accessed in `add_input_impl` (https://github.com/clab/dynet/blob/master/dynet/lstm.cc#L443). This will lead to an assertation error in MSVC debug mode and I believe it is an illegal memory assessment.

**Comment by neubig** [comment]
Fixed by https://github.com/clab/dynet/pull/735
