### ISSUE TITLE
installation of newest dynet ，./examples folder are missed in folder builder

### ISSUE THREAD

**Issue by liesun1994** [clab/dynet#738]
Hi，
I'm installing newest dynet，after the command "make -j 2"， examples folder is not found in folder build .
Something wrong with dynet 2.0 ? （dynet 1.1 works well）

**Comment by xunzhang** [comment]
It is expected since we want to short installing(actually compiling c++ code) time. By default is won't be compiled but you can turn it on by `-DENABLE_CPP_EXAMPLES=ON` during configuration.

**Comment by neubig** [comment]
Yes. This is a recent change that we made to reduce compile time. It's documented in the C++ installation instructions though, so I think it's OK to close the issue.

**Comment by liesun1994** [comment]
Thanks ~~ Ah , solved this problem ~
