### ISSUE TITLE
using CompactVanillaLSTMBuilder with dropout produces error

### ISSUE THREAD

**Issue by jcyk** [clab/dynet#739]
I tried the new CompactVanillaLSTMBuilder, but when I set dropout on it, I got
```
CUDA failure in cudaMemcpy(val.v, t, sizeof(real) * val.d.size(), cudaMemcpyHostToDevice)
an illegal memory access was encountered
```
It only occurs on GPU.

**Comment by jcyk** [comment]
hi!
For nodes in `Dynet`, does the output of `dim_forward` equal to `fx.d` ?

**Comment by neubig** [comment]
@msperber, have you tested dropout on GPU? If not, could you take a look quickly?

**Comment by msperber** [comment]
Hmm I had tried it and it worked for me.. @jcyk could post a minimal example so I can reproduce this?

**Comment by jcyk** [comment]
Sorry for the late reply.
```
import dynet as dy
import numpy as np

dropout_x = 0.3
dropout_h = 0.3
batch_size = 5
inputs = np.random.randint(0, 100, (6, 5), dtype=np.int32)

pc = dy.ParameterCollection()
embs = pc.add_lookup_parameters((100, 10))
builder = dy.CompactVanillaLSTMBuilder(1, 10, 20, pc)

emb_inputs = [ dy.lookup_batch(embs, x) for x in inputs]
lstm = builder.initial_state()
builder.set_dropouts(dropout_x, dropout_h)
builder.set_dropout_masks(batch_size)
outputs = lstm.transduce(emb_inputs)
print outputs[-1].npvalue()
```
The error information:
```
CUDA failure in cudaMemcpy(&res[0], v.v, sizeof(real) * res.size(), cudaMemcpyDeviceToHost)
an illegal memory access was encountered
terminate called after throwing an instance of 'dynet::cuda_exception'
  what():  cudaMemcpy(&res[0], v.v, sizeof(real) * res.size(), cudaMemcpyDeviceToHost)
Aborted (core dumped)
```

**Comment by msperber** [comment]
Thank you! I'm currently traveling but will take a look as soon as I have a chance.

**Comment by msperber** [comment]
@jcyk I couldn't reproduce your problem, but would you mind checking if it still persists after the most recent commit?

**Comment by jcyk** [comment]
@msperber  Thanks! But the new PR didn't fix the error occurs in my environment.

Note the same error information as above.

However, I tried the following modification, and the problem disappeared. 
That is [using `vanilla_lstm_gates` instead of `vanilla_lstm_gates_dropout` with **manually "dropouted" inputs**] [code link.](https://github.com/jcyk/dynet/blob/my-mem-efficient-lstm/dynet/lstm.cc#L681-L685)
but, I still have no idea why it works but direct use of `vanilla_lstm_gates_dropout` did not.

Will this provide some hints to you?

**Comment by jcyk** [comment]
By the way, as I inspected the code. I found condition in this [line](https://github.com/clab/dynet/blob/master/dynet/lstm.cc#L681) could be considered as a minor bug? 

`(dropout_rate_h > 0.f)` should be => `(dropout_rate > 0.f || dropout_rate_h > 0.f)`

**Comment by FilippoC** [comment]
Indeed, I already corrected that for other LSTM classes : https://github.com/clab/dynet/pull/687/commits/f0a378ea709ca7f69e6fa6997b07c84c5a1c7f9b

**Comment by neubig** [comment]
Could you confirm if #787 has fixed this?

**Comment by jcyk** [comment]
The newest PR fixed my problem. Thanks @msperber @neubig
