### ISSUE TITLE
Unable to find GLIBCXX_3.4.20

### ISSUE THREAD

**Issue by napsternxg** [clab/dynet#751]
I installed dynet using the following instructions on my linux machine:

```
sudo apt-get install build-essential cmake mercurial

$ pip install git+https://github.com/clab/dynet#egg=dynet
Collecting dynet from git+https://github.com/clab/dynet#egg=dynet
  Cloning https://github.com/clab/dynet to /tmp/pip-build-ndgrzmvy/dynet
Requirement already satisfied: cython in /anaconda3/lib/python3.6/site-packages (from dynet)
Requirement already satisfied: numpy in /anaconda3/lib/python3.6/site-packages (from dynet)
Installing collected packages: dynet
  Running setup.py install for dynet ... done
Successfully installed dynet-0.0.0
```

When I try to run it on my jupyter notebook I get the following error:
```
ImportError                               Traceback (most recent call last)
<ipython-input-1-7769503f4e43> in <module>()
----> 1 import dynet as dy
      2 import numpy as np

/anaconda3/lib/python3.6/site-packages/dyNET-0.0.0-py3.6-linux-x86_64.egg/dynet.py in <module>()
     15     def print_graphviz(**kwarge):
     16         print("Run with --dynet-viz to get the visualization behavior.")
---> 17     from _dynet import *
     18 
     19 __version__ = 2.0

ImportError: /anaconda3/lib/python3.6/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /anaconda3/lib/libdynet.so)
```

I checked and I do have `g++ (Debian 4.9.2-10) 4.9.2` installed. 
I also checked the ldd version which is as follows:

```
$ ldd --version
ldd (Debian GLIBC 2.19-18+deb8u10) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

A related issue is  ContinuumIO/anaconda-issues#483

**Comment by neubig** [comment]
My guess is that you either installed DyNet outside of Anaconda, and are trying to run it inside of Anaconda, or vice-versa. Could you try to activate/deactivate Anaconda and see if it works?

If that doesn't fix the problem, you'll probably need to add the path to the appropriate library to your `LD_LIBRARY_PATH`.

**Comment by napsternxg** [comment]
@neubig if you notice the location where pip checks for packages you will see that the pip command is from anaconda. Furthermore, the dynet command is also run from inside of conda, as shown in the file 
throwing the error message. Also, my `LD_LIBRARY_PATH` is empty.

However, that doesn't matter now as I reinstalled dynet again from github and this time it ran successfully. So I will close the issue.  

Is there a conda package for dynet which I can use for installation ?

**Comment by neubig** [comment]
Hmm, can you create a completely clean anaconda environment and try to install there? Try running, for example:

    conda create --name test-dynet python=3 cython numpy
    pip install git+https://github.com/clab/dynet#egg=dynet

Then whatever code you're trying to run. I suspect you have extra stuff installed in your conda environment, which is causing DyNet to find an incompatible library.

**Comment by napsternxg** [comment]
This is fixed. I used a fresh environment and it works now. Details provided in https://github.com/clab/dynet/issues/773#issuecomment-325160082

This is related to Issue #773
