### ISSUE TITLE
pip install should show the correct version number

### ISSUE THREAD

**Issue by napsternxg** [clab/dynet#752]
I just installed dynet on my linux machine using pip. 

```
$ pip install git+https://github.com/clab/dynet#egg=dynet
Collecting dynet from git+https://github.com/clab/dynet#egg=dynet
  Cloning https://github.com/clab/dynet to /tmp/pip-build-ndgrzmvy/dynet
Requirement already satisfied: cython in /anaconda3/lib/python3.6/site-packages (from dynet)
Requirement already satisfied: numpy in /anaconda3/lib/python3.6/site-packages (from dynet)
Installing collected packages: dynet
  Running setup.py install for dynet ... done
Successfully installed dynet-0.0.0
```

I believe the Success command should show the correct dynet version instead of `0.0.0`

**Comment by danielhers** [comment]
The master branch is not a specific version though.
Installing from PyPI shows the correct version: `pip install dynet`.

**Comment by neubig** [comment]
OK. Maybe we can change the documentation to note that you can just do `pip install dynet` for the latest release, or the `pip install git+https://github.com/clab/dynet#egg=dynet` for the latest master branch.

**Comment by neubig** [comment]
We now have the __gitversion__ flag that allows you to see the git commit. https://github.com/clab/dynet/pull/1229

Installing with pip install dynet will give a real version number.
