### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by sunacc** [clab/dynet#753]
Hi, I met some problems after installing dynet by:
>xcode-select --install
brew install cmake hg python # Using homebrew.
pip install git+https://github.com/clab/dynet#egg=dynet

and the problem is:
>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>`
  File "build/bdist.macosx-10.12-intel/egg/dynet.py", line 17, in <module>
  File "build/bdist.macosx-10.12-intel/egg/_dynet.py", line 7, in <module>
  File "build/bdist.macosx-10.12-intel/egg/_dynet.py", line 6, in __bootstrap__
ImportError: dlopen(/Users/sunacc/.python-eggs/dyNET-0.0.0-py2.7-macosx-10.12-intel.egg-tmp/_dynet.so, 2): Library not loaded: /tmp/pip-build-mRuMZK/dynet/build/py2.7-64bit/dynet/libdynet.dylib
  Referenced from: /Users/sunacc/.python-eggs/dyNET-0.0.0-py2.7-macosx-10.12-intel.egg-tmp/_dynet.so
  Reason: image not found

After reading other issues, I tried add 
>export DYLD_LIBRARY_PATH=/path/to/dynet/build/dynet/:$DYLD_LIBRARY_PATH

but nothing is changed.

and I used `pip list` to see the version of dynet, finding it's `0.0.0`, is it normal?

**Comment by sunacc** [comment]
After manually installing, I have solved this problem.
But the version in pip list is still 0.0.0, should we modify it?

**Comment by neubig** [comment]
Yes, a pull request modifying the pip version would be appreciated.

**Comment by neubig** [comment]
Actually, on second thought: the master branch itself does not have a version, so 0.0.0 is perhaps correct. The version should be appropriate for the released packages.
