### ISSUE TITLE
Segmentation fault 11 (Mac OS 10.12.6)

### ISSUE THREAD

**Issue by prashantbudania** [clab/dynet#757]
I am getting a segmentation fault when I am trying to run dynet. It was working fine before but I made a fresh installation of dynet and now it is not working anymore. I tried deleting all (old) dynet folder/files and doing a manual installation but it is still showing the same error. I read somewhere that an older version might be creating a conflict but I made sure that there is no other version. 

`import dynet as dy`
`print dy.__version__`

This prints 2.0 but anything else than else shows the segmentation fault.

**Comment by neubig** [comment]
Could you run:

    lldb python
    run my_dynet_program.py
    bt

This should give you the location where the error is occurring.

**Comment by neubig** [comment]
Haven't heard about this, so I'll close.
