### ISSUE TITLE
comment typo

### ISSUE THREAD

**Issue by liweiiewil** [clab/dynet#760]
void ParameterNode::accumulate_grad(const Tensor& g) {
  if(params.p != nullptr)
    params.get_storage().accumulate_grad(g);
  else if(lparams.p != nullptr)
    lparams.get_storage().accumulate_grad(g);
  else
    // !!!here: ConstParameterNode should be ParameterNode !!!
    DYNET_RUNTIME_ERR("ConstParameterNode has neither Parameter nor LookupParameter");
}

**Comment by neubig** [comment]
Thanks! Fixed by https://github.com/clab/dynet/commit/d2a732613f445d87a6828fd8857f2f0efe44dd05
