### ISSUE TITLE
How to install an old version of dynet

### ISSUE THREAD

**Issue by egrcc** [clab/dynet#779]
Hello,

I want to install an old version, but the command 
```
pip install git+https://github.com/clab/dynet#egg=dynet
```
will install the latest version. What the command can I use to install an old version?

**Comment by FilippoC** [comment]
Did you try to checkout the commit you want to install and then manually call setup.py ?

**Comment by xunzhang** [comment]
Hi @egrcc , DyNet starts supporting pip installation from v2.0. If you want to install v1.1, you can build from source by your own: `git checkout v1.1` and then compile.

**Comment by egrcc** [comment]
@FilippoC @xunzhang thank you~ I have performed a manual install
