### ISSUE TITLE
Enable Travis CI test for pip installation on OSX

### ISSUE THREAD

**Issue by danielhers** [clab/dynet#784]
#596 enabled Travis CI test for pip installation on Linux, but on OSX it doesn't work because `libdynet.dylib` is not found. This can be resolved by adding its location to `DYLD_LIBRARY_PATH`. It's not `$TRAVIS_BUILD_DIR/build/dynet` because the pip installation creates a build directory inside `build` called something like `py3.4-64bit`, but instead of trying to figure that out, it should be possible to use the virtualenv, something like `$(dirname $(which python))/../lib` because it installs it into that location.

I've been trying forever to make the Python bindings work on OSX without requiring `DYLD_LIBRARY_PATH`, but I can't figure out how to add the lib properly to `RUNTIME_LIBRARY_DIRS`. Perhaps someone with more Mac experience can help.

**Comment by neubig** [comment]
Thanks for the pointer! This would be really nice to fix, so hopefully someone could help. I'll also take a look but I'm a bit swamped at the moment.

**Comment by danielhers** [comment]
So am I, otherwise I would have done it myself :)
I did open #783, which is related, and took a lot more time than I expected to fix...
