### ISSUE TITLE
dynet install error 

### ISSUE THREAD

**Issue by liesun1994** [clab/dynet#786]
Something wrong with my installing. 
Following the command: 
hg clone https://bitbucket.org/eigen/eigen/ -r 346ecdb
git clone https://github.com/clab/dynet.git
mkdir build
cd build
cmake .. -DEIGEN3_INCLUDE_DIR=/path/to/eigen -DENABLE_CPP_EXAMPLES=ON -DBACKEND=/usr/local/cuda-7.5

After last command, errors occurred. 
![image](https://user-images.githubusercontent.com/16813308/29355373-66c79820-82a3-11e7-9637-b5ab08285e51.png)

I am confused about the issue.

**Comment by neubig** [comment]
Replace `-DBACKEND=/usr/local/cuda-7.5` with `-DBACKEND=cuda -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-7.5`
