### ISSUE TITLE
error occurs while compiling newest dynet. 

### ISSUE THREAD

**Issue by liesun1994** [clab/dynet#802]
I am trying to install dynet on top of linux. 
But error occured while compling newest dynet. 
![image](https://user-images.githubusercontent.com/16813308/29515775-598746be-86a0-11e7-8d80-b5f1e4ab4f68.png)

Thx

**Comment by liesun1994** [comment]
error 2 : 
![image](https://user-images.githubusercontent.com/16813308/29516354-a59d30fc-86a2-11e7-95c7-675ba9a8bc3b.png)

**Comment by neubig** [comment]
It looks like Eigen is requesting the "hfloor" and "hciel" functions, but
these aren't recognized by your version of CUDA.

Could you please tell us your versions of CUDA and GCC? Are you using the
version of Eigen suggested in the manual installation instructions? Or the
newest version of Eigen?

**Comment by liesun1994** [comment]
Yeah, I am using the following command: 

    hg clone https://bitbucket.org/eigen/eigen/ -r 346ecdb

    cmake .. -DEIGEN3_INCLUDE_DIR=/home/kwang/freecode/dynet-base/eigen -DENABLE_CPP_EXAMPLES=ON -DBACKEND=cuda -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda-7.5

It seems that something missing in floder cuda-7.5 
![image](https://user-images.githubusercontent.com/16813308/29516593-825e9e90-86a3-11e7-89ba-f73b9ff34cd0.png)

Thank you very much !

**Comment by neubig** [comment]
I'm having trouble reproducing this. Could you try using the latest version of Eigen (e.g. `hg clone https://bitbucket.org/eigen/eigen/` with no `-r 346ecdb`) and see if it fixes the problem?

**Comment by liesun1994** [comment]
Something is missing with my cuda7.5，the problem fixed with newly cuda，thanks. my fault.I should pull the solution the time I fixed it. kun 在2017年08月25日 20:54，Graham Neubig 写道： I'm having trouble reproducing this. Could you try using the latest version of Eigen (e.g. hg clone https://bitbucket.org/eigen/eigen/ with no -r 346ecdb) and see if it fixes the problem? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by neubig** [comment]
OK, great!
