### ISSUE TITLE
setup.py pypandoc fails on Python 2.7

### ISSUE THREAD

**Issue by neubig** [clab/dynet#810]
It seems that pypandoc commands in `setup.py` are failing on Python 2.7?

https://twitter.com/haldaume3/status/900005830354980864

This is a temporary fix that should be good enough for now:
https://github.com/clab/dynet/pull/809

**Comment by danielhers** [comment]
Not sure it's because of Python 2 - this happens when `pypandoc` is installed (so no `ImportError`) but `README.md` is missing.

**Comment by neubig** [comment]
Maybe this is resolved?
