### ISSUE TITLE
in the docs for python, you also need to install cython

### ISSUE THREAD

**Issue by hal3** [clab/dynet#811]
in https://github.com/clab/dynet/blob/master/doc/source/python.rst

before doing the pip install git+...

you need to pip install cython

**Comment by ozancaglayan** [comment]
its actually instructed but towards the end of the document..

**Comment by xunzhang** [comment]
Addressed here: https://github.com/clab/dynet/commit/9cffa9c547b22c32673196de35a63c9baad6b386. Since current pip install needs to compile, `cython` is required. Once [dynet-657](https://github.com/clab/dynet/issues/657) is finished, I think it is no longer necessary. Thanks.
