### ISSUE TITLE
how to set --dynet-mem properly?

### ISSUE THREAD

**Issue by xc-kiwiberry** [clab/dynet#815]
emm... I want to ask that what's the meaning of "scratch" in "--dynet-mem FOR,BACK,PARAM,SCRATCH"?
emm... Does it mean that if I use "--dynet-mem FOR,BACK,PARAM,SCRATCH" to set memory, I should try many possibility until "cuda out-of-memory" disappear ?

I have been troubled by this problem for a long time, and I have glanced over all issues about "out of memory". But I think some bugs have been fixed. So I still don't know what I should do explicitly on the "--dynet-mem".

Is the "--dynet-mem 4" can add the memory in precision of 1MB? Or dynet has already implemented this implicitly, so I don't need to set "--dynet-mem 4"?

so..maybe my problem is I don't know the stratagem of Dynet to alloc memory.

Thank you sincerely!

**Comment by jcyk** [comment]
I think SCRTCh is for extra memory that is needed temporarily.

By default the amount of memory given to each pool should be the same, 128MB each. You can use--dynet-mem to specify the amount of memory for each pool. In either way, Dynet will automatically increase a pool by 16MB every time you exceed the allotted amount.

**Comment by neubig** [comment]
Yes, @jcyk's explanation is correct.
