### ISSUE TITLE
Doc about setting global parameters in DyNet is stale

### ISSUE THREAD

**Issue by neubig** [clab/dynet#822]
The doc here doesn't mention the new way of setting DyNet parameters through `dynet_config`:
> http://dynet.readthedocs.io/en/latest/python_ref.html#dynet.DynetParams

@xunzhang, could you take a look?

**Comment by xunzhang** [comment]
Sure, it is been mentioned here http://dynet.readthedocs.io/en/latest/python.html#using-the-gpu-from-python. For the `python_ref` page, let me fix this part.
