### ISSUE TITLE
SelectRows and SelectColumns should be generalized

### ISSUE THREAD

**Issue by neubig** [clab/dynet#823]
Currently SelectRows and SelectColumns do not work on tensors in general (e.g. SelectColumns only works on square matrices). These should be generalized to something like SelectByDim, and make corresponding select_rows and select_cols expressions reference SelectByDim.

**Comment by redpony** [comment]
We should ensure that whatever solution we come up with for this also
solves the Python __getitem__ issue (#767). These are two halves of one
issue.
