### ISSUE TITLE
Please make a cross-platform conda binary available

### ISSUE THREAD

**Issue by napsternxg** [clab/dynet#829]
Installing dynet in different machines can be a hassle at times (requiring installation of cmake, mercurial, eigen, MKL etc.), especially on Windows. It would be great if there is a dynet binary available on a conda channel for various OSs similar to how pytorch does it via `conda install pytorch torchvision -c soumith ` from the channel `soumith`, an installation command selector similar to http://pytorch.org/ page would be a big plus 😄 

It would make life a lot more easier for running it on different platforms.

**Comment by neubig** [comment]
Yes, we're working on pre-built pip binaries and a conda package would also be nice. The setup script is not quite stable yet, but once we do this and resolve a couple other issues we'll freeze version 2.0.1 and try to make the package.

**Comment by neubig** [comment]
`pip install dynet` can now install cross-platform binaries.

**Comment by fmailhot** [comment]
bump

any progress on a conda package?
