### ISSUE TITLE
BatchedExecutionEngine::combine_tensors crash due to tout.device being null.

### ISSUE THREAD

**Issue by mattr1** [clab/dynet#836]
exec.cc line 219: tout.device is nullptr, so this line crashes. Crash happens whether or not I specify --dynet-devices GPU:0. Perhaps it's because autobatch-created nodes take the same device as the nodes they are created from (?) and those nodes had a null device?

What is the expectation for node.device? I see it is allowed to be null to mean "the same as my inputs", but when I look at the code, there is a lot of code that dereferences node.device without checking if its null first. Are there segments of code where we know the devices have been "filled in"? Perhaps it would be cleaner to always fill in the device as soon as it's added to the graph (since the inputs are known at that point) and therefore disallow the device to be null.

Adding @xunzhang @neubig who worked on the multi-device commit.

Stack Trace:
dynet::BatchedExecutionEngine::combine_tensors(std::vector<unsigned int,std::allocator<unsigned int> > batch_ids, int aid, dynet::Tensor & tout) Line 219
dynet::BatchedExecutionEngine::incremental_forward_no_update(unsigned int upto, int autobatch_strategy) Line 742
dynet::BatchedExecutionEngine::incremental_forward(unsigned int i) Line 786
dynet::ComputationGraph::incremental_forward(unsigned int last) Line 377

**Comment by xunzhang** [comment]
Don't have time to reproduce yet. But yes, we want to make sure the device attribute of a node is set not to be null at definition. Like [here](https://github.com/clab/dynet/blob/master/dynet/dynet.h#L761) and the `Parameter/LookParameter` constructor. Could you help print out the node type(input/parameter/function) of this line for combining tensor.

**Comment by mattr1** [comment]
Okay, good to know. So basically once a node is in the computation graph, the device should be non-null. 

I did notice that the versions of add_function that take "const T& arguments" just set the device to the default device, rather than the device of the first argument (lines 800 and 815in dynet.h). I can see why this is the case for things with no input (like "zeros"), but these functions are also being called when adding the VanillaLSTMGates (in vanilla_lstm_gates_concat and vanilla_lstm_gates_dropout_concat, expr.cc lines 218 and 237) and the "detail::f" versions of adding a function (expr.h lines 118 and 126). The latter is used by almost everything in expr.h like average(), sum(), max(), ... I must admit I don't know why the detail::f methods are calling add_function(const T&) instead of add_function(initializer_list). (I commented-out add_function(const T&) and looked to see where the compiler broke) In these cases, it seems like it will be problematic that they are using the default device rather than the device from their inputs. I'm not sure how to fix it and ensure it stays fixed -- perhaps add the device as an argument so it's very explicit when the device is being taken from the default instead of from the inputs? Or perhaps rename add_function(const T&) to something like add_inputless_function? In both cases, it would be good to ensure detail::f calls add_function(initializer_list) so we can tell there are inputs and set the device appropriately.

Apologies if you already worked through all of this to make sure it will work right. I just want to prevent future mysterious bugs where nodes are executing on the wrong device by accident.

I'll get you more details on the types in combine_tensors.

**Comment by mattr1** [comment]
Actually, I think we can fix this by reading node->args after creating the node, rather than using the passed-in arguments directly. I'll try this and have you take a look.

In the meantime, the combine_tensors is working on a PickNegLogSoftmax node. I think the problem is PickNegLogSoftmax defines autobatch_pseudo_node(), which leaves device set to null. I modified the code so that the pseudo_node's device is set, after it's created, to the device used by one of the nodes in the batch. Can you take a look at the commit and see if it looks reasonable: https://github.com/clab/dynet/commit/d4fa40d43a4df9647c5d0db6a875a527c5babbb2? Thanks!

**Comment by mattr1** [comment]
Okay, I've also updated the add_function to always use the first input device (if there are inputs) regardless of how it was added. See commit https://github.com/clab/dynet/commit/1dde5c26719308a0f91878e1cfcb7d9e8741ecc1. I'll merge these two commits once you sign off.

**Comment by neubig** [comment]
Fixed by https://github.com/clab/dynet/pull/846

**Comment by xunzhang** [comment]
Oh, I missed this thread for some reason. @mattr1 Good catch and nice fix, it also simplifies the code. Thanks!
