### ISSUE TITLE
GPU and other command line parameters

### ISSUE THREAD

**Issue by michaelcapizzi** [clab/dynet#842]
Hi all -

I have the most up-to-date `dynet` (just `pull`ed this morning), but I'm still having trouble getting `GPU` usage.

I have tried the following:
```
import dynet_config
dynet_config.set_gpu()
dynet_config.set(mem=2048, weight_decay=0.001, requested_gpus=1)
import dynet as dy
```

but it appears as if the parameters weren't found:
```
[dynet] initializing CUDA
Request for 0 GPUs ...
[dynet] random seed: 2218163657
[dynet] allocating memory: 512MB
[dynet] memory allocation done.
```

As you can see, the memory wasn't registered, and while it says `initializing CUDA`, the `Request for 0 GPUs...` line is confusing.

Interestingly enough, if I try *not* using `.set_gpu()`:

```
import dynet_config
dynet_config.set(mem=2048, weight_decay=0.001, requested_gpus=1)
import dynet as dy
```

The memory is registered, but there is still an `initializing CUDA` line that is unexpected.

```
[dynet] initializing CUDA
Request for 0 GPUs ...
[dynet] random seed: 288333531
[dynet] allocating memory: 2048MB
[dynet] memory allocation done.
```

I've also tried: 

```
import _dynet as dy
dyparams = dy.DynetParams()
dyparams.set_mem(2048)
dyparams.set_requested_gpus(1)
dyparams.set_weight_decay(0.001)
dyparams.init()
```

This time the `memory` is registered, but the same `Request for 0 GPUs...` line appears.

```
[dynet] initializing CUDA
Request for 0 GPUs ...
[dynet] random seed: 288333534
[dynet] allocating memory: 2048MB
[dynet] memory allocation done.
```

I was also under the impression that `_dynet` was deprecated, and so I'm hesitant to use that.

I know that the code base is going through some changes right now, and I appreciate the collaborators working so quickly with these issues as they pop up.  

Thanks in advance, for any guidance.
-M

**Comment by xunzhang** [comment]
It is definitely a bug when you call `dynet_config.set_gpu()` then `dynet_config.set()`, I fixed it https://github.com/clab/dynet/pull/845 and it has been merged. I think I'll also add unit-tests for `dynet_config` in CI later.

**Comment by michaelcapizzi** [comment]
Thank you @xunzhang for the quick fix!  As always, I think I speak for the community when I say that we appreciate the speed with which issues are tackled.
