### ISSUE TITLE
Summary of changes from 2.0 to 2.0.1

### ISSUE THREAD

**Issue by danielhers** [clab/dynet#856]
The latest release has a few changes. They are summarized in the [release notes](https://github.com/clab/dynet/releases/tag/2.0.1), but it would be helpful to have a document telling me just what I need to change in my 2.0-based code to upgrade to 2.0.1.

**Comment by neubig** [comment]
Realistically, I don't think we're going to do this... I'll try to be better about this for future breaking changes.
