### ISSUE TITLE
'undefined vector' error when implementing user defined node without 'using namespace std;'

### ISSUE THREAD

**Issue by Oneplus** [clab/dynet#860]
When I implemented a new node and register it by `DYNET_NODE_INST_DEV_IMPL(MyNewNode)`. MSVC raised 
```
error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
error C2143: syntax error: missing ',' before '<'
```

This error was resulted by line 115 in `nodes-macros.h` when declaring vector without std namespace.

**Comment by neubig** [comment]
Fixed by #861
