### ISSUE TITLE
lookup parameters initialized to zeros (v2)

### ISSUE THREAD

**Issue by yoavg** [clab/dynet#88]
The lookup parameters seem to be initialized to zeros instead of random values.

```
import pycnn as pc
m = pc.Model()
print "lookups"
lp = m.add_lookup_parameters((10,10))
for i in xrange(10):
    print lp[i].npvalue()

# vs.
print "regular"
p = m.add_parameters((10,10))
print pc.parameter(p).npvalue()
```

**Comment by neubig** [comment]
This is confusing, and needs to be either be fixed or documented. But I guess we need to decide what the ideal behavior is first.

**Comment by redpony** [comment]
LookupParameters should also be initialized with random values or whatever the dynet default is- lookup params are no more special than any other params.

**Comment by neubig** [comment]
OK, fixed in this commit: https://github.com/clab/dynet/commit/b0041d78bd593f7956cefed0bf41d1fecc402334
