### ISSUE TITLE
Dilated Convolution

### ISSUE THREAD

**Issue by neubig** [clab/dynet#891]
CUDNN v6 supports dilated convolution apparently, so it would nice to have the option to use it in DyNet.

**Comment by liesun1994** [comment]
👍

**Comment by supakjk** [comment]
Isn't there a plan to add this feature?

**Comment by neubig** [comment]
Yes, this is something we definitely want but haven't gotten around to yet. Contributions would be appreciated if you (or anyone else) would be interested!
