### ISSUE TITLE
function cdiv issues 

### ISSUE THREAD

**Issue by liesun1994** [clab/dynet#892]
I used function cdiv in my code. But it reshapes my expression. 
Samples are follows:
`Expression temp = cdiv(Expression temp1, Expression temp2);`
shape of temp1 : d= {4, 1, ...} , nd = 2 , bd =2 
shape of temp2 : d= {4, 1, ...} , nd = 2 , bd =2 
shape of temp :   d={4, 1, ...},   nd =1,  bd =2 
The returned shape puzzles me a lot .

**Comment by chunyang-wen** [comment]
could you please provide any demo code that can repeat your error? As it will be easier to find out what happens.

**Comment by msperber** [comment]
I think this should be fixed now (as of #776)

**Comment by msperber** [comment]
This issue should no longer persist so I'll close.
