### ISSUE TITLE
Performance slow down after several mnist epochs in Windows

### ISSUE THREAD

**Issue by tohtsky** [clab/dynet#896]
I've built CPU-mode dynet with Visual Studio 2015 with the option `` /Ob2 /Oi /Ot /Gs- /utf-8 /arch:AVX2`` in the release configuration, and run the train_mnist.exe with ``--batch_size 128``.
When it's close to the end of the second epoch, the performance starts to slow down.

I could also compile it using clang-cl (with VS backend), the performance of which is much better compared to the VS version overall, but it again exhibited the same problem at exactly the same position in the learning.

Meanwhile, when I use Intel C++ compiler 17.0 (with or without MKL) does not suffer from this phenomenon.

It seems this is the issue in backward path only, as this performance decay is not observed for the validation accuracy computing stage.

Does anyone else observe this problem ?

**Comment by tohtsky** [comment]
Sorry, this seems to be the problem not in ``cg.backward()``, but in ``trainer.update()``.
If we use ``SimpleSGDTrainer`` or ``AdagradTrainer``, this does not happen,
but a significant speed down takes place for 
``Adadelta``, ``Adam``, ``RMSProp``, ``MomentumSGD`` trainers.

**Comment by neubig** [comment]
This is bizarre. I unfortunately don't have a windows machine to test this out on, but it'd be nice to know if this happens for others as well.

**Comment by tohtsky** [comment]
So I dug out  my old and poor MacBook Air (OSX version 10.10.5), and again encountered exactly the same problem.
Does anyone else encounter this on Mac??

**Comment by tohtsky** [comment]
It seems that the problem is caused by denormals: see this similar [issue](https://github.com/chainer/chainer/issues/2554) raised in Chainer.
