### ISSUE TITLE
Add ParameterInitXavier as an alias of ParameterInitGlorot for better discoverability?

### ISSUE THREAD

**Issue by tetsuok** [clab/dynet#901]
It would be nice to have "ParameterInitXavier" as a typedef of "ParameterInitGlorot" for better discoverability.  The phrase "Xavier initialization" can be seen in the web or papers.

**Comment by neubig** [comment]
I don't think adding an alias is necessary, but we can add it to the doc.

**Comment by tetsuok** [comment]
Thanks for the comment. I agree.

**Comment by pmichel31415** [comment]
FWIW I find it very weird to use Xavier because it's the author's 1st name while Glorot is his last name. Anyway I will update the docs accordingly since it seems to be a common denomination

**Comment by neubig** [comment]
Let's be pragmatic :) No-one calls AlexNet "KrizhevskyNet".

**Comment by pmichel31415** [comment]
Agreed. I fixed the documentation ( 425aacaa8e381c7a509fa65764c4ba9e3fadc147 ) let me know if that's OK for you.

**Comment by neubig** [comment]
LGTM!
