### ISSUE TITLE
Hardcoded build folder

### ISSUE THREAD

**Issue by xunzhang** [clab/dynet#906]
Current `setup.py` has several places with hardcoded `build` folder. In other words, I can only create build folder named `build`. But I usually have several build folders in my development environment to switch with different branches and different build modes.

**Comment by xunzhang** [comment]
I will try to fix this later today.

**Comment by danielhers** [comment]
Note that `build` is the default for the Distutils `build` command's `build_base` argument: https://github.com/python/cpython/blob/master/Lib/distutils/command/build.py#L57
So it's going to be created anyway and used for some Python temp files unless you change `build_base` too.

**Comment by danielhers** [comment]
Another option is, of course, to use `self.build_base` rather than literal `"build"`.

**Comment by xunzhang** [comment]
Solved via https://github.com/clab/dynet/commit/6e1e9f496973c7f77d85aea44481e9a50c654249.
