### ISSUE TITLE
Simplify manually build process without `cd python`

### ISSUE THREAD

**Issue by xunzhang** [clab/dynet#907]
As described in https://github.com/clab/dynet/pull/862, it might be more friendly to install python module without entering to python folder. https://github.com/clab/dynet/pull/862 only solves part of the issue of Eigen, but it doesn't actually work.

**Comment by danielhers** [comment]
Might be related to #877. The current hack "tricks" Distutils/Setuptools to find the generated/copied Python files by `cd`ing into `build/python`, but a proper solution might be to put them in a package and build it normally.

**Comment by xunzhang** [comment]
I tried to modify the `py_modules` values using the absolute path of python files. But it still failed to create egg file. I think the `os.chdir` has some tricky behavior, we should not use it in the future. And yes, I think a package solution is the best :)

**Comment by danielhers** [comment]
I also tried it without success before settling on the `cd` workaround...

**Comment by neubig** [comment]
Maybe this won't be fixed for now?
