### ISSUE TITLE
ImportError: libdynet.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zodiacR** [clab/dynet#915]
I'm installing dynet with python interface (GPU supported), and followed the instruction at manual installation section. I successfully installed dynet at my home dir. However when I import dynet, it complains the following error:
`ImportError: libdynet.so: cannot open shared object file: No such file or directory`
I checked the location of _libdynet.so_ which is at $PATH_TO_DYNET/build_gpu/dynet/, so I did this suggestion `export DYLD_LIBRARY_PATH=$PATH_TO_DYNET/build_gpu/dynet/:$DYLD_LIBRARY_PATH`, but still report this error.
I can import dynet under $PATH_TO_DYNET/build_gpu/python without any trouble. Can someone help me fix this issue.

**Environment:
Linux distribution: Linux version 2.6.32-431.5.1.el6.centos.plus.x86_64
Python: Python 2.7.11**

**Comment by tetsuok** [comment]
Can you find `_dynet.so` at installed location, and run `ldd _dynet.so`?
That command will tell you the location of `libdynet.so` which `_dynet.so` expects.

Also, the manual is assumed to macOS users for some reason. You can try `LD_LIBRARY_PATH` instead of `DYLD_LIBRARY_PATH`.

**Comment by zodiacR** [comment]
Thanks @tetsuok. Using `LD_LIBRARY_PATH` works for me.
