### ISSUE TITLE
Travis CI is overloaded with configurations

### ISSUE THREAD

**Issue by neubig** [clab/dynet#918]
We're testing a whole bunch of different configurations on Travis CI, and as a result it's falling far behind our pull requests. I think perhaps we should choose a core set of configurations that we want to test all the time, then maybe enable all the configurations before a release.

(FYI: I disabled building on "push" to try to reduce this problem, but it looks like building on push is enabled again)

**Comment by xunzhang** [comment]
I agree, maybe we can run a whole CI once a day with a bunch of commits. Not sure how to configure that in Travis CI.

**Comment by danielhers** [comment]
A new feature on Travis CI allows skipping specific configurations for PRs: travis-ci/travis-ci#7451

**Comment by danielhers** [comment]
And daily builds can be added easily: https://docs.travis-ci.com/user/cron-jobs/

**Comment by pmichel31415** [comment]
> (FYI: I disabled building on "push" to try to reduce this problem, but it looks like building on push is enabled again)

@neubig Yeah I think I'm the one who reactivated it for one particular pr (can't remember which one), my bad.

**Comment by danielhers** [comment]
Also, another new feature should be helpful: https://blog.travis-ci.com/2017-09-21-default-auto-cancellation
Builds will auto-cancel if a more recent version of the branch/PR is waiting. Is it enabled in clab/dynet?

**Comment by neubig** [comment]
I enabled auto-cancellation and a weekly cron job. I think weekly is sufficient, as the default configurations should be enough to catch most bugs.

**Comment by neubig** [comment]
It seems that the build is failing at the very beginning now for all PRs. I'm not sure if this is due to the changes in travis.yaml?

https://travis-ci.org/clab/dynet/jobs/278355578

**Comment by neubig** [comment]
Sorry, nevermind. I think this was just because I merged something while this build was processing.
