### ISSUE TITLE
"invalid device name" in Python tests

### ISSUE THREAD

**Issue by neubig** [clab/dynet#926]
It seems that Python tests are failing *sometimes* on Travis CI with an "invalid device name" error.
> https://travis-ci.org/clab/dynet/builds/278565464

I imagine this is because of the introduction of the Python multi-device interface. Any ideas @xunzhang or @yoavg ?

**Comment by xunzhang** [comment]
I can successfully run `python test.py` in my local environment with both CPU mode and GPU mode. I think the environment in Travis is just CPU mode, right?

**Comment by neubig** [comment]
Things are broken on Python 3. I'll try to fix this.

**Comment by neubig** [comment]
Should be fixed by https://github.com/clab/dynet/commit/5d44a8d948e425bd1504760a3c091e48c33a2067

Will close this once tests have passed.

**Comment by xunzhang** [comment]
Great

**Comment by danielhers** [comment]
Looks like this is fixed, no?

**Comment by xunzhang** [comment]
Fixed.
