### ISSUE TITLE
Feature request for some standard dimension-wise and broadcasting functions

### ISSUE THREAD

**Issue by mitchellstern** [clab/dynet#928]
Missing from Python:
* I see that a `SumDimension` node exists in C++, but `sum_dim` is missing in the Python interface. Would it be possible to add a wrapper? (This would also address the lack of a `sum_rows` operation analogous to the existing `sum_cols` operation.)

Nice to have:
* Would it be possible to add a dimension-wise logsumexp operation called `logsumexp_dim`? This would be useful when implementing a CRF, for example. We currently have `esum` and `logsumexp` for lists of expressions. If `sum_dim` mentioned above is added, users could implement `logsumexp_dim` in terms of `log`, `exp`, `sum_dim`, and `max_dim`, but a built-in numerically stable version would be ideal.
* Would it be possible to add an addition operation that broadcasts over rows called `rowwise_add` analogous to the existing `colwise_add`? Or is there an alternative way to do broadcasting addition over rows using the current API other than transposing, performing `colwise_add`, and transposing back?

**Comment by neubig** [comment]
Some of these will be supported by https://github.com/clab/dynet/pull/776 once I finish debugging it. Some of the others (e.g. logsumexp_dim) would be very nice to have.

**Comment by neubig** [comment]
`sum_dim` just got merged, and as of #776 regular componentwise operations such as addition support broadcasting. I'm working on `logsumexp_dim` which will be merged soon (CC: @violet-zct)

**Comment by neubig** [comment]
OK, all of these should be implemented as of #1001 !

**Comment by mitchellstern** [comment]
Thank you!
