### ISSUE TITLE
model saving and loading is broken

### ISSUE THREAD

**Issue by yoavg** [clab/dynet#93]
One of the latest changes broke the model loading mechanism: loading a saved model results in a boost input stream error exception.

(this happened at: a6d937dcd820ed871c8e91d40fb35b740eecdf3c )

To reproduce: run 
```
cd build/examples
./read-write
```

**Comment by neubig** [comment]
Confirmed. This needs to be fixed ASAP, and model write/read also need unit test coverage.

**Comment by neubig** [comment]
Fixed by https://github.com/clab/dynet/commit/f2c60e8d5ffd609c84bd8c02b767b33f9830a6fe
