### ISSUE TITLE
Garbage collector problems?

### ISSUE THREAD

**Issue by borgr** [clab/dynet#930]
When model is not used anymore (del or just no reference in python for it) things break, in the minimal example in line ` par.value()` segfault is thrown (instead of printing a random value).

```
import dynet as dn
import tqdm
def params():
    model = dn.ParameterCollection()
    param = dn.parameter(model.add_parameters((1, )))
    return param

def main():
    par = params()
    for i in tqdm.trange(1000000):
        pass
    par.value()

if __name__ == '__main__':
    main()
```

**Comment by danielhers** [comment]
A little elaboration: the `model` variable is losing its single reference when the `params` function returns. The `tqdm.trange(1000000)` is just to pass the time and let the Python GC work (it shows a fancy progress bar in the meantime; not also that `sleep` and a simple `range` didn't have the same result, supposedly due to optimization and thread yield).
An equivalent version would be

    from dynet import *
    p = parameter(ParameterCollection().add_parameters((1,)))
    for _ in tqdm.trange(1000000):
        pass
    p.value()

**Comment by chunyang-wen** [comment]
```python
from dynet import *
model = ParameterCollection()
p = parameter(model.add_parameters((1,)))
for _ in tqdm.trange(1000000):
    pass
# gc.collect()
p.value()
```
 Above code does not repeat segment error even a forced garbage collection.

**Comment by danielhers** [comment]
Of course, since the `model` variable is not deleted.

**Comment by danielhers** [comment]
It might be argued that it's never appropriate to lose all references to a `ParameterCollection` object while still using its parameters, but here @borgr tried to do that legitimately. Conceptually, I think, there's a problem with allowing a parameter to exist independently of its model (syntactically speaking; as we saw in runtime it causes an error).

**Comment by chunyang-wen** [comment]
Yeah. I agree. Maybe the way that parameter is evaluated is not right.

> Conceptually, I think, there's a problem with allowing a parameter to exist independently of its model (syntactically speaking; as we saw in runtime it causes an error

It is similar to that we return a pointer pointing to somewhere on the stack of a function in C or C++. It may crash when we dereference. Those kinds of invalid usages are hard to prevent.

**Comment by danielhers** [comment]
I don't think you should ever return a pointer to a stack variable in C++.
Anyway, in this case, shouldn't the ParameterCollection destructor avoid deleting the parameters if they still have other references hanging around? Or do Python references not count as references?
