### ISSUE TITLE
[Need explaination] DeviceMempool 

### ISSUE THREAD

**Issue by chunyang-wen** [clab/dynet#936]
When reading source code of dynet, I come across the definition of `DeviceMempool`.

```c
enum DeviceMempool {FXS = 0, DEDFS = 1, PS = 2, SCS = 3, NONE = 4};
```

But It has no documentation. For other codes, I guess:

+ FXS: storage for forward
+ DEDFS: storage for backward

Can anyone provide more elaboration for the definition?

**Comment by neubig** [comment]
FXS -> forward pass memory
DEDFS -> backward pass memory
PS -> parameter memory
SCS -> scratch memory (for use in temporary calculations)
NONE -> when a memory pool has not been assigned yet

**Comment by chunyang-wen** [comment]
Thanks for your quick response. Maybe those words should be included in the code.

**Comment by neubig** [comment]
A pull request would be welcomed!
