### ISSUE TITLE
Travis CI builds failing on Linux

### ISSUE THREAD

**Issue by danielhers** [clab/dynet#941]
Due to conda/conda#6030

**Comment by danielhers** [comment]
Maybe we can ditch Miniconda altogether and use Travis CI's native Python (specifying the version is possible too). I'm thinking of something like https://stackoverflow.com/a/44054333/223267

**Comment by neubig** [comment]
Sounds like a plan! I'm always for reducing dependencies.

**Comment by pmichel31415** [comment]
+1, I introduced miniconda because it was the easiest thing to do at the time but native python would be better.
