### ISSUE TITLE
Multi-GPU support still not finished yet

### ISSUE THREAD

**Issue by neubig** [clab/dynet#952]
Apparently multi-GPU support is still not working completely. See https://github.com/clab/dynet/pull/947 and https://github.com/clab/dynet/pull/916#issuecomment-331745925

Hopefully we can finish up the remaining things soon.

**Comment by xunzhang** [comment]
Resolved via https://github.com/clab/dynet/pull/967, https://github.com/clab/dynet/pull/994, and https://github.com/clab/dynet/pull/999.

**Comment by neubig** [comment]
Awesome, thank you! I think we can think of doing a minor version release pretty soon.

**Comment by xunzhang** [comment]
Sure, let's do that.
