### ISSUE TITLE
Recommended Eigen version does not build on OS X

### ISSUE THREAD

**Issue by MattX** [clab/dynet#955]
I was not able to build dynet through pip nor following the [documentation](https://dynet.readthedocs.io/en/latest/python.html), because [the recommended version of Eigen does not seem to build with Apple Clang](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1459).

I was able to get dynet to work using revision 699b6595fc47 of Eigen instead.

pip output for reference: https://pastebin.com/aDdQpxvN

**Comment by sserr23** [comment]
I was having the same issue. Another solution that works is to change one header file in Eigen as described here: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1459 (that's what I ended up doing)

**Comment by neubig** [comment]
What version of clang/OS X are you talking about? This currently compiles on my computer, so it must be a version-specific thing.

**Comment by MattX** [comment]
I'm running OS X 10.12.6 and Xcode 9.0.0 / clang-900.0.37.

**Comment by Aditi138** [comment]
@MattX - Can you please tell how did you go about this ?  "to get dynet to work using revision 699b6595fc47 of Eigen instead"

**Comment by neubig** [comment]
@Aditi138 You can just change `346ecdb` to `699b659` in the manual install instructions. (I'll be updating the doc shortly once integration tests pass on #966)
