### ISSUE TITLE
g++: error: unrecognized command line option ‘-R’: Unable to install Dynet with CUDA support on linux(Python version)

### ISSUE THREAD

**Issue by bmurali1994** [clab/dynet#956]
I get an error when trying to install the python version of Dynet with CUDA support.
I tried exporting variables with the correct paths to gcc and g++, but still gives me the same issue. 
Any ideas on how to address this issue? Thank you!

**make** output:
[ 98%] Built target dynet
[ 98%] Built target pydynet_precopy
[100%] Generating timestamp
running build_ext
INFO:root:Building Cython extensions...
INFO:root:INCLUDE_DIRS='/home/paperspace/dynet-base/dynet /home/paperspace/dynet-base/eigen'
INFO:root:LIBRARIES='dynet cublas'
INFO:root:LIBRARY_DIRS='. /usr/local/cuda/lib64 /home/paperspace/dynet-base/dynet/build/dynet/'
INFO:root:COMPILER_ARGS='-std=c++11 -Wno-unused-function'
INFO:root:EXTRA_LINK_ARGS="-Wl,-rpath='/usr/local/lib/',--no-as-needed"
INFO:root:RUNTIME_LIB_DIRS='/home/paperspace/dynet-base/dynet/build/dynet/ /usr/local/lib/'
cythoning /home/paperspace/dynet-base/dynet/build/python/_dynet.pyx to /home/paperspace/dynet-base/dynet/build/python/_dynet.cpp
building '_dynet' extension
/usr/bin/gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/paperspace/dynet-base/dynet -I/home/paperspace/dynet-base/eigen -I/home/paperspace/anaconda3/include/python3.6m -c /home/paperspace/dynet-base/dynet/build/python/_dynet.cpp -o build/temp.linux-x86_64-3.6/home/paperspace/dynet-base/dynet/build/python/_dynet.o -std=c++11 -Wno-unused-function
/home/paperspace/dynet-base/dynet/build/python/_dynet.cpp: In function ‘PyObject* __pyx_f_6_dynet_16LookupParameters_init_from_array(__pyx_obj_6_dynet_LookupParameters*, PyObject*, int)’:
/home/paperspace/dynet-base/dynet/build/python/_dynet.cpp:17703:77: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   __pyx_t_7 = ((__pyx_t_6 > __pyx_v_self->thisptr.get_storage().values.size()) != 0);
                                                                             ^
/usr/bin/g++ -pthread -shared -B /home/paperspace/anaconda3/compiler_compat -L/home/paperspace/anaconda3/lib -Wl,-rpath=/home/paperspace/anaconda3/lib,--no-as-needed build/temp.linux-x86_64-3.6/home/paperspace/dynet-base/dynet/build/python/_dynet.o -L. -L/usr/local/cuda/lib64 -L/home/paperspace/dynet-base/dynet/build/dynet/ -L/home/paperspace/anaconda3/lib -R/home/paperspace/dynet-base/dynet/build/dynet/ -R/usr/local/lib/ -ldynet -lcublas -lpython3.6m -o /home/paperspace/dynet-base/dynet/build/python/_dynet.cpython-36m-x86_64-linux-gnu.so -Wl,-rpath='/usr/local/lib/',--no-as-needed
g++: error: unrecognized command line option ‘-R’
g++: error: unrecognized command line option ‘-R’
error: command '/usr/bin/g++' failed with exit status 1
make[2]: *** [python/timestamp] Error 1
make[1]: *** [python/CMakeFiles/pydynet.dir/all] Error 2
make: *** [all] Error 2

##**env** output:
XDG_SESSION_ID=3
TERM=xterm-256color
SHELL=/bin/bash
DERBY_HOME=/usr/lib/jvm/java-8-oracle/db
SSH_CLIENT=143.215.34.137 64879 22
OLDPWD=/home/paperspace/dynet-base
SSH_TTY=/dev/pts/2
USER=paperspace
LD_LIBRARY_PATH=/usr/local/lib:/home/paperspace/src/torch/install/lib:/usr/local/lib:/home/paperspace/src/torch/install/lib:
MAIL=/var/mail/paperspace
PATH=/home/paperspace/anaconda3/bin:/home/paperspace/src/torch/install/bin:/home/paperspace/anaconda3/bin:/home/paperspace/src/torch/install/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin:/usr/local/cuda/bin:/usr/local/cuda/bin
QT_QPA_PLATFORMTHEME=appmenu-qt5
PWD=/home/paperspace/dynet-base/dynet/build
JAVA_HOME=/usr/lib/jvm/java-8-oracle
LUA_PATH=/.luarocks/share/lua/5.1/?.lua;/.luarocks/share/lua/5.1/?/init.lua;/home/paperspace/src/torch/install/share/lua/5.1/?.lua;/home/paperspace/src/torch/install/share/lua/5.1/?/init.lua;./?.lua;/home/paperspace/src/torch/install/share/luajit-2.1.0-beta1/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua
LANG=en_US.UTF-8
LUA_CPATH=/home/paperspace/src/torch/install/lib/?.so;/.luarocks/lib/lua/5.1/?.so;/home/paperspace/src/torch/install/lib/lua/5.1/?.so;./?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so
CXX=/usr/bin/g++
SHLVL=1
HOME=/home/paperspace
DYLD_LIBRARY_PATH=/home/paperspace/src/torch/install/lib:/home/paperspace/src/torch/install/lib:
PYTHONPATH=/home/paperspace/src/caffe/python:/home/paperspace/src/caffe/python:
LOGNAME=paperspace
J2SDKDIR=/usr/lib/jvm/java-8-oracle
SSH_CONNECTION=143.215.34.137 64879 10.64.11.213 22
LESSOPEN=| /usr/bin/lesspipe %s
CC=/usr/bin/gcc
XDG_RUNTIME_DIR=/run/user/1000
CAFFE_ROOT=/home/paperspace/src/caffe
J2REDIR=/usr/lib/jvm/java-8-oracle/jre
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/env

**Comment by stefan-it** [comment]
What's your version of GCC?

**Comment by bmurali1994** [comment]
I was initially using an older version: gcc: 4.8.1, but then upgraded it to gcc version: 5.4.1.
It still does not help!

**Comment by neubig** [comment]
Could you please send your whole build log and the exact commands that you ran to get the error (from a fresh checkout of DyNet)? Thanks!

**Comment by chloebt** [comment]
hi,

I have the same issue. I tried the manual installation of the python version, and get the same error (see log enclosed). 
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0
[log_dynet.txt](https://github.com/clab/dynet/files/1386997/log_dynet.txt)

Thanks for your help!

**Comment by SophieZhou** [comment]
I met the same problem, could anyone give suggestion?

**Comment by neubig** [comment]
OK, this is a bizarre error. I'm not sure exactly why this is happening, but it seems like a very similar issue is here: https://github.com/NixOS/nixpkgs/issues/5655

I'm not sure why this is happening in @chloebt 's particular case, as the compiler seems to be set to gcc though. It'll be difficult for us to debug if we can't reproduce, but if someone on the thread who can reproduce the error can dig further that would be greatly appreciated.

**Comment by chloebt** [comment]
A very strange thing happened: my first try was a manual installation (as you can see in the log), and, just to check, I tried the "pip install", and it worked perfectly well! So, I still don't know where the error comes from, but I managed to install dynet.

**Comment by bmurali1994** [comment]
quick update: upgrading gcc and g++. and setting these paths right when installing dynet solves the above issue!!

**Comment by bmurali1994** [comment]
link update: upgrading gcc and following this link solved the above issue: https://gist.github.com/stephenturner/e3bc5cfacc2dc67eca8b

**Comment by pcyin** [comment]
I got the same error. Here's my workaround:
if you are using anaconda, try to use an older version (e.g., 4.3.1):
```
wget https://repo.continuum.io/archive/Anaconda2-4.3.1-Linux-x86_64.sh
conda install libgcc
follow the official installation guide
```

**Comment by dowobeha** [comment]
Graham, I'm getting this same error on Ubuntu 16.04.3 using the stock gcc (version 5.4.0). 

Is the only solution "Upgrade gcc"?

**Comment by dowobeha** [comment]
@neubig FYI, I was able to work around this problem on Ubuntu 16.04.3 by using clang instead of gcc.

I suggest that the instructions be updated with this info, since Ubuntu 16.04 is a common platform, and since the stock gcc on it doesn't work for compiling dynet (at least for me).

`CXX=/usr/bin/clang++ CC=/usr/bin/clang BACKEND=cuda pip install git+https://github.com/clab/dynet#egg=dynet`
