### ISSUE TITLE
Can't build Dynet on macOS 10.12.6

### ISSUE THREAD

**Issue by sserr23** [clab/dynet#959]
I've followed the installation instructions for Dynet for Python, and I've also tried the instructions for manual installation, as well as the instructions to install Dynet for C++. None of them succeeds in building Dynet on my machine. I'm not using CUDA or any other GPU support. The following is the error I get when I run the command

`pip install git+https://github.com/clab/dynet#egg=dynet`

to try and install Dynet the non-manual way:

Collecting dynet from git+https://github.com/clab/dynet#egg=dynet
  Cloning https://github.com/clab/dynet to /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet
Requirement already satisfied: cython in /Library/Python/2.7/site-packages (from dynet)
Requirement already satisfied: numpy in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from dynet)
Installing collected packages: dynet
  Running setup.py install for dynet ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-JN1shW-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    INFO:root:CMAKE_PATH='/usr/local/bin/cmake'
    INFO:root:MAKE_PATH='/usr/bin/make'
    INFO:root:MAKE_FLAGS='-j 4'
    INFO:root:EIGEN3_INCLUDE_DIR='/private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit/eigen'
    INFO:root:EIGEN3_DOWNLOAD_URL='https://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2'
    INFO:root:CC_PATH='/usr/local/bin/gcc'
    INFO:root:CXX_PATH='/usr/bin/g++'
    INFO:root:SCRIPT_DIR='/private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet'
    INFO:root:BUILD_DIR='/private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit'
    INFO:root:INSTALL_PREFIX='/Library/Python/2.7/site-packages/../../..'
    INFO:root:PYTHON='/usr/bin/python'
    cmake version 3.9.3
    
    CMake suite maintained and supported by Kitware (kitware.com/cmake).
    Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
    Apple LLVM version 9.0.0 (clang-900.0.37)
    Target: x86_64-apple-darwin16.7.0
    Thread model: posix
    InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
    INFO:root:Creating build directory /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit
    INFO:root:Fetching Eigen...
    INFO:root:Unpacking Eigen...
    INFO:root:Configuring...
    -- The C compiler identification is GNU 5.4.0
    -- The CXX compiler identification is AppleClang 9.0.0.9000037
    -- Checking whether C compiler has -isysroot
    -- Checking whether C compiler has -isysroot - yes
    -- Checking whether C compiler supports OSX deployment target flag
    -- Checking whether C compiler supports OSX deployment target flag - yes
    -- Check for working C compiler: /usr/local/bin/gcc
    -- Check for working C compiler: /usr/local/bin/gcc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/usr/bin/g++
    -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/usr/bin/g++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- BACKEND not specified, defaulting to eigen.
    -- Eigen dir is /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit/eigen/eigen-eigen-5a0156e40feb
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - found
    -- Found Threads: TRUE
    -- Found Cython version 0.27.1
    
    CMAKE_INSTALL_PREFIX="/Library"
    PROJECT_SOURCE_DIR="/private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet"
    PROJECT_BINARY_DIR="/private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit"
    LIBS=""
    EIGEN3_INCLUDE_DIR="/private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit/eigen/eigen-eigen-5a0156e40feb"
    MKL_LINK_DIRS=""
    WITH_CUDA_BACKEND=""
    CUDA_RT_FILES=""
    CUDA_RT_DIRS=""
    CUDA_CUBLAS_FILES=""
    CUDA_CUBLAS_DIRS=""
    MSVC=""
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit
    INFO:root:Compiling...
    Scanning dependencies of target dynet
    [  1%] Building CXX object dynet/CMakeFiles/dynet.dir/aligned-mem-pool.cc.o
    [  3%] Building CXX object dynet/CMakeFiles/dynet.dir/cfsm-builder.cc.o
    [  6%] Building CXX object dynet/CMakeFiles/dynet.dir/deep-lstm.cc.o
    [  6%] Building CXX object dynet/CMakeFiles/dynet.dir/devices.cc.o
    [  7%] Building CXX object dynet/CMakeFiles/dynet.dir/dict.cc.o
    In file included from /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/dynet/deep-lstm.cc:1:
    In file included from /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/dynet/deep-lstm.h:4:
    In file included from /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/dynet/dynet.h:17:
    In file included from /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/dynet/devices.h:10:
    In file included from /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit/eigen/eigen-eigen-5a0156e40feb/unsupported/Eigen/CXX11/Tensor:142:
    /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit/eigen/eigen-eigen-5a0156e40feb/unsupported/Eigen/CXX11/src/Tensor/TensorStorage.h:39:7: error: class template partial specialization is not more specialized than the primary template [-Winvalid-partial-specialization]
    class TensorStorage<T, FixedDimensions, Options_>
          ^
    /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit/eigen/eigen-eigen-5a0156e40feb/unsupported/Eigen/CXX11/src/Tensor/TensorStorage.h:34:63: note: template is declared here
    template<typename T, typename Dimensions, int Options_> class TensorStorage;
                                                                  ^
    In file included from /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/dynet/cfsm-builder.cc:1:
    In file included from /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/dynet/cfsm-builder.h:15:
    In file included from /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/dynet/dynet.h:17:
    In file included from /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/dynet/devices.h:10:
    In file included from /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit/eigen/eigen-eigen-5a0156e40feb/unsupported/Eigen/CXX11/Tensor:142:
    /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit/eigen/eigen-eigen-5a0156e40feb/unsupported/Eigen/CXX11/src/Tensor/TensorStorage.h:39:7: error: class template partial specialization is not more specialized than the primary template [-Winvalid-partial-specialization]
    class TensorStorage<T, FixedDimensions, Options_>
          ^
    /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit/eigen/eigen-eigen-5a0156e40feb/unsupported/Eigen/CXX11/src/Tensor/TensorStorage.h:34:63: note: template is declared here
    template<typename T, typename Dimensions, int Options_> class TensorStorage;
                                                                  ^
    In file included from /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/dynet/devices.cc:1:
    In file included from /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/dynet/devices.h:10:
    In file included from /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit/eigen/eigen-eigen-5a0156e40feb/unsupported/Eigen/CXX11/Tensor:142:
    /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit/eigen/eigen-eigen-5a0156e40feb/unsupported/Eigen/CXX11/src/Tensor/TensorStorage.h:39:7: error: class template partial specialization is not more specialized than the primary template [-Winvalid-partial-specialization]
    class TensorStorage<T, FixedDimensions, Options_>
          ^
    /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/build/py2.7-64bit/eigen/eigen-eigen-5a0156e40feb/unsupported/Eigen/CXX11/src/Tensor/TensorStorage.h:34:63: note: template is declared here
    template<typename T, typename Dimensions, int Options_> class TensorStorage;
                                                                  ^
    1 error generated.
    make[2]: *** [dynet/CMakeFiles/dynet.dir/devices.cc.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    1 error generated.
    make[2]: *** [dynet/CMakeFiles/dynet.dir/deep-lstm.cc.o] Error 1
    1 error generated.
    make[2]: *** [dynet/CMakeFiles/dynet.dir/cfsm-builder.cc.o] Error 1
    make[1]: *** [dynet/CMakeFiles/dynet.dir/all] Error 2
    make: *** [all] Error 2
    error: /usr/bin/make -j 4
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-JN1shW-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/ky/p276tl61531f64tz4mcp698r0000gn/T/pip-build-7Wa1PN/dynet/

The error messages I got when trying either the manual way or the C++ version are very similar to that one, mentioning the exact same issue with TensorStorage, with the only difference being that they only make it as far as "Building CXX object dynet/CMakeFiles/dynet.dir/deep-lstm.cc.o" before crashing.

Thanks in advance!

**Comment by sserr23** [comment]
Just fixed the issue-- looks like it was a problem with my version of clang being too new for a header file in eigen. I referenced this to help me fix the problem: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1459

**Comment by Aditi138** [comment]
@sserr23 Can you please tell how you resolved it? Did you change the function templates as mentioned in the link? Or did you make it point to an older clang version? 

Thanks!

**Comment by neubig** [comment]
@Aditi138  You can use a different version of Eigen, see here: https://github.com/clab/dynet/issues/955

FYI: I'm installing the latest version of Xcode so I can work on a permanent fix now.
