### ISSUE TITLE
Manual Installation issue on Mac Sierra

### ISSUE THREAD

**Issue by Aditi138** [clab/dynet#961]
I tried both pip install and manual install, both are not installing correctly. 

I am getting the following error on manual installation- 
cmake .. -DEIGEN3_INCLUDE_DIR=../../eigen -DPYTHON=`which python`
-- BACKEND not specified, defaulting to eigen.
-- Eigen dir is /Users/aditichaudhary/Documents/CMU/dynet-base/eigen
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named Cython
CMake Error at python/CMakeLists.txt:15 (if):
  if given arguments:

    "VERSION_LESS" "0.23"

  Unknown arguments specified
Call Stack (most recent call first):
  python/CMakeLists.txt:28 (check_cython_version)

-- Configuring incomplete, errors occurred!
Cython current version installed is cython-0.27.1. Should I be installing a lower version?

Thanks!

**Comment by neubig** [comment]
No, I think the installation process is not finding Cython for some reason. (It should fail if you are less than 0.23, not more). Could you check that cython can be found properly in your environment?

**Comment by Aditi138** [comment]
Cython can be found on the environment, as when I type 'cython', it is able to recognize it and does not give an issue.

**Comment by neubig** [comment]
Actually, this may be a problem with cmake. What version of cmake are you using? Could you try to install the most recent version and try again?

**Comment by Aditi138** [comment]
Thanks @neubig  for the help, my issue got resolved. It was due to multiple versions of python on my system. I resolved by creating a conda environment for python 2.7 and installed on that, its working fine now.
