### ISSUE TITLE
possible discrepancy in pairwise_rank_loss

### ISSUE THREAD

**Issue by sandeepsoni** [clab/dynet#963]
Hi -- I'm noticing unexpected behavior in the ```pairwise_rank_loss``` function.  I've the following basic code:
```python
import numpy as np
import dynet as dy
n = np.array ([1.4, 0.9])
e = dy.inputVector (n) # create an expression
print dy.hinge(e,1).scalar_value() #hinge loss
print dy.pairwise_rank_loss (dy.pick(e,0), dy.pick(e,1)).scalar_value() #pairwise ranking loss
```
I get the following response:
```
1.50000011921
0.5
```
Based on the documentation for [both](http://dynet.readthedocs.io/en/latest/python_ref.html#dynet.pairwise_rank_loss) [functions](http://dynet.readthedocs.io/en/latest/python_ref.html#dynet.hinge), I think both ```pairwise_rank_loss``` and ```hinge``` should yield the same value -- ```1.5``` for this example. But it seems that the order of inputs for ```pairwise_rank_loss``` is reversed from the one which is documented. Am I missing anything? I'm new to Dynet, so I may have gotten this completely backwards.

**Comment by neubig** [comment]
Sorry about this! Apparently the doc for `pairwise_rank_loss` was wrong. It has been fixed (https://github.com/clab/dynet/commit/7f4305b8df46343e89d351f90cffab8531de8156) to accurately reflect that pairwise rank loss is calculating `max(0, m - x + y)`:
