### ISSUE TITLE
When using GPU, memory usage on CPU and the accompanying message is confusing

### ISSUE THREAD

**Issue by neubig** [clab/dynet#98]
When using GPU, if memory is set using --dynet_mem, the memory on the GPU is set properly, but DyNet additionally allocates 512MB of memory on the CPU and sends a message indicating so. This unneeded allocation and confusing message should be fixed.

**Comment by pmichel31415** [comment]
Seeing this now I think this was also fixed in #117 

Can't check right now though

**Comment by neubig** [comment]
Yes, it was, thanks!
