### ISSUE TITLE
Python Tutorials in Doc Disappeared?

### ISSUE THREAD

**Issue by neubig** [clab/dynet#980]
I think we used to have better tutorials in the doc, but now we only have a saving/loading tutorial. We should fix this to add more tutorials and also add a link to the examples page:

http://dynet.readthedocs.io/en/latest/tutorial.html

**Comment by pmichel31415** [comment]
Yes I'm fairly sure this is a bug of some sorts, the links to the other tutorials are still in the source of the doc. I'll look into it

**Comment by pmichel31415** [comment]
I think this was broken in 5049e5995f169fe1798139e1ca4dc98a7c0c4317 

I fixed it, I'll close the issue as soon as the doc rebuilds and I confirm the fix

**Comment by neubig** [comment]
Thanks!
