### ISSUE TITLE
Travis CI push trigger is disabled

### ISSUE THREAD

**Issue by danielhers** [clab/dynet#982]
Builds are enabled only for PRs and cron: https://travis-ci.org/clab/dynet/builds
So when looking at [commits](https://github.com/clab/dynet/commits/master) you can't see if one broke the build.
Is this intentional? If the reason is too many jobs then we can enable the full set only for cron (not push+cron as it is now).

**Comment by neubig** [comment]
This is for two reasons:
1. pushes were triggering the full suite of tests.
2. whenever you send a PR it does a duplicate test, one for the push and one for the PR.

Both of these were wasting time on Travis. If both of these are resolved I think we can turn it back on, but if not I'm relatively happy with it remaining off.

**Comment by danielhers** [comment]
#985 resolves both these issues.

**Comment by pmichel31415** [comment]
I thin this one can be closed then?

**Comment by danielhers** [comment]
I think the push trigger is still disabled; only PR and cron are enabled.

**Comment by danielhers** [comment]
@neubig looks like Travis CI push trigger is still disabled. Just making sure this is intentional...
