### ISSUE TITLE
dy.cmult() automatically drops a dim when its size is 1

### ISSUE THREAD

**Issue by zodiacR** [clab/dynet#991]
I use python interface. When I use dy.cmult(x,y), where x.dim=((4,1),4) and y.dim=((4,1), 4), this operation returns z whose dim becomes ((4,),4). This causes my program crashed, as some following operations wanna keep z's dim constant as x's. Not sure whether someone else prefers this design. 
P.S. this phenomenon happens to c.div() as well.

**Comment by msperber** [comment]
This should be fixed as of #776 , can you confirm you are using the most recent version?

**Comment by zodiacR** [comment]
I'm using version 2.0. So the most recent version in on the master branch?

**Comment by msperber** [comment]
Yes, please try the most recent version on master branch

**Comment by zodiacR** [comment]
Great. It works. thx.
